### ISSUE TITLE
[Feature request] Add blacklist button

### ISSUE THREAD

**Issue by czullo** [TLDRMissions/TLDRMissions#132]
TLDR version: Adding Blacklist button

There is still misssions with like over 100k calculation with no resolve, and mission can stay up to 12hours, so my proposal is to add blacklist button that will blacklist this particulal mission from calculating till this missions expire. For someone whos checking missions often its verry helpfull, cuz skipping missions and then login in 2 hours addon will still calculate this mission and its waste of time.

**Comment by teelolws** [comment]
I'll consider it.

**Comment by teelolws** [comment]
Still something I'm considering, just not a priority atm.

**Comment by teelolws** [comment]
Coming next patch:
![image](https://user-images.githubusercontent.com/49792789/168686224-a9d4436d-e086-4a4f-ae3c-d9372012437d.png)

Its going to default to 30,000, which I feel is generous enough.

The simulations counter at the bottom will also now reset for each mission.

**Comment by zeenk** [comment]
Would it be possible to add some sort of summary at the end of calculations now with the new maximum simulations per mission feature? telling us if any missions took to long and got skipped etc if I have the max at like 5k for example so it's I know if I can logout or should try manually send it out faster with vp? :P small idea but would be nice to have imo.

![2022-05-17_04-10-04](https://user-images.githubusercontent.com/68170439/168714202-7d84d613-9461-4f7f-b3c9-26c2c0933b0d.png)

**Comment by teelolws** [comment]
Eh, I guess. I'll add it to the wishlist.

**Comment by teelolws** [comment]
If it stops after 5000 simulations, it still stores the results of those 5000 simulations into the cache. Next time you try calculate, as long as your followers didn't heal up, those results are still there and get skipped over - it'll continue from where it left off. Its not going to repeat calculations it already did.

**Comment by czullo** [comment]
YOu added option to blacklist some mission thats failes to calculate? I dont see that option.

**Comment by teelolws** [comment]
I don't currently have any plans to add the "blacklist" button you requested. The issue can be addressed in better ways. You could set a maximum simulations limit that will skip over it. You could let it run all the simulations, which will put them in the "results cache". In the future, I am planning to have the addon do simulations in the background to fill up the results cache. The blacklist would just make you miss opportunities where you might actually beat the mission.
