### ISSUE TITLE
Calculation Error - Infinite Calculations

### ISSUE THREAD

**Issue by Alexander-Gremory** [TLDRMissions/TLDRMissions#191]
I got about 30,000 calculations on a single mission, I had only 6 follows left and it just would keep going and going. 

Please give us a slider or function that skips after simulating too many times

**Comment by teelolws** [comment]
Skipping is not the solution. It might skip 1 calculation before finding a solution.

See the front page:

`Q: The number of simulations is really high. Is it broken?`

`A: Some missions involve "randomness", such as spells that have a random target. When this happens, the addon could take a long time to find a way to guarantee success. If you would prefer the addon finds solutions more quickly, change some of the advanced settings. Perhaps lower the level restriction, so low level minions aren't tested on high level missions.`

**Comment by Alexander-Gremory** [comment]
I adjusted the settings, but I wanted to let you know of another issue I ran into. I let it simulate and once it his 36,8XX something the addon broke completely and refused to simulate, skip, or anything afterwards.

**Comment by teelolws** [comment]
Did you get any lua errors?

`/console scriptErrors 1`

to turn them on, if you've got them off

**Comment by zeenk** [comment]
![2022-05-16_19-39-23](https://user-images.githubusercontent.com/68170439/168651249-7ccea4a6-382a-4def-a4d7-8edad5f59fbf.png)

Same thing as Alexander mentioned just happened to me, got stuck like this but just clicking cancel and then calculate again fixes it, sadly did not have lua errors enabled when this happened so can't give ya any more information about it.

**Comment by teelolws** [comment]
Yeah I've had that a couple of times. Its the internal double-checks of the followers. Something is happening that assigns the wrong followers to the mission, so the addon doesn't send them out. To protect you from having the wrong follower sent out, TLDR stops. Just, as you said, press Cancel and start it again.

**Comment by Frici42** [comment]
I am not sure if this is the same issue or I should make a new ticket (flag me so and I will)

But couple past days on Kyrian I have been getting a high number of calculations then it drops to 0 and if i recalculate it goes really high then down to 0 again. 
The missions send fine but the calculation count goes/drops to 0 instead of showing how many calculations it did like before.

**Comment by teelolws** [comment]
The simulations number shown is per-missions now, not a running overall total. If it drops to zero, it means it moved onto the next mission. A nice side effect is you can now set a maximum simulations per-mission in the Advanced tab, which defaults to 30,000.
