### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by TGJH** [TLDRMissions/TLDRMissions#225]
Zipped file added.

Github won't allow you to upload a .lua file directly, but you can either .zip it up or just copy/paste the entire contents of the file here.
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8712944/TLDRMissions.zip)

**Comment by teelolws** [comment]
Thanks! Will be fixed next patch.
