### ISSUE TITLE
Add a 'short missions' filter

### ISSUE THREAD

**Issue by arcadepro** [TLDRMissions/TLDRMissions#227]
Add an option to only consider missions shorter than 5 hours.

**Comment by teelolws** [comment]
Uh yeah I could add a mission duration filter. A slider like the anima cost ones. I'll put it on the wishlist for the future.

**Comment by teelolws** [comment]
Coming soon:
![image](https://user-images.githubusercontent.com/49792789/169623223-d4e116c7-fe95-4723-a306-e89f4ff97c5d.png)
