### ISSUE TITLE
Feature Req: Optimize XP gain

### ISSUE THREAD

**Issue by rodalpho** [TLDRMissions/TLDRMissions#228]
I have a bunch of alts leveling up their followers with TLDRmissions. To simplify, lets say I only care about two rewards, follower XP (priority 1) and gold (priority 2).

a) XP missions: I would like them to be packed with as many non-level-60 followers as possible, as they all get that XP reward. 

b) Gold missions: I want them to be completed with a single follower for efficiency, alongside as many troops as required to guarantee success.

As far as I can tell there's no way to do this right now, we have to pick between behaviors by changing the option for follower  count under advanced prefs.

**Comment by teelolws** [comment]
For a) check out the special treatment option, it overwrites the other settings for missions that award Bonus Follower XP:
![image](https://user-images.githubusercontent.com/49792789/169156761-ef0a0f87-8839-4c3a-bf9c-e3b0fa875151.png)

Then for b) just set it up how you would with gold as a priority below XP missions

**Comment by rodalpho** [comment]
When I check the "special treatment for XP missions" checkbox, the addon tries to send a single follower on an anima mission, even though I have bonus XP as priority #1. See screenshots.

Then when I uncheck that box, it wants to send a SINGLE follower on the XP mission. This does respect my order, but only wants to send one guy. See screenshot.

What I want is to send all three of my followers on that XP mission and then be done with it.
![settings2](https://user-images.githubusercontent.com/747832/169302347-8a79dad3-9ff5-42f7-ac76-7b7dad96961c.jpg)
![settings3](https://user-images.githubusercontent.com/747832/169302348-8ca04898-991a-496a-b631-0dab1bf2f604.jpg)
![companions1](https://user-images.githubusercontent.com/747832/169302349-71def416-4fd0-49c8-b719-2e3d63912ccd.jpg)
![settings](https://user-images.githubusercontent.com/747832/169302351-a9ab4ce5-e9d0-4469-91e2-1678405825b1.jpg)

**Comment by teelolws** [comment]
Why do you only have 3 followers? The "special treatment" option requires a minimum of 4 followers. Because other players deemed < 4 followers on XP missions to be a "waste".

**Comment by rodalpho** [comment]
Ahh, that's the problem then. 

Briefly, the optimal way to level followers on an alt is to go Night Fae, only get Niya, level her up quickly to get all troops up to level 60, and then get the remaining followers. On a couple of my alts I messed up and got all three of the initial followers. Most of the rest just have Niya.
