### ISSUE TITLE
Rahel - Slicing Shadows targetting

### ISSUE THREAD

**Issue by zeenk** [TLDRMissions/TLDRMissions#229]
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8723236/TLDRMissions.zip)
2227 failed 060c

Damn it was hoping for a full day without any fails or discrepancies

**Comment by zeenk** [comment]
Btw for future discrepancy reports, I saw you made some new issue templates for those. Can I still do mega posts if I would get more than 1 in a session or do you only want 1 ID per issue now?

**Comment by teelolws** [comment]
Doesn't really matter. Your choice.

**Comment by teelolws** [comment]
The log you posted here https://github.com/TLDRMissions/TLDRMissions/issues/127#issuecomment-1133947759 conflicts with this one in a way I don't understand.

			"Rahel[3] meleed Green Slime[7][0HP] for 320 damage.", -- [88]
			"Rahel[3] killed Green Slime[7][0HP].", -- [89]
			"Rahel[3] cast Slicing Shadows at Green Slime[5][0HP] for 288  damage.", -- [90]
			"Rahel[3] killed Green Slime[5][0HP].", -- [91]
			"Venthyr Soulcaster[1] shot Slime Cat[11][828HP] for 295 damage.", -- [92]

vs

			"Rahel[2] meleed Necrotic Ritualist[7][0HP] for 320 damage.", -- [118]
			"Rahel[2] killed Necrotic Ritualist[7][0HP].", -- [119]
			"Rahel[2] cast Slicing Shadows at Warden of Rituals[11][2142HP] for 383  damage.", -- [120]
			"Rahel[2] cast Slicing Shadows at Necrotic Ritualist[12][36HP] for 383  damage.", -- [121]

The attack: "Rahel cheerfully slices the closest enemy and hurls a dagger at the farthest enemy, dealing $s1 Shadow damage to both."

**Comment by teelolws** [comment]
"Rahel[2] meleed Deviant Scholar[10][0HP] for 350 damage.", -- [88]
			"Rahel[2] killed Deviant Scholar[10][0HP].", -- [89]
			"Rahel[2] cast Slicing Shadows at Deviant Scholar[11][481HP] for 315  damage.", -- [90]
			"Rahel[2] cast Slicing Shadows at Tempted Scholar[8][466HP] for 315  damage.", -- [91]
			"Deviant Scholar[11] shot Rahel[2][62HP] for 136 damage.", -- [92]

**Comment by teelolws** [comment]
The target can be the same:

"Rahel[0] meleed Invasive Lasher[10][0HP] for 350 damage.", -- [84]
"Rahel[0] killed Invasive Lasher[10][0HP].", -- [85]
"Rahel[0] cast Slicing Shadows at Invasive Creeper[8][770HP] for 315  damage.", -- [86]
"Invasive Creeper[8] cast Drust Thorns at Rahel[0][254HP] for 170  damage.", -- [87]
"Rahel[0] cast Slicing Shadows at Invasive Creeper[8][455HP] for 315  damage.", -- [88]

**Comment by teelolws** [comment]
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8904038/TLDRMissions.zip)

Now I have one where it kills its autoattack target, its first spell target, but still continues on to cast the second spell.
