### ISSUE TITLE
Subcategories for Sanctum Feature

### ISSUE THREAD

**Issue by cpuritscher** [TLDRMissions/TLDRMissions#230]
TLDR version: Check if the currency the mission is for is at its limit before sending it

I think the only limited currency you can get from the mission table is the Venthyr "Infused Ruby" (=1820)

**Comment by teelolws** [comment]
Its a nice idea in theory, but remember the mission takes time to finish. Maybe the player plans to spend them before the mission finishes?

**Comment by teelolws** [comment]
The sanctum feature rewards could be the way to go. The list is really really really long though :x

**Comment by cpuritscher** [comment]
No idea if it helps, Covenant rewards can appear only in the missions 2210,2272,2192 and 2293, and if it weren't for the Venthyr they would be quite straight forward:

<pre>
Venthyr		
item	168583	Widowbloom
item	170554	Vigil's Torch
item	171264	Potion of Shaded Sight
item	171267	Spiritual Healing Potion
item	171301	Spiritual Anti-Venom
item	171831	Phaedrum Ore
item	171840	Porous Stone
item	172230	Soul Dust
item	172902	Bomb Bola Launcher
item	173049	Tome of the Still Mind
item	173109	Angerseye
item	173202	Shrouded Cloth
currency	1816	Sinstone Fragments
currency	1820	Infused Ruby
item	168589	Marrowroot
item	171263	Potion of Soul Purity
item	171266	Potion of the Hidden Spirit
item	171274	Potion of Spectral Stamina
item	171828	Laestrite Ore
item	171832	Sinvyr Ore
item	171841	Shaded Stone
item	172416	Enchant Bracers - Shaded Hearthing
item	172904	Shadow Land Mine
item	173059	Luminous Ink
item	173141	Masterful Laestrite Choker
item	177061	Twilight Bark
		
Kyrian		
currency	1819	Medallion of Service
		
Nightfae		
item	177699	Greater Untamed Spirit
item	178880	Greater Dutiful Spirit
item	178877	Greater Martial Spirit
item	178883	Greater Prideful Spirit
		
Necrolords		
item	183744	Superior Parts
</pre>

**Comment by teelolws** [comment]
Yeah I have that list coded in already. Its how it detects if the reward is a "sanctum feature" reward. But all those Venthyr rewards means a dropdown list will get quite long. I'll put it on the wishlist and see how it goes.

**Comment by teelolws** [comment]
Well thats a lot of space, but at least it doesn't take up the whole screen
![image](https://user-images.githubusercontent.com/49792789/169675194-af84a369-4df6-4b4a-a252-37f5da505786.png)
