### ISSUE TITLE
Equipment - subfilter based on vendor price

### ISSUE THREAD

**Issue by Bexoday** [TLDRMissions/TLDRMissions#237]
Some items have 120-160 vendor gold value which is quite fine.

**Comment by teelolws** [comment]
Not sure what you mean. The "Equipment" filter *is* gear.

**Comment by Bexoday** [comment]
Rewards from equipment missons come with different sell price. Necks can be sold to a vendor for 35 gold while weapons for 160.  I want to ignore missons with low sell price.

**Comment by teelolws** [comment]
I'll add it to the list.

**Comment by teelolws** [comment]
In progress:
![image](https://user-images.githubusercontent.com/49792789/169674760-4864ad2c-ef70-47d9-af2d-4ef239be35e2.png)

![image](https://user-images.githubusercontent.com/49792789/169674764-7091eda3-c621-4611-846d-f368b03a1489.png)
