### ISSUE TITLE
[Feature request] Anima tresholds to send out certain types of missions

### ISSUE THREAD

**Issue by Cealeth** [TLDRMissions/TLDRMissions#240]
TLDR version: set treshold to send out certain missions based on how much anime you have

I cycle through a bunch of characters with this addon but on some characters the anima is drained and I am constantly changing the config. Would be wonderful if I can setup a profile for example:

1. Anima missions
2. if >500 anima: Gold missions
3. if >1k anima: Crafting Materials
4. if >2k anima: runes, rep, ....

Thank you!

**Comment by teelolws** [comment]
I mean... thats a level of automation that would be so niche, you'd probably be the only one to use it. That means coding time and taking up space on the UI. Can you not just set up the profiles, and switch them yourself based on the character's anima?

If you really want to automate it, make a macro like:

`/run local a = C_CurrencyInfo.GetCurrencyInfo(C_CovenantSanctumUI.GetAnimaInfo()).quantity if a < 500 then TLDRMissions:RestoreProfile("AnimaProfile") else TLDRMissions:RestoreProfile("GoldProfile") end`

Fill in the name you gave the profile, add the other conditions. Maybe you could fit it into a Weakaura that triggers when you login?

**Comment by Cealeth** [comment]
Oke thank you, I will look into that
