### ISSUE TITLE
Wrong followers being sent on Breaking the Briarbane [Mission 2266]

### ISSUE THREAD

**Issue by zeenk** [TLDRMissions/TLDRMissions#243]
### Mission ID

2266

### Upload the saved variable file here

[2266-062.zip](https://github.com/TLDRMissions/TLDRMissions/files/8748676/2266-062.zip)

Alright lets see if your changes in 062 fixed the issue with sending out wrong followers for this mission

**Comment by teelolws** [comment]
It did not. Its always 2266 and Night Fae Te'zan. I don't have a Night Fae to test with anymore.

**Comment by zeenk** [comment]
Aw :/

**Comment by zeenk** [comment]
[2266-065.zip](https://github.com/TLDRMissions/TLDRMissions/files/8764586/2266-065.zip)

**Comment by teelolws** [comment]
I can't really do much to fix it. I don't have a character that is Night Fae atm so I can't even test it :x

**Comment by zeenk** [comment]
Yeah it's only happening on NF so far, so u want me to keep upload logs for it if I get more are they all the same logs?

**Comment by teelolws** [comment]
No need to upload logs about it, they're not going to help. I'm working on getting another alt to 60 so I can investigate this one myself.

The good news is you don't seem to get failed missions for it at least.

**Comment by zeenk** [comment]
Okay, yeah that's good at least :P

**Comment by zeenk** [comment]
I see you added some new error message for this, it says it tried to send it but
![2022-05-25_17-56-18](https://user-images.githubusercontent.com/68170439/170305645-cad06f5d-1d1d-4190-8a21-4363f57bcd31.png)

but it did get sent out, and this was a NF char ofc :P
![2022-05-25_17-57-32](https://user-images.githubusercontent.com/68170439/170305872-3f4279fa-91d9-4b1c-8ec9-3c52b08c8984.png)

**Comment by teelolws** [comment]
So its what I suspected. Its trying to send the mission twice.

Upload the logs for that character, we'll see whether it was TLDRMissions that sent it the first time, or another addon is interfering.

**Comment by zeenk** [comment]
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8774332/TLDRMissions.zip)
I'm pretty sure it was this one

**Comment by teelolws** [comment]
Okay not addon interference then. I think something is "clicking" that Start Mission button twice. Well that new error message will suppress the second click. I'll remove the message and set it to continue calculations instead.

**Comment by zeenk** [comment]
It went through without any errors this time with 067, just have to wait and see tomorrow if I get discrepancy for it

https://user-images.githubusercontent.com/68170439/170410365-d51a697f-2010-4ff7-92de-434c5f8630ca.mp4

**Comment by teelolws** [comment]
The latest code is stopping the second attempt before it can try and start it, and before it saves a log. If there is a discrepancy tomorrow, then I'm out of ideas!

**Comment by zeenk** [comment]
uh want me to upload the lua now?

**Comment by teelolws** [comment]
Sure

**Comment by zeenk** [comment]
oh you mean ingame?

**Comment by teelolws** [comment]
Yeah. Look in Venture Plan to see what followers are on the mission.

**Comment by zeenk** [comment]
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8776064/TLDRMissions.zip)

**Comment by teelolws** [comment]
Yup. Kota + Dream + 3 Trappers in that log.

**Comment by zeenk** [comment]
![2022-05-26_05-39-04](https://user-images.githubusercontent.com/68170439/170411258-f3e78aae-948e-456d-bef4-c0511d23134a.png)

**Comment by zeenk** [comment]
👍

**Comment by teelolws** [comment]
I wonder that its not the mission, its the need for 2 followers to finally get a success. And this mission is just a difficult mission that pops up most often when this happen. I'll need to take a closer look at the way my 2-followers loop is dealt with.

**Comment by zeenk** [comment]
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8776086/TLDRMissions.zip)
Check if this one also matches, just got sent out on another nf char with 067b
![2022-05-26_05-42-39](https://user-images.githubusercontent.com/68170439/170411714-e8f7f13d-53e2-4ef1-ae5f-cce54cc2b152.png)

Looks like you had solved the problem with this issue now, i'll report back tomorrow with the results ^^

**Comment by teelolws** [comment]
The log says Te'zan, Dreamweaver, a trapper, and 2 grovetenders. I don't know what those icons are though.

**Comment by zeenk** [comment]
That is correct then

**Comment by zeenk** [comment]
And yes this is a pretty hard mission, my venthyr alt here can't beat it with a full follower setup lol.. night fae is just too stronk

![2022-05-26_05-50-44](https://user-images.githubusercontent.com/68170439/170412319-1973312c-1156-4cc4-9ced-76cca550ed3d.png)

**Comment by teelolws** [comment]
Oh yeah I was wrong about it being NF only. I had it on my Kyrian and couldn't beat it either.

**Comment by zeenk** [comment]
Hmm I just got a discprenacy for 2266 but on Necrolord char this time 🤔

[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8776171/TLDRMissions.zip)

**Comment by teelolws** [comment]
That ones a genuine discrepancy.

![image](https://user-images.githubusercontent.com/49792789/170413938-20e5ec72-ebe8-4e21-8bec-3fbc3eb72acc.png)


Wrong target from "CHARGE!" led to the troop finishing with less HP than the addon predicted.

**Comment by teelolws** [comment]
The most recent bunch of issues I'm finding, which includes that one, are spells that say they target "the closest ally". But when the combat log comes back, it targetted itsself. It turns out, some of the spells that say "closest ally" actually target "either an ally next to me, or if they're all dead, then myself". I can't just do a sweeping change to all the "closest ally" spells because some of them don't follow that logic. So I have to wait until I get a combat log to fix it :x

**Comment by zeenk** [comment]
oof that sounds annoying to deal with but you're doing amazing work trying to fix it👍

**Comment by zeenk** [comment]
The 2 nf characters did not get any discrepancies for 2266 today, seem to be working  as it should now :D

**Comment by teelolws** [comment]
Good. If it happens again reopen this.

**Comment by zeenk** [comment]
Hmm I think it's trying to send this mission twice again, I saw it sent it before this and then it got stuck, was it a blizzard error or something you could try fix?

![2022-05-29_19-45-53](https://user-images.githubusercontent.com/68170439/170884251-95e358e5-8d25-4817-be53-61004d7a2ab9.png)

**Comment by zeenk** [comment]
Sent this mission out again on another nf alt and had no problems this time but maybe because it was the last mission in the queue 🤔

**Comment by zeenk** [comment]
Weird, I changed the mission prio so anima missions would get sent out first to see if that was causing it to break but it went through just fine this time on 3rd nf alt 🤔 
https://user-images.githubusercontent.com/68170439/170885493-b6d255d9-d063-4db4-8bad-6b8a48644b53.mp4

**Comment by teelolws** [comment]
I don't know why it keeps trying to send out two setups for that mission. I'm out of ideas. At least its catching its own mistake and stopping though. You can just cancel and restart calculations when it happens.

**Comment by zeenk** [comment]
Yea
