### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by Kanegasi** [TLDRMissions/TLDRMissions#245]
### Upload your Saved Variables here

[TLDRMissions.txt](https://github.com/TLDRMissions/TLDRMissions/files/8748764/TLDRMissions.txt)

(SavedVariables files are .txt files, WoW just names the extension .lua which doesn't mean anything)

**Comment by teelolws** [comment]
Thanks. Found a mistake in the targeting of Deranged Gouge https://www.wowhead.com/adventure-combatant-ability/deranged-gouge-125 in the simulator engine.

It will be fixed in the next patch.
