### ISSUE TITLE
[Feature request] Make Profiles account wide

### ISSUE THREAD

**Issue by ChristopherL01** [TLDRMissions/TLDRMissions#246]
Please change the way **Profiles** are stored to be account wide & not per character.

Profiles are actually stored **per character**, and any changes done to them aren't propagated on other toons which uses the same profile.
If you make any change to said Profile on one character, when going on another character _(which uses the same one)_ you have to :
1. go to the TLDR Missions › Profile tab
2. open the Restore Profile dropdown
3. select the previously modified Profile to bring the new changes in

Make this on 20 characters, and you're in heaven ^^

Thanks !

**Comment by teelolws** [comment]
They **are** account wide.

**Comment by ChristopherL01** [comment]
Well, that is the point of the feature request, to make them as an _"active profile"_ ;)
