### ISSUE TITLE
[Feature Request] Override Follower Number for Bonus EXP Missions

### ISSUE THREAD

**Issue by braddyb7** [TLDRMissions/TLDRMissions#251]
TLDR version:  
Ability to override the setting for number of followers to send on a mission for ones offering bonus EXP

Longer Version:
The "Prefer fewest or most followers?" setting will attempt to put only 1 follower on bonus exp missions if set to fewest. Adding a button to override this only for bonus exp missions would be great, as they could then pile in as many followers as possible to get max benefit from the exp.

**Comment by teelolws** [comment]
This option? Or do you want to customise it further? It currently expects 4 or 5 followers, but I'm considering ways to add an option to change the minimum followers
![image](https://user-images.githubusercontent.com/49792789/169907587-0ed12602-e500-4d6f-8612-c894a7059995.png)

**Comment by braddyb7** [comment]
Yeah that one, sorry :)
