### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by BradCOnGitHub** [TLDRMissions/TLDRMissions#260]
### Upload your Saved Variables here

I'm actually getting a lot of failed missions. I think 3 of them failed the last time I ran missions.

TLDRMissionsOptions = {
	["lowestOrHighest"] = "lowest",
	["moreOrLessTroops"] = "more",
	["durationLower"] = 1,
	["hardestOrEasiest"] = "hard",
	["excludedRewards"] = {
		"followerxp", -- [1]
		"anima", -- [2]
		"sanctum", -- [3]
	},
	["animaCosts"] = {
		["FollowerXPItems"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["Anima"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["Reputation"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["AugmentRunes"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["Runecarver"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["SanctumFeature"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["Campaign"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["Gold"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["FollowerXP"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["Gear"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["CraftingCache"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
		["PetCharms"] = {
			["10-49"] = true,
			["100+"] = true,
			["50-99"] = true,
		},
	},
	["animaItemQualities"] = {
		true, -- [1]
		true, -- [2]
		true, -- [3]
		true, -- [4]
	},
	["followerXPSpecialTreatmentMinimum"] = 4,
	["durationHigher"] = 24,
	["craftingCacheTypes"] = {
		[8613] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[2575] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[2366] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		["zereth"] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[3908] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[7411] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[2550] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
		[131474] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
		},
	},
	["reputations"] = {
		[1806] = true,
		[1804] = true,
		[1805] = true,
		[1807] = true,
	},
	["workPerFrame"] = 10,
	["fewestOrMost"] = "fewest",
	["selectedRewards"] = {
		"pet-charms", -- [1]
		"augment-runes", -- [2]
		"reputation", -- [3]
		"gold", -- [4]
		"crafting-cache", -- [5]
		"gear", -- [6]
	},
	["sanctumFeatureCategories"] = {
		[171831] = true,
		[1820] = true,
		[173141] = true,
		[178880] = true,
		[1819] = true,
		[178877] = true,
		[171266] = true,
		[171301] = true,
		[171274] = true,
		[172904] = true,
		[171840] = true,
		[168589] = true,
		[172902] = true,
		[171263] = true,
		[170554] = true,
		[1816] = true,
		[172230] = true,
		[168583] = true,
		[171841] = true,
		[171267] = true,
		[177699] = true,
		[171264] = true,
		[171828] = true,
		[177061] = true,
		[171832] = true,
		[173109] = true,
		[173049] = true,
		[178883] = true,
		[173059] = true,
		[173202] = true,
		[172416] = true,
		[183744] = true,
	},
	["gearGoldCategories"] = {
		["70-79"] = true,
		["40-49"] = true,
		["100+"] = true,
		["0-19"] = true,
		["60-69"] = true,
		["90-99"] = true,
		["30-39"] = true,
		["50-59"] = true,
		["20-29"] = true,
		["80-89"] = true,
	},
	["runecarver"] = {
		[1767] = false,
		[1828] = true,
		[2009] = true,
		[1906] = true,
	},
	["estimateLimit"] = 30000,
}
TLDRMissionsLogging = {
}

**Comment by teelolws** [comment]
Are you sure they're actually failing? Theres nothing in that log to suggest anything failed. If you're using Venture Plan to finish the missions, it often claims a mission failed when it didn't actually fail.
