### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by Rathaniel** [TLDRMissions/TLDRMissions#262]
### Copy/paste the Lua error here

4x TLDRMissions\simulation.lua:615: attempt to index field '?' (a nil value)
[string "@TLDRMissions\simulation.lua"]:615: in function <TLDRMissions\simulation.lua:595>
[string "@TLDRMissions\simulation.lua"]:808: in function <TLDRMissions\simulation.lua:709>
[string "@TLDRMissions\simulation.lua"]:1166: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function <TLDRMissions\simulation.lua:1101>
[string "@TLDRMissions\simulation.lua"]:1175: in function `turnRecursion'
[string "@TLDRMissions\simulation.lua"]:1182: in function <TLDRMissions\simulation.lua:23>
[string "@TLDRMissions\simulation.lua"]:1299: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:7: in function `func'
[string "@TLDRMissions\workhandler.lua"]:50: in function <TLDRMissions\workhandler.lua:23>

Locals:
follower = <table> {
 maxHP = 1160
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 0
 name = "Lloth'wellyn"
 followerID = "0x000000007072538D"
 baseAttack = 406
 buffs = <table> {
 }
 HP = 509
 thorns = <table> {
 }
}
spells = <table> {
 effects = <table> {
 }
 onCooldown = 3
 duration = 0
 cooldown = 3
 spellID = 95
}
rngTargets = nil
overrideTarget = <table> {
}
targetType = "furthest_enemy"
result = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(for control) = 1
i = 1
t = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
 maxHP = 1160
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 0
 name = "Lloth'wellyn"
 followerID = "0x000000007072538D"
 baseAttack = 406
 buffs = <table> {
 }
 HP = 509
 thorns = <table> {
 }
}
(*temporary) = <table> {
 effects = <table> {
 }
 onCooldown = 3
 duration = 0
 cooldown = 3
 spellID = 95
}
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to index field '?' (a nil value)"
getTargets = <function> defined @TLDRMissions\simulation.lua:108
processSpell = <function> defined @TLDRMissions\simulation.lua:514

I used bugsack hope this info is what you need, all other addons turned off.

**Comment by teelolws** [comment]
Thanks for the report. Will be fixed next patch.
