### ISSUE TITLE
[BUG] Lua error (zero anima mission ?)

### ISSUE THREAD

**Issue by zalidthebur** [TLDRMissions/TLDRMissions#264]
### Copy/paste the Lua error here

Happened when I ran missions. Could be tied to running our of anima, though this is regular on this character (running out of anima).

Date: 2022-05-25 18:53:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\TLDRMissions\guihandlers.lua line 526:
   attempt to compare number with nil
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=[C]"]: ?
   [string "@TLDRMissions\guihandlers.lua"]:526:
      TLDRMissions\guihandlers.lua:501
   [string "@TLDRMissions\guihandlers.lua"]:275:
      TLDRMissions\guihandlers.lua:216
   [string "@TLDRMissions\combinations.lua"]:354:
      TLDRMissions\combinations.lua:352
   [string "@TLDRMissions\combinations.lua"]:20:
      TLDRMissions\combinations.lua:7
   [string "@TLDRMissions\simulation.lua"]:1309: callback()
   [string "@TLDRMissions\simulation.lua"]:1201:
      TLDRMissions\simulation.lua:23
   [string "@TLDRMissions\simulation.lua"]:1308: Simulate()
   [string "@TLDRMissions\combinations.lua"]:7: func()
   [string "@TLDRMissions\workhandler.lua"]:50:
      TLDRMissions\workhandler.lua:23
Locals:
errMsg = "Interface\AddOns\TLDRMissions\guihandlers.lua:526: attempt to compare number with nil"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:609
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  swatter, v<%version%> (<%codename%>)
  WowheadLooter, v90200
  Ace3, vRelease-r1259
  AchievementsReminder, v
  AckisRecipeList, v9.1.0.1
  AckisRecipeListQuickScan, v7.3.0.1
  ACP, v3.5.7 
  AddonFactory, v9.2.001
  AdiBags, vv1.9.26
  AdvancedInterfaceOptions, v1.7.1
  AllTheThings, vSL-2.7.12
  Altoholic, v9.2.001
  Armory, vv16.5.0
  ArmoryGuildBank, vv16.5.0
  AskMrRobot, v111
  Auctionator, v9.2.17
  BadBoy, vv9.2.2
  BarrelsOEasy, v1.2.02
  BattlePetDailyTamer, v3.1.9
  BattlePetBreedID, vv1.20.2
  BonusRollPreview, v90000.48-Release
  BtWObjectiveFilter, v1.3
  BtWQuests, v2.14.0
  BtWQuestsBattleForAzeroth, v53.11
  BtWQuestsShadowlands, v5.3
  BtWQuestsShadowlandsPrologue, v1.6
  CanIMogIt, v9.1.5v1.32
  Chinchilla, vv2.12.2
  ClassTimer, v2.4.90001.1
  Collectinator, v9.0.2
  CollectionShop, v4.04
  CollectMe, v2.11
  ConfirmSP, v0.21.07.06
  CovenantMissionHelper, v3.2.0
  DataStore, v2022.03.14
  DataStoreAchievements, v9.2.001
  DataStoreAgenda, v9.2.001
  DataStoreAuctions, v9.2.001
  DataStoreCharacters, v2022.04.24
  DataStoreContainers, v9.2.001
  DataStoreCrafts, v9.2.003
  DataStoreCurrencies, v9.2.001
  DataStoreGarrisons, v9.2.003
  DataStoreInventory, v9.2.001
  DataStoreMails, v2022.03.14
  DataStorePets, v9.2.001
  DataStoreQuests, v9.2.003b
  DataStoreReputations, v9.2.002
  DataStoreSpells, v2022.03.14
  DataStoreStats, v9.2.001
  DataStoreTalents, v9.2.001
  DBMCore, vb1468f5
  DBMStatusBarTimers, vb1468f5
  DBMVPVEM, v9d95365
  DeathAlerts, v1.2
  Decursive, v2.7.8.5
  DejaCharacterStats, vR90200r3
  Dejunk, v9.1.2
  Details, v
  DetailsDataStorage, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDelete, v9.0.1
  EasyMail, v4.4.9
  ExaltedPlus, v15
  ExRT, v4630
  FactionAddict, v1.72
  FamilyFamiliarHelper, v1.4.9
  FishingBuddy, v1.16.10
  FlaresThatWork, vr47
  FocusHealthPercent, v4.0.1
  GarrisonMissionManager, vv62
  GTFO, v4.66.6
  GuildRosterManager, v1.9297
  GuildBankSnapshots, vv2.0.9
  GuildCheck, vv 2.5.1
  HandyNotes, vv1.6.5
  HandyNotesArgus, vv0.34
  HandyNotesBattleForAzeroth, v9
  HandyNotesBattleForAzerothTreasures, vv22
  HandyNotesBrokenShore, vv1.47
  HandyNotesDungeonLocations, v1.54
  HandyNotesLegionTreasures, vv25
  HandyNotesLostAndFound, vv16
  HandynotesPandaria, v1.5.1
  HandyNotesShadowlandsTreasures, vv64
  HandyNotesTreasureHunter, vv25
  HandyNotesWorldMapButton, v90200.01-Retail
  InFlightLoad, v9.2.0
  InstanceAchievementTracker, v3.40.0
  InterruptNoSpam, v1.8.5
  LargerMacroIconSelection, vv1.7.2
  LoggerHeadLite, v1.5.6
  LootSpecSwapper, v9.2.0.02
  MageNuggets, v7.0.3
  MasterPlanA, vA
  MaxDps, v9.1.5
  MinimalArchaeology, v9.2.0
  MinimapButtonFrame, v3.2.2
  MinimapButtonFrameSkinPack, v3.0.1b
  mOnArsWardrobeHelper, v1.21
  MRT, v4630
  Notes, v9.1.1
  Omen, v3.2.4
  OneClickEnchant, v9.2.0-release(r1)
  Overachiever, v1.1.5
  OverachieverCache, v1.1.5
  OverachieverTabs, v1.1.5
  OverachieverTrade, v1.1.5
  PakuTotems, v1.62
  PetBattleMaster, v9.0.1
  PetTracker, v9.2.0
  PetTrackerConfig, v
  PetTrackerJournal, v
  Plexus, vv2.2.27
  PointBlankSniper, v5.1
  QuestSounds, v901-2020.10.14
  QuickMark, v
  QuizHelper, v
  RaidAchieveFilter, v2.0.5
  RareScanner, v9.2.0.8
  Rematch, v4.11.23
  SavedInstances, v9.2.2
  SetCollector, v3.3.6
  SharedMediaCausese, v
  SilverDragon, vv90200.11
  SilverDragonBattleForAzeroth, vv90200.11
  SilverDragonBurningCrusade, vv90200.11
  SilverDragonCataclysm, vv90200.11
  SilverDragonLegion, vv90200.11
  SilverDragonMists, vv90200.11
  SilverDragonOverlay, vv90200.11
  SilverDragonRangeExtender, vv90200.11
  SilverDragonShadowlands, vv90200.11
  SilverDragonVanilla, vv90200.11
  SilverDragonWarlords, vv90200.11
  SilverDragonWrath, vv90200.11
  SkillHelper, vv4.1.13
  SoulshapeJournal, v1.2.1
  Stubby, v<%version%> (<%codename%>)
  SuperDuperMacro, vretail 9.0.1.2, classic 1.13.5.4
  TargetHealthPercent, v5.0
  tdBattlePetScript, v9.0.1
  tdBattlePetScriptRematch, v80100.01
  TellMeWhen, v9.2.3
  TheUndermineJournal, v5.6.20220524
  TidyPlatesThreatPlates, v10.3.7
  TLDRMissions, v9.2-066
  TokenSplainer, vr04
  TomTom, vv3.0.6
  TradeSkillMaster, vv4.11.29
  TradeSkillMasterAppHelper, vv4.0.20
  tullaRange, v9.2.0
  VenturePlan, v4.16a
  WarfrontRareTracker, v1.2.6
  WeakAuras, v4.0.1
  WorldQuestTracker, v
  XanDurability, v5.0
  ZerethMortisPuzzleHelper, v1.5
  ZygorGuidesViewer, v8.1
  BlizRuntimeLib_enUS v9.2.0.90200 <none>
  (ck=119e)

**Comment by teelolws** [comment]
Hmm. Apparently you have a mission that doesn't cost any anima. I didn't know this was possible.

**Comment by zalidthebur** [comment]
Me neither :-O
I checked now, but looks like the mission has gone. I'll keep an eye for this happening again.

**Comment by teelolws** [comment]
Thinking about it further, errors like this could happen if you've somehow opened the addon while you're not at the mission table. I remember getting a similar error when I left the calculations going while I teleported to Oribos.

**Comment by zalidthebur** [comment]
That definitely was not the case here. I've never walked away from a mission table with calculations ongoing yet ;-)

**Comment by teelolws** [comment]
Well I'm not sure how you managed to get this. According to the wowhead mission database, the only Shadowlands mission that doesn't cost anima is a test mission meant for the developers. 

Either way I added a check to suppress the error and continue if it doesn't get anima cost data.

**Comment by zalidthebur** [comment]
Wish I'd screenshot it. Guess we'll never know how this occurred now :-D
