### ISSUE TITLE
Dead companion selected for mission.

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#269]
My companion is dead (0 HP), but the addons tries to send him for mission. Wow does not allow to even choose this companion until it's healed, so "Start mission" won't work.
![image](https://user-images.githubusercontent.com/25015943/170471077-5b0d03d6-1d11-4f38-878a-07941a46ca0e.png)

**Comment by deNoor** [comment]
At 6 HP this companion was successfully assigned for mission. Let's wait for outcome.

**Comment by teelolws** [comment]
Its not dead. It has 3HP. Thats in your picture: "Health 3/440". Its perfectly fine to go out on a mission. The troops will carry it.

**Comment by deNoor** [comment]
The game actually didn't allow me to assign this companion at 0-3 HP. :) I noticed because addon's "Start mission" did nothing and also tried to start manually.
The mission started successfully at 6 HP.

**Comment by teelolws** [comment]
Hmm. If there really is a minimum HP to send out a follower, I'll add a workaround for it. I'll investigate.

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/170604002-b3547766-a079-47e4-a471-ce8ff62ad365.png)
![image](https://user-images.githubusercontent.com/49792789/170604020-81f7aa26-4172-46bf-a544-4c7af54ff210.png)
![image](https://user-images.githubusercontent.com/49792789/170604045-79478c54-28b1-4264-8d80-ef990b7de016.png)
![image](https://user-images.githubusercontent.com/49792789/170604061-3c8ccebf-3c6f-4ed5-8ad3-43b9307c3771.png)

It doesn't allow me to start the mission when the follower has 0HP. That only really happens for the first 10-20 seconds after a follower finishes a mission. Once the follower has as little as 1HP, I can start it.

Heres what I'll do: I'll add a check for 0HP followers when the Calculate button is clicked. If there are any, it'll put a message like "You have a follower with 0HP. Wait about 10-20 seconds then try again".

**Comment by deNoor** [comment]
True. I was able to send with 1 HP. Unfortunately, I forgot to apply the latest update so haven't checked the new warning. :(
