### ISSUE TITLE
Anima cost is incorrect.

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#270]
Addons says: 10 anima, wow client says 14 anima (10 for a follower and +1 for every troop).
![image](https://user-images.githubusercontent.com/25015943/170474058-b9eda09a-20a1-4b7d-ad6b-cf64a41f6c28.png)
Started mission with addon to check the real cost: 1378 - 1364 = 14 anima.
![image](https://user-images.githubusercontent.com/25015943/170474219-341dcbcc-e437-46f9-a1b5-0152bc1114bf.png)

**Comment by teelolws** [comment]
The "Cost" is displayed before troops are assigned. It costs 14 because it added 4 troops to the mission to get a solution. The cost shown there only matters for the mission filter, which is in increments of 10.

**Comment by teelolws** [comment]
Next patch it will show the modified cost.
