### ISSUE TITLE
[Discrepancy EOI] I want to volunteer.

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#271]
### Github or Discord?

Github

**Comment by teelolws** [comment]
Great! Heres how to participate:

1. Run this command. You'll need to run it once on every character you want to test with. Its set-and-forget, you won't need to run it every login or anything:

`/run TLDRMissions.db.profile.DEVTESTING = true`

2. When you complete a mission, if the combat log did not exactly match the combat log that the simulator was expecting, you will see a message in chat like "DEVTESTING: Discrepancy for mission 2221". When this happens, logout, and create an issue with the Discrepancy Report template, uploading the characters saved variables.
