### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by Endlessherald** [TLDRMissions/TLDRMissions#274]
### Upload your Saved Variables here

[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8781045/TLDRMissions.zip)

**Comment by teelolws** [comment]
Hi there. Unfortunately, you have uploaded your **account-wide** saved variables. To investigate a failed mission, I need the **character-specific** saved variables of the character the mission failed on.
