### ISSUE TITLE
Faster way to calculate Corrupted Builders + Break the Briarbane?

### ISSUE THREAD

**Issue by Rathaniel** [TLDRMissions/TLDRMissions#276]
Perhaps for harder missions better followers have priority on harder missions?

https://user-images.githubusercontent.com/20883388/170581552-fd6e0a41-e1e3-410a-8f37-a63731f3e748.mp4

I had over 90k sims but in the end i sent Dreamweaver and Llothwellyn, the mission was successful but i did gamble this, the calculation took a few seconds on venture plan which is outdated.

I end up skipping these as NF.

**Comment by teelolws** [comment]
I find for missions like that, I prefer to just skip them. Then, if I still have followers left over at the end, try them again. That second time around, hopefully your lower level followers will have been sent out on other missions, and won't need to be tested anymore.  Sometimes I'll switch to "highest follower first" for that second attempt.

I don't really want to automatically switch up the priority. It might be what you want, but it won't be what others want. I'll get questioned "why did it send my lv60, I was saving it" etc.

**Comment by Rathaniel** [comment]
"I don't really want to automatically switch up the priority. It might be what you want, but it won't be what others want. I'll get questioned "why did it send my lv60, I was saving it" etc."

Ye that makes sense no problem. Thanks for all your work and hopefully this results cache will be perfected soon so you can rest :)
