### ISSUE TITLE
[BUG] Other - Ignored a mission

### ISSUE THREAD

**Issue by zalidthebur** [TLDRMissions/TLDRMissions#284]
Any idea why this mission was ignored ?
![WoWScrnShot_052722_233603](https://user-images.githubusercontent.com/22801358/170797058-9ab6be6f-663b-4c4c-8bde-180ac137c82d.jpg)
[ezyzip.zip](https://github.com/TLDRMissions/TLDRMissions/files/8790019/ezyzip.zip)

**Comment by teelolws** [comment]
Check your advanced settings. How many followers do you have available? Do you have the "special treatment for bonus XP" box checked? What about the settings for that?

**Comment by zeenk** [comment]
You don't have followers available to be able to send it out

![2022-05-28_01-36-41](https://user-images.githubusercontent.com/68170439/170800377-04097e55-4462-4cf4-9bbc-2fe95e2fe1f6.png)

**Comment by teelolws** [comment]
If you look at the TLDR settings in the pic, XP missions are supposed to be sent first. But it chose anima and gold missions over the second XP mission. There was probably a follower level limit, or they didn't have 4 followers available when it got to that mission.

**Comment by zeenk** [comment]
Ah yeah, my bad missed that part ^^

**Comment by zalidthebur** [comment]
Ah darn it. Yeah, Special Treatment was still set at the default of 4. I had changed it and saved the profile, but as you do not use account-wide profiles, it was never changed. Well at least I know why it happened now :-)
I know you were working on account-wide profiles and see that they are now enabled. Yay :)
I do not run the Curseforge app every day, so missed some updates (I'll change that). But I notice that several links are broken from the latest update: 9.2-070, Full Changelog, Previous Releases, Not sure if that is a Curseforge issue or what. But they are also broken on the Curseforge page too (https://www.curseforge.com/wow/addons/tldr-missions/files).

**Comment by teelolws** [comment]
> but as you do not use account-wide profiles,

Since a couple of versions back, I use AceDB for the profiles now. Its in the options somewhere to use account-wide profiles. Character-specific is just the default now.

**Comment by zalidthebur** [comment]
Got that now. Nice addition :-)
