### ISSUE TITLE
[BUG] Lua error FrameXML\CompactUnitFrame.lua:1122 (In combat Lua error since one of the recent patches)

### ISSUE THREAD

**Issue by Asherak** [TLDRMissions/TLDRMissions#286]
### Copy/paste the Lua error here

1287x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}

**Comment by Asherak** [comment]
Copy of my taint.log from part of a dungeon where the error was occuring: 

5/28 12:35:39.046  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame3:Show()
5/28 12:35:39.046      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:35:39.046      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:35:39.046      Interface\FrameXML\CompactUnitFrame.lua:116
5/28 12:35:40.327  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame3:Show()
5/28 12:35:40.327      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:35:40.327      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:35:40.327      Interface\FrameXML\CompactUnitFrame.lua:116
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame1:ClearAllPoints()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame1:SetPoint()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame2:ClearAllPoints()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame2:SetPoint()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame3:ClearAllPoints()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame3:SetPoint()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame4:ClearAllPoints()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame4:SetPoint()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame5:ClearAllPoints()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame5:SetPoint()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
5/28 12:36:01.664      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
5/28 12:36:01.664      CompactRaidFrameContainer:OnEvent()
5/28 12:36:01.664  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua:372 CompactRaidFrameManager_GetSetting()
5/28 12:36:01.664  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrameManagerContainerResizeFrame:Hide()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua:574 CompactRaidFrameManager_LockContainer()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua:567 CompactRaidFrameManager_UpdateContainerLockVisibility()
5/28 12:36:01.664      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua:56
5/28 12:36:01.665  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame1:Show()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:48
5/28 12:36:01.665  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame2:Show()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:48
5/28 12:36:01.665  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame3:Show()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:48
5/28 12:36:01.665  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame4:Show()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:48
5/28 12:36:01.665  An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame5:Show()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
5/28 12:36:01.665      Interface\FrameXML\CompactUnitFrame.lua:48

**Comment by Asherak** [comment]
Some context:
Was doing some timewalking dungeons when I noticed bugsack picking up these Lua errors like crazy. Ran a taint log and came back with TLDR being the offender. Verified this by disabling the addon and running multiple more dungeons with no further issues.

Suspect the issue has come up within the last week~ or so, as I hadn't updated TLDR for that period of time (currently manually updating as I still use Wowup). After manually updating is when the errors started to occur. Hadn't had any issues like this prior.

**Comment by teelolws** [comment]
Its not TLDR Missions causing that. Its just some other addon that uses Ace3. TLDR is copping the blame because it loaded first for whatever reason. 

`5/28 12:35:39.046 An action was blocked in combat because of taint from TLDRMissions - CompactRaidFrame3:Show()`

This is a very common error across multiple addons. They all have one thing in common: they use Ace3 for their libraries. Google that error, remove the `TLDRMissions` bit, and you'll see pages and pages of reports of it across different addons.

**Comment by Asherak** [comment]
Suspected as much as well from my initial googling but couldn't recreate the error/taint with TLDR disabled. Reverting back to an older version of TLDR has also remedied it so I'm a bit stuck. Will keep an eye on it.

**Comment by teelolws** [comment]
Often its from mousing over a part of the UI you don't normally think of. Often its the mouseover that opens an addons menu. When I have this sort of problem, one of my checks is to get in combat with a target dummy, then slowly run my mouse over every part of my screen until an error pops up.

**Comment by Asherak** [comment]
Will have a play around later today and see if I can recreate the issue with all other weakauras disabled

**Comment by teelolws** [comment]
Okay heres what I've done. I've moved the libraries TLDR uses into a private namespace. This means they'll load and be used in isolation. It also means other addons using the same libraries will need to load their own copy. A bit of a longer loading screen time. But now, after the next update, if you get any taint issues that point to TLDR, then theres a serious problem going on. Cause my addon doesn't do anything with your raid frames, and shouldn't be causing that.

**Comment by teelolws** [comment]
Another user reported a similar issue. Are you using the addon "BigDebuffs" by any chance?

**Comment by tflo** [comment]
Have you already tried with [TaintLess](https://www.townlong-yak.com/addons/taintless)?

**Comment by teelolws** [comment]
> You may benefit from this if your addon uses UIDropDownMenu, InterfaceOptionsFrame, or parts of FrameXML that interact with these APIs.

Unless TaintLess has been expanded upon since that description was written, doesn't look like it will help here. The taint is attached to the raid frames while in a party. 
![image](https://user-images.githubusercontent.com/49792789/170824591-e04306dd-2323-40c4-94f6-9110f762f0b5.png)

**Comment by Asherak** [comment]
Haven't had a chance to play around further with disabling all add-ons except TLDR, but:
- I don't use BigDebuffs
- haven't had the error (or any other error) since rolling back to an older pre-Ace3 version of TLDR
I spammed a lot of dungeons today so I'm fairly confident I would have come up again if it was something else causing it

Will try to narrow it down more tomorrow

**Comment by teelolws** [comment]
In the next update I'm changing all UIDropDownMenu calls to use https://www.wowace.com/projects/libuidropdownmenu

If you still get this issue after that then I'm out of ideas!

**Comment by Asherak** [comment]
Did a quick test in a few dungeons with the latest release.
1. Did my mission tables, then zoned into a LFG timewalking dungeon, same error occurred almost immediately
2. Disabling TLDR fixed the issue for the remainder of the dungeon
3. Quit game, reinstalled older pre-ace3 version of TLDR (9.2-060). Sent some new missions, queued into a dungeon, no issues.
4. Re-installed latest release of TLDR and restarted game. Queued into a dungeon again - no errors occurred if I never interacted with the mission table on that load.
5. Disabled all addons except bugsack/grabber and TLDR. Was not able to force the errors to occur in any content. 

Seems like an addon conflict given that I couldn't force it to occur with only bugsack + TLDR, but would otherwise only occur if I brought up the addon ui by opening the mission table. Pre-ace3 version still works with zero issue.

When I have time I will try to go through TLDR + each addon loaded individually to see if I find the conflict (assuming that is the issue)

**Comment by teelolws** [comment]
Can you try this one
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8792506/TLDRMissions.zip)

**Comment by teelolws** [comment]
When you say "same error occurred almost immediately", do you mean this one?

> Attempt to access forbidden object from code tainted by an AddOn

If so, did you check taint.log to see what its blaming?

**Comment by Asherak** [comment]
Same error yes. Didn't check taint.log after each attempt as was just trying to narrow down what action was causing it.

Will try the new patch you linked, do some runs and check taint.log and report back

**Comment by Asherak** [comment]
**Short version: Resolved. After using the above patch, I found it is the addon Clique generating the errors after opening the Interface->AddOns menu panel, which TLDR does whenever you select the profiles tab. Don't need to read below unless you want the testing process.**

Installed the patch. Results are:
- No longer get any errors from interacting with the mission table, sending missions, changing anything in the advanced tab, etc. *EXCEPT* if I click the profiles tab.
- If I click the profiles tab from the mission table interface at any point then queue into a dungeon, I will begin getting the following 2 errors:

```
2x [ADDON_ACTION_BLOCKED] AddOn 'Clique' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
```

```
2249x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
```

The issue can be resolved by /reloading at any point after I have opened the profiles tab in TLDR - no further errors will occur.

Taint.log can be found here [https://pastebin.com/WN839D4k](https://pastebin.com/WN839D4k)

As per above it is now attributing the error source to Clique. Clique hasn't been updated since February and I'm unable to recreate any of the errors without opening the profiles tab in TLDR specifically. Double checked and can confirm that going to the profiles tab is not an issue in the pre-ace3 version of TLDR.

Disabled Clique and was no longer able to recreate the error. Still unsure if this is a Clique issue or an Addon conflict on some sort.

Given that TLDR opens the Interface->AddOns panel when selecting the profiles tab, I decided to try something else. I re-enabled Clique, did a fresh /reload, opened up the AddOns panel and went through opening all of my addons options except TLDR, then ran a dungeon - suddenly, the same errors began to appear. Reconfirmed this with a /reload and ran another dungeon, opening addon option panels during combat and the errors would start appearing.

Not sure how I didn't notice this sooner - guess I didn't go into my addon options tab much to notice it. Either way, the issue seems purely on Cliques end.

**Comment by Asherak** [comment]
On a completely unrelated note - is there any consideration for uploading this addon on WowUp as well as curse for us wowup users?

Either way cheers for your work on this addon, it's fantastic.

**Comment by teelolws** [comment]
Good to hear you found the true source of the problem. I may just remove that Profile tab at some point if it continues to be a problem. Let the user navigate to the Interface options themselves.

No plans to host outside of Curseforge. The alternatives require me to hand over a level of Intellectual Property rights that I do not agree with.
