### ISSUE TITLE
[BUG] TLDR sends Stygia missions when option is deselected

### ISSUE THREAD

**Issue by kulakai** [TLDRMissions/TLDRMissions#289]
Runecarver Crafting Currencies is checked.  Stygia and Soul Ash are not checked, while Cosmic Flux and Soul Cinders are checked.  TLDR will attempt to complete Stygia missions like "Dark Skies, Darker Prospects"

**Comment by teelolws** [comment]
The missions that award Stygia also award other stuff. Do you have that "other stuff" selected?
