### ISSUE TITLE
[Discrepancy EOI]

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#291]
### Github or Discord?

Imperator#5218

**Comment by pingje** [comment]
That's my Discord ID. Or you have me here. Either way. I run tables every day on 8 characters; mostly NF but I have one of each of the other covenants. Some are still leveling.

**Comment by teelolws** [comment]
Great! Heres how to participate:

1. Run this command. You'll need to run it once on every character you want to test with. Its set-and-forget, you won't need to run it every login or anything:

`/run TLDRMissions.db.profile.DEVTESTING = true`

2. When you complete a mission, if the combat log did not exactly match the combat log that the simulator was expecting, you will see a message in chat like "DEVTESTING: Discrepancy for mission 2221". When this happens, logout, and upload your character-specific saved variables into the TLDRMissions channel on discord.

3. I will send you an invite to the discord server directly.

**Comment by teelolws** [comment]
Can you change your Discord settings?
![image](https://user-images.githubusercontent.com/49792789/170818445-0f9ed560-e276-46c0-ae34-00c6360b21e9.png)
Feel free to change it back after.

**Comment by pingje** [comment]
It's open now.
