### ISSUE TITLE
[BUG] Other - Sacrificing followers won't send followers on missions, but also won't allow me to send them manually (possible interaction with Venture Plan?)

### ISSUE THREAD

**Issue by nzall** [TLDRMissions/TLDRMissions#292]
![image](https://user-images.githubusercontent.com/6772095/170819928-d6073598-7d0a-48cc-9a4f-5ddb2bc0f8f0.png)
****

![image](https://user-images.githubusercontent.com/6772095/170819944-94b91264-6d2d-4991-986e-55a251f75c73.png)

It appears as if the addon is trying to send followers it has already sent on other missions. In order to fix this, I need to either /reloadui, or I need to cancel and recalculate so it does use the correct followers.

**Comment by teelolws** [comment]
Yeah, there is a weird glitch that happens sometimes, where followers get stuck in a party. I can't remove them, can't send the mission. All I can do is /reload. Its something on Blizzards end, unfortunately I can't do anything about it.

**Comment by nzall** [comment]
@teelolws It appears I found a workaround for this bug by sending out followers in two attempts: first send out all missions WITHOUT having the "sacrifice followers" checkbox marked, and then when it can't send any more but there are still followers left, you can mark the "sacrifice followers" checkbox and calculate again, and in my experience it will NEVER try to send out followers that were already in a party. I've replicated this with Night Fae and Kyrian followers and it appears to always work, at least in situations where there is only 1-5 followers to send out.

Maybe you could do something with this workaround somehow?

**Comment by teelolws** [comment]
When was the last time you tried it? I pushed this fix 2 days ago when I noticed it wasn't checking if the followers were already planned for another mission:
![image](https://user-images.githubusercontent.com/49792789/171050378-208d3e1a-02ee-4b77-8413-48cc02724131.png)

**Comment by nzall** [comment]
I made that post as I found what I thought was the workaround. I am using version 9.2-068, and I hadn't yet updated the addon manually.
