### ISSUE TITLE
[BUG] Lua error  Set Focus on Raid Frame blocked by Addon

### ISSUE THREAD

**Issue by Jraken** [TLDRMissions/TLDRMissions#299]
### Copy/paste the Lua error here

2x [ADDON_ACTION_FORBIDDEN] AddOn 'TLDRMissions' tried to call the protected function 'FocusUnit()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `FocusUnit'
[string "@FrameXML\UnitPopup.lua"]:1943: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:914: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

[taint.log](https://github.com/TLDRMissions/TLDRMissions/files/8791706/taint.log)

**Comment by Jraken** [comment]
This error seems similar to Issue #286 and #288.  I can consistently trigger the "TLDRMissions has been blocked from an action..." error by joining a group (party or raid), right clicking a party member other than myself, and selecting "Set Focus".  When recreating this error to grab the taint log I noticed that sometimes there would be no error on a fresh logon unless I reloaded the UI, then I could recreate the error without fail.

I've been able to trigger the error without any other addons enabled, including Bug Sack/Bug Grabber (attached taint log is TLDRM only).  I first noticed this issue about a week ago while doing dungeons.  This only seems to happen when using Raid Frames, if I switch to regular Party Frames there is no issue.  Also does not happen if I Set Focus using the Target Frame, only Raid Frames.

Great Addon by the way, keep up the awesome work!

**Comment by teelolws** [comment]
Can you try this beta? I switched all references to UIDropDownMenu to https://www.wowace.com/projects/libuidropdownmenu
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8791803/TLDRMissions.zip)

**Comment by Jraken** [comment]
It appears that resolved the issue with Set Focus.  With the beta version I am unable to replicate the error, with our without other add-ons enabled.  Thanks!

**Comment by teelolws** [comment]
Good. I should have seen this coming. UIDropDownMenu has been a problem for a long time. I'll roll that fix out in the next patch later.
