### ISSUE TITLE
[BUG] You forgot to change to 071 in title menu?

### ISSUE THREAD

**Issue by zeenk** [TLDRMissions/TLDRMissions#303]
Just downloaded the 071 patch but still says 070, dno if it's a big deal or not but thought I would mention it to u at least lol

![2022-05-29_04-28-12](https://user-images.githubusercontent.com/68170439/170849472-09fd142a-8f22-45eb-bd0c-4e547c0bf39e.png)

**Comment by teelolws** [comment]
Er. Yeah. I didn't update the .toc
