### ISSUE TITLE
[Discrepancy] Night Fae 2333 2251 2254

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#305]
### Mission ID

2333 2251 2254

### Upload the saved variable file here

Also contains discrepancies for 2251, 2254. Night Fae.
[TLDRMissions.lua_Wawona_2333_2251_2254_20220529-120123.txt](https://github.com/TLDRMissions/TLDRMissions/files/8794090/TLDRMissions.lua_Wawona_2333_2251_2254_20220529-120123.txt)

**Comment by teelolws** [comment]
2333: spell 375 was overstatted in the simulator

2251: the problem was fixed in -072, but you sent this mission out in -070

2254: spell 235 "Targets enemies at range, calling down missles of pure maw anima, dealing $s1 Shadow damage." well thats a lie, it only hits one enemy, not all of them
