### ISSUE TITLE
[Discrepancy] Venthyr 2243

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#306]
### Mission ID

2243

### Upload the saved variable file here

[TLDRMissions.lua_Siannodel_2243_20220529-115254.txt](https://github.com/TLDRMissions/TLDRMissions/files/8794100/TLDRMissions.lua_Siannodel_2243_20220529-115254.txt)

**Comment by teelolws** [comment]
Spirits of Rejuvenation was set to do its healing at the wrong time. Start of turn when its supposed to be before the follower that cast it attacks.
