### ISSUE TITLE
Last update broke profiles

### ISSUE THREAD

**Issue by Pitikixo** [TLDRMissions/TLDRMissions#310]
With the last update when you click on the profiles tab, it redirects you to the wow-addons default screen and you can't switch profiles. Plz make it work like before </3

**Comment by teelolws** [comment]
When I click the profiles tab, it opens this:
![image](https://user-images.githubusercontent.com/49792789/170899832-b38f68ca-0ac0-49fc-8e0f-eb9f391cc6e9.png)

Got errors enabled? Getting any errors?

**Comment by Pitikixo** [comment]
Yea, i know, but yesterday it opened a diferent screen and that worked perfectly, today i cant switch profiles

**Comment by teelolws** [comment]
Why not? What happens when you try?

**Comment by BlueNightSky** [comment]
I also found that when the first time I log in, when the profiles tag is switched, the wrong page will be turned on. When the correct label is selected manually, it will return to normal.
The following screenshot is the page that appeared at the first time to log in:
![WoWScrnShot_053022_101519](https://user-images.githubusercontent.com/20654416/170905694-bbf9ffbc-7aef-4e72-82a2-68c8d30feae0.jpg)

**Comment by teelolws** [comment]
Okay I'll rollback how the Profile button works. But if I keep getting "addon blocked" reports about it, I'll have to remove the button. It will be safer for you to just navigate to the sections under Interface yourself.

**Comment by teelolws** [comment]
Nvm I found a better way to do it. Instead of opening Blizzards interface options I'll use `AceConfigDialog:Open(`
