### ISSUE TITLE
[Discrepancy] 2171, 2296

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#313]
### Mission ID

2171, 2296

### Upload the saved variable file here

[TLDRMissions-2022-05-30--2171-2296.zip](https://github.com/TLDRMissions/TLDRMissions/files/8797040/TLDRMissions-2022-05-30--2171-2296.zip)

**Comment by deNoor** [comment]
Simulated and sent with 072, completed with 073.

**Comment by teelolws** [comment]
Thanks. Spell 300 was dealing too much damage in the simulator.
