### ISSUE TITLE
Slight visual UI improvements

### ISSUE THREAD

**Issue by Nillx** [TLDRMissions/TLDRMissions#314]
I know you are busy with more important stuff but once you have time take a look at this things, i think its a small improvement.

Original on the left, edited on the Right. Pink zones were changed.

- There is a gap between the bottom buttons and the UI frame.
- I think it looks better when the top edge of the bar frame is hidden under the main frame. Also increase the width with a few pixels to match the main frame.

![c1](https://user-images.githubusercontent.com/34476875/170967950-15d2034b-4c44-4476-96e2-0599e40c3ba2.jpg)

**Comment by teelolws** [comment]
Hadn't noticed the tabs were hovering like that. Probably cause most of my characters are necrolords so everything has a black background anyway. Oops. I'll look at nudging those up a few pixels.

**Comment by Nillx** [comment]
Hehe it was quite noticeable with my kyrian character.

**Comment by teelolws** [comment]
[gui.zip](https://github.com/TLDRMissions/TLDRMissions/files/8797517/gui.zip)
try this

**Comment by teelolws** [comment]
Nudging the X button a couple pixels up. Now looks like this:
![image](https://user-images.githubusercontent.com/49792789/170972478-dbd9bf20-4540-4904-a9fc-4411ae164952.png)
[gui.zip](https://github.com/TLDRMissions/TLDRMissions/files/8797557/gui.zip)

**Comment by Nillx** [comment]
Thats great, can you widen the bar a bit too so it reaches the border?
![x1](https://user-images.githubusercontent.com/34476875/170973283-b67fa123-308d-4326-9997-c6181d19722b.jpg)

**Comment by teelolws** [comment]
Hmm. How many pixels off do you reckon it is

**Comment by Nillx** [comment]
It looks like 3 or 4 px

**Comment by teelolws** [comment]
Can't check atm, playing classic. Hows this?
[gui.zip](https://github.com/TLDRMissions/TLDRMissions/files/8797606/gui.zip)

**Comment by Nillx** [comment]
Looks good to me
![vv](https://user-images.githubusercontent.com/34476875/170974247-262a0ccf-8308-4cdc-b9dd-0f1e4bf8de6b.jpg)

**Comment by Nillx** [comment]
There is also another thing that slightly bothers me but i cant find whats wrong. Look at the arrow  buttons, they look somehow offset the square in the back. (or the square is smaller the button a bit?) 
![33](https://user-images.githubusercontent.com/34476875/171009559-71b03577-b0e9-4395-80c7-1533036a6305.jpg)

**Comment by teelolws** [comment]
I can't really do much with those ones. The buttons are setup by Blizzard, I can only control the frame behind it. I set the width to 10px which gives it that border around the button.

**Comment by Nillx** [comment]
Fair enough its not a big deal anyway.
