### ISSUE TITLE
WoWUp Availability

### ISSUE THREAD

**Issue by BlazeDale** [TLDRMissions/TLDRMissions#326]
**Make TLDRMissions Compatible with the WoWUp client so that users aren't forced to use CurseForge**

**Many user choose not to use the CurseForge/Overwolf client to manage their wow addons. For myself, its incompatible with my windows version. 

So I've been using WoWUp to track addons from GitHub URLs. For some addons this works for others it does not. When I attempt to install TLDRMissions from URL using WoWUp, I get the following error, "Cannot Read Properties of Undefined( reading 'assets')**

**Additional context**

**Comment by teelolws** [comment]
I currently have no plans to host outside of Curseforge.
