### ISSUE TITLE
[Discrepancy] Night Fae 2204

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#328]
### Mission ID

2204

### Upload the saved variable file here

[TLDRMissions.lua_Galanodel_2204_20220601-104743.txt](https://github.com/TLDRMissions/TLDRMissions/files/8817730/TLDRMissions.lua_Galanodel_2204_20220601-104743.txt)

**Comment by teelolws** [comment]
Trickster's Torment did not trigger thorns on its target.
