### ISSUE TITLE
[Discrepancy] Kyrian 2198

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#329]
### Mission ID

2198

### Upload the saved variable file here

[TLDRMissions.lua_Dammarill_2198_20220601-111404.txt](https://github.com/TLDRMissions/TLDRMissions/files/8817883/TLDRMissions.lua_Dammarill_2198_20220601-111404.txt)

**Comment by teelolws** [comment]
This is different because you sent the mission out before 9.2.5. Mikanikos was nerfed in 9.2.5. I have since adjusted the addon to account for that nerf.
