### ISSUE TITLE
Wave of Eternal Death - Spell ID 300, Mission ID: 2296, 2297

### ISSUE THREAD

**Issue by teelolws** [TLDRMissions/TLDRMissions#338]
Witnessed here: https://github.com/TLDRMissions/TLDRMissions/issues/337#event-6734993147

And here: https://github.com/TLDRMissions/TLDRMissions/issues/313

The first is 2297, the debuff did 3 damage per tick.

The second is 2296, the debuff did 2 damage per tick.

The data returned by C_Garrison.GetAutoMissionEnvironmentEffect is:

		["environmentEffect"] = {
			["name"] = "The Maw",
			["autoCombatSpellInfo"] = {
				["description"] = "Powerful death magic rolls across the Planes of Torment, causing a stacking damage over time effect to all of your party.",
				["autoCombatSpellID"] = 300,
				["duration"] = 3,
				["previewMask"] = 0,
				["name"] = "Wave of Eternal Death",
				["spellTutorialFlag"] = 0,
				["cooldown"] = 1,
				["schoolMask"] = 32,
				["icon"] = 136160,
				["hasThornsEffect"] = false,
			},

Unsure how to predict the actual damage using only that info. Is it different base damage because of the mission ID?

**Comment by cpuritscher** [comment]
Imho the damage depends on your average _overall_ follower level (not only those in the party).

**Comment by teelolws** [comment]
I doubt its based on your followers, but the level of the mission is possible, which is indirectly based on your followers level. I'd need to see more logs about for these missions to know for sure.

**Comment by teelolws** [comment]
I've seen more logs, can confirm just increasing the baseattack for 2297 covered this case.
