### ISSUE TITLE
[BUG] A mission failed! Mission ID = 2238

### ISSUE THREAD

**Issue by I-AM-T3X** [TLDRMissions/TLDRMissions#339]
### Upload your Character-Specific Saved Variables here

TLDRMissionsOptions = {
}
TLDRMissionsLogging = {
	[2238] = {
		["missionID"] = 2238,
		["followers"] = {
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -92,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 1295,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["predictedFinalHP"] = -77,
				["name"] = "Kyrian Phalanx",
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["baseAttack"] = 74,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1295,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 1295,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["predictedFinalHP"] = -3,
				["name"] = "Kyrian Phalanx",
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["baseAttack"] = 74,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1295,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 1500,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 245,
					}, -- [1]
				},
				["predictedFinalHP"] = 80,
				["name"] = "Croman",
				["followerID"] = "0x0000000034966090",
				["baseAttack"] = 300,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 444,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 111,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["addonVersion"] = "9.2-077",
		["enemies"] = {
			{
				["maxHP"] = 2650,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 4,
						["spellID"] = 174,
					}, -- [1]
				},
				["name"] = "Privileged Contributor",
				["boardIndex"] = 10,
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2650,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 1190,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 6,
				["baseAttack"] = 117,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1190,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 1190,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 7,
				["baseAttack"] = 117,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1190,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 1190,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 5,
				["baseAttack"] = 117,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1190,
				["followerID"] = -4,
			}, -- [4]
			{
				["maxHP"] = 1190,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 175,
					}, -- [1]
				},
				["name"] = "Party Animal",
				["boardIndex"] = 8,
				["baseAttack"] = 117,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1190,
				["followerID"] = -5,
			}, -- [5]
		},
	},
	[2218] = {
		["addonVersion"] = "9.2-073",
		["followers"] = {
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -8,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 1295,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["predictedFinalHP"] = 214,
				["name"] = "Kyrian Phalanx",
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["baseAttack"] = 74,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1295,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 279,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 600,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 3,
						["spellID"] = 85,
					}, -- [1]
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 84,
					}, -- [2]
				},
				["predictedFinalHP"] = 9,
				["name"] = "Mikanikos",
				["followerID"] = "0x0000000038BBB46A",
				["baseAttack"] = 150,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 600,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = -36,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["missionID"] = 2218,
		["enemies"] = {
			{
				["maxHP"] = 2315,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Bonewrought Thrasher",
				["boardIndex"] = 6,
				["baseAttack"] = 82,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 5,
						["spellID"] = 204,
					}, -- [1]
				},
				["HP"] = 2315,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 2315,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Bonewrought Thrasher",
				["boardIndex"] = 7,
				["baseAttack"] = 82,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 5,
						["spellID"] = 204,
					}, -- [1]
				},
				["HP"] = 2315,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 1515,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Callous Monstrosity",
				["boardIndex"] = 9,
				["baseAttack"] = 92,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 4,
						["spellID"] = 200,
					}, -- [1]
				},
				["HP"] = 1515,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 1615,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Soulless Monstrosity",
				["boardIndex"] = 12,
				["baseAttack"] = 102,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 201,
					}, -- [1]
				},
				["HP"] = 1615,
				["followerID"] = -4,
			}, -- [4]
		},
	},
	[2216] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Telethakas[0] shot Callous Monstrosity[8][1365HP] for 150 damage.", -- [4]
			"Telethakas[0] cast Physiker's Potion on Telethakas[0][750HP] for 150 healing.", -- [5]
			"Telethakas[0] applied Physiker's Potion to Telethakas[0][780HP].", -- [6]
			"Kyrian Halberdier[4] meleed Callous Monstrosity[8][1217HP] for 148 damage.", -- [7]
			"Kyrian Halberdier[4] cast Halberd Strike at Callous Monstrosity[5][1338HP] for 177  damage.", -- [8]
			"Callous Monstrosity[5] meleed Telethakas[0][688HP] for 92 damage.", -- [9]
			"Callous Monstrosity[5] cast Stunning Swipe at Kyrian Halberdier[4][463HP] for 92  damage.", -- [10]
			"Callous Monstrosity[5] applied Stunning Swipe to Kyrian Halberdier[4][463HP].", -- [11]
			"Callous Monstrosity[8] meleed Kyrian Halberdier[4][371HP] for 92 damage.", -- [12]
			"Callous Monstrosity[8] cast Stunning Swipe at Kyrian Halberdier[4][279HP] for 92  damage.", -- [13]
			"Callous Monstrosity[8] applied Stunning Swipe to Kyrian Halberdier[4][279HP].", -- [14]
			",", -- [15]
			"Start of round 2", -- [16]
			",", -- [17]
			"Telethakas[0] shot Callous Monstrosity[8][1067HP] for 150 damage.", -- [18]
			"Kyrian Halberdier[4] meleed Callous Monstrosity[8][1067HP] for 0 damage.", -- [19]
			"Callous Monstrosity[5] removed Stunning Swipe from Kyrian Halberdier[4][279HP].", -- [20]
			"Callous Monstrosity[5] meleed Telethakas[0][596HP] for 92 damage.", -- [21]
			"Callous Monstrosity[8] removed Stunning Swipe from Kyrian Halberdier[4][279HP].", -- [22]
			"Callous Monstrosity[8] meleed Kyrian Halberdier[4][187HP] for 92 damage.", -- [23]
			",", -- [24]
			"Start of round 3", -- [25]
			",", -- [26]
			"Telethakas[0] removed Physiker's Potion from Telethakas[0][596HP].", -- [27]
			"Telethakas[0] shot Callous Monstrosity[8][917HP] for 150 damage.", -- [28]
			"Kyrian Halberdier[4] meleed Callous Monstrosity[8][769HP] for 148 damage.", -- [29]
			"Callous Monstrosity[5] meleed Telethakas[0][504HP] for 92 damage.", -- [30]
			"Callous Monstrosity[8] meleed Kyrian Halberdier[4][95HP] for 92 damage.", -- [31]
			",", -- [32]
			"Start of round 4", -- [33]
			",", -- [34]
			"Telethakas[0] shot Callous Monstrosity[8][619HP] for 150 damage.", -- [35]
			"Kyrian Halberdier[4] meleed Callous Monstrosity[8][471HP] for 148 damage.", -- [36]
			"Callous Monstrosity[5] meleed Telethakas[0][412HP] for 92 damage.", -- [37]
			"Callous Monstrosity[8] meleed Kyrian Halberdier[4][3HP] for 92 damage.", -- [38]
			",", -- [39]
			"Start of round 5", -- [40]
			",", -- [41]
			"Telethakas[0] shot Callous Monstrosity[8][321HP] for 150 damage.", -- [42]
			"Telethakas[0] cast Physiker's Potion on Telethakas[0][562HP] for 150 healing.", -- [43]
			"Telethakas[0] applied Physiker's Potion to Telethakas[0][592HP].", -- [44]
			"Kyrian Halberdier[4] meleed Callous Monstrosity[8][173HP] for 148 damage.", -- [45]
			"Kyrian Halberdier[4] cast Halberd Strike at Callous Monstrosity[5][1161HP] for 177  damage.", -- [46]
			"Callous Monstrosity[5] meleed Telethakas[0][500HP] for 92 damage.", -- [47]
			"Callous Monstrosity[8] meleed Kyrian Halberdier[4][0HP] for 92 damage.", -- [48]
			"Callous Monstrosity[8] killed Kyrian Halberdier[4][0HP].", -- [49]
			",", -- [50]
			"Start of round 6", -- [51]
			",", -- [52]
			"Telethakas[0] shot Callous Monstrosity[8][23HP] for 150 damage.", -- [53]
			"Callous Monstrosity[5] meleed Telethakas[0][408HP] for 92 damage.", -- [54]
			"Callous Monstrosity[5] cast Stunning Swipe at Telethakas[0][316HP] for 92  damage.", -- [55]
			"Callous Monstrosity[5] applied Stunning Swipe to Telethakas[0][316HP].", -- [56]
			"Callous Monstrosity[8] meleed Telethakas[0][224HP] for 92 damage.", -- [57]
			"Callous Monstrosity[8] cast Stunning Swipe at Telethakas[0][132HP] for 92  damage.", -- [58]
			"Callous Monstrosity[8] applied Stunning Swipe to Telethakas[0][132HP].", -- [59]
			",", -- [60]
			"Start of round 7", -- [61]
			",", -- [62]
			"Telethakas[0] removed Physiker's Potion from Telethakas[0][132HP].", -- [63]
			"Telethakas[0] shot Callous Monstrosity[8][23HP] for 0 damage.", -- [64]
			"Callous Monstrosity[5] removed Stunning Swipe from Telethakas[0][132HP].", -- [65]
			"Callous Monstrosity[5] meleed Telethakas[0][40HP] for 92 damage.", -- [66]
			"Callous Monstrosity[8] removed Stunning Swipe from Telethakas[0][40HP].", -- [67]
			"Callous Monstrosity[8] meleed Telethakas[0][0HP] for 92 damage.", -- [68]
			"Callous Monstrosity[8] killed Telethakas[0][0HP].", -- [69]
		},
		["addonVersion"] = "9.2-077",
		["followers"] = {
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 117,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 4,
			}, -- [1]
			{
				["maxHP"] = 750,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 3,
						["spellID"] = 26,
					}, -- [1]
				},
				["predictedFinalHP"] = -78,
				["name"] = "Telethakas",
				["followerID"] = "0x0000000038BC7516",
				["baseAttack"] = 150,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 750,
				["boardIndex"] = 0,
			}, -- [2]
		},
		["missionID"] = 2216,
		["enemies"] = {
			{
				["maxHP"] = 1515,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 4,
						["spellID"] = 200,
					}, -- [1]
				},
				["name"] = "Callous Monstrosity",
				["boardIndex"] = 5,
				["baseAttack"] = 92,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1515,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 1515,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 4,
						["spellID"] = 200,
					}, -- [1]
				},
				["name"] = "Callous Monstrosity",
				["boardIndex"] = 8,
				["baseAttack"] = 92,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1515,
				["followerID"] = -2,
			}, -- [2]
		},
	},
	[2171] = {
		["missionID"] = 2171,
		["followers"] = {
			{
				["maxHP"] = 1085,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 3,
						["spellID"] = 314,
					}, -- [1]
				},
				["predictedFinalHP"] = -1,
				["name"] = "Cromas the Mystic",
				["followerID"] = "0x0000000038CE02AD",
				["baseAttack"] = 124,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1085,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 555,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["predictedFinalHP"] = 287,
				["name"] = "Kyrian Halberdier",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 148,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 555,
				["boardIndex"] = 0,
			}, -- [2]
		},
		["addonVersion"] = "9.2-077",
		["enemies"] = {
			{
				["maxHP"] = 342,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Bony Skeleton",
				["boardIndex"] = 6,
				["baseAttack"] = 48,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 342,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 178,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Swarming Skeleton",
				["boardIndex"] = 11,
				["baseAttack"] = 24,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 178,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 178,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Swarming Skeleton",
				["boardIndex"] = 10,
				["baseAttack"] = 24,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 178,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 342,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Bony Skeleton",
				["boardIndex"] = 7,
				["baseAttack"] = 48,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 342,
				["followerID"] = -4,
			}, -- [4]
			{
				["maxHP"] = 178,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Swarming Skeleton",
				["boardIndex"] = 9,
				["baseAttack"] = 24,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 178,
				["followerID"] = -5,
			}, -- [5]
			{
				["maxHP"] = 178,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Swarming Skeleton",
				["boardIndex"] = 5,
				["baseAttack"] = 24,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 178,
				["followerID"] = -6,
			}, -- [6]
			{
				["maxHP"] = 684,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 1,
						["spellID"] = 12,
					}, -- [1]
				},
				["name"] = "Nort the Noxious",
				["boardIndex"] = 12,
				["baseAttack"] = 24,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 684,
				["followerID"] = -7,
			}, -- [7]
			{
				["maxHP"] = 342,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 7,
					}, -- [1]
				},
				["name"] = "Bony Skeleton",
				["boardIndex"] = 8,
				["baseAttack"] = 48,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 342,
				["followerID"] = -8,
			}, -- [8]
		},
	},
}

**Comment by teelolws** [comment]
Thanks. First time seeing a log with the follower Telethakas. Fixed its spell data.
