### ISSUE TITLE
crashing on start [BUG] Other

### ISSUE THREAD

**Issue by Wood1313** [TLDRMissions/TLDRMissions#342]
As soon as you start the simulation it crashes the game any character any server (tested on 3 servers 5 characters)

**Comment by teelolws** [comment]
can you show me a screenshot of the addons settings, before you start any simulations

**Comment by reyard** [comment]
4x TLDRMissions\guihandlers.lua:581: bad argument #2 to 'format' (string expected, got no value)
[string "=[C]"]: in function `format'
[string "@TLDRMissions\guihandlers.lua"]:581: in function <TLDRMissions\guihandlers.lua:575>
[string "@TLDRMissions\guihandlers.lua"]:621: in function <TLDRMissions\guihandlers.lua:614>
[string "@TLDRMissions\guihandlers.lua"]:744: in function <TLDRMissions\guihandlers.lua:418>

Locals:
(*temporary) = "Misión: %s"
(*temporary) = "string expected, got no value"

**Comment by Wood1313** [comment]
Error code as well on this. Game crashed but recovered"Ice Cream Goes In The Freezer" - Tardy Turtle

9-11-01 We Shall Not ForgetOn Jun 3, 2022, at 10:09 PM, teelolws ***@***.***> wrote:can you show me a screenshot of the addons settings, before you start any simulations—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by teelolws** [comment]
> Error code as well on this. Game crashed but recovered"Ice Cream Goes In The Freezer" - Tardy Turtle 9-11-01 We Shall Not Forget

Show me the error?
