### ISSUE TITLE
[BUG] Lua error when it gets to mission "Cutting the Threads", reward is 150 Soul Ash

### ISSUE THREAD

**Issue by Rethyn** [TLDRMissions/TLDRMissions#345]
### Copy/paste the Lua error here

1x TLDRMissions\simulation.lua:697: attempt to compare number with nil
[string "@TLDRMissions\simulation.lua"]:697: in function <TLDRMissions\simulation.lua:663>
[string "@TLDRMissions\simulation.lua"]:966: in function <TLDRMissions\simulation.lua:780>
[string "@TLDRMissions\simulation.lua"]:1259: in function `func'
[string "@TLDRMissions\workhandler.lua"]:41: in function <TLDRMissions\workhandler.lua:23>

Locals:
rngTargets = <table> {
 enemies_random_ally = 8
 enemies_random_enemy = -1
 followers_random_ally = -1
 followers_random_enemy = -1
}
target = <table> {
 1 = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Mawsworn Ritual5 = <table> {
 }
 Mawsworn Ritual13 = <table> {
 }
}
(for control) = "Mawsworn Ritual13"
_ = "Mawsworn Ritual13"
buff = <table> {
 type = "buff"
 duration = 2
 changeDamageTakenPercent = -50
 stacks = 1
 name = "Mawsworn Ritual"
 target = <table> {
 }
 ID = 23
 stackLimit = 1
}
(*temporary) = nil
(*temporary) = <table> {
 type = "buff"
 duration = 2
 changeDamageTakenPercent = -50
 stacks = 1
 name = "Mawsworn Ritual"
 target = <table> {
 }
 ID = 23
 stackLimit = 1
}
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
}
(*temporary) = 11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 8
(*temporary) = <table> {
 maxHP = 2100
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 8
 name = "Winged Automaton"
 followerID = -5
 baseAttack = 180
 buffs = <table> {
 }
 HP = 1388
 thorns = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
environmentEffect = <table> {
 name = "The Maw"
 autoCombatSpellInfo = <table> {
 }
 onCooldown = 4
 alternate = true
 cooldown = 4
 effects = <table> {
 }
}
field = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
}
getTargets = <function> defined @TLDRMissions\simulation.lua:112
environmentEffectFollower = <table> {
 followerID = "environment"
 name = "The Maw"
 boardIndex = 13
 baseAttack = 100
 buffs = <table> {
 }
 changeDamageDealtPercent = 100
 changeDamageDealtRaw = 0
}
print = <function> defined @TLDRMissions\simulation.lua:4
checkDeath = <function> defined @TLDRMissions\simulation.lua:508
processBuff = <function> defined @TLDRMissions\simulation.lua:442
unregisterBuff = <function> defined @TLDRMissions\simulation.lua:492
registerBuff = <function> defined @TLDRMissions\simulation.lua:213
calculateDamage = <function> defined @TLDRMissions\simulation.lua:358

**Comment by teelolws** [comment]
Thanks. I'm pushing a fix that *should* solve this issue, but I am unable to test if it can still solve the mission. I'll leave this open until I can get this mission on one of my characters and try it.

**Comment by Rethyn** [comment]
After updating, I got this LUA error for the same mission.

1x TLDRMissions\simulation.lua:697: attempt to compare number with nil
[string "@TLDRMissions\simulation.lua"]:697: in function <TLDRMissions\simulation.lua:663>
[string "@TLDRMissions\simulation.lua"]:961: in function <TLDRMissions\simulation.lua:775>
[string "@TLDRMissions\simulation.lua"]:1340: in function <TLDRMissions\simulation.lua:1275>
[string "@TLDRMissions\simulation.lua"]:1315: in function `func'
[string "@TLDRMissions\workhandler.lua"]:41: in function <TLDRMissions\workhandler.lua:23>

Locals:
rngTargets = nil
target = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Mawsworn Ritual10 = <table> {
 }
 Mawsworn Ritual13 = <table> {
 }
}
(for control) = "Mawsworn Ritual13"
_ = "Mawsworn Ritual13"
buff = <table> {
 type = "buff"
 duration = 2
 changeDamageTakenPercent = -50
 stacks = 1
 name = "Mawsworn Ritual"
 target = <table> {
 }
 ID = 8
 stackLimit = 1
}
(*temporary) = nil
(*temporary) = <table> {
 type = "buff"
 duration = 2
 changeDamageTakenPercent = -50
 stacks = 1
 name = "Mawsworn Ritual"
 target = <table> {
 }
 ID = 8
 stackLimit = 1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
environmentEffect = <table> {
 name = "The Maw"
 autoCombatSpellInfo = <table> {
 }
 onCooldown = 4
 cooldown = 4
 effects = <table> {
 }
}
field = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
}
getTargets = <function> defined @TLDRMissions\simulation.lua:112
environmentEffectFollower = <table> {
 followerID = "environment"
 name = "The Maw"
 boardIndex = 13
 baseAttack = 100
 buffs = <table> {
 }
 changeDamageDealtPercent = 100
 changeDamageDealtRaw = 0
}
print = <function> defined @TLDRMissions\simulation.lua:4
checkDeath = <function> defined @TLDRMissions\simulation.lua:508
processBuff = <function> defined @TLDRMissions\simulation.lua:442
unregisterBuff = <function> defined @TLDRMissions\simulation.lua:492
registerBuff = <function> defined @TLDRMissions\simulation.lua:213
calculateDamage = <function> defined @TLDRMissions\simulation.lua:358

**Comment by teelolws** [comment]
I need to get an idea of where the simulation is going wrong. Can you add me on discord? Teelo#2307
