### ISSUE TITLE
[Discrepancy] Night Fae 2300

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#346]
### Mission ID

2300

### Upload the saved variable file here

[TLDRMissions.lua_Dammarill_2300_20220604-143229.txt](https://github.com/TLDRMissions/TLDRMissions/files/8838882/TLDRMissions.lua_Dammarill_2300_20220604-143229.txt)

**Comment by teelolws** [comment]
Thanks. Minor targetting issue with cleave from Slot 10.
