### ISSUE TITLE
[Feature request] Show what followers need to be leveled to increase troops lvl.

### ISSUE THREAD

**Issue by czullo** [TLDRMissions/TLDRMissions#354]
**TLDR Version of your idea**
Show what followers need to be leveled to increase troops lvl.

**Comment by teelolws** [comment]
Seems a bit outside the scope of my addon. I have this option here to prioritise leveling those followers, but showing you what they are? Who cares, too long didn't read!

![image](https://user-images.githubusercontent.com/49792789/172473257-050dadb8-1dd7-4089-a836-02e7c6141f9f.png)
