### ISSUE TITLE
[BUG] Checkboxes not cleared after change profile

### ISSUE THREAD

**Issue by Mistrick** [TLDRMissions/TLDRMissions#362]
First profile
![image](https://user-images.githubusercontent.com/4307674/173210138-d47458b2-8868-4f6a-b636-2796c58ae111.png)
Second profile
![image](https://user-images.githubusercontent.com/4307674/173210166-e42e270c-0678-4869-86d5-25c029155551.png)

After switch from 1st to 2nd
![image](https://user-images.githubusercontent.com/4307674/173210149-266d9091-4a97-41ba-a3f9-3d8da3a15ad7.png)
(Reload)After switch from 2nd to 1st
![image](https://user-images.githubusercontent.com/4307674/173210176-e7589b61-46d8-460b-ae92-1f8ee3fe874b.png)

Same behavior on 085 version

**Comment by teelolws** [comment]
I'll get that next patch. Here, if you don't want to wait:
[guihandlers.zip](https://github.com/TLDRMissions/TLDRMissions/files/8885008/guihandlers.zip)
