### ISSUE TITLE
[BUG] A mission failed! Mission ID: 2254

### ISSUE THREAD

**Issue by Korono22** [TLDRMissions/TLDRMissions#364]
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/8886814/TLDRMissions.zip)

**Comment by teelolws** [comment]
Thanks.

Related to: https://github.com/teelolws/TLDRMissions/issues/92 Mawsworn Strength was targetting the wrong follower in the Simulator under specific circumstances.

Also, this is the first time I've seen a log with the environment effect 228 "After ten turns a wave of absolute destruction flows through the The Tremaculum, dealing $s1 damage to your party." I have made some corrections to how that effect is handled.

Will be fixed next patch.
