### ISSUE TITLE
save successful mission layouts

### ISSUE THREAD

**Issue by Cr42yC4r1** [TLDRMissions/TLDRMissions#365]
**TLDR Version of your idea**
TLDR version: save successful mission layouts for future start points of simulations.

**Slightly longer version**
shorten simulation time by saving predicted and confirmed successful mission layouts and running those simulations first

**Additional context**
random heavy missions that run for thousands of simulations could be sped up a ton

**Comment by teelolws** [comment]
It already does. If a follower heals (even 1HP can change things) or levels up, it has to recalculate it.

**Comment by Cr42yC4r1** [comment]
ah sweet. sorry then. I thought I'd seen it timeout on repeat missions that I had manually set up and completed with this addon. Of course healing and leveling would change things but those would still be good start points for simulation

**Comment by Cr42yC4r1** [comment]
I made what I was thinking of. I'll find out if it works once I get a repeat mission. could probably keep the order of followers but didn't care to figure it out.
toc
```
## Interface: 90205
## Title: TLDRHistoryRepeats
## Version: 1
## Notes: Try known good mission combinations first
## Dependencies: TLDRMissions
## SavedVariablesPerCharacter: missionHistory
## SavedVariables: 
TLDRHistoryRepeats.lua
```
lua
```lua
--TLDRHistoryRepeats

--Onload to get saved variables
---[[
local ADDON_LOADEDFrame=CreateFrame("Frame")
local function OnADDON_LOADED(self, event, arg1)
	ADDON_LOADEDFrame:UnregisterAllEvents()
	--do saved var stuff
	if not missionHistory then missionHistory={} end
end
ADDON_LOADEDFrame:RegisterEvent("ADDON_LOADED")
ADDON_LOADEDFrame:SetScript("OnEvent", OnADDON_LOADED)--]]

--things on GARRISON_MISSION_COMPLETE_RESPONSE
local GARRISON_MISSION_COMPLETE_RESPONSEFrame=CreateFrame("Frame")
local function OnGARRISON_MISSION_COMPLETE_RESPONSE(self, event, missionID, canComplete, success, overmaxSucceeded, followerDeaths, autoCombatResult)
	--log it
	if not missionHistory[missionID] then missionHistory[missionID]={} end
	--DevTools_Dump(followerDeaths)
	local followersSent={}
	for k,v in ipairs(followerDeaths) do
		info = C_Garrison.GetFollowerInfo(v.followerID)
		table.insert(followersSent,info.garrFollowerID)--this is the ID i want
	end
	table.sort(followersSent)
	followersSent=table.concat(followersSent,"-")
	if not missionHistory[missionID][followersSent] then missionHistory[missionID][followersSent]={} end
	if success then
		missionHistory[missionID][followersSent]["successes"]=(missionHistory[missionID]["successes"] or 0)+1
	else
		missionHistory[missionID][followersSent]["failures"]=(missionHistory[missionID]["failures"] or 0)+1
	end
end
GARRISON_MISSION_COMPLETE_RESPONSEFrame:RegisterEvent("GARRISON_MISSION_COMPLETE_RESPONSE")
GARRISON_MISSION_COMPLETE_RESPONSEFrame:SetScript("OnEvent", OnGARRISON_MISSION_COMPLETE_RESPONSE)

local function FollowerCombinationsHistory(followers, missionID, callback, sortBy, troopsSetting)
	--check for missionHistory
	if missionHistory[missionID] then
		for followersSent,missionData in missionHistory[missionID] do
			if (missionData.successes or 0)>1 and not (missionData.failures or 0)>1 then
				--check that followers are available
				local tfollowersSent=strplittable("-",followersSent)
				local allAvailable=true
				for k,v in ipairs(tfollowersSent) do
					if not tContains(followers,tonumber(v)) then
						allAvailable=false
					end
				end
				if allAvailable then
					--push into work queue
					TLDRMissions:arrangeAllFollowerPositions(tonumber(tfollowersSent[1]), tonumber(tfollowersSent[2]), tonumber(tfollowersSent[3]), tonumber(tfollowersSent[4]), tonumber(tfollowersSent[5]), missionID, callback)
				end
			end
		end
	end
end

--I don't care about most or fewest followers hook both
hooksecurefunc(TLDRMissions,"arrangeFollowerCombinationsByMostFollowersPlusTroops",FollowerCombinationsHistory)
hooksecurefunc(TLDRMissions,"arrangeFollowerCombinationsByFewestFollowersPlusTroops",FollowerCombinationsHistory)
```

**Comment by teelolws** [comment]
Your logic is flawed. You're not giving any consideration to:

1. the health the follower starts the mission with
2. the level of the follower
3. the level of the mission

You're only going to leave to disappointment when you save a successful mission and send it out later with lower HP followers on a higher level mission and fail.

As I mentioned before, my code already tracks this sort of thing. Look in `caching.lua`

**Comment by Cr42yC4r1** [comment]
I'm not considering those things because I'm not sending the mission. I'm putting that follower combination in the work queue to simulate first. The simulation considers their health and levels and the existing caching gets used there. I'm adding work that will get duplicated later as each follower combination is considered. `caching.lua` only seems to shortcut the final step of simulation but I am interested in shortcutting much earlier in `combinations.lua`

I guess to rephrase it I want to better optimize the order of follower combinations tested by some guess of most likely to win. and the guess I'd suggest is that that combination previously did win

**Comment by teelolws** [comment]
I understand now. That would make things faster, but you risk missing more efficient combinations with that method. Say your code locks in 2 followers + 3 troops as a successful team. Next time you get that mission, a different follower has levelled up, a follower that could do the mission with 4 troops. Your code will skip that and send 2 followers + 3 troops instead. I'm trying to be efficient with follower usage as much as possible, even if it takes longer to find results.
