### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by Rethyn** [TLDRMissions/TLDRMissions#366]
### Upload your Character-Specific Saved Variables here

TLDRMissionsOptions = {
}
TLDRMissionsLogging = {
	[2265] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Kaletar[4] shot Sinstone Shardling[5][2006HP] for 244 damage.", -- [4]
			"Simone[3] shot Sinstone Shardling[5][1762HP] for 244 damage.", -- [5]
			"Simone[3] cast Mirror of Torment at Sinstone Shardling[5][1457HP] for 305  damage.", -- [6]
			"Venthyr Nightblade[0] meleed Sinstone Shardling[5][1274HP] for 183 damage.", -- [7]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Shardling[5][1183HP] for 91  damage.", -- [8]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Shardling[5][1138HP] for 45  damage.", -- [9]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][4317HP] for 183 damage.", -- [10]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Hoarder[6][4226HP] for 91  damage.", -- [11]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Hoarder[6][4181HP] for 45  damage.", -- [12]
			"Venthyr Nightblade[2] meleed Sinstone Shardling[5][955HP] for 183 damage.", -- [13]
			"Venthyr Nightblade[2] cast Double Stab at Sinstone Shardling[5][864HP] for 91  damage.", -- [14]
			"Venthyr Nightblade[2] cast Double Stab at Sinstone Shardling[5][819HP] for 45  damage.", -- [15]
			"Sinstone Hoarder[6] meleed Venthyr Nightblade[2][1355HP] for 170 damage.", -- [16]
			"Sinstone Hoarder[6] applied Dreadful Exhaust to Venthyr Nightblade[2][1355HP].", -- [17]
			"Sinstone Rampager[7] meleed Simone[3][1513HP] for 190 damage.", -- [18]
			"Sinstone Rampager[7] cast Stone Swipe at Venthyr Nightblade[0][1411HP] for 114  damage.", -- [19]
			"Sinstone Rampager[7] cast Stone Swipe at Venthyr Nightblade[1][1411HP] for 114  damage.", -- [20]
			"Sinstone Shardling[5] meleed Venthyr Nightblade[2][1055HP] for 300 damage.", -- [21]
			"Sinstone Shardling[5] cast Stone Bash at Venthyr Nightblade[2][455HP] for 600  damage.", -- [22]
			"Sinstone Shardling[8] meleed Kaletar[4][1630HP] for 200 damage.", -- [23]
			"Sinstone Shardling[8] cast Stone Bash at Kaletar[4][1230HP] for 400  damage.", -- [24]
			",", -- [25]
			"Start of round 2", -- [26]
			",", -- [27]
			"Simone[3] shot Sinstone Shardling[5][575HP] for 244 damage.", -- [28]
			"Venthyr Nightblade[0] meleed Sinstone Shardling[5][392HP] for 183 damage.", -- [29]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][3998HP] for 183 damage.", -- [30]
			"Kaletar[4] shot Sinstone Shardling[5][148HP] for 244 damage.", -- [31]
			"Kaletar[4] applied Spirits of Rejuvenation to Venthyr Nightblade[0][1411HP].", -- [32]
			"Kaletar[4] applied Spirits of Rejuvenation to Venthyr Nightblade[1][1411HP].", -- [33]
			"Kaletar[4] applied Spirits of Rejuvenation to Venthyr Nightblade[2][455HP].", -- [34]
			"Kaletar[4] applied Spirits of Rejuvenation to Simone[3][1513HP].", -- [35]
			"Kaletar[4] applied Spirits of Rejuvenation to Kaletar[4][1230HP].", -- [36]
			"Venthyr Nightblade[2] meleed Sinstone Shardling[5][0HP] for 183 damage.", -- [37]
			"Venthyr Nightblade[2] killed Sinstone Shardling[5][0HP].", -- [38]
			"Sinstone Hoarder[6] meleed Venthyr Nightblade[2][200HP] for 255 damage.", -- [39]
			"Sinstone Rampager[7] meleed Simone[3][1323HP] for 190 damage.", -- [40]
			"Sinstone Shardling[8] meleed Kaletar[4][1030HP] for 200 damage.", -- [41]
			",", -- [42]
			"Start of round 3", -- [43]
			",", -- [44]
			"Venthyr Nightblade[0] meleed Sinstone Hoarder[6][3815HP] for 183 damage.", -- [45]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][3632HP] for 183 damage.", -- [46]
			"Simone[3] shot Sinstone Shardling[8][2006HP] for 244 damage.", -- [47]
			"Simone[3] cast Mirror of Torment at Sinstone Shardling[8][1701HP] for 305  damage.", -- [48]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][1472HP] for 61.", -- [49]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][1472HP] for 61.", -- [50]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[2][261HP] for 61.", -- [51]
			"Kaletar[4]'s Spirits of Rejuvenation healed Simone[3][1384HP] for 61.", -- [52]
			"Kaletar[4]'s Spirits of Rejuvenation healed Kaletar[4][1091HP] for 61.", -- [53]
			"Kaletar[4] shot Sinstone Hoarder[6][3388HP] for 244 damage.", -- [54]
			"Venthyr Nightblade[2] meleed Sinstone Hoarder[6][3205HP] for 183 damage.", -- [55]
			"Sinstone Hoarder[6] removed Dreadful Exhaust from Venthyr Nightblade[2][261HP].", -- [56]
			"Sinstone Hoarder[6] meleed Venthyr Nightblade[2][91HP] for 170 damage.", -- [57]
			"Sinstone Rampager[7] meleed Simone[3][1194HP] for 190 damage.", -- [58]
			"Sinstone Shardling[8] meleed Kaletar[4][891HP] for 200 damage.", -- [59]
			",", -- [60]
			"Start of round 4", -- [61]
			",", -- [62]
			"Venthyr Nightblade[0] meleed Sinstone Hoarder[6][3022HP] for 183 damage.", -- [63]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][2839HP] for 183 damage.", -- [64]
			"Simone[3] shot Sinstone Shardling[8][1457HP] for 244 damage.", -- [65]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][1525HP] for 61.", -- [66]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][1525HP] for 61.", -- [67]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[2][152HP] for 61.", -- [68]
			"Kaletar[4]'s Spirits of Rejuvenation healed Simone[3][1255HP] for 61.", -- [69]
			"Kaletar[4]'s Spirits of Rejuvenation healed Kaletar[4][952HP] for 61.", -- [70]
			"Kaletar[4] shot Sinstone Hoarder[6][2595HP] for 244 damage.", -- [71]
			"Venthyr Nightblade[2] meleed Sinstone Hoarder[6][2412HP] for 183 damage.", -- [72]
			"Sinstone Hoarder[6] meleed Venthyr Nightblade[2][0HP] for 170 damage.", -- [73]
			"Sinstone Hoarder[6] killed Venthyr Nightblade[2][0HP].", -- [74]
			"Sinstone Hoarder[6] applied Dreadful Exhaust to Simone[3][1255HP].", -- [75]
			"Sinstone Rampager[7] meleed Simone[3][970HP] for 285 damage.", -- [76]
			"Sinstone Shardling[8] meleed Kaletar[4][752HP] for 200 damage.", -- [77]
			",", -- [78]
			"Start of round 5", -- [79]
			",", -- [80]
			"Venthyr Nightblade[0] meleed Sinstone Hoarder[6][2229HP] for 183 damage.", -- [81]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Hoarder[6][2138HP] for 91  damage.", -- [82]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Hoarder[6][2093HP] for 45  damage.", -- [83]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][1910HP] for 183 damage.", -- [84]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Hoarder[6][1819HP] for 91  damage.", -- [85]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Hoarder[6][1774HP] for 45  damage.", -- [86]
			"Simone[3] shot Sinstone Shardling[8][1213HP] for 244 damage.", -- [87]
			"Simone[3] cast Mirror of Torment at Sinstone Shardling[8][908HP] for 305  damage.", -- [88]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][1525HP] for 61.", -- [89]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][1525HP] for 61.", -- [90]
			"Kaletar[4]'s Spirits of Rejuvenation healed Simone[3][1031HP] for 61.", -- [91]
			"Kaletar[4]'s Spirits of Rejuvenation healed Kaletar[4][813HP] for 61.", -- [92]
			"Kaletar[4] shot Sinstone Hoarder[6][1530HP] for 244 damage.", -- [93]
			"Sinstone Rampager[7] meleed Simone[3][746HP] for 285 damage.", -- [94]
			"Sinstone Hoarder[6] meleed Simone[3][491HP] for 255 damage.", -- [95]
			"Sinstone Shardling[8] meleed Kaletar[4][613HP] for 200 damage.", -- [96]
			"Sinstone Shardling[8] cast Stone Bash at Kaletar[4][213HP] for 400  damage.", -- [97]
			",", -- [98]
			"Start of round 6", -- [99]
			",", -- [100]
			"Venthyr Nightblade[0] meleed Sinstone Hoarder[6][1347HP] for 183 damage.", -- [101]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][1164HP] for 183 damage.", -- [102]
			"Simone[3] shot Sinstone Shardling[8][664HP] for 244 damage.", -- [103]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][1525HP] for 61.", -- [104]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][1525HP] for 61.", -- [105]
			"Kaletar[4]'s Spirits of Rejuvenation healed Simone[3][552HP] for 61.", -- [106]
			"Kaletar[4]'s Spirits of Rejuvenation healed Kaletar[4][274HP] for 61.", -- [107]
			"Kaletar[4] removed Spirits of Rejuvenation from Venthyr Nightblade[0][1525HP].", -- [108]
			"Kaletar[4] removed Spirits of Rejuvenation from Venthyr Nightblade[1][1525HP].", -- [109]
			"Kaletar[4] removed Spirits of Rejuvenation from Simone[3][552HP].", -- [110]
			"Kaletar[4] removed Spirits of Rejuvenation from Kaletar[4][274HP].", -- [111]
			"Kaletar[4] shot Sinstone Hoarder[6][920HP] for 244 damage.", -- [112]
			"Sinstone Rampager[7] meleed Simone[3][267HP] for 285 damage.", -- [113]
			"Sinstone Rampager[7] cast Stone Swipe at Venthyr Nightblade[0][1411HP] for 114  damage.", -- [114]
			"Sinstone Rampager[7] cast Stone Swipe at Venthyr Nightblade[1][1411HP] for 114  damage.", -- [115]
			"Sinstone Hoarder[6] removed Dreadful Exhaust from Simone[3][267HP].", -- [116]
			"Sinstone Hoarder[6] meleed Simone[3][97HP] for 170 damage.", -- [117]
			"Sinstone Shardling[8] meleed Kaletar[4][74HP] for 200 damage.", -- [118]
			",", -- [119]
			"Start of round 7", -- [120]
			",", -- [121]
			"Venthyr Nightblade[0] meleed Sinstone Hoarder[6][737HP] for 183 damage.", -- [122]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][554HP] for 183 damage.", -- [123]
			"Simone[3] shot Sinstone Shardling[8][420HP] for 244 damage.", -- [124]
			"Simone[3] cast Mirror of Torment at Sinstone Shardling[8][115HP] for 305  damage.", -- [125]
			"Kaletar[4] shot Sinstone Hoarder[6][310HP] for 244 damage.", -- [126]
			"Kaletar[4] applied Spirits of Rejuvenation to Venthyr Nightblade[0][1411HP].", -- [127]
			"Kaletar[4] applied Spirits of Rejuvenation to Venthyr Nightblade[1][1411HP].", -- [128]
			"Kaletar[4] applied Spirits of Rejuvenation to Simone[3][97HP].", -- [129]
			"Kaletar[4] applied Spirits of Rejuvenation to Kaletar[4][74HP].", -- [130]
			"Sinstone Rampager[7] meleed Simone[3][0HP] for 190 damage.", -- [131]
			"Sinstone Rampager[7] killed Simone[3][0HP].", -- [132]
			"Sinstone Hoarder[6] meleed Venthyr Nightblade[0][1241HP] for 170 damage.", -- [133]
			"Sinstone Hoarder[6] applied Dreadful Exhaust to Venthyr Nightblade[0][1241HP].", -- [134]
			"Sinstone Shardling[8] meleed Kaletar[4][0HP] for 200 damage.", -- [135]
			"Sinstone Shardling[8] killed Kaletar[4][0HP].", -- [136]
			",", -- [137]
			"Start of round 8", -- [138]
			",", -- [139]
			"Venthyr Nightblade[1] meleed Sinstone Hoarder[6][127HP] for 183 damage.", -- [140]
			"Venthyr Nightblade[0] meleed Sinstone Hoarder[6][0HP] for 183 damage.", -- [141]
			"Venthyr Nightblade[0] killed Sinstone Hoarder[6][0HP].", -- [142]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][1302HP] for 61.", -- [143]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][1472HP] for 61.", -- [144]
			"Sinstone Rampager[7] meleed Venthyr Nightblade[0][1017HP] for 285 damage.", -- [145]
			"Sinstone Shardling[8] meleed Venthyr Nightblade[1][1272HP] for 200 damage.", -- [146]
			",", -- [147]
			"Start of round 9", -- [148]
			",", -- [149]
			"Venthyr Nightblade[1] meleed Sinstone Rampager[7][2817HP] for 183 damage.", -- [150]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Rampager[7][2726HP] for 91  damage.", -- [151]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Rampager[7][2681HP] for 45  damage.", -- [152]
			"Venthyr Nightblade[0] meleed Sinstone Rampager[7][2498HP] for 183 damage.", -- [153]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Rampager[7][2407HP] for 91  damage.", -- [154]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Rampager[7][2362HP] for 45  damage.", -- [155]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][1078HP] for 61.", -- [156]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][1333HP] for 61.", -- [157]
			"Sinstone Rampager[7] meleed Venthyr Nightblade[0][793HP] for 285 damage.", -- [158]
			"Sinstone Shardling[8] meleed Venthyr Nightblade[1][1133HP] for 200 damage.", -- [159]
			"Sinstone Shardling[8] cast Stone Bash at Venthyr Nightblade[1][733HP] for 400  damage.", -- [160]
			"Sinstone Hoarder[6] removed Dreadful Exhaust from Venthyr Nightblade[0][793HP].", -- [161]
			",", -- [162]
			"Start of round 10", -- [163]
			",", -- [164]
			"Venthyr Nightblade[0] meleed Sinstone Rampager[7][2179HP] for 183 damage.", -- [165]
			"Venthyr Nightblade[1] meleed Sinstone Rampager[7][1996HP] for 183 damage.", -- [166]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][854HP] for 61.", -- [167]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][794HP] for 61.", -- [168]
			"Sinstone Rampager[7] meleed Venthyr Nightblade[0][664HP] for 190 damage.", -- [169]
			"Sinstone Shardling[8] meleed Venthyr Nightblade[1][594HP] for 200 damage.", -- [170]
			",", -- [171]
			"Start of round 11", -- [172]
			",", -- [173]
			"Venthyr Nightblade[0] meleed Sinstone Rampager[7][1813HP] for 183 damage.", -- [174]
			"Venthyr Nightblade[1] meleed Sinstone Rampager[7][1630HP] for 183 damage.", -- [175]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[0][725HP] for 61.", -- [176]
			"Kaletar[4]'s Spirits of Rejuvenation healed Venthyr Nightblade[1][655HP] for 61.", -- [177]
			"Kaletar[4] removed Spirits of Rejuvenation from Venthyr Nightblade[0][725HP].", -- [178]
			"Kaletar[4] removed Spirits of Rejuvenation from Venthyr Nightblade[1][655HP].", -- [179]
			"Sinstone Rampager[7] meleed Venthyr Nightblade[0][535HP] for 190 damage.", -- [180]
			"Sinstone Rampager[7] cast Stone Swipe at Venthyr Nightblade[0][421HP] for 114  damage.", -- [181]
			"Sinstone Rampager[7] cast Stone Swipe at Venthyr Nightblade[1][541HP] for 114  damage.", -- [182]
			"Sinstone Shardling[8] meleed Venthyr Nightblade[1][341HP] for 200 damage.", -- [183]
			",", -- [184]
			"Start of round 12", -- [185]
			",", -- [186]
			"Venthyr Nightblade[0] meleed Sinstone Rampager[7][1447HP] for 183 damage.", -- [187]
			"Venthyr Nightblade[1] meleed Sinstone Rampager[7][1264HP] for 183 damage.", -- [188]
			"Sinstone Rampager[7] meleed Venthyr Nightblade[0][231HP] for 190 damage.", -- [189]
			"Sinstone Shardling[8] meleed Venthyr Nightblade[1][141HP] for 200 damage.", -- [190]
			",", -- [191]
			"Start of round 13", -- [192]
			",", -- [193]
			"Venthyr Nightblade[0] meleed Sinstone Rampager[7][1081HP] for 183 damage.", -- [194]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Rampager[7][990HP] for 91  damage.", -- [195]
			"Venthyr Nightblade[0] cast Double Stab at Sinstone Rampager[7][945HP] for 45  damage.", -- [196]
			"Venthyr Nightblade[1] meleed Sinstone Rampager[7][762HP] for 183 damage.", -- [197]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Rampager[7][671HP] for 91  damage.", -- [198]
			"Venthyr Nightblade[1] cast Double Stab at Sinstone Rampager[7][626HP] for 45  damage.", -- [199]
			"Sinstone Rampager[7] meleed Venthyr Nightblade[0][41HP] for 190 damage.", -- [200]
			"Sinstone Shardling[8] meleed Venthyr Nightblade[1][0HP] for 200 damage.", -- [201]
			"Sinstone Shardling[8] killed Venthyr Nightblade[1][0HP].", -- [202]
			"Sinstone Shardling[8] cast Stone Bash at Venthyr Nightblade[0][0HP] for 400  damage.", -- [203]
			"Sinstone Shardling[8] killed Venthyr Nightblade[0][0HP].", -- [204]
		},
		["addonVersion"] = "9.2-084",
		["followers"] = {
			{
				["maxHP"] = 1525,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 44,
					}, -- [1]
				},
				["predictedFinalHP"] = -151,
				["name"] = "Venthyr Nightblade",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 183,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1525,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 1703,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 1,
						["spellID"] = 56,
					}, -- [1]
				},
				["predictedFinalHP"] = 121,
				["name"] = "Simone",
				["followerID"] = "0x00000000234AE9FC",
				["baseAttack"] = 244,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1703,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 1830,
				["spells"] = {
					{
						["duration"] = 4,
						["cooldown"] = 4,
						["spellID"] = 21,
					}, -- [1]
				},
				["predictedFinalHP"] = -65,
				["name"] = "Kaletar",
				["followerID"] = "0x00000000241C514A",
				["baseAttack"] = 244,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1830,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 1525,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 44,
					}, -- [1]
				},
				["predictedFinalHP"] = 1525,
				["name"] = "Venthyr Nightblade",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 183,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1525,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 1525,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 44,
					}, -- [1]
				},
				["predictedFinalHP"] = 1525,
				["name"] = "Venthyr Nightblade",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 183,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1525,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["missionID"] = 2265,
		["enemies"] = {
			{
				["maxHP"] = 4500,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 2,
						["spellID"] = 295,
					}, -- [1]
				},
				["name"] = "Sinstone Hoarder",
				["boardIndex"] = 6,
				["baseAttack"] = 170,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 4500,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 2250,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 294,
					}, -- [1]
				},
				["name"] = "Sinstone Shardling",
				["boardIndex"] = 5,
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2250,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 2250,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 294,
					}, -- [1]
				},
				["name"] = "Sinstone Shardling",
				["boardIndex"] = 8,
				["baseAttack"] = 200,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2250,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 3000,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 288,
					}, -- [1]
				},
				["name"] = "Sinstone Rampager",
				["boardIndex"] = 7,
				["baseAttack"] = 190,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 3000,
				["followerID"] = -4,
			}, -- [4]
		},
	},
}

**Comment by teelolws** [comment]
Thanks. The follower Kaletar is slightly overtuned in the Simulator. A fix for this will go up tomorrow.
