### ISSUE TITLE
[Feedback] Possible to cache calculations for future use?

### ISSUE THREAD

**Issue by Akhaim** [TLDRMissions/TLDRMissions#367]
Hi,

Thanks so much for building this addon :)

I wanted to check with you how feasible is it to cache calculations for successful missions and use them for the future? The reason for this is to avoid some of the long waiting times for sending some of the "random everything" missions?

My thinking is:
1. Addon calculates missions and caches successful follower/troop combos along with mission itself.
2. Second time that mission comes around the addon can check the cache, test the previously successful combo (if the follower is available) and either send the mission on its way or then recalculate a new combo if something changed.

Kindly let me know your thoughts and please close this if it doesn't fit.

Many thanks again for building such a useful addon.

**Comment by teelolws** [comment]
https://github.com/TLDRMissions/TLDRMissions/issues/73
https://github.com/TLDRMissions/TLDRMissions/issues/365
