### ISSUE TITLE
[Discrepancy] 2188 Venthyr

### ISSUE THREAD

**Issue by pingje** [TLDRMissions/TLDRMissions#369]
### Mission ID

2188

### Upload the saved variable file here

[TLDRMissions.lua_Siannodel_2188_20220613-083625.txt](https://github.com/TLDRMissions/TLDRMissions/files/8892487/TLDRMissions.lua_Siannodel_2188_20220613-083625.txt)

**Comment by teelolws** [comment]
Hi, unfortunately the log doesn't match the followers that were saved. It looks like the Saved Variables were not written properly when you logged out after sending the mission out. This can happen sometimes if your game crashes, you get disconnected, or various other reasons beyond our control.
