### ISSUE TITLE
Heal button

### ISSUE THREAD

**Issue by I-AM-T3X** [TLDRMissions/TLDRMissions#372]
Heal button on addon that processes the heal action from the companions Tab

Basically I have so much anima and i might only use 2k anima a week on missions, Could we possiably either get a reminder to heal or even a button added to addons UI to process the heal all command from the companions tab, so we can more effectively send our companions on missions

**Comment by teelolws** [comment]
Sorry, I don't think I'll do this. The vast majority of people don't want to do this, as healing followers is considered a waste. I don't want to be blamed for people "accidentally" clicking it and burning all their anima.
