### ISSUE TITLE
Podtender rounding issues

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#373]
### Mission ID

2308

### Upload the saved variable file here

[TLDRMissions-2022-06-14--2308.zip](https://github.com/TLDRMissions/TLDRMissions/files/8896123/TLDRMissions-2022-06-14--2308.zip)

**Comment by teelolws** [comment]
A workaround I previously made for Podtender is not working for this combatlog. Not sure if Blizzard simply fixed the rounding error, of if its more complicated. Will need to watch for more logs for this one.
