### ISSUE TITLE
[Feature Request] Something between "Prefer fewest" and "Prefer most" followers

### ISSUE THREAD

**Issue by tyfon7** [TLDRMissions/TLDRMissions#376]
I recognize this is a complex request, but a middle ground between these two options would be such a nice optimization.

The issue with the current options is that preferring most followers is very, very sub-optimal, but preferring fewest will go through 30k iterations and fail to find a solution to a mission that would be *easily* done by even just 2 followers. I assume its currently testing every follower with every combination of troops in every configuration, and it doesn't even get to 2 followers before it hits 30k and skips. 

An example of this is the "Duelmaster Rowyn" mission. My Kyrian followers are all lvl 60, but with "fewest" selected, TLDR was unable to find a solution to this lvl 38, single-enemy mission. 

An incredible solution to this would be a better heuristic to know when to stop testing lone followers and jump to 2, or 3, etc. I don't know how difficult this would be.

An easier solution would be simply allowing us to prefer 2, or prefer 3 followers, which would still be sub-optimal (but less so) while finding solutions to many more missions.

Thanks for this amazing addon!

**Comment by teelolws** [comment]
I appreciate the suggestion, though I am trying to take the programming in a different direction.

I am working on a system that will process, outside of the game before I distribute an update to the addon, whether it is not possible for a follower to solo a mission.

It will consider:

For each level of the mission between 50 and 62 (this is the typical level range where they are most difficult):
Test each follower under these circumstances:
- if the follower is level 60
- all troops are level 60
- the follower has full HP
Test every possible arrangement of that follower with 4 troops, if it cannot find a way to beat the mission, then it will save that {mission + level + follower} combination into a database, marking that combination as completely impossible.

The addon will then be able to look to that reference database, and if it finds that combination in the database, it will skip to the next follower. Then, if all the followers are in the database, it can skip straight to trying 2 followers.

I have yet to have a mission that failed with 2 followers but succeeded with 3 or 4. I'm sure it is possible, but it is a situation I'm not that concerned about.

Setting up that database is taking a considerable amount of computing power though, so it won't be ready for testing for a while.

For just 1 mission: 96 followers * 12 levels * 5! = 138240 simulations, this took my computer 16 minutes to chew through.

There are a about 150 missions.
