### ISSUE TITLE
Torghast Follower Farm localization help

### ISSUE THREAD

**Issue by Unplayed** [TLDRMissions/TLDRMissions#378]
**TLDR Version of your idea**
TLDR version: 87

9.2-087

Runecarver says on ruRU locale:

local runecarverSpeeches = {
        ["A child of Bastion... undeserving of such a fate. Lead them into light."] = 1,
"Дитя Бастиона не заслуживает такой судьбы. Спаси эту кирию."
        ["One who aspires has fallen prey. Guide them back upon the path."] = 1,
"Претендент стал жертвой. Направь пленника на истинный путь."
        ["Even a harvester of pride does not deserve to languish here. Save the venthyr from this fate."] = 2,
"Даже жнецы гордыни не заслуживают такой участи. Спаси этого вентира."
        ["The sins of the prideful echo through these halls. A harvester calls for aid."] = 2,
"Слышишь отголоски грехов горделивых душ? Жнец просит о помощи."
        ["A lost fae, bound in torment. Free them... lest they be consumed by darkness."] = 3,
"Потерянная, скованная душа из ночного народца... освободи ее от тьмы."
        ["A cry from your covenant... a fae to be freed. Do not let this one be lost."] = 3,
"Крик о помощи от твоего ковенанта... дитя ночного народца. Не дай ему сгинуть."
        ["Even your mightiest allies fall prey to these torments. Aid your covenant."] = 4,
"Даже сильнейшим из твоих союзников не выдержать этих мук. Помоги своему ковенанту."
        ["The brave... the mighty... the treacherous. All are bound here. Free them."] = 4,
"Смелые... могучие... коварные души. Все они здесь. Освободи их."

local treasureNames = {
    ["Rune Locked Vault"] = true,
"Запечатанное рунами хранилище"
    ["Lever Locked Chest"] = true,
"Управляемый рычагом сундук"

**Comment by teelolws** [comment]
Wow, someones actually using that? I'll add those next patch.

**Comment by Unplayed** [comment]
One problem.

Coldheart Interstitia, I'm Night Fae, found Renavyth (useless venthyr), I hear/see correct phrase:

[17:12:27] Резчик Рун говорит: Даже жнецы гордыни не заслуживают такой участи. Спаси этого вентира.

(Even a harvester of pride does not deserve to languish here. Save the venthyr from this fate)

...but addon doesn't auto leaves. On chests it works perfectly: autoleaves
![WoWScrnShot_061622_171529](https://user-images.githubusercontent.com/43932588/174051323-38eb7a26-3f2b-43c4-96c1-29ef96edc91c.jpg)
.

**Comment by teelolws** [comment]
Is "Резчик Рун говорит" Runecarver?

**Comment by teelolws** [comment]
Try this
[torghast-farm.zip](https://github.com/TLDRMissions/TLDRMissions/files/8918216/torghast-farm.zip)

**Comment by Unplayed** [comment]
Version in zip works ok.

"Резчик Рун" = "Runecarver"
"говорит" = "says".

Thank you! ;)

**Comment by Unplayed** [comment]
More localizations:

    ["Indri the Treesinger"] = true,
"Индри Древопев"
    ["Sawn"] = true,
"Шон"
    ["Indigo"] = true,
"Индиго"
    ["Renavyth"] = true,
"Ренавит"
    ["Moriaz the Red"] = true,
"Мориаза Красная"
    ["Calix"] = true,
"Каликс"
    ["Bloodletter Phantoriax"] = true,
"Кровопускатель Фанториакс"
    ["Gallath"] = true,
"Геллат"
    ["Ve'lor the Messenger"] = true,
"Ве'лор Посланник"


                print("[TLDR-TFF]: Treasure Chest detected, leaving...")
"Обнаружен сундук с сокровищами, выходим..."
                print("[TLDR-TFF]: That follower cannot be recruited. Leaving...")
"Этот спутник не может быть нанят. Выходим..."

**Comment by teelolws** [comment]
There probably won't be a patch today, so use this in the meantime:
[torghast-farm.zip](https://github.com/TLDRMissions/TLDRMissions/files/8934465/torghast-farm.zip)
