### ISSUE TITLE
Feature request: set max Campaign Mission Progress

### ISSUE THREAD

**Issue by sirzooro** [TLDRMissions/TLDRMissions#379]
**TLDR Version of your idea**
TLDR version: 
Allow setting maximum Campaign Mission Progress filter for missions.

**Slightly longer version**
Campaign Mission Progress 16 allows access to almost all of mission rewards. Last 4 levels awards mounts only, and increases mission difficulty. For alts it is better to stop at 16 and have easier to complete missions. Please add option to choose max Campaign Mission Progress, with values 16 and 20.

**Comment by teelolws** [comment]
I don't keep track of the Campaign Mission Progress and don't know how to. Can you not just uncheck and Exclude Campaign Missions when you get to 16?

**Comment by sirzooro** [comment]
I can to this and send missions manually, but I prefer some automation here.

Campaign Mission Progress is stored as currency 1889:
```/script print(C_CurrencyInfo.GetCurrencyInfo(1889).quantity)```

**Comment by teelolws** [comment]
I'll consider it for the future. Have other parts of this addon I'm working on for now.

**Comment by cpuritscher** [comment]
As a word of warning, C_CurrencyInfo.GetCurrencyInfo(1889).quantity is not reliable. 
Sometimes it works (and shows only the progress on your current covenant), but sometimes it bugs out and shows the progress among all your covenants:

![grafik](https://user-images.githubusercontent.com/67310095/173825202-2658ae13-aaca-43ff-b27e-50c1fcf61a33.png)

(Venture plan suffers from the same issue):
![grafik](https://user-images.githubusercontent.com/67310095/173824991-6225ad9e-8ea3-459c-a259-a169c022cddd.png)

**Comment by sirzooro** [comment]
I am aware of this bug. It happen when you start with one Covenant, switch to another one and then return back to the first one. For some reason this confuses WoW and it shows sum of all levels. I reported this bug to Blizzard recently but it is not fixed yet.

Anyway, despite this bug this feature would be useful. For most alts I did not unlock mission table on other covenants except for Night Fae, so returned value is correct. On few other ones I can use VenturePlan to manually start upgrade missions until I reach level when mounts are offered as a reward.

**Comment by teelolws** [comment]
Next patch:
![image](https://user-images.githubusercontent.com/49792789/175797864-0b22b003-98fc-42cb-a950-1ea6d14a182e.png)

**Comment by teelolws** [comment]
Probably but theres no internal "has this character *ever* done this missionID before?" function. I could track it within the addon, but that would mean I wouldn't know what ones the player completed before installing the addon, on another computer, before they lost their saved variables, etc. Also not sure how they work, are they a set list of missions always completed in order, or do you just do a random one out of a pool of missions?

**Comment by cpuritscher** [comment]
You unlock pools of missions when you reach a certain stage.

So if my memory serves well that means you unlock the four mount missions when you reach progress 15, but the order in which the actual missions of that pool appear is random. 

So if someone knows at what stage you trigger the pools you could group them by those stages.

**Comment by teelolws** [comment]
Its not a priority for me. If someone wants to compile a list of the Campaign Mission IDs with what bracket they can appear in, I'll add the code for that data.
