### ISSUE TITLE
[BUG] A mission failed! - 2243 Investigate the Investigators

### ISSUE THREAD

**Issue by sandarato** [TLDRMissions/TLDRMissions#380]
### Upload your Character-Specific Saved Variables here

TLDRMissionsOptions = {
}
TLDRMissionsLogging = {
	[2243] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Ardenweald Trapper[2] meleed Loyal Footman[6][2440HP] for 210 damage.", -- [4]
			"Ardenweald Trapper[2] cast Bramble Trap at Loyal Footman[6][2398HP] for 42  damage.", -- [5]
			"Ardenweald Trapper[2] cast Bramble Trap at Loyal Footman[7][2608HP] for 42  damage.", -- [6]
			"Ardenweald Trapper[2] cast Bramble Trap at Conceited Noble[9][2658HP] for 42  damage.", -- [7]
			"Ardenweald Trapper[2] cast Bramble Trap at Archive Investigator[10][3458HP] for 42  damage.", -- [8]
			"Ardenweald Trapper[2] cast Bramble Trap at Voracious Collector[11][2558HP] for 42  damage.", -- [9]
			"Ardenweald Trapper[2] cast Bramble Trap at Conceited Noble[12][2658HP] for 42  damage.", -- [10]
			"Ardenweald Trapper[2] applied Bramble Trap to Loyal Footman[6][2398HP].", -- [11]
			"Ardenweald Trapper[2] applied Bramble Trap to Loyal Footman[7][2608HP].", -- [12]
			"Ardenweald Trapper[2] applied Bramble Trap to Conceited Noble[9][2658HP].", -- [13]
			"Ardenweald Trapper[2] applied Bramble Trap to Archive Investigator[10][3458HP].", -- [14]
			"Ardenweald Trapper[2] applied Bramble Trap to Voracious Collector[11][2558HP].", -- [15]
			"Ardenweald Trapper[2] applied Bramble Trap to Conceited Noble[12][2658HP].", -- [16]
			"Ardenweald Grovetender[0] shot Conceited Noble[12][2308HP] for 350 damage.", -- [17]
			"Ardenweald Grovetender[1] shot Conceited Noble[9][2308HP] for 350 damage.", -- [18]
			"Ardenweald Grovetender[4] shot Conceited Noble[9][1958HP] for 350 damage.", -- [19]
			"Ardenweald Grovetender[4] cast Revitalizing Vines on Sulanoom[3][1254HP] for 350 healing.", -- [20]
			"Sulanoom[3] shot Conceited Noble[9][1608HP] for 350 damage.", -- [21]
			"Sulanoom[3] cast Roots of Submission at Conceited Noble[9][1188HP] for 420  damage.", -- [22]
			"Sulanoom[3] cast Roots of Submission at Archive Investigator[10][3038HP] for 420  damage.", -- [23]
			"Sulanoom[3] cast Roots of Submission at Voracious Collector[11][2138HP] for 420  damage.", -- [24]
			"Sulanoom[3] cast Roots of Submission at Conceited Noble[12][1888HP] for 420  damage.", -- [25]
			"Archive Investigator[10] shot Ardenweald Trapper[2][1916HP] for 184 damage.", -- [26]
			"Archive Investigator[10] applied Deceptive Practice to Ardenweald Grovetender[0][1400HP].", -- [27]
			"Archive Investigator[10] applied Deceptive Practice to Ardenweald Grovetender[1][1400HP].", -- [28]
			"Archive Investigator[10] applied Deceptive Practice to Ardenweald Trapper[2][1916HP].", -- [29]
			"Archive Investigator[10] applied Deceptive Practice to Sulanoom[3][1254HP].", -- [30]
			"Archive Investigator[10] applied Deceptive Practice to Ardenweald Grovetender[4][1400HP].", -- [31]
			"Conceited Noble[9] shot Ardenweald Grovetender[4][1216HP] for 184 damage.", -- [32]
			"Conceited Noble[9] applied Arrogant Denial to Ardenweald Grovetender[0][1400HP].", -- [33]
			"Conceited Noble[9] applied Arrogant Denial to Ardenweald Grovetender[1][1400HP].", -- [34]
			"Conceited Noble[9] applied Arrogant Denial to Ardenweald Trapper[2][1916HP].", -- [35]
			"Conceited Noble[9] applied Arrogant Denial to Sulanoom[3][1254HP].", -- [36]
			"Conceited Noble[9] applied Arrogant Denial to Ardenweald Grovetender[4][1216HP].", -- [37]
			"Conceited Noble[12] shot Ardenweald Trapper[2][1686HP] for 230 damage.", -- [38]
			"Conceited Noble[12] applied Arrogant Denial to Ardenweald Grovetender[0][1400HP].", -- [39]
			"Conceited Noble[12] applied Arrogant Denial to Ardenweald Grovetender[1][1400HP].", -- [40]
			"Conceited Noble[12] applied Arrogant Denial to Ardenweald Trapper[2][1686HP].", -- [41]
			"Conceited Noble[12] applied Arrogant Denial to Sulanoom[3][1254HP].", -- [42]
			"Conceited Noble[12] applied Arrogant Denial to Ardenweald Grovetender[4][1216HP].", -- [43]
			"Loyal Footman[6] meleed Ardenweald Trapper[2][1512HP] for 174 damage.", -- [44]
			"Loyal Footman[6] cast Shoulder Charge at Ardenweald Trapper[2][1427HP] for 85  damage.", -- [45]
			"Loyal Footman[7] meleed Sulanoom[3][1080HP] for 174 damage.", -- [46]
			"Loyal Footman[7] cast Shoulder Charge at Sulanoom[3][995HP] for 85  damage.", -- [47]
			"Voracious Collector[11] meleed Ardenweald Trapper[2][1139HP] for 288 damage.", -- [48]
			"Voracious Collector[11] cast Icy Blast at Ardenweald Grovetender[0][1184HP] for 216  damage.", -- [49]
			"Voracious Collector[11] applied Icy Blast to Ardenweald Grovetender[0][1184HP].", -- [50]
			",", -- [51]
			"Start of round 2", -- [52]
			",", -- [53]
			"Ardenweald Grovetender[1] shot Conceited Noble[9][1013HP] for 175 damage.", -- [54]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Ardenweald Grovetender[0][1400HP] for 350 healing.", -- [55]
			"Ardenweald Grovetender[4] shot Conceited Noble[9][838HP] for 175 damage.", -- [56]
			"Ardenweald Grovetender[0] shot Conceited Noble[12][1801HP] for 87 damage.", -- [57]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Ardenweald Trapper[2][1489HP] for 350 healing.", -- [58]
			"Ardenweald Trapper[2] removed Bramble Trap from Loyal Footman[6][2398HP].", -- [59]
			"Ardenweald Trapper[2] removed Bramble Trap from Loyal Footman[7][2608HP].", -- [60]
			"Ardenweald Trapper[2] removed Bramble Trap from Conceited Noble[9][838HP].", -- [61]
			"Ardenweald Trapper[2] removed Bramble Trap from Archive Investigator[10][3038HP].", -- [62]
			"Ardenweald Trapper[2] removed Bramble Trap from Voracious Collector[11][2138HP].", -- [63]
			"Ardenweald Trapper[2] removed Bramble Trap from Conceited Noble[12][1801HP].", -- [64]
			"Ardenweald Trapper[2] meleed Loyal Footman[6][2293HP] for 105 damage.", -- [65]
			"Sulanoom[3] shot Conceited Noble[9][663HP] for 175 damage.", -- [66]
			"Archive Investigator[10] shot Ardenweald Trapper[2][1144HP] for 345 damage.", -- [67]
			"Loyal Footman[7] meleed Sulanoom[3][778HP] for 217 damage.", -- [68]
			"Loyal Footman[6] meleed Ardenweald Trapper[2][927HP] for 217 damage.", -- [69]
			"Voracious Collector[11] meleed Ardenweald Trapper[2][567HP] for 360 damage.", -- [70]
			"Conceited Noble[12] removed Arrogant Denial from Ardenweald Grovetender[0][1400HP].", -- [71]
			"Conceited Noble[12] removed Arrogant Denial from Ardenweald Grovetender[1][1400HP].", -- [72]
			"Conceited Noble[12] removed Arrogant Denial from Ardenweald Trapper[2][567HP].", -- [73]
			"Conceited Noble[12] removed Arrogant Denial from Sulanoom[3][778HP].", -- [74]
			"Conceited Noble[12] removed Arrogant Denial from Ardenweald Grovetender[4][1216HP].", -- [75]
			"Conceited Noble[12] shot Ardenweald Trapper[2][280HP] for 287 damage.", -- [76]
			"Conceited Noble[9] removed Arrogant Denial from Ardenweald Grovetender[0][1400HP].", -- [77]
			"Conceited Noble[9] removed Arrogant Denial from Ardenweald Grovetender[1][1400HP].", -- [78]
			"Conceited Noble[9] removed Arrogant Denial from Ardenweald Trapper[2][280HP].", -- [79]
			"Conceited Noble[9] removed Arrogant Denial from Sulanoom[3][778HP].", -- [80]
			"Conceited Noble[9] removed Arrogant Denial from Ardenweald Grovetender[4][1216HP].", -- [81]
			"Conceited Noble[9] shot Ardenweald Grovetender[4][986HP] for 230 damage.", -- [82]
			",", -- [83]
			"Start of round 3", -- [84]
			",", -- [85]
			"Ardenweald Grovetender[0] shot Conceited Noble[12][1714HP] for 87 damage.", -- [86]
			"Ardenweald Grovetender[1] shot Conceited Noble[9][488HP] for 175 damage.", -- [87]
			"Ardenweald Grovetender[4] shot Conceited Noble[9][313HP] for 175 damage.", -- [88]
			"Sulanoom[3] shot Conceited Noble[9][138HP] for 175 damage.", -- [89]
			"Sulanoom[3] cast Roots of Submission at Conceited Noble[9][0HP] for 210  damage.", -- [90]
			"Sulanoom[3] cast Roots of Submission at Archive Investigator[10][2828HP] for 210  damage.", -- [91]
			"Sulanoom[3] cast Roots of Submission at Voracious Collector[11][1928HP] for 210  damage.", -- [92]
			"Sulanoom[3] cast Roots of Submission at Conceited Noble[12][1504HP] for 210  damage.", -- [93]
			"Sulanoom[3] killed Conceited Noble[9][0HP].", -- [94]
			"Ardenweald Trapper[2] meleed Loyal Footman[6][2188HP] for 105 damage.", -- [95]
			"Ardenweald Trapper[2] cast Bramble Trap at Loyal Footman[6][2167HP] for 21  damage.", -- [96]
			"Ardenweald Trapper[2] cast Bramble Trap at Loyal Footman[7][2587HP] for 21  damage.", -- [97]
			"Ardenweald Trapper[2] cast Bramble Trap at Archive Investigator[10][2807HP] for 21  damage.", -- [98]
			"Ardenweald Trapper[2] cast Bramble Trap at Voracious Collector[11][1907HP] for 21  damage.", -- [99]
			"Ardenweald Trapper[2] cast Bramble Trap at Conceited Noble[12][1483HP] for 21  damage.", -- [100]
			"Ardenweald Trapper[2] applied Bramble Trap to Loyal Footman[6][2167HP].", -- [101]
			"Ardenweald Trapper[2] applied Bramble Trap to Loyal Footman[7][2587HP].", -- [102]
			"Ardenweald Trapper[2] applied Bramble Trap to Archive Investigator[10][2807HP].", -- [103]
			"Ardenweald Trapper[2] applied Bramble Trap to Voracious Collector[11][1907HP].", -- [104]
			"Ardenweald Trapper[2] applied Bramble Trap to Conceited Noble[12][1483HP].", -- [105]
			"Archive Investigator[10] removed Deceptive Practice from Ardenweald Grovetender[0][1400HP].", -- [106]
			"Archive Investigator[10] removed Deceptive Practice from Ardenweald Grovetender[1][1400HP].", -- [107]
			"Archive Investigator[10] removed Deceptive Practice from Ardenweald Trapper[2][280HP].", -- [108]
			"Archive Investigator[10] removed Deceptive Practice from Sulanoom[3][778HP].", -- [109]
			"Archive Investigator[10] removed Deceptive Practice from Ardenweald Grovetender[4][986HP].", -- [110]
			"Archive Investigator[10] shot Ardenweald Trapper[2][96HP] for 184 damage.", -- [111]
			"Loyal Footman[7] meleed Sulanoom[3][662HP] for 116 damage.", -- [112]
			"Loyal Footman[6] meleed Ardenweald Trapper[2][0HP] for 116 damage.", -- [113]
			"Loyal Footman[6] killed Ardenweald Trapper[2][0HP].", -- [114]
			"Voracious Collector[11] removed Icy Blast from Ardenweald Grovetender[0][1400HP].", -- [115]
			"Voracious Collector[11] meleed Sulanoom[3][470HP] for 192 damage.", -- [116]
			"Conceited Noble[12] shot Ardenweald Grovetender[0][1216HP] for 184 damage.", -- [117]
			",", -- [118]
			"Start of round 4", -- [119]
			",", -- [120]
			"Ardenweald Grovetender[1] shot Archive Investigator[10][2457HP] for 350 damage.", -- [121]
			"Ardenweald Grovetender[0] shot Conceited Noble[12][1133HP] for 350 damage.", -- [122]
			"Ardenweald Grovetender[4] shot Archive Investigator[10][2107HP] for 350 damage.", -- [123]
			"Ardenweald Grovetender[4] cast Revitalizing Vines on Sulanoom[3][820HP] for 350 healing.", -- [124]
			"Sulanoom[3] shot Conceited Noble[12][783HP] for 350 damage.", -- [125]
			"Ardenweald Trapper[2] removed Bramble Trap from Loyal Footman[6][2167HP].", -- [126]
			"Ardenweald Trapper[2] removed Bramble Trap from Loyal Footman[7][2587HP].", -- [127]
			"Ardenweald Trapper[2] removed Bramble Trap from Archive Investigator[10][2107HP].", -- [128]
			"Ardenweald Trapper[2] removed Bramble Trap from Voracious Collector[11][1907HP].", -- [129]
			"Ardenweald Trapper[2] removed Bramble Trap from Conceited Noble[12][783HP].", -- [130]
			"Archive Investigator[10] shot Sulanoom[3][590HP] for 230 damage.", -- [131]
			"Loyal Footman[7] meleed Sulanoom[3][445HP] for 145 damage.", -- [132]
			"Loyal Footman[6] meleed Sulanoom[3][300HP] for 145 damage.", -- [133]
			"Voracious Collector[11] meleed Sulanoom[3][60HP] for 240 damage.", -- [134]
			"Conceited Noble[12] shot Ardenweald Grovetender[0][986HP] for 230 damage.", -- [135]
			",", -- [136]
			"Start of round 5", -- [137]
			",", -- [138]
			"Ardenweald Grovetender[1] shot Archive Investigator[10][1757HP] for 350 damage.", -- [139]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Ardenweald Grovetender[0][1336HP] for 350 healing.", -- [140]
			"Ardenweald Grovetender[0] shot Conceited Noble[12][433HP] for 350 damage.", -- [141]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Sulanoom[3][410HP] for 350 healing.", -- [142]
			"Ardenweald Grovetender[4] shot Archive Investigator[10][1407HP] for 350 damage.", -- [143]
			"Sulanoom[3] shot Conceited Noble[12][83HP] for 350 damage.", -- [144]
			"Sulanoom[3] cast Roots of Submission at Archive Investigator[10][987HP] for 420  damage.", -- [145]
			"Sulanoom[3] cast Roots of Submission at Voracious Collector[11][1487HP] for 420  damage.", -- [146]
			"Sulanoom[3] cast Roots of Submission at Conceited Noble[12][0HP] for 420  damage.", -- [147]
			"Sulanoom[3] killed Conceited Noble[12][0HP].", -- [148]
			"Loyal Footman[7] meleed Sulanoom[3][265HP] for 145 damage.", -- [149]
			"Loyal Footman[7] cast Shoulder Charge at Sulanoom[3][193HP] for 72  damage.", -- [150]
			"Loyal Footman[6] meleed Sulanoom[3][48HP] for 145 damage.", -- [151]
			"Loyal Footman[6] cast Shoulder Charge at Sulanoom[3][0HP] for 72  damage.", -- [152]
			"Loyal Footman[6] killed Sulanoom[3][0HP].", -- [153]
			"Archive Investigator[10] shot Ardenweald Grovetender[4][756HP] for 230 damage.", -- [154]
			"Voracious Collector[11] meleed Ardenweald Grovetender[4][516HP] for 240 damage.", -- [155]
			",", -- [156]
			"Start of round 6", -- [157]
			",", -- [158]
			"Ardenweald Grovetender[1] shot Archive Investigator[10][637HP] for 350 damage.", -- [159]
			"Ardenweald Grovetender[0] shot Voracious Collector[11][1137HP] for 350 damage.", -- [160]
			"Ardenweald Grovetender[4] shot Archive Investigator[10][287HP] for 350 damage.", -- [161]
			"Loyal Footman[7] meleed Ardenweald Grovetender[4][371HP] for 145 damage.", -- [162]
			"Loyal Footman[6] meleed Ardenweald Grovetender[0][1191HP] for 145 damage.", -- [163]
			"Voracious Collector[11] meleed Ardenweald Grovetender[4][131HP] for 240 damage.", -- [164]
			"Voracious Collector[11] cast Icy Blast at Ardenweald Grovetender[0][1011HP] for 180  damage.", -- [165]
			"Voracious Collector[11] applied Icy Blast to Ardenweald Grovetender[0][1011HP].", -- [166]
			"Archive Investigator[10] shot Ardenweald Grovetender[4][0HP] for 230 damage.", -- [167]
			"Archive Investigator[10] killed Ardenweald Grovetender[4][0HP].", -- [168]
			",", -- [169]
			"Start of round 7", -- [170]
			",", -- [171]
			"Ardenweald Grovetender[1] shot Archive Investigator[10][0HP] for 350 damage.", -- [172]
			"Ardenweald Grovetender[1] killed Archive Investigator[10][0HP].", -- [173]
			"Ardenweald Grovetender[0] shot Voracious Collector[11][875HP] for 262 damage.", -- [174]
			"Loyal Footman[7] meleed Ardenweald Grovetender[0][866HP] for 145 damage.", -- [175]
			"Loyal Footman[6] meleed Ardenweald Grovetender[0][721HP] for 145 damage.", -- [176]
			"Voracious Collector[11] meleed Ardenweald Grovetender[0][481HP] for 240 damage.", -- [177]
			",", -- [178]
			"Start of round 8", -- [179]
			",", -- [180]
			"Ardenweald Grovetender[1] shot Voracious Collector[11][525HP] for 350 damage.", -- [181]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Ardenweald Grovetender[0][831HP] for 350 healing.", -- [182]
			"Ardenweald Grovetender[0] shot Voracious Collector[11][263HP] for 262 damage.", -- [183]
			"Loyal Footman[7] meleed Ardenweald Grovetender[0][686HP] for 145 damage.", -- [184]
			"Loyal Footman[6] meleed Ardenweald Grovetender[0][541HP] for 145 damage.", -- [185]
			"Voracious Collector[11] removed Icy Blast from Ardenweald Grovetender[0][541HP].", -- [186]
			"Voracious Collector[11] meleed Ardenweald Grovetender[0][301HP] for 240 damage.", -- [187]
			",", -- [188]
			"Start of round 9", -- [189]
			",", -- [190]
			"Ardenweald Grovetender[1] shot Voracious Collector[11][0HP] for 350 damage.", -- [191]
			"Ardenweald Grovetender[1] killed Voracious Collector[11][0HP].", -- [192]
			"Ardenweald Grovetender[0] shot Loyal Footman[7][2237HP] for 350 damage.", -- [193]
			"Loyal Footman[7] meleed Ardenweald Grovetender[0][156HP] for 145 damage.", -- [194]
			"Loyal Footman[7] cast Shoulder Charge at Ardenweald Grovetender[0][84HP] for 72  damage.", -- [195]
			"Loyal Footman[6] meleed Ardenweald Grovetender[0][0HP] for 145 damage.", -- [196]
			"Loyal Footman[6] killed Ardenweald Grovetender[0][0HP].", -- [197]
			"Loyal Footman[6] cast Shoulder Charge at Ardenweald Grovetender[1][1328HP] for 72  damage.", -- [198]
			",", -- [199]
			"Start of round 10", -- [200]
			",", -- [201]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][1817HP] for 350 damage.", -- [202]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][1183HP] for 145 damage.", -- [203]
			"Loyal Footman[6] meleed Ardenweald Grovetender[1][1038HP] for 145 damage.", -- [204]
			",", -- [205]
			"Start of round 11", -- [206]
			",", -- [207]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][1467HP] for 350 damage.", -- [208]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Ardenweald Grovetender[1][1388HP] for 350 healing.", -- [209]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][1243HP] for 145 damage.", -- [210]
			"Loyal Footman[6] meleed Ardenweald Grovetender[1][1098HP] for 145 damage.", -- [211]
			",", -- [212]
			"Start of round 12", -- [213]
			",", -- [214]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][1117HP] for 350 damage.", -- [215]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][953HP] for 145 damage.", -- [216]
			"Loyal Footman[6] meleed Ardenweald Grovetender[1][808HP] for 145 damage.", -- [217]
			",", -- [218]
			"Start of round 13", -- [219]
			",", -- [220]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][767HP] for 350 damage.", -- [221]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][663HP] for 145 damage.", -- [222]
			"Loyal Footman[7] cast Shoulder Charge at Ardenweald Grovetender[1][591HP] for 72  damage.", -- [223]
			"Loyal Footman[6] meleed Ardenweald Grovetender[1][446HP] for 145 damage.", -- [224]
			"Loyal Footman[6] cast Shoulder Charge at Ardenweald Grovetender[1][374HP] for 72  damage.", -- [225]
			",", -- [226]
			"Start of round 14", -- [227]
			",", -- [228]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][417HP] for 350 damage.", -- [229]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Ardenweald Grovetender[1][724HP] for 350 healing.", -- [230]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][579HP] for 145 damage.", -- [231]
			"Loyal Footman[6] meleed Ardenweald Grovetender[1][434HP] for 145 damage.", -- [232]
			",", -- [233]
			"Start of round 15", -- [234]
			",", -- [235]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][67HP] for 350 damage.", -- [236]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][289HP] for 145 damage.", -- [237]
			"Loyal Footman[6] meleed Ardenweald Grovetender[1][144HP] for 145 damage.", -- [238]
			",", -- [239]
			"Start of round 16", -- [240]
			",", -- [241]
			"Ardenweald Grovetender[1] shot Loyal Footman[6][0HP] for 350 damage.", -- [242]
			"Ardenweald Grovetender[1] killed Loyal Footman[6][0HP].", -- [243]
			"Loyal Footman[7] meleed Ardenweald Grovetender[1][0HP] for 145 damage.", -- [244]
			"Loyal Footman[7] killed Ardenweald Grovetender[1][0HP].", -- [245]
		},
		["addonVersion"] = "9.2-088",
		["followers"] = {
			{
				["maxHP"] = 2100,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 1,
						["spellID"] = 302,
					}, -- [1]
				},
				["predictedFinalHP"] = -20,
				["name"] = "Ardenweald Trapper",
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["baseAttack"] = 210,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2100,
				["boardIndex"] = 2,
			}, -- [1]
			{
				["maxHP"] = 1750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 1,
						["spellID"] = 305,
					}, -- [1]
				},
				["predictedFinalHP"] = -29,
				["name"] = "Sulanoom",
				["followerID"] = "0x00000000332AAB00",
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 904,
				["boardIndex"] = 3,
			}, -- [2]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["predictedFinalHP"] = -1,
				["name"] = "Ardenweald Grovetender",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["boardIndex"] = 4,
			}, -- [3]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["predictedFinalHP"] = 757,
				["name"] = "Ardenweald Grovetender",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["boardIndex"] = 0,
			}, -- [4]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["predictedFinalHP"] = 1400,
				["name"] = "Ardenweald Grovetender",
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["boardIndex"] = 1,
			}, -- [5]
		},
		["missionID"] = 2243,
		["enemies"] = {
			{
				["boardIndex"] = 6,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 177,
					}, -- [1]
				},
				["name"] = "Loyal Footman",
				["followerID"] = -1,
				["baseAttack"] = 145,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2650,
				["maxHP"] = 2650,
			}, -- [1]
			{
				["boardIndex"] = 7,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 177,
					}, -- [1]
				},
				["name"] = "Loyal Footman",
				["followerID"] = -2,
				["baseAttack"] = 145,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2650,
				["maxHP"] = 2650,
			}, -- [2]
			{
				["boardIndex"] = 9,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 3,
						["spellID"] = 176,
					}, -- [1]
				},
				["name"] = "Conceited Noble",
				["followerID"] = -3,
				["baseAttack"] = 230,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 2700,
				["maxHP"] = 2700,
			}, -- [3]
			{
				["boardIndex"] = 12,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 3,
						["spellID"] = 176,
					}, -- [1]
				},
				["name"] = "Conceited Noble",
				["followerID"] = -4,
				["baseAttack"] = 230,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 2700,
				["maxHP"] = 2700,
			}, -- [4]
			{
				["boardIndex"] = 10,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 5,
						["spellID"] = 182,
					}, -- [1]
				},
				["name"] = "Archive Investigator",
				["followerID"] = -5,
				["baseAttack"] = 230,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 3500,
				["maxHP"] = 3500,
			}, -- [5]
			{
				["boardIndex"] = 11,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 173,
					}, -- [1]
				},
				["name"] = "Voracious Collector",
				["followerID"] = -6,
				["baseAttack"] = 240,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2600,
				["maxHP"] = 2600,
			}, -- [6]
		},
	},
}

**Comment by teelolws** [comment]
It looks like I introduced a bug in patch 088 that made the simulator not use your followers starting HP correctly. This bug caused your other mission to fail, too.

I've fixed the problem and released patch 090 now.
