### ISSUE TITLE
Blisswing Dazzledust rounding error

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#382]
### Mission ID

2236

### Upload the saved variable file here

[TLDRMissions-2022-06-17--2236.zip](https://github.com/TLDRMissions/TLDRMissions/files/8922607/TLDRMissions-2022-06-17--2236.zip)

**Comment by teelolws** [comment]
There is a Blisswing's Dazzledust spell math inconsistency. Comparing it to https://github.com/TLDRMissions/TLDRMissions/issues/318

In your log:

`Blisswing[1] applied Dazzledust to Callous Peacekeeper`
`Callous Peacekeeper[10] shot Blisswing[1][209HP] for 14 damage.`
Blisswing has baseattack 175, Dazzledust reduces damage dealt by 60% of baseattack --> 175*.6 = 105
Callous Peacekeeper has baseattack 120. 120 - 105 = 15. But it dealt 14 damage.

Compare to the linked log:

`Blisswing[0] applied Dazzledust to Party Animal[8][980HP].`
`Party Animal[8] meleed Ardenweald Grovetender[3][1242HP] for 3 damage.`
Blisswing's baseattack: 220. Dazzledust reduces damage dealt --> 220*.6 = 132
Party Animal has baseattack 135. 135 - 132 = 3. As expected.

**Comment by teelolws** [comment]
[2203] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Ardenweald Grovetender[0] shot Misguided Steward[8][1650HP] for 350 damage.", -- [4]
			"Ardenweald Grovetender[3] shot Misguided Steward[5][1650HP] for 350 damage.", -- [5]
			"Blisswing[2] meleed Misguided Steward[5][1490HP] for 160 damage.", -- [6]
			"Blisswing[2] applied Dazzledust to Misguided Steward[8][1650HP].", -- [7]
			"Decieved Steward[6] meleed Blisswing[2][395HP] for 85 damage.", -- [8]
			"Decieved Steward[6] applied Cursed Knowledge to Ardenweald Grovetender[0][1400HP].", -- [9]
			"Decieved Steward[6] applied Cursed Knowledge to Blisswing[2][395HP].", -- [10]
			"Decieved Steward[6] applied Cursed Knowledge to Ardenweald Grovetender[3][1400HP].", -- [11]
			"Misguided Steward[5] meleed Blisswing[2][255HP] for 140 damage.", -- [12]
			"Misguided Steward[5] cast Frantic Flap at Blisswing[2][143HP] for 112  damage.", -- [13]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][1260HP] for 140 damage.", -- [14]
			"Misguided Steward[7] cast Frantic Flap at Ardenweald Grovetender[3][1148HP] for 112  damage.", -- [15]
			"Misguided Steward[8] meleed Ardenweald Grovetender[3][1143HP] for 5 damage.", -- [16]
			"Misguided Steward[8] cast Frantic Flap at Ardenweald Grovetender[3][1143HP] for 0  damage.", -- [17]
			",", -- [18]
			"Start of round 2", -- [19]
			",", -- [20]
			"Ardenweald Grovetender[0] shot Misguided Steward[8][1300HP] for 350 damage.", -- [21]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Blisswing[2][480HP] for 350 healing.", -- [22]
			"Ardenweald Grovetender[3] shot Misguided Steward[5][1140HP] for 350 damage.", -- [23]
			"Blisswing[2] meleed Misguided Steward[5][980HP] for 160 damage.", -- [24]
			"Decieved Steward[6] meleed Blisswing[2][361HP] for 119 damage.", -- [25]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][1003HP] for 140 damage.", -- [26]
			"Misguided Steward[8] meleed Ardenweald Grovetender[3][998HP] for 5 damage.", -- [27]
			"Misguided Steward[5] meleed Blisswing[2][221HP] for 140 damage.", -- [28]
			",", -- [29]
			"Start of round 3", -- [30]
			",", -- [31]
			"Ardenweald Grovetender[0] shot Misguided Steward[8][950HP] for 350 damage.", -- [32]
			"Ardenweald Grovetender[3] shot Misguided Steward[5][630HP] for 350 damage.", -- [33]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Blisswing[2][480HP] for 350 healing.", -- [34]
			"Blisswing[2] meleed Misguided Steward[5][470HP] for 160 damage.", -- [35]
			"Decieved Steward[6] removed Cursed Knowledge from Ardenweald Grovetender[0][1400HP].", -- [36]
			"Decieved Steward[6] removed Cursed Knowledge from Blisswing[2][480HP].", -- [37]
			"Decieved Steward[6] removed Cursed Knowledge from Ardenweald Grovetender[3][998HP].", -- [38]
			"Decieved Steward[6] meleed Blisswing[2][395HP] for 85 damage.", -- [39]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][898HP] for 100 damage.", -- [40]
			"Misguided Steward[8] meleed Ardenweald Grovetender[3][894HP] for 4 damage.", -- [41]
			"Misguided Steward[5] meleed Blisswing[2][295HP] for 100 damage.", -- [42]
			",", -- [43]
			"Start of round 4", -- [44]
			",", -- [45]
			"Ardenweald Grovetender[0] shot Misguided Steward[8][600HP] for 350 damage.", -- [46]
			"Ardenweald Grovetender[3] shot Misguided Steward[5][120HP] for 350 damage.", -- [47]
			"Blisswing[2] removed Dazzledust from Misguided Steward[8][600HP].", -- [48]
			"Blisswing[2] meleed Misguided Steward[5][0HP] for 160 damage.", -- [49]
			"Blisswing[2] killed Misguided Steward[5][0HP].", -- [50]
			"Decieved Steward[6] meleed Blisswing[2][210HP] for 85 damage.", -- [51]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][794HP] for 100 damage.", -- [52]
			"Misguided Steward[8] meleed Ardenweald Grovetender[3][694HP] for 100 damage.", -- [53]
			",", -- [54]
			"Start of round 5", -- [55]
			",", -- [56]
			"Ardenweald Grovetender[0] shot Misguided Steward[8][250HP] for 350 damage.", -- [57]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Blisswing[2][480HP] for 350 healing.", -- [58]
			"Ardenweald Grovetender[3] shot Misguided Steward[8][0HP] for 350 damage.", -- [59]
			"Ardenweald Grovetender[3] killed Misguided Steward[8][0HP].", -- [60]
			"Blisswing[2] meleed Decieved Steward[6][2340HP] for 160 damage.", -- [61]
			"Decieved Steward[6] meleed Blisswing[2][395HP] for 85 damage.", -- [62]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][594HP] for 100 damage.", -- [63]
			",", -- [64]
			"Start of round 6", -- [65]
			",", -- [66]
			"Ardenweald Grovetender[0] shot Misguided Steward[7][1650HP] for 350 damage.", -- [67]
			"Ardenweald Grovetender[3] shot Decieved Steward[6][1990HP] for 350 damage.", -- [68]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Blisswing[2][480HP] for 350 healing.", -- [69]
			"Blisswing[2] meleed Decieved Steward[6][1830HP] for 160 damage.", -- [70]
			"Blisswing[2] applied Dazzledust to Misguided Steward[7][1650HP].", -- [71]
			"Decieved Steward[6] meleed Blisswing[2][395HP] for 85 damage.", -- [72]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][590HP] for 4 damage.", -- [73]
			"Misguided Steward[7] cast Frantic Flap at Ardenweald Grovetender[3][590HP] for 0  damage.", -- [74]
			",", -- [75]
			"Start of round 7", -- [76]
			",", -- [77]
			"Ardenweald Grovetender[0] shot Misguided Steward[7][1300HP] for 350 damage.", -- [78]
			"Ardenweald Grovetender[3] shot Decieved Steward[6][1480HP] for 350 damage.", -- [79]
			"Blisswing[2] meleed Decieved Steward[6][1320HP] for 160 damage.", -- [80]
			"Decieved Steward[6] meleed Blisswing[2][310HP] for 85 damage.", -- [81]
			"Decieved Steward[6] applied Cursed Knowledge to Ardenweald Grovetender[0][1400HP].", -- [82]
			"Decieved Steward[6] applied Cursed Knowledge to Blisswing[2][310HP].", -- [83]
			"Decieved Steward[6] applied Cursed Knowledge to Ardenweald Grovetender[3][590HP].", -- [84]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][585HP] for 5 damage.", -- [85]
			",", -- [86]
			"Start of round 8", -- [87]
			",", -- [88]
			"Ardenweald Grovetender[0] shot Misguided Steward[7][950HP] for 350 damage.", -- [89]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Blisswing[2][480HP] for 350 healing.", -- [90]
			"Ardenweald Grovetender[3] shot Decieved Steward[6][970HP] for 350 damage.", -- [91]
			"Blisswing[2] meleed Decieved Steward[6][810HP] for 160 damage.", -- [92]
			"Decieved Steward[6] meleed Blisswing[2][361HP] for 119 damage.", -- [93]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][580HP] for 5 damage.", -- [94]
			",", -- [95]
			"Start of round 9", -- [96]
			",", -- [97]
			"Ardenweald Grovetender[0] shot Misguided Steward[7][600HP] for 350 damage.", -- [98]
			"Ardenweald Grovetender[3] shot Decieved Steward[6][460HP] for 350 damage.", -- [99]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Blisswing[2][480HP] for 350 healing.", -- [100]
			"Blisswing[2] removed Dazzledust from Misguided Steward[7][600HP].", -- [101]
			"Blisswing[2] meleed Decieved Steward[6][300HP] for 160 damage.", -- [102]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][440HP] for 140 damage.", -- [103]
			"Decieved Steward[6] removed Cursed Knowledge from Ardenweald Grovetender[0][1400HP].", -- [104]
			"Decieved Steward[6] removed Cursed Knowledge from Blisswing[2][480HP].", -- [105]
			"Decieved Steward[6] removed Cursed Knowledge from Ardenweald Grovetender[3][440HP].", -- [106]
			"Decieved Steward[6] meleed Blisswing[2][395HP] for 85 damage.", -- [107]
			",", -- [108]
			"Start of round 10", -- [109]
			",", -- [110]
			"Ardenweald Grovetender[0] shot Misguided Steward[7][250HP] for 350 damage.", -- [111]
			"Ardenweald Grovetender[3] shot Decieved Steward[6][0HP] for 350 damage.", -- [112]
			"Ardenweald Grovetender[3] killed Decieved Steward[6][0HP].", -- [113]
			"Blisswing[2] meleed Misguided Steward[7][90HP] for 160 damage.", -- [114]
			"Misguided Steward[7] meleed Ardenweald Grovetender[3][340HP] for 100 damage.", -- [115]
			",", -- [116]
			"Start of round 11", -- [117]
			",", -- [118]
			"Ardenweald Grovetender[0] shot Misguided Steward[7][0HP] for 350 damage.", -- [119]
			"Ardenweald Grovetender[0] killed Misguided Steward[7][0HP].", -- [120]
		},
		["addonVersion"] = "9.2-092",
		["followers"] = {
			{
				["maxHP"] = 480,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 4,
						["spellID"] = 91,
					}, -- [1]
				},
				["xp"] = 150,
				["boardIndex"] = 2,
				["level"] = 22,
				["predictedFinalHP"] = 395,
				["name"] = "Blisswing",
				["levelXP"] = 1900,
				["baseAttack"] = 160,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 480,
				["followerID"] = "0x0000000022928917",
			}, -- [1]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 3,
				["level"] = 60,
				["predictedFinalHP"] = 346,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [2]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 0,
				["level"] = 60,
				["predictedFinalHP"] = 1400,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [3]
		},
		["missionID"] = 2203,
		["enemies"] = {
			{
				["maxHP"] = 2500,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 5,
						["spellID"] = 156,
					}, -- [1]
				},
				["name"] = "Decieved Steward",
				["boardIndex"] = 6,
				["baseAttack"] = 85,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2500,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 2000,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 157,
					}, -- [1]
				},
				["name"] = "Misguided Steward",
				["boardIndex"] = 7,
				["baseAttack"] = 100,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2000,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 2000,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 157,
					}, -- [1]
				},
				["name"] = "Misguided Steward",
				["boardIndex"] = 5,
				["baseAttack"] = 100,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2000,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 2000,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 157,
					}, -- [1]
				},
				["name"] = "Misguided Steward",
				["boardIndex"] = 8,
				["baseAttack"] = 100,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2000,
				["followerID"] = -4,
			}, -- [4]
		},
	},

**Comment by teelolws** [comment]
Seems to be issues with anything that does a -60% modifier. If the amount its reduced by is an odd number, it rounds up to an even number (so far).

https://github.com/TLDRMissions/TLDRMissions/issues/393
https://github.com/TLDRMissions/TLDRMissions/issues/370
