### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#397]
### Upload your Character-Specific Saved Variables here

2268
[TLDRMissions-2022-06-21--2268.zip](https://github.com/TLDRMissions/TLDRMissions/files/8947536/TLDRMissions-2022-06-21--2268.zip)

**Comment by teelolws** [comment]
Do you use this option?
![image](https://user-images.githubusercontent.com/49792789/174766838-f2b23c21-4679-4835-8f39-573eb28ce069.png)

**Comment by deNoor** [comment]
Yes :) But usually it does not report such death as "Failed mission".

**Comment by teelolws** [comment]
Yeah its not supposed to. It looks like its checking against when you sent the same mission out about a week ago. I'll tighten the checks up a bit to remove those older logs.
