### ISSUE TITLE
Simulation Overload

### ISSUE THREAD

**Issue by Gholrua** [TLDRMissions/TLDRMissions#398]
Having a strange issue.  Strange in that it's only happening on a single character, and in a single situation.  Whenever simulating Campaign missions on my Tauren Night Fae Shaman, shortly after starting (maybe 500 simulations in) my computer will restart.  I thought it might be an addon conflict or memory overload from too many addons, so I tried running the addon alone and that worked ONCE.  But today when I tried it again, my plan being to tell the addon not to send missions automatically and then start turning on addons one at a time while rerunning the simulations to find the culprit, the computer restarted about 2000 simulations in.
The mission he was trying to run was a Level 24 Campaign mission and he has 13 companions, 5 of which are level 21.  The addon was set to use followers 3 levels below the mission level (the default, I think).  On other characters I've seen the addon able to run 10,000 or more simulations without a problem.

**Comment by Gholrua** [comment]
OK, I had already sent a couple missions after I sent the original message cause I didn't expect a response so fast so I didn't have many companions available.  But it was able to run 1016 simulations and gave me a "No successful simulations found." message.  And that was with all other addons running.  Which is more sims than I usually get with other addons running on this character.  So, that might do the trick.  Will try again tomorrow when these missions have completed.

**Comment by Gholrua** [comment]
OK, logged back in today.  Was able to successfully run ~27k sims before finally finding a successful composition for the Campaign mission.  So, that seems to have done the trick.  Thank you so much. 

Still kinda irked by the one off of the situation.  Just thankful for individual profiles I guess.

**Comment by teelolws** [comment]
I'm guessing you were just playing on rather old hardware that couldn't keep up with the processing. Slowing the processing down sorted that out.
