### ISSUE TITLE
Fractal Thoughtbinder token type missions

### ISSUE THREAD

**Issue by jberryl** [TLDRMissions/TLDRMissions#400]
Fractal thoughtbinder token type missions: This question is mostly a reality check question. 
There are two types of follower exp boxes on the priority list and for me, those two are my top two in priority. Leveling up my followers. The fractal type tokens I thought would be assigned to that type of mission. Because it's so automated I'm just wondering if (because I saw some not being sent) these tokens are in fact marked as a follower exp. type mission. Sorry if this is not the place to ask the question.

**Comment by teelolws** [comment]
Yes, those tokens will be under the Follower XP Items category. If the mission wasn't sent, its probably because either:
- the anima cost was outside your filters
- it couldn't find a way to beat the mission with the followers and troops you have
