### ISSUE TITLE
[Discrepancy] [Failed] 2308

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#402]
### Mission ID

2308

### Upload the saved variable file here

[TLDRMissions-2022-06-22--2308.zip](https://github.com/TLDRMissions/TLDRMissions/files/8956227/TLDRMissions-2022-06-22--2308.zip)

**Comment by teelolws** [comment]
Looks the same as https://github.com/TLDRMissions/TLDRMissions/issues/397, you sent the mission out before my patch that fixed that problem.
