### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by zalidthebur** [TLDRMissions/TLDRMissions#408]
### Copy/paste the Lua error here

Date: 2022-06-24 00:13:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\TLDRMissions\guihandlers.lua line 593:
   attempt to perform arithmetic on local 'duration' (a nil value)
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=[C]"]: ?
   [string "@TLDRMissions\guihandlers.lua"]:593:
      TLDRMissions\guihandlers.lua:589
   [string "@TLDRMissions\guihandlers.lua"]:616: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:730: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:705: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:705: processing()
   [string "@TLDRMissions\guihandlers.lua"]:741:
      TLDRMissions\guihandlers.lua:608
   [string "@TLDRMissions\guihandlers.lua"]:959:
      TLDRMissions\guihandlers.lua:943
   [string "@TLDRMissions\guihandlers.lua"]:801: garrisonMissionStartedHandler()
   [string "@TLDRMissions\events.lua"]:66:
      TLDRMissions\events.lua:50
Locals:
errMsg = "Interface\AddOns\TLDRMissions\guihandlers.lua:593: attempt to perform arithmetic on local 'duration' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:609
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  swatter, v<%version%> (<%codename%>)
  WowheadLooter, v90205
  Ace3, vRelease-r1259
  AchievementsReminder, v
  AckisRecipeList, v9.1.0.1
  AckisRecipeListQuickScan, v7.3.0.1
  ACP, v3.5.7 
  AddonFactory, v9.2.001
  AdiBags, vv1.9.26
  AdvancedInterfaceOptions, v1.7.1
  AllTheThings, vSL-2.8.4
  Altoholic, v9.2.004
  Armory, vv16.5.0
  ArmoryGuildBank, vv16.5.0
  AskMrRobot, v112
  Auctionator, v9.1.19
  BadBoy, vv9.2.3
  BarrelsOEasy, v1.2.02
  BattlePetDailyTamer, v3.1.10
  BattlePetBreedID, vv1.20.2
  BonusRollPreview, v90000.48-Release
  BtWObjectiveFilter, v1.3
  BtWQuests, v2.15.3
  BtWQuestsBattleForAzeroth, v53.12
  BtWQuestsShadowlands, v6.2
  BtWQuestsShadowlandsPrologue, v1.7
  CanIMogIt, v9.2.5v1.33
  Chinchilla, vv2.12.2
  ClassTimer, v2.4.90001.1
  Collectinator, v9.0.2
  Collectionator, v0.91
  Collectionatordata, v0.91
  CollectMe, v2.11
  ConfirmSP, v0.21.07.06
  CovenantMissionHelper, v3.2.0
  DataStore, v2022.06.05
  DataStoreAchievements, v9.2.004
  DataStoreAgenda, v9.2.004
  DataStoreAuctions, v9.2.004
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v9.2.004
  DataStoreCrafts, v9.2.004
  DataStoreCurrencies, v9.2.004
  DataStoreGarrisons, v9.2.004
  DataStoreInventory, v9.2.004
  DataStoreMails, v2022.06.05
  DataStorePets, v9.2.004
  DataStoreQuests, v9.2.004
  DataStoreReputations, v9.2.004
  DataStoreSpells, v2022.06.05
  DataStoreStats, v9.2.004
  DataStoreTalents, v9.2.004
  DBMCore, v504201b
  DBMStatusBarTimers, v504201b
  DBMVPVEM, v49d3d7e
  DeathAlerts, v1.2
  Decursive, v2.7.8.6
  DejaCharacterStats, vR90205r1
  Dejunk, v9.1.2
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDelete, v9.0.1
  EasyMail, v4.4.9
  ExaltedPlus, v15
  ExRT, v4630
  FactionAddict, v1.72
  FamilyFamiliarHelper, v1.4.10
  FishingBuddy, v1.16.10
  FlaresThatWork, vr47
  FocusHealthPercent, v4.0.1
  GarrisonMissionManager, vv62
  GTFO, v4.67
  GuildRosterManager, v1.9297
  GuildBankSnapshots, vv2.0.9
  GuildCheck, vv 2.5.1
  HandyNotes, vv1.6.6
  HandyNotesBattleForAzeroth, v10
  HandyNotesBattleForAzerothTreasures, vv24
  HandyNotesBrokenShore, vv1.47
  HandyNotesDungeonLocations, v1.54
  HandyNotesLegionTreasures, vv27
  HandyNotesMistsOfPandariaTreasures, vv18
  HandynotesPandaria, v1.5.2
  HandyNotesShadowlandsTreasures, vv68
  HandyNotesTreasureHunter, vv26
  HandyNotesWorldMapButton, v90200.01-Retail
  Immersion, v1.4.3
  InFlightLoad, v9.2.0
  InstanceAchievementTracker, v3.41.0
  InterruptNoSpam, v1.8.6
  LargerMacroIconSelection, vv1.7.2
  LoggerHeadLite, v1.5.6
  LootSpecSwapper, v9.2.5.02
  MasterPlanA, vA
  MaxDps, v9.1.5
  MinimalArchaeology, v9.2.0
  MinimapButtonFrame, v3.2.2
  MinimapButtonFrameSkinPack, v3.0.1b
  mOnArsWardrobeHelper, v1.22
  MRT, v4630
  Notes, v9.1.1
  NPCTime, v1.0.6
  Omen, v3.2.4
  Overachiever, v1.1.5
  OverachieverCache, v1.1.5
  OverachieverTabs, v1.1.5
  OverachieverTrade, v1.1.5
  PakuTotems, v1.62
  PetBattleMaster, v9.0.1
  PetTracker, v9.2.0
  PetTrackerConfig, v
  PetTrackerJournal, v
  Plexus, vv2.2.30
  PointBlankSniper, v5.2
  ProtoformSynthesisFieldJournal, v1.2.9
  QuestSounds, v901-2020.10.14
  QuickMark, v
  QuizHelper, v
  RaidAchieveFilter, v2.0.5
  RareScanner, v9.2.5.1
  Rematch, v4.11.24
  SavedInstances, v9.2.2
  SilverDragon, vv90205.2
  SilverDragonBattleForAzeroth, vv90205.2
  SilverDragonBurningCrusade, vv90205.2
  SilverDragonCataclysm, vv90205.2
  SilverDragonLegion, vv90205.2
  SilverDragonMists, vv90205.2
  SilverDragonOverlay, vv90205.2
  SilverDragonRangeExtender, vv90205.2
  SilverDragonShadowlands, vv90205.2
  SilverDragonVanilla, vv90205.2
  SilverDragonWarlords, vv90205.2
  SilverDragonWrath, vv90205.2
  SkillHelper, vv4.1.13
  SoulshapeJournal, v1.2.1
  Stubby, v<%version%> (<%codename%>)
  SuperDuperMacro, vretail 9.0.1.2, classic 1.13.5.4
  TargetHealthPercent, v5.0
  tdBattlePetScript, v9.0.1
  tdBattlePetScriptRematch, v80100.01
  TellMeWhen, v9.2.3
  TheUndermineJournal, v5.6.20220621
  TidyPlatesThreatPlates, v10.3.8
  TLDRMissions, v9.2-099
  TokenSplainer, vr04
  TomTom, vv3.0.7
  TradeSkillMaster, vv4.11.32
  TradeSkillMasterAppHelper, vv4.0.21
  tullaRange, v9.2.0
  VenturePlan, v4.16a
  WarfrontRareTracker, v1.2.6
  WeakAuras, v4.0.2
  WorldQuestTracker, v
  WoWthingCollector, v9.2.5.6
  XanDurability, v5.0
  ZerethMortisPuzzleHelper, v1.5
  ZygorGuidesViewer, v8.1
  BlizRuntimeLib_enUS v9.2.5.90205 <none>
  (ck=1189)

This popped on one of my characters. All missions were sent and this popped.

**Comment by teelolws** [comment]
Thanks. I've seen this one before. For some reason, Blizzards code isn't telling me how long one of your missions is supposed to take. I'll add a check for it in the next patch.
