### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by teelolws** [TLDRMissions/TLDRMissions#410]
In the next version I'm updating the main UI a bit to look like this:
![image](https://user-images.githubusercontent.com/49792789/175444161-645359ab-ead9-4066-9329-f321ceef8b61.png)

I've always hated that the addon is just two pages of walls of text.

So, I'll give it a day before I release this. In the meantime, I need translations for that instructions line. In enUS it is:
`L["InstructionsLabel"] = "Choose the rewards you want, by how important they are:"`

@BlueNightSky @marco-kretz @Machou @SappFire2008

**Comment by teelolws** [comment]
Following feedback from one of my testers, I'm adding a second instruction line:
![image](https://user-images.githubusercontent.com/49792789/175446633-d00298c1-b01d-4d51-8da7-657a460cf9ad.png)

enUS.lua has been updated

**Comment by BlueNightSky** [comment]
zhtw & zhcn has been updated.

**Comment by Machou** [comment]
`L["InstructionsLabel"] = "Choisissez les récompenses que vous souhaitez, en fonction de leur importance :"`

:)

Nice Upgrade !

**Comment by teelolws** [comment]
The feedback from testers has been almost universally negative. I'm scrapping this design.
