### ISSUE TITLE
Follower names next to number of simulations.

### ISSUE THREAD

**Issue by deNoor** [TLDRMissions/TLDRMissions#417]
Looks like not intended because of mess. The names are being updated while simulation is in progress.
![image](https://user-images.githubusercontent.com/25015943/175765726-50dc67fe-5c7e-4830-b2f7-0367162748fe.png)

**Comment by teelolws** [comment]
You're only seeing it cause you have testing turned on. Its just some testing stuff while I figure out an issue. It'll be gone in a patch or two.
