### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by cdirection** [TLDRMissions/TLDRMissions#421]
The level 25 mission Subdue The Stewards is never being caught by TLDR and followers sent out, I have to do it manually. I don't know if that's just because it's a new mission and not worked in yet, but I figured I'd leave a note. It's always ignored, whether or not I have troops available.

**Comment by teelolws** [comment]
Whats the reward from that mission?

**Comment by cdirection** [comment]
Gold. 300ish.

**Comment by teelolws** [comment]
Then it wouldn't get skipped for no reason. Check all your filters and settings. If its a level 25 mission, then the default is not to try followers below level 22 on it.

**Comment by cdirection** [comment]
I will check it out when I swap back to that alt to be sure, but I think the follower I assigned to it manually was 24.

**Comment by cdirection** [comment]
Sorry about the delay, spent the night at the hospital. I had manually assigned a 24 to the quest as I thought, however the quest on another alt auto-triggered as it's supposed to. Waiting to see when Stewards comes around again on that specific alt.

**Comment by cdirection** [comment]
I had, yes, it's set to max, but if the quest won't assign 22 or lower on defaults that's irrelevant when sending a 24. When the mission re-arrives on that toon, I'll see what it does.

**Comment by teelolws** [comment]
What about your other settings? Anima cost, duration restrictions?

**Comment by cdirection** [comment]
Anima cost is set to middling, and no restriction on duration. It's possible the mission popped while it was calculating, I wouldn't know as I hadn't paid attention at the time. I do have it set to use minimum troops if they're not needed, would that affect it?

**Comment by cdirection** [comment]
Sorry, been sick. It's still consistently happening with that one toon, but it seems to be a conflict with other addons I have specific to that toon. If I disable everything but TLDR it doesn't happen, so I guess there's nothing on your end to be fixed, I just have to hunt down which of my dozens upon dozens of addons is making issues.

**Comment by teelolws** [comment]
Other players have reported an issue like yours https://github.com/TLDRMissions/TLDRMissions/issues/434 but I probably won't be able to fix it until it happens to me.

**Comment by teelolws** [comment]
Finally found the problem. Fix going up now.
