### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by jberryl** [TLDRMissions/TLDRMissions#422]
### Upload your Character-Specific Saved Variables here

Something changed. Prior to this post I had 1-7 mission types checked. No 1 and 2 priorities were the mission types dealing with follower XP. They were picking up the bonus tokens like Mind Expanding Prism. Then today it stopped picking ANY of them. I started unchecking mission types.
I have only two mission types checked now and both are the follower XP options. It STILL isn't picking up those bonus XP tokens at all. It's picking out crap stuff I never had checked (anima and mats). What happened cause I wasn't changing parameters until today. Tell me what the setup needs to be that picks these tokens and all xp missions only (like X + Y= all xp) first. If it's not going to do that let me know please. #1 priority is leveling my followers.

**Comment by teelolws** [comment]
Check your advanced settings. Your followers being a lot lower level than the mission is a common cause for this. Just change the slider if you don't like it:
![image](https://user-images.githubusercontent.com/49792789/175832610-c88f34af-0cec-4f29-b9da-48baa896efa5.png)

**Comment by jberryl** [comment]
Hey - I'm not sure why that would be an issue if it is suppose to be -  
Priority 1 - Bonus exp
Priority 2 - I want it to pick missions with Bonus Tokens. 
Most times two things are occurring - 1. While the Tokens contain more exp within the token than most Bonus exp missions the base exp. of other missions outside of those parameters are higher than the base exp of the Token Missions. For instnace
Bonus Exp missions are completed (Usually only 1 maybe 2 are available
P2 - Base exp is 500 but there are other missions that have 1500 base exp but the rewards I have no interest in. And it looks like its picking these missions. 
I get the "use followers less than" - but if I pick up a new follower and the average of my group of followers say is 35, (the avg really doesn't matter) on that priority 1 bonus exp mission, I want any follower that will increase their level on this type of mission starting with the lowest level follower working upward. 
So with that in mind, what should my advance settings be set at? (I'm obviously a little confused about that.)

But I do want to ask if the Reward portion of the mission when all are X out except bonus missions are being negated by the base exp over the exp tokens. Today I manually sent out all my Bonus exp missions before running TLDR for the rest. None failed. Yesterday using TLDR all failed. You can see why this might lead me to ask the question.

regards

**Comment by teelolws** [comment]
I don't understand you. Do you want to prioritise levelling followers that will increase your troops level? That is what this setting is for:
![image](https://user-images.githubusercontent.com/49792789/176089487-d39f8ca8-83f0-45fe-8d56-91d01ce68f53.png)

**Comment by jberryl** [comment]
Well that's funny because if you look at the last photo it picked out an X'd (bottom left) item because the add-on can't tell that the EXP token has more exp than the base value of any item in the board. Doesn't each item regardless of what it is have an ID#? It's too bad it cant. 
Seems like those tokens are the second most important item for leveling your followers with added value that they are account bound, not soulbound. Regards

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 28, 2022 at 3:03 PM, ***@***.***> wrote:   


It didn't send those missions because you have the red X next to Reputation and Crafting Cache. This is telling the addon not to send out missions that reward them, no matter what.

**Comment by teelolws** [comment]
You said the followers it didn't send were level 60. Why would you want them sent on XP missions when they are max level?

**Comment by jberryl** [comment]
"Why would you want them sent on XP missions when they are max level?"

There are two types of XP missions. One that awards straight up exp (base + completion reward) and one that awards a base exp, plus an account wide exp token (of 3000, 7500, or 10K which can be shared with alts) plus another award like gold, pet charms or mats. 
This begins with the mission table is at level 16. One caveat is that you have to have checked off the gold, pet charms or mats checked positive for it to be able to completed. Example: If you're not collecting pet charms so you decide to turn that off, any of the token + pet charms will not be sent out. At the time I asked this question, it was not clear that those conditions had to be true. 

Hope that answers why I'd want to use any follower regardless of level to be part of the mission crew. Completing the mission is more important than who completes the mission.
    On Tuesday, October 11, 2022 at 03:11:08 AM CDT, teelolws ***@***.***> wrote:  
 
 


You said the followers it didn't send were level 60. Why would you want them sent on XP missions when they are max level?

**Comment by teelolws** [comment]
In your picture example, one of the missions with a Follower XP Item did not send because you Red X Crossed out the other reward that mission has - the crafting cache. If you want it to disregard the crafting cache, rather than forbid the reward, then leave that box blank instead of Red X-ing it out.
