### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by philkjacobs** [TLDRMissions/TLDRMissions#423]
### Upload your Character-Specific Saved Variables here

Hello! I saw the popup requesting the `SavedVariables/` file when I failed a mission. Here's the output: https://gist.github.com/philkjacobs/5414dd27bc04914b6acb8ac663e34292

**Comment by teelolws** [comment]
Hi, you're running version 9.2-098. There was a bug that has since been fixed that caused this mission to fail. Make sure to update.
