### ISSUE TITLE
Follower bonus XP missions

### ISSUE THREAD

**Issue by phoenixsoap** [TLDRMissions/TLDRMissions#426]
Hi,

Great addon! I have 2 feature ideas

1. When checking who to send on a bonus follower xp mission it'd be great to check to see if that companion is not level 60 already

2. Sending one follower on a mission is great, but more than one can be sent. I like to send 5 on mine, it'd be great to have an option for this too

Thanks for the great work!

**Comment by teelolws** [comment]
Hi, check the advanced settings tab. Its already an option to do what you're asking for.

**Comment by teelolws** [comment]
Not that, look for a checkbox, something like "special treatment for follower XP"
