### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by Imna1975** [TLDRMissions/TLDRMissions#427]
### Copy/paste the Lua error here

1x TLDRMissions\simulation.lua:1538: attempt to index local 'info' (a nil value)
[string "@TLDRMissions\simulation.lua"]:1538: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:8: in function `func'
[string "@TLDRMissions\workhandler.lua"]:51: in function <TLDRMissions\workhandler.lua:23>

Locals:
self = <table> {
 createWorkBatch = <function> defined @TLDRMissions\workhandler.lua:100
 TestFirstTenFollowersPlusTroops = <function> defined @TLDRMissions\testing.lua:49
 reputationCurrencyIDs = <table> {
 }
 updateRewards = <function> defined @TLDRMissions\guihandlers.lua:28
 craftingCacheCategories = <table> {
 }
 getFrontEnemies = <function> defined @TLDRMissions\targetting.lua:421
 logSentMission = <function> defined @TLDRMissions\logging.lua:10
 isCurrentWorkBatchEmpty = <function> defined @TLDRMissions\workhandler.lua:119
 craftingCacheQualities = <table> {
 }
 getAllEnemies = <function> defined @TLDRMissions\targetting.lua:524
 unpauseWorker = <function> defined @TLDRMissions\workhandler.lua:92
 setResultCacheGuaranteedFailure = <function> defined @TLDRMissions\caching.lua:94
 getAdjacentAlliesOrAllAllies = <function> defined @TLDRMissions\targetting.lua:379
 ProfileChanged = <function> defined @TLDRMissions\profiles.lua:563
 LibStub = <table> {
 }
 sortFollowers = <function> defined @TLDRMissions\combinations.lua:111
 GetAllMissionsMatchingFilter = <function> defined @TLDRMissions\missions.lua:201
 sanctumFeatureItems = <table> {
 }
 getBackEnemies = <function> defined @TLDRMissions\targetting.lua:462
 getLineEnemies = <function> defined @TLDRMissions\targetting.lua:207
 isResultCacheGuaranteedFailure = <function> defined @TLDRMissions\caching.lua:77
 SimulateFromLog = <function> defined @TLDRMissions\simulation.lua:1591
 spellsDB = <table> {
 }
 getPseudorandomMawswornStrength = <function> defined @TLDRMissions\targetting.lua:618
 runecarverCurrencyIDs = <table> {
 }
 GUI = TLDRMissionsFrame {
 }
 getCleaveEnemies = <function> defined @TLDRMissions\targetting.lua:67
 getClosestEnemy = <function> defined @TLDRMissions\targetting.lua:23
 arrangeAllFollowerPositions = <function> defined @TLDRMissions\combinations.lua:31
 getAllAllies = <function> defined @TLDRMissions\targetting.lua:512
 Simulate = <function> defined @TLDRMissions\simulation.lua:1474
 dontWait = false
 RefreshProfile = <function> defined @TLDRMissions\profiles.lua:8
 getFurthestEnemy = <function> defined @TLDRMissions\targetting.lua:140
 db = <table> {
 }
 C_Garrison_GetFollowerAutoCombatStats = <function> defined @TLDRMissions\caching.lua:262
 setResultCacheCombinationKnown = <function> defined @TLDRMissions\caching.lua:207
 setResultCacheCombinationUnknown = <function> defined @TLDRMissions\caching.lua:173
 GetRunecarverMissions = <function> defined @TLDRMissions\missions.lua:382
 isResultCacheCombinationKnown = <function> defined @TLDRMissions\caching.lua:128
 getPseudorandomLashOut = <function> defined @TLDRMissions\targetting.lua:865
 followerXPItemIDs = <table> {
 }
 getConeEnemies = <function> defined @TLDRMissions\targetting.lua:268
 C_Garrison_GetFollowerInfo = <function> defined @TLDRMissions\caching.lua:6
 GetCraftingCacheMissions = <function> defined @TLDRMissions\missions.lua:348
 garrisonMissionStartedHandler = <function> defined @TLDRMissions\guihandlers.lua:809
 addWork = <function> defined @TLDRMissions\workhandler.lua:106
 GetFollowerXPItemMissions = <function> defined @TLDRMissions\missions.lua:265
 arrangeFollowerCombinationsByFewestFollowersPlusTroops = <function> defined @TLDRMissions\combinations.lua:360
 TestExistingMission = <function> defined @TLDRMissions\testing.lua:69
 GetPetCharmMissions = <function> defined @TLDRMissions\missions.lua:304
 registerW

**Comment by teelolws** [comment]
Did you change zones while the simulator was running? Hearthstoned while you were at the table trying to send out missions?

**Comment by Imna1975** [comment]
I ran the simulation in maldraxxus and the error came only after loading it again

**Comment by teelolws** [comment]
Something went wrong with the game on Blizzards end. If it happens again, just /reload and try again.

**Comment by Thecrashbug** [comment]
I updated my "libuidropdownmenu" manually on curse and my errors went away.
