### ISSUE TITLE
Refresh mission list after starting a mission

### ISSUE THREAD

**Issue by B88000005** [TLDRMissions/TLDRMissions#428]
**TLDR Version of your idea**
TLDR version: 101

**Slightly longer version**

**Additional context**
Sometimes a new mission will appear after I start a mission. I think it is because the mission list has an upper limit. The addon can auto-refresh the mission list and check the type of reward of the new mission after it start a mission.

**Comment by teelolws** [comment]
Can't do this, due to the way the assign is designed. If new missions appear and you want them included, you should cancel and restart the calculations.
