### ISSUE TITLE
High XP missions

### ISSUE THREAD

**Issue by palacode** [TLDRMissions/TLDRMissions#430]
**TLDR Version of your idea**
TLDR version: A new category called "High XP missions" with 500-999, and 1000+ options.

**Slightly longer version**
It would be great if we can prioritize the High XP missions regardless of the other reward. Similar to bonus follower xp missions, these missions are also sent with maximum number of followers to maximize xp gain. 
This is different than "send followers to fail for XP" because player might not want to fail. 

**Additional context**

**Comment by teelolws** [comment]
Hi, this has been suggested here https://github.com/TLDRMissions/TLDRMissions/issues/390 and is on my list, just not a priority.
