### ISSUE TITLE
[BUG] No successful mission were found

### ISSUE THREAD

**Issue by cpuritscher** [TLDRMissions/TLDRMissions#434]
I have the problem since a few versions I think that sometimes mission are no longer being sent although there is a perfectly easy solution.
Right here you see two missions "invasive Action" and "Bag Inspection" that should be sent according to my settings, and I have one follower (Elwyn, level 55, now at 323/1950 life) and level 60 troops. Both missions would be easily won with any follower and 5 trappers, but tldr doesn't seem to agree:
![grafik](https://user-images.githubusercontent.com/67310095/176738706-fd6d2807-60a6-44ce-b4f4-18f308219860.png)

Also both venture plan as well as the covenant mission helper agree that the mission would be easily won:
![grafik](https://user-images.githubusercontent.com/67310095/176738843-8efe2305-eb3c-4e35-8375-81f7ebce611e.png)

Any idea? Anything I could further provide?

**Comment by teelolws** [comment]
I am aware of this issue from reports from other players, but unfortunately I cant find the cause of it, and probably won't be able to fix it until the problem happens to me.

**Comment by teelolws** [comment]
Finally found the problem. Fix going up now.
