### ISSUE TITLE
the button is abnormally large

### ISSUE THREAD

**Issue by artazika** [TLDRMissions/TLDRMissions#436]
TLDR version: [9.2-103]

The button after the last update has become abnormally huge. Is it possible to return everything back, it looks ugly and stands out from the interface.

**Comment by BlueNightSky** [comment]
I also think it is a bit bigger...

**Comment by teelolws** [comment]
Yeah I doubled the size of the button because a lot of people have made videos about the addon, and the one thing I noticed on them all is the button was barely noticable, so I wanted to make it more prominent.

**Comment by glassleo** [comment]
Can we have an option to make it smaller? It's very obnoxious and I always have the window open automatically anyway so I never actually need to click on it.

Also, the button shows up on the Shadowlands map when you are choosing which zone to pick during Threads of Fate. I don't think that's intended.

**Comment by m4xc4v413r4** [comment]
> Yeah I doubled the size of the button because a lot of people have made videos about the addon, and the one thing I noticed on them all is the button was barely noticable, so I wanted to make it more prominent.

They probably have a very high resolution and have the UI scaled. Instead of just making it bigger you should take those variables into account.

I agree with the others that the buttons are now way too large.
