### ISSUE TITLE
[BUG] A venth mission failed!

### ISSUE THREAD

**Issue by Nillx** [TLDRMissions/TLDRMissions#437]
### Upload your Character-Specific Saved Variables here

[TLDRMissions.txt](https://github.com/TLDRMissions/TLDRMissions/files/9031679/TLDRMissions.txt)

**Comment by teelolws** [comment]
Thanks. Mission 2343 has 2 minions with Taunt, and Taunt behaves... weirdly. I just have to address them when I get logs. Fixed next patch.
