### ISSUE TITLE
Mission exceeding Anima Cost

### ISSUE THREAD

**Issue by pcangelnc** [TLDRMissions/TLDRMissions#439]
Maybe I am misunderstanding the settings (new to using this addon), but I have Anima Price Limit set to 50.  However, it just tried to send a Sacrifice Followers mission with an Anima cost of 100.  Am I missing a setting or is this a bug?

Also, I've noticed that some Sacrifice Followers missions, If I manually add the helpers, the mission is successful, is there a setting I missed to make this happen? (I mean why not get the rewards AND the xp?)

**Comment by teelolws** [comment]
The sacrifice doesn't currently follow the anima restrictions, it'll send out anything with the highest amount of XP, which is usually also high anima. Are you sure you'd rather have it subject to the anima restriction? You won't get as much XP for the mission.

**Comment by pcangelnc** [comment]
Good to know-still using anima for other things so trying to balance xp with anima.  Now that I know, I'll watch it more carefully. What is the logic for making that different or not offering an option for the amount of anima?

**Comment by teelolws** [comment]
No logic, I just didn't consider it when I was making that. I'm interested in your feedback, though. If you limit them by anima, you won't get as much XP. If you have the limits low enough, there would be a point where you'd probably be better off not sending them, just save them for when new missions popup in an hour.

**Comment by pcangelnc** [comment]
Well, I only send missions out once/day (if that).  The one I noticed it happening on was with only 2 followers so decided it wasn't worth it. The other question I asked about was related to this, as I had a Sacrifice mission that was set to fail with just the last 2 followers. So I used my other addon, Venture Plan, and it was successful with adding 1 helper.  Is there a setting I have wrong so tl:dr didn't do this?

**Comment by teelolws** [comment]
Well the latest version adds the option to just send those last two on anything that awards the most XP. You could use that instead? It will respect your special treatment setting:
![image](https://user-images.githubusercontent.com/49792789/176986097-d8634320-8909-4299-88c6-0f1609c8dc3c.png)

**Comment by pcangelnc** [comment]
Thank you and apologize for taking up so much of your time.  I'll tweak it some more and watch to see what it does.  I appreciate your time responding to me-I am really enjoying the automation and personalization available with the addon :)
