### ISSUE TITLE
[BUG] profiles are not working

### ISSUE THREAD

**Issue by Ahfau77** [TLDRMissions/TLDRMissions#442]
Hi,
first i want to thank you for this great addon and the frequent care you are investing in it.

When i open the profile-options i cannot change/edit anything there anymore.
It only shows "current profile: Default" but i am unable to change, copy or delete profiles.
All fields are empty and when i click on any dropdown-button at this page nothing happens at all.

regards

**Comment by teelolws** [comment]
You probably have another addon interfering with it. Turn on errors and show me the error.

`/console scriptErrors 1`

**Comment by czullo** [comment]
i got similar problem. Im using single profile for all tons. When i select new option, and relog on another toon, option isnt selected but TLDRMission is doing this mission

**Comment by Ahfau77** [comment]
Unfortunately enabling scriptErrors (with /reload afterwards) didn't show anything.

So, i decided to deactivate all addons and re-activate again them step by step.
I was able to find the deprecated addon "Makro Toolkit" (https://www.curseforge.com/wow/addons/macro-toolkit) as reason for my problem with your addon...

**Comment by Ahfau77** [comment]
As addition, the newly added option "Then, anything else for XP:" is not saved in my profile(s).

**Comment by czullo** [comment]
> As addition, the newly added option "Then, anything else for XP:" is not saved in my profile(s).

its "saved" but its not visible. its visual bug i think.

**Comment by teelolws** [comment]
Correct, thats just a visual bug. I'll fix it next patch. I'll also investigate that addon you linked.
