### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by truecallingAD** [TLDRMissions/TLDRMissions#444]
### Upload your Character-Specific Saved Variables here

TLDRMissionsOptions = nil
TLDRMissionsLogging = {
	[2239] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Kyrian Phalanx[2] meleed Viscious Terrorwing[5][1346HP] for 134 damage.", -- [4]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Kyrian Phalanx[2][2345HP].", -- [5]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Clora[0][576HP].", -- [6]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Kyrian Halberdier[1][1005HP].", -- [7]
			"Kyrian Phalanx[3] meleed Fiendish Terrorwing[6][846HP] for 134 damage.", -- [8]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Phalanx[3][2345HP].", -- [9]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Clora[0][576HP].", -- [10]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Halberdier[1][1005HP].", -- [11]
			"ELGU - 007[4] meleed Fiendish Terrorwing[7][650HP] for 330 damage.", -- [12]
			"ELGU - 007[4] cast Panoptic Beam at Fiendish Terrorwing[7][56HP] for 594  damage.", -- [13]
			"ELGU - 007[4] cast Panoptic Beam at Feral Terrorwing[10][1886HP] for 594  damage.", -- [14]
			"ELGU - 007[4] cast Panoptic Beam at Starving Terrorwing[11][386HP] for 594  damage.", -- [15]
			"ELGU - 007[4] cast Panoptic Beam at Starving Terrorwing[12][386HP] for 594  damage.", -- [16]
			"Kyrian Halberdier[1] meleed Fiendish Terrorwing[6][578HP] for 268 damage.", -- [17]
			"Kyrian Halberdier[1] cast Halberd Strike at Starving Terrorwing[9][659HP] for 321  damage.", -- [18]
			"Clora[0] meleed Viscious Terrorwing[5][1136HP] for 210 damage.", -- [19]
			"Clora[0] cast Cleave at Viscious Terrorwing[5][1073HP] for 63  damage.", -- [20]
			"Clora[0] cast Cleave at Fiendish Terrorwing[6][515HP] for 63  damage.", -- [21]
			"Clora[0] cast Cleave at Fiendish Terrorwing[7][0HP] for 63  damage.", -- [22]
			"Clora[0] cast Cleave at Viscious Terrorwing[8][1417HP] for 63  damage.", -- [23]
			"Clora[0] killed Fiendish Terrorwing[7][0HP].", -- [24]
			"Feral Terrorwing[10] shot Kyrian Phalanx[2][2119HP] for 226 damage.", -- [25]
			"Feral Terrorwing[10] cast Razor Shards at Kyrian Halberdier[1][703HP] for 302  damage.", -- [26]
			"Viscious Terrorwing[5] meleed Kyrian Phalanx[2][1902HP] for 217 damage.", -- [27]
			"Viscious Terrorwing[5] cast Winged Assault at Kyrian Phalanx[2][1249HP] for 653  damage.", -- [28]
			"Viscious Terrorwing[8] meleed ELGU - 007[4][1738HP] for 242 damage.", -- [29]
			"Viscious Terrorwing[8] cast Winged Assault at ELGU - 007[4][1012HP] for 726  damage.", -- [30]
			"Fiendish Terrorwing[6] meleed Kyrian Phalanx[2][1041HP] for 208 damage.", -- [31]
			"Fiendish Terrorwing[6] applied Dark Flame to Kyrian Phalanx[2][1041HP].", -- [32]
			"Fiendish Terrorwing[6] applied Dark Flame to Clora[0][576HP].", -- [33]
			"Fiendish Terrorwing[6]'s Dark Flame dealt 417  to Kyrian Phalanx[2][624HP].", -- [34]
			"Fiendish Terrorwing[6]'s Dark Flame dealt 371  to Clora[0][205HP].", -- [35]
			"Starving Terrorwing[9] shot Kyrian Phalanx[2][425HP] for 199 damage.", -- [36]
			"Starving Terrorwing[9] cast Leeching Bite at Starving Terrorwing[12][164HP] for 222  damage.", -- [37]
			"Starving Terrorwing[9] cast Leeching Bite on Starving Terrorwing[9][770HP] for 111 healing.", -- [38]
			"Starving Terrorwing[11] shot Kyrian Phalanx[2][226HP] for 199 damage.", -- [39]
			"Starving Terrorwing[11] cast Leeching Bite at Starving Terrorwing[12][0HP] for 222  damage.", -- [40]
			"Starving Terrorwing[11] killed Starving Terrorwing[12][0HP].", -- [41]
			"Starving Terrorwing[11] cast Leeching Bite on Starving Terrorwing[11][497HP] for 111 healing.", -- [42]
			",", -- [43]
			"Start of round 2", -- [44]
			",", -- [45]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Phalanx[3][2345HP].", -- [46]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Clora[0][205HP].", -- [47]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Halberdier[1][703HP].", -- [48]
			"Kyrian Phalanx[3] meleed Fiendish Terrorwing[6][381HP] for 134 damage.", -- [49]
			"ELGU - 007[4] meleed Viscious Terrorwing[8][1087HP] for 330 damage.", -- [50]
			"Kyrian Halberdier[1] meleed Fiendish Terrorwing[6][113HP] for 268 damage.", -- [51]
			"Kyrian Phalanx[2] removed Shield of Tomorrow from Kyrian Phalanx[2][226HP].", -- [52]
			"Kyrian Phalanx[2] removed Shield of Tomorrow from Clora[0][205HP].", -- [53]
			"Kyrian Phalanx[2] removed Shield of Tomorrow from Kyrian Halberdier[1][703HP].", -- [54]
			"Kyrian Phalanx[2] meleed Viscious Terrorwing[5][939HP] for 134 damage.", -- [55]
			"Clora[0] meleed Viscious Terrorwing[5][729HP] for 210 damage.", -- [56]
			"Feral Terrorwing[10] shot Kyrian Phalanx[2][0HP] for 252 damage.", -- [57]
			"Feral Terrorwing[10] killed Kyrian Phalanx[2][0HP].", -- [58]
			"Viscious Terrorwing[8] meleed ELGU - 007[4][770HP] for 242 damage.", -- [59]
			"Viscious Terrorwing[5] meleed Clora[0][0HP] for 242 damage.", -- [60]
			"Viscious Terrorwing[5] killed Clora[0][0HP].", -- [61]
			"Starving Terrorwing[9] shot Kyrian Phalanx[3][2123HP] for 222 damage.", -- [62]
			"Fiendish Terrorwing[6] meleed Kyrian Phalanx[3][1891HP] for 232 damage.", -- [63]
			"Starving Terrorwing[11] shot Kyrian Phalanx[3][1669HP] for 222 damage.", -- [64]
			",", -- [65]
			"Start of round 3", -- [66]
			",", -- [67]
			"Kyrian Phalanx[3] meleed Fiendish Terrorwing[6][0HP] for 134 damage.", -- [68]
			"Kyrian Phalanx[3] killed Fiendish Terrorwing[6][0HP].", -- [69]
			"ELGU - 007[4] meleed Viscious Terrorwing[8][757HP] for 330 damage.", -- [70]
			"Kyrian Halberdier[1] meleed Starving Terrorwing[11][229HP] for 268 damage.", -- [71]
			"Feral Terrorwing[10] shot Kyrian Phalanx[3][1417HP] for 252 damage.", -- [72]
			"Viscious Terrorwing[8] meleed ELGU - 007[4][528HP] for 242 damage.", -- [73]
			"Starving Terrorwing[9] shot Kyrian Phalanx[3][1195HP] for 222 damage.", -- [74]
			"Viscious Terrorwing[5] meleed Kyrian Phalanx[3][953HP] for 242 damage.", -- [75]
			"Starving Terrorwing[11] shot Kyrian Phalanx[3][731HP] for 222 damage.", -- [76]
			",", -- [77]
			"Start of round 4", -- [78]
			",", -- [79]
			"Kyrian Phalanx[3] meleed Viscious Terrorwing[5][595HP] for 134 damage.", -- [80]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Phalanx[3][731HP].", -- [81]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Halberdier[1][703HP].", -- [82]
			"Kyrian Halberdier[1] meleed Starving Terrorwing[11][0HP] for 268 damage.", -- [83]
			"Kyrian Halberdier[1] killed Starving Terrorwing[11][0HP].", -- [84]
			"ELGU - 007[4] meleed Viscious Terrorwing[8][427HP] for 330 damage.", -- [85]
			"Feral Terrorwing[10] shot Kyrian Phalanx[3][505HP] for 226 damage.", -- [86]
			"Starving Terrorwing[9] shot Kyrian Phalanx[3][306HP] for 199 damage.", -- [87]
			"Starving Terrorwing[9] cast Leeching Bite at Feral Terrorwing[10][1664HP] for 222  damage.", -- [88]
			"Starving Terrorwing[9] cast Leeching Bite on Starving Terrorwing[9][881HP] for 111 healing.", -- [89]
			"Viscious Terrorwing[8] meleed ELGU - 007[4][286HP] for 242 damage.", -- [90]
			"Viscious Terrorwing[5] meleed Kyrian Phalanx[3][89HP] for 217 damage.", -- [91]
			",", -- [92]
			"Start of round 5", -- [93]
			",", -- [94]
			"Kyrian Halberdier[1] meleed Viscious Terrorwing[8][159HP] for 268 damage.", -- [95]
			"Kyrian Halberdier[1] cast Halberd Strike at Starving Terrorwing[9][560HP] for 321  damage.", -- [96]
			"ELGU - 007[4] meleed Viscious Terrorwing[8][0HP] for 330 damage.", -- [97]
			"ELGU - 007[4] killed Viscious Terrorwing[8][0HP].", -- [98]
			"ELGU - 007[4] cast Panoptic Beam at Feral Terrorwing[10][1070HP] for 594  damage.", -- [99]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Phalanx[3][89HP].", -- [100]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Halberdier[1][703HP].", -- [101]
			"Kyrian Phalanx[3] meleed Viscious Terrorwing[5][461HP] for 134 damage.", -- [102]
			"Feral Terrorwing[10] shot Kyrian Phalanx[3][0HP] for 252 damage.", -- [103]
			"Feral Terrorwing[10] killed Kyrian Phalanx[3][0HP].", -- [104]
			"Starving Terrorwing[9] shot Kyrian Halberdier[1][481HP] for 222 damage.", -- [105]
			"Viscious Terrorwing[5] meleed Kyrian Halberdier[1][239HP] for 242 damage.", -- [106]
			",", -- [107]
			"Start of round 6", -- [108]
			",", -- [109]
			"ELGU - 007[4] meleed Feral Terrorwing[10][740HP] for 330 damage.", -- [110]
			"Kyrian Halberdier[1] meleed Feral Terrorwing[10][472HP] for 268 damage.", -- [111]
			"Feral Terrorwing[10] shot ELGU - 007[4][34HP] for 252 damage.", -- [112]
			"Feral Terrorwing[10] cast Razor Shards at Kyrian Halberdier[1][0HP] for 378  damage.", -- [113]
			"Feral Terrorwing[10] killed Kyrian Halberdier[1][0HP].", -- [114]
			"Starving Terrorwing[9] shot ELGU - 007[4][0HP] for 222 damage.", -- [115]
			"Starving Terrorwing[9] killed ELGU - 007[4][0HP].", -- [116]
		},
		["missionID"] = 2239,
		["finalHealth"] = {
			0, -- [1]
			0, -- [2]
			0, -- [3]
			0, -- [4]
			461, -- [5]
			0, -- [6]
			0, -- [7]
			0, -- [8]
			560, -- [9]
			472, -- [10]
			0, -- [11]
			0, -- [12]
			[0] = 0,
		},
		["followers"] = {
			{
				["maxHP"] = 2345,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -26,
				["name"] = "Kyrian Phalanx",
				["boardIndex"] = 2,
				["baseAttack"] = 134,
				["level"] = 57,
				["HP"] = 2345,
				["levelXP"] = 1,
			}, -- [1]
			{
				["maxHP"] = 2345,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -163,
				["name"] = "Kyrian Phalanx",
				["boardIndex"] = 3,
				["baseAttack"] = 134,
				["level"] = 57,
				["HP"] = 2345,
				["levelXP"] = 1,
			}, -- [2]
			{
				["maxHP"] = 1980,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 312,
					}, -- [1]
				},
				["xp"] = 5550,
				["followerID"] = "0x0000000025DFD112",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = 34,
				["name"] = "ELGU - 007",
				["boardIndex"] = 4,
				["baseAttack"] = 330,
				["level"] = 56,
				["HP"] = 1980,
				["levelXP"] = 20900,
			}, -- [3]
			{
				["maxHP"] = 2800,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 1,
						["spellID"] = 78,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0x000000001E62FD0B",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -37,
				["name"] = "Clora",
				["boardIndex"] = 0,
				["baseAttack"] = 210,
				["level"] = 60,
				["HP"] = 576,
				["levelXP"] = 1,
			}, -- [4]
			{
				["maxHP"] = 1005,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = 325,
				["name"] = "Kyrian Halberdier",
				["boardIndex"] = 1,
				["baseAttack"] = 268,
				["level"] = 57,
				["HP"] = 1005,
				["levelXP"] = 1,
			}, -- [5]
		},
		["addonVersion"] = "9.2-102",
		["enemies"] = {
			{
				["followerID"] = -1,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Fiendish Terrorwing",
				["maxHP"] = 980,
				["baseAttack"] = 232,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 6,
						["spellID"] = 164,
					}, -- [1]
				},
				["HP"] = 980,
				["boardIndex"] = 6,
			}, -- [1]
			{
				["followerID"] = -2,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Fiendish Terrorwing",
				["maxHP"] = 980,
				["baseAttack"] = 232,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 6,
						["spellID"] = 164,
					}, -- [1]
				},
				["HP"] = 980,
				["boardIndex"] = 7,
			}, -- [2]
			{
				["followerID"] = -3,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Viscious Terrorwing",
				["maxHP"] = 1480,
				["baseAttack"] = 242,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 165,
					}, -- [1]
				},
				["HP"] = 1480,
				["boardIndex"] = 5,
			}, -- [3]
			{
				["followerID"] = -4,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Viscious Terrorwing",
				["maxHP"] = 1480,
				["baseAttack"] = 242,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 165,
					}, -- [1]
				},
				["HP"] = 1480,
				["boardIndex"] = 8,
			}, -- [4]
			{
				["followerID"] = -5,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Starving Terrorwing",
				["maxHP"] = 980,
				["baseAttack"] = 222,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 166,
					}, -- [1]
				},
				["HP"] = 980,
				["boardIndex"] = 9,
			}, -- [5]
			{
				["followerID"] = -6,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Starving Terrorwing",
				["maxHP"] = 980,
				["baseAttack"] = 222,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 166,
					}, -- [1]
				},
				["HP"] = 980,
				["boardIndex"] = 12,
			}, -- [6]
			{
				["followerID"] = -7,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Feral Terrorwing",
				["maxHP"] = 2480,
				["baseAttack"] = 252,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 167,
					}, -- [1]
				},
				["HP"] = 2480,
				["boardIndex"] = 10,
			}, -- [7]
			{
				["followerID"] = -8,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Starving Terrorwing",
				["maxHP"] = 980,
				["baseAttack"] = 222,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 166,
					}, -- [1]
				},
				["HP"] = 980,
				["boardIndex"] = 11,
			}, -- [8]
		},
	},
	[2226] = {
		["addonVersion"] = "9.2-102",
		["followers"] = {
			{
				["maxHP"] = 2345,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -215,
				["name"] = "Kyrian Phalanx",
				["boardIndex"] = 2,
				["baseAttack"] = 134,
				["level"] = 57,
				["HP"] = 2345,
				["levelXP"] = 1,
			}, -- [1]
			{
				["maxHP"] = 2345,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -49,
				["name"] = "Kyrian Phalanx",
				["boardIndex"] = 3,
				["baseAttack"] = 134,
				["level"] = 57,
				["HP"] = 2345,
				["levelXP"] = 1,
			}, -- [2]
			{
				["maxHP"] = 1005,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = 167,
				["name"] = "Kyrian Halberdier",
				["boardIndex"] = 4,
				["baseAttack"] = 268,
				["level"] = 57,
				["HP"] = 1005,
				["levelXP"] = 1,
			}, -- [3]
			{
				["maxHP"] = 2070,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 79,
					}, -- [1]
				},
				["xp"] = 550,
				["followerID"] = "0x00000000206F84B4",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["predictedFinalHP"] = -50,
				["name"] = "Disciple Kosmas",
				["boardIndex"] = 0,
				["baseAttack"] = 276,
				["level"] = 59,
				["HP"] = 2070,
				["levelXP"] = 23600,
			}, -- [4]
			{
				["maxHP"] = 2100,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 87,
					}, -- [1]
					{
						["duration"] = 3,
						["cooldown"] = 3,
						["spellID"] = 88,
					}, -- [2]
				},
				["xp"] = 0,
				["followerID"] = "0x000000001E1EA784",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["predictedFinalHP"] = 140,
				["name"] = "Pelagos",
				["boardIndex"] = 1,
				["baseAttack"] = 280,
				["level"] = 60,
				["HP"] = 126,
				["levelXP"] = 1,
			}, -- [5]
		},
		["missionID"] = 2226,
		["enemies"] = {
			{
				["followerID"] = -1,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["name"] = "Warden of Rituals",
				["maxHP"] = 3085,
				["baseAttack"] = 168,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 214,
					}, -- [1]
				},
				["HP"] = 3085,
				["boardIndex"] = 11,
			}, -- [1]
			{
				["followerID"] = -2,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 5,
			}, -- [2]
			{
				["followerID"] = -3,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 8,
			}, -- [3]
			{
				["followerID"] = -4,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 6,
			}, -- [4]
			{
				["followerID"] = -5,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 7,
			}, -- [5]
			{
				["followerID"] = -6,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 9,
			}, -- [6]
			{
				["followerID"] = -7,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 12,
			}, -- [7]
			{
				["followerID"] = -8,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Necrotic Ritualist",
				["maxHP"] = 1685,
				["baseAttack"] = 158,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 209,
					}, -- [1]
				},
				["HP"] = 1685,
				["boardIndex"] = 10,
			}, -- [8]
		},
	},
}

**Comment by teelolws** [comment]
Thanks, will be fixed next patch.
