### ISSUE TITLE
TLDR TFF Feature: map ID selection

### ISSUE THREAD

**Issue by Tigerji** [TLDRMissions/TLDRMissions#446]
Been using TLDR TFF to get followers for alts. This is an extra feature that  this WA can check for non-follower maps: mapid. 

C_Map.GetBestMapForUnit("player")

For upper reaches, there are 3 maps that won't have follower quests: 1920, 1791 and 1792, TLDR TFF can check the map id, then leave party if there is a match.

1920, 1791 and 1792 are not exclusive to upper reaches, they may appear in other zone as well. It is possible to compile a list of maps that won't respawn followers.

**Comment by teelolws** [comment]
Thanks, I was wondering if there was a way to do that.

**Comment by teelolws** [comment]
Doing some testing. Sometimes when I zone in, the zone name doesn't change from "Torghast" to "The Upper Reaches" properly. I won't be able to catch it when that bug happens.

**Comment by Tigerji** [comment]
Ya, thats a bug, if you have mini map turned on (Shift+M), when you enter Torghast(Upper Reaches), the map takes several secs (maybe more) to change into upper reaches and sometimes it changes to the map of the entire azeroth (bug). But if you use the macro /dump C_Map.GetBestMapForUnit("player"), it would always show the correct zone/map ID (at least to my limited test cases).

**Comment by teelolws** [comment]
Right, but if the 1920 can be in other zones, then I have to only check it against Upper Reaches. So I need to check it against the zone name, too.

**Comment by Tigerji** [comment]
1920 will always not have a follower no matter which zone it falls into. so dont need to double check.

**Comment by teelolws** [comment]
Ah ok.

**Comment by Tigerji** [comment]
It is possible to compile a list of maps that won't respawn followers, but i didn't try other zones as upper reach is pretty fast. However this brings another question: which zone is best for getting followers. For Upper Reach, there are 5-6 maps for starting level, about half of the time there is guarentee no follower. For other zones the ratio of non-follower maps may be smaller. I think those 3 maps would a start, other maps can be added and optimization advices can be given later.

**Comment by teelolws** [comment]
I also think Upper Reach is the best one. Its the easiest to avoid aggro on everything.
