### ISSUE TITLE
[BUG] Mission duration restrictions are ignored when sacrificing followers

### ISSUE THREAD

**Issue by nzall** [TLDRMissions/TLDRMissions#448]
I have my mission duration set to 9 hours such that I can do them before and after working hours, but it's sending followers on 12 and 14 hour missions because those missions give more EXP.

**Comment by teelolws** [comment]
Next patch the sacrifice option will obey your global anima cost limits and duration restrictions.

**Comment by nzall** [comment]
> Next patch the sacrifice option will obey your global anima cost limits and duration restrictions.

Will this also include the option right above that about "any mission for EXP"?
