### ISSUE TITLE
[BUG] Can't Open The Garrison Report While This Is Active

### ISSUE THREAD

**Issue by ssamgang2** [TLDRMissions/TLDRMissions#450]
It started couple days ago, clicking on the garrison report button does nothing, I've disabled every addon except for this one and it still happens, soon as I disable this addon it works again and I can open it again.

**Comment by teelolws** [comment]
Are you getting an error? Turn them on with

`/console scriptErrors 1`

**Comment by BlueNightSky** [comment]
The situation I encountered is that after turning on this addon, the conversation content of the mission NPC cannot be displayed.
It is normal after closing, without any error message.

**Comment by teelolws** [comment]
Yeah I found a way to restrict it to Covenant stuff only. It'll be fixed next patch.
