### ISSUE TITLE
Old content tables?

### ISSUE THREAD

**Issue by HatWearingKid** [TLDRMissions/TLDRMissions#451]
TLDR version: 
Could this be used to automate past xpac tables? Bfa, Legion or even WoD?

**Slightly longer version**
I love using this add-on as is. But I tried it on the Legion board and unfortunately it didnt work. Could this add-on be the same for past xpac versions of the mission table/board? With some of us having many, many toons. It could be really nice to have!

**Comment by teelolws** [comment]
Hi, I'm not looking to recreate what other addons already do. Look for the Master Plan series of addons, they do exactly that already: https://www.curseforge.com/wow/addons/master-plan
