### ISSUE TITLE
TLDR & Start button merge

### ISSUE THREAD

**Issue by BlueNightSky** [TLDRMissions/TLDRMissions#452]
**TLDR Version of your idea**
TLDR version: 9.2-106

**Additional context**
I have a small suggestion, whether the TLDR can be integrated with the start button, the left button can open the option window, the right button is to start automatically, and add a tooltip to the mouse.
Or put the "start" on the right side, the same size, this seems to be more beautiful.
It's just a small suggestion. If you think the status quo is better, I have no opinion.

**Comment by teelolws** [comment]
Having them left/right buttons was my first idea. But feedback from users didn't like my buttons getting too close to the Venture Plan button, so I made it up/down instead.

Right clicking could have been a way to go, but I think its too late now. I don't want to confuse people by changing it.
