### ISSUE TITLE
Unable to start mission

### ISSUE THREAD

**Issue by derekengel** [TLDRMissions/TLDRMissions#453]
I have a new character I'm running through the mission table setup.  There is one anima mission up, and when I click Start or calculate, doesn't matter, I get the following error and nothing happens.

`Message: Interface\AddOns\TLDRMissions\guihandlers.lua:775: attempt to compare nil with number
Time: Wed Jul  6 17:31:27 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\guihandlers.lua:775: attempt to compare nil with number
[string "=[C]"]: ?
[string "@Interface\AddOns\TLDRMissions\guihandlers.lua"]:775: in function `func'
[string "@Interface\AddOns\TLDRMissions\workhandler.lua"]:41: in function <Interface\AddOns\TLDRMissions\workhandler.lua:23>

Locals: `

**Comment by teelolws** [comment]
Does the mission have an anima cost?

**Comment by derekengel** [comment]
Yes they did.  They were the introduction missions that take 1 minute to complete.  I manually did them and still had the issue.  Now after logging out and in again, things are working with the complete mission table.

**Comment by teelolws** [comment]
Found the problem. Those tutorial missions don't have an expiry time.
