### ISSUE TITLE
[BUG] Last follower is not sent

### ISSUE THREAD

**Issue by Fugaz1** [TLDRMissions/TLDRMissions#456]
I noticed often one follower is not being sent despite missions being successful.

See example here, 1 follower left and we have lvl 36 gold mission for 10 anima:
![image](https://user-images.githubusercontent.com/759426/177790343-ae3331af-0ab8-4da4-9b93-a5adfdd8adaa.png)

Here is this mission with venture plan:
![image](https://user-images.githubusercontent.com/759426/177790447-f80900c5-3e80-44e9-b12c-cac186b79d49.png)

This happens on almost every character.

**Comment by teelolws** [comment]
Can you confirm if, when you sent it out using Venture Plan, the mission actually succeeded?

**Comment by Fugaz1** [comment]
Yes, I sent plenty this way and did not notice any failures.

That being said I noticed my version was 102 not current 107 because curse did not update it for some reason. I will monitor it with this version and reopen if issue persists.

**Comment by teelolws** [comment]
Actually the issue has been reported by other users: https://github.com/TLDRMissions/TLDRMissions/issues/421 https://github.com/TLDRMissions/TLDRMissions/issues/434 

But the issue is so rare that I can't find the cause. Until the problem happens to me, I probably won't be able to fix it.

**Comment by Fugaz1** [comment]
Maybe indeed there is some other addon interfering, I sent missions from laptop (minimum addons) and PC (lots more addons) - I  will keep an eye on this.

**Comment by Fugaz1** [comment]
I sent missions today on version 108 and everything went fine. Possibly it was just fixed since 102.
