### ISSUE TITLE
Campaign limit set not working properly?

### ISSUE THREAD

**Issue by crialexyz** [TLDRMissions/TLDRMissions#457]
hey!
Im getting this problem with the campaign mission progress limit setting
even if I have it set up to 16 (17+ unchecked) it keeps trying to sim and send the 17-18-19 missions (17 passed without me noticing, then i saw 18 already sent and then today i had to skip the sim when i saw it trying to send it).
I have the campaign filter as 11th priority, but i do have follower xp item in 3rd priority...so that may be the reason (i've noticed that it tries to sim the campaign mission way before its place in the priority order).

can't go without saying thanks for the great work.
gg

**Comment by teelolws** [comment]
Hi, yes, if you have the secondary reward in your priority list it will still try to send out the mission. This is as intended - you wanted the secondary reward so it will send out the mission. If you want it to never send Campaign missions even if it has a secondary reward that you want, you need to add it to your exclusion list by changing Campaign missions to the red X.

**Comment by crialexyz** [comment]
hmm, if its working as intended then its ok. but, let me put it this way:
in the prioriry list, the campaign progress option is useful because i may want to prioritize gold over campaign progress or whatever.
BUT, when given the option to set a limit to the campaign progress, the desition changes from prioritize other missions over campaign, to simply whether i want or not go past over that lvl, because all missions avg lvl and difficulty are tied to that lvl.
So, i think it would be much more useful if when i set a limit to the campaign progres and once i get to that lvl, the addon just skip or filter out campaign missions from the priority list even if the follower xp item is prioritized higer on the list, because the desition to put a limit to that progress takes priority over xp item or whatever.

Maybe a solution would be to put the campaign lvl limit on the advanced options and filter out campaign mission before the priority list.

PS: Maybe im thinking too much on my own way of using the addon, but i really think that the real utility of the campaign lvl cap is way more important and comes above the priority list.

**Comment by teelolws** [comment]
I think you're overthinking the problem a bit. If you used the troops trick to get level 60 troops, it shouldn't matter how hard the missions you have are - they'll be solved anyway. And harder missions are a good thing - it means better rewards. If you have a lower level table on some characters, then just uncheck Campaign missions once those characters get to table level 16.

**Comment by crialexyz** [comment]
just logged in and put

**Comment by crialexyz** [comment]
hey!
just logged in and tried putting the red X in campaign progress but even doing so, the addon tries to send the mission.
now i dont know whats happening.

![imagen](https://user-images.githubusercontent.com/75538963/177896736-9b81bdb2-08ec-4504-95c0-7aca31befac6.png)

**Comment by teelolws** [comment]
Because you've got the 17+ unchecked, its not including them as an exclusion.

**Comment by crialexyz** [comment]
yep, that was the thing.
i assume it was something like "false x false = true" kind of interaction
i thought the X would automatically disable the filter inside

tyvm for you time and help.

**Comment by teelolws** [comment]
I would prefer to have X in the submenus, but its not possible with Blizzards menu code.
