### ISSUE TITLE
[BUG] "Everything else for XP" not working

### ISSUE THREAD

**Issue by Fugaz1** [TLDRMissions/TLDRMissions#460]
![image](https://user-images.githubusercontent.com/759426/177947684-ffdbcc50-aa4b-4f42-9161-c789e203078c.png)

![image](https://user-images.githubusercontent.com/759426/177947735-98010ff5-2115-41f6-9a20-59851def3d73.png)

It should send dreamweaver to, ideally, one of rep token missions (they easily pass).

**Comment by teelolws** [comment]
Check this dropdown. You probably have it set to min 4 followers.
![image](https://user-images.githubusercontent.com/49792789/177949390-a3723064-fed4-41d8-9f69-8b091ca3fa66.png)

**Comment by teelolws** [comment]
I made that option apply to the "anything for XP" category, too. Seemed logical - they're both just for getting your followers XP, so you'd want the same rules for them, right?

**Comment by Fugaz1** [comment]
Understand, thanks for clarifying. My approach is different, for bonus xp I want all (to not waste bonus xp) but for leftovers I just want them to run anything (with lowest anima possible) to not sit idle :)

**Comment by teelolws** [comment]
I suggest you just put the rest of the categories in order and set them to 10-49 anima only.
