### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by truecallingAD** [TLDRMissions/TLDRMissions#468]
Hi teelolws,

Thanks again for this addon, it's absolutely awesome, friends I've pointed it out to have expletives to describe how amazing it is so great job! Thank you as well for sneaking in the missing companions + source, and your companion farming plugin is incredible.

I have a couple of random questions/issues that I couldn't dig out details for on github.

Firstly, this might be an issue with Curseforge specifically, but the changelog links over there are broken and return a 404:

Full Changelog: https://github.com/TLDRMissions/main/compare/9.2-109...9.2-110
Previous Releases: https://github.com/TLDRMissions/main/releases

Secondly, I am not au fait enough with weak auras to understand how to do this, but I was hoping to make use of the WA you posted that rebinds space to the shortcut button. Either I'm misunderstanding how it works, or it's broken, as I've imported it but it doesn't seem to do anything. The rebinding part I'm guessing is working, but I was anticipating that hitting space would trigger the calculation / mission completion stuff. If not, could you be a saint and find some time to do this for us?

Thanks again,
Truecalling - AD EU

**Comment by teelolws** [comment]
I'll change the script I use to upload releases to CurseForge to leave out those changelog URLs. They're not intended to be linked.

I'm not a WeakAura expert; I don't know why its not working for you. One possibility is you don't have the TLDR Missions window open? Theres probably a way to edit the WA to look for just the Mission Table being open, but not really my area.

**Comment by truecallingAD** [comment]
Weirdly, I restarted the game and the WA started working, so apologies for not doing due diligence there.

Do you have a running change log somewhere by any chance?

**Comment by teelolws** [comment]
> Do you have a running change log somewhere by any chance?

Not publicly. Theres nothing interesting to see there. Its just my notes about all the changes I make to each spell, with links to the combat log I based the change on.

**Comment by truecallingAD** [comment]
Ok, no worries, thanks again!
