### ISSUE TITLE
Feature request : Mind-Expanding Prism - Fractal Thoughtbinder - etc one button use

### ISSUE THREAD

**Issue by Cyxi** [TLDRMissions/TLDRMissions#469]
Hi,

with so many adventurer table we got a lot of xp follower item. Would it be possible to add a functionnality to use them all with one button on low lvl follower automatically.

Cheers Cyxi

**Comment by teelolws** [comment]
Unfortunately that requires setting up spell buttons, and thats a bit outside of my area. I have been told there might be a Weakaura somewhere that does this?

**Comment by zeenk** [comment]
https://wago.io/rNc7NvCF9 not exactly what he's looking for but close enough?

**Comment by Cyxi** [comment]
Ty, i will try it :)

**Comment by Fugaz1** [comment]
Aura is good but you still need to find lowest XP follower yourself.

**Comment by gaveer** [comment]
@Cyxi  https://wago.io/uh9TtCwDg
