### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by BradCOnGitHub** [TLDRMissions/TLDRMissions#471]
Got stuck simulating a mission it shouldn't be doing. I unchecked Stygia but it still wants to run that mission

![image](https://user-images.githubusercontent.com/15109073/178171388-d658aaab-dd89-4817-ae31-353a517928f8.png)

**Comment by teelolws** [comment]
You really need to update the addon. Its at least 2 months out of date. Theres been about 50 patches since, including one that fixed your issue.
