### ISSUE TITLE
[BUG] UI stuck on calculating

### ISSUE THREAD

**Issue by Fugaz1** [TLDRMissions/TLDRMissions#472]
![image](https://user-images.githubusercontent.com/759426/178218216-8407d5e5-85c2-4f11-88af-d9df020f99b2.png)

![image](https://user-images.githubusercontent.com/759426/178218329-6844b1ea-0c69-471e-ae53-77664c0c3be1.png)

This is 2nd time that happened to me.

There is no such mission on table, thinking maybe it expired and blizz api was too slow to refresh?

**Comment by teelolws** [comment]
Yes thats probably what happened. Just cancel it and start over.
