### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by L30m4nc3r** [TLDRMissions/TLDRMissions#474]
### Copy/paste the Lua error here

1x TLDRMissions\simulation.lua:1542: attempt to index local 'info' (a nil value)
[string "@TLDRMissions\simulation.lua"]:1542: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:14: in function `func'
[string "@TLDRMissions\workhandler.lua"]:51: in function <TLDRMissions\workhandler.lua:23>

Locals:
self = <table> {
 createWorkBatch = <function> defined @TLDRMissions\workhandler.lua:100
 TestFirstTenFollowersPlusTroops = <function> defined @TLDRMissions\testing.lua:49
 reputationCurrencyIDs = <table> {
 }
 updateRewards = <function> defined @TLDRMissions\guihandlers.lua:28
 craftingCacheCategories = <table> {
 }
 getFrontEnemies = <function> defined @TLDRMissions\targetting.lua:424
 logSentMission = <function> defined @TLDRMissions\logging.lua:10
 isCurrentWorkBatchEmpty = <function> defined @TLDRMissions\workhandler.lua:119
 craftingCacheQualities = <table> {
 }
 getAllEnemies = <function> defined @TLDRMissions\targetting.lua:528
 unpauseWorker = <function> defined @TLDRMissions\workhandler.lua:92
 setResultCacheGuaranteedFailure = <function> defined @TLDRMissions\caching.lua:94
 getAdjacentAlliesOrAllAllies = <function> defined @TLDRMissions\targetting.lua:382
 ProfileChanged = <function> defined @TLDRMissions\profiles.lua:624
 LibStub = <table> {
 }
 sortFollowers = <function> defined @TLDRMissions\combinations.lua:117
 GetAllMissionsMatchingFilter = <function> defined @TLDRMissions\missions.lua:201
 sanctumFeatureItems = <table> {
 }
 getBackEnemies = <function> defined @TLDRMissions\targetting.lua:465
 getLineEnemies = <function> defined @TLDRMissions\targetting.lua:208
 isResultCacheGuaranteedFailure = <function> defined @TLDRMissions\caching.lua:77
 SimulateFromLog = <function> defined @TLDRMissions\simulation.lua:1595
 spellsDB = <table> {
 }
 getPseudorandomMawswornStrength = <function> defined @TLDRMissions\targetting.lua:622
 runecarverCurrencyIDs = <table> {
 }
 GUI = TLDRMissionsFrame {
 }
 getCleaveEnemies = <function> defined @TLDRMissions\targetting.lua:67
 getClosestEnemy = <function> defined @TLDRMissions\targetting.lua:23
 arrangeAllFollowerPositions = <function> defined @TLDRMissions\combinations.lua:37
 getAllAllies = <function> defined @TLDRMissions\targetting.lua:516
 Simulate = <function> defined @TLDRMissions\simulation.lua:1477
 dontWait = false
 db = <table> {
 }
 RefreshProfile = <function> defined @TLDRMissions\profiles.lua:8
 getFurthestEnemy = <function> defined @TLDRMissions\targetting.lua:141
 followerList = <table> {
 }
 C_Garrison_GetFollowerAutoCombatStats = <function> defined @TLDRMissions\caching.lua:262
 setResultCacheCombinationKnown = <function> defined @TLDRMissions\caching.lua:207
 setResultCacheCombinationUnknown = <function> defined @TLDRMissions\caching.lua:173
 GetRunecarverMissions = <function> defined @TLDRMissions\missions.lua:408
 isResultCacheCombinationKnown = <function> defined @TLDRMissions\caching.lua:128
 getPseudorandomLashOut = <function> defined @TLDRMissions\targetting.lua:871
 followerXPItemIDs = <table> {
 }
 getConeEnemies = <function> defined @TLDRMissions\targetting.lua:269
 C_Garrison_GetFollowerInfo = <function> defined @TLDRMissions\caching.lua:6
 GetCraftingCacheMissions = <function> defined @TLDRMissions\missions.lua:374
 garrisonMissionStartedHandler = <function> defined @TLDRMissions\guihandlers.lua:953
 addWork = <function> defined @TLDRMissions\workhandler.lua:106
 GetFollowerXPItemMissions = <function> defined @TLDRMissions\missions.lua:261
 arrangeFollowerCombinationsByFewestFollowersPlusTroops = <function> defined @TLDRMissions\combinations.lua:353
 TestExistingMission = <function> defined @TLDRMissions\testing.lua:69
 GetPetCharmMissions = <function> defined @TLDRMission

**Comment by teelolws** [comment]
You would have got an error in your chatlog telling you that you're getting that error. It happens if your mission expires while the addon is still trying to simulate it. Just /reload, start again, and hope another mission doesn't expire!
