### ISSUE TITLE
[BUG] Lua error (guihandlers.lua:298)

### ISSUE THREAD

**Issue by Ahfau77** [TLDRMissions/TLDRMissions#475]
### Copy/paste the Lua error here

As i clicked on the button to start the third mission the following error occurs:

Message: Interface\AddOns\TLDRMissions\guihandlers.lua:298: attempt to perform arithmetic on local 'duration' (a nil value)
Time: Tue Jul 12 11:47:33 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\guihandlers.lua:298: attempt to perform arithmetic on local 'duration' (a nil value)
[string "@Interface\AddOns\TLDRMissions\events.lua"]:101: in function <Interface\AddOns\TLDRMissions\events.lua:81>

Locals: self = <unnamed> {
 0 = <userdata>
}
event = "GARRISON_MISSION_STARTED"
arg1 = 123
adventureMapOpenHandler = <function> defined @Interface\AddOns\TLDRMissions\events.lua:36
preloadItemRewards = <function> defined @Interface\AddOns\TLDRMissions\events.lua:66
addon = <table> {
 createWorkBatch = <function> defined @Interface\AddOns\TLDRMissions\workhandler.lua:100
 TestFirstTenFollowersPlusTroops = <function> defined @Interface\AddOns\TLDRMissions\testing.lua:49
 reputationCurrencyIDs = <table> {
 }
 updateRewards = <function> defined @Interface\AddOns\TLDRMissions\guihandlers.lua:28
 craftingCacheCategories = <table> {
 }
 getFrontEnemies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:424
 logSentMission = <function> defined @Interface\AddOns\TLDRMissions\logging.lua:10
 isCurrentWorkBatchEmpty = <function> defined @Interface\AddOns\TLDRMissions\workhandler.lua:119
 craftingCacheQualities = <table> {
 }
 getAllEnemies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:528
 unpauseWorker = <function> defined @Interface\AddOns\TLDRMissions\workhandler.lua:92
 setResultCacheGuaranteedFailure = <function> defined @Interface\AddOns\TLDRMissions\caching.lua:94
 getAdjacentAlliesOrAllAllies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:382
 ProfileChanged = <function> defined @Interface\AddOns\TLDRMissions\profiles.lua:624
 LibStub = <table> {
 }
 sortFollowers = <function> defined @Interface\AddOns\TLDRMissions\combinations.lua:117
 GetAllMissionsMatchingFilter = <function> defined @Interface\AddOns\TLDRMissions\missions.lua:201
 sanctumFeatureItems = <table> {
 }
 getBackEnemies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:465
 getLineEnemies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:208
 isResultCacheGuaranteedFailure = <function> defined @Interface\AddOns\TLDRMissions\caching.lua:77
 SimulateFromLog = <function> defined @Interface\AddOns\TLDRMissions\simulation.lua:1595
 spellsDB = <table> {
 }
 getPseudorandomMawswornStrength = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:622
 runecarverCurrencyIDs = <table> {
 }
 GUI = TLDRMissionsFrame {
 }
 getCleaveEnemies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:67
 getClosestEnemy = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:23
 arrangeAllFollowerPositions = <function> defined @Interface\AddOns\TLDRMissions\combinations.lua:37
 getAllAllies = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:516
 Simulate = <function> defined @Interface\AddOns\TLDRMissions\simulation.lua:1477
 dontWait = false
 db = <table> {
 }
 RefreshProfile = <function> defined @Interface\AddOns\TLDRMissions\profiles.lua:8
 getFurthestEnemy = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:141
 followerList = <table> {
 }
 C_Garrison_GetFollowerAutoCombatStats = <function> defined @Interface\AddOns\TLDRMissions\caching.lua:262
 setResultCacheCombinationKnown = <function> defined @Interface\AddOns\TLDRMissions\caching.lua:207
 setResultCacheCombinationUnknown = <function> defined @Interface\AddOns\TLDRMissions\caching.lua:173
 GetRunecarverMissions = <function> defined @Interface\AddOns\TLDRMissions\missions.lua:408
 isResultCacheCombinationKnown = <function> defined @Interface\AddOns\TLDRMissions\caching.lua:128
 getPseudorandomLashOut = <function> defined @Interface\AddOns\TLDRMissions\targetting.lua:871
 followerXPItemIDs = <table> {
 }
 getConeEnemies = <function> defined @Interface\AddOns\TLDRMissions\targetting.

**Comment by teelolws** [comment]
The mission probably expired while it was calculation. Just /reload and try it again. I'll add a catch for that error next patch.
