### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by angrren** [TLDRMissions/TLDRMissions#476]
### Upload your Character-Specific Saved Variables here

TLDRMissionsOptions = nil
TLDRMissionsLogging = {
	[2312] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Kyrian Phalanx[2] meleed Frenzied Razorwing[5][1932HP] for 138 damage.", -- [4]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Kyrian Phalanx[2][2415HP].", -- [5]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Kyrian Halberdier[0][1035HP].", -- [6]
			"Kyrian Phalanx[3] meleed Frenzied Razorwing[5][1794HP] for 138 damage.", -- [7]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Phalanx[3][2415HP].", -- [8]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Halberdier[0][1035HP].", -- [9]
			"Molako[4] shot Ravenous Scavenger[9][3864HP] for 276 damage.", -- [10]
			"Molako[4] cast Purification Ray at Ravenous Scavenger[11][3864HP] for 276  damage.", -- [11]
			"Kyrian Halberdier[0] meleed Frenzied Razorwing[5][1518HP] for 276 damage.", -- [12]
			"Kyrian Halberdier[0] cast Halberd Strike at Ravenous Scavenger[9][3533HP] for 331  damage.", -- [13]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[2][2291HP] for 124 damage.", -- [14]
			"Ravenous Scavenger[9] cast Heel Bite at Kyrian Phalanx[2][2255HP] for 36  damage.", -- [15]
			"Ravenous Scavenger[9] applied Heel Bite to Kyrian Phalanx[2][2255HP].", -- [16]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[2][2131HP] for 124 damage.", -- [17]
			"Ravenous Scavenger[10] cast Heel Bite at Kyrian Phalanx[2][2095HP] for 36  damage.", -- [18]
			"Ravenous Scavenger[10] applied Heel Bite to Kyrian Phalanx[2][2095HP].", -- [19]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[2][1971HP] for 124 damage.", -- [20]
			"Ravenous Scavenger[11] cast Heel Bite at Kyrian Phalanx[2][1935HP] for 36  damage.", -- [21]
			"Ravenous Scavenger[11] applied Heel Bite to Kyrian Phalanx[2][1935HP].", -- [22]
			"Frenzied Razorwing[5] shot Kyrian Phalanx[2][1687HP] for 248 damage.", -- [23]
			"Frenzied Razorwing[5] applied Protective Wings to Frenzied Razorwing[5][1518HP].", -- [24]
			"Frenzied Razorwing[5] applied Protective Wings to Ravenous Scavenger[9][3533HP].", -- [25]
			"Frenzied Razorwing[5] applied Protective Wings to Ravenous Scavenger[10][4140HP].", -- [26]
			"Frenzied Razorwing[5] applied Protective Wings to Ravenous Scavenger[11][3864HP].", -- [27]
			",", -- [28]
			"Start of round 2", -- [29]
			",", -- [30]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Phalanx[3][2415HP].", -- [31]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Halberdier[0][1035HP].", -- [32]
			"Kyrian Phalanx[3] meleed Frenzied Razorwing[5][1463HP] for 55 damage.", -- [33]
			"Molako[4] shot Ravenous Scavenger[9][3340HP] for 193 damage.", -- [34]
			"Kyrian Phalanx[2] removed Shield of Tomorrow from Kyrian Phalanx[2][1687HP].", -- [35]
			"Kyrian Phalanx[2] removed Shield of Tomorrow from Kyrian Halberdier[0][1035HP].", -- [36]
			"Kyrian Phalanx[2] meleed Frenzied Razorwing[5][1404HP] for 59 damage.", -- [37]
			"Kyrian Halberdier[0] meleed Frenzied Razorwing[5][1211HP] for 193 damage.", -- [38]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[2][1549HP] for 138 damage.", -- [39]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[2][1411HP] for 138 damage.", -- [40]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[2][1273HP] for 138 damage.", -- [41]
			"Frenzied Razorwing[5] shot Kyrian Phalanx[2][997HP] for 276 damage.", -- [42]
			",", -- [43]
			"Start of round 3", -- [44]
			",", -- [45]
			"Kyrian Phalanx[3] meleed Frenzied Razorwing[5][1156HP] for 55 damage.", -- [46]
			"Molako[4] shot Ravenous Scavenger[9][3147HP] for 193 damage.", -- [47]
			"Kyrian Halberdier[0] meleed Frenzied Razorwing[5][963HP] for 193 damage.", -- [48]
			"Kyrian Phalanx[2] meleed Frenzied Razorwing[5][904HP] for 59 damage.", -- [49]
			"Ravenous Scavenger[10] removed Heel Bite from Kyrian Phalanx[2][997HP].", -- [50]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[2][859HP] for 138 damage.", -- [51]
			"Ravenous Scavenger[11] removed Heel Bite from Kyrian Phalanx[2][859HP].", -- [52]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[2][721HP] for 138 damage.", -- [53]
			"Ravenous Scavenger[9] removed Heel Bite from Kyrian Phalanx[2][721HP].", -- [54]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[2][583HP] for 138 damage.", -- [55]
			"Frenzied Razorwing[5] shot Kyrian Phalanx[2][307HP] for 276 damage.", -- [56]
			",", -- [57]
			"Start of round 4", -- [58]
			",", -- [59]
			"Kyrian Phalanx[3] meleed Frenzied Razorwing[5][849HP] for 55 damage.", -- [60]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Phalanx[3][2415HP].", -- [61]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Halberdier[0][1035HP].", -- [62]
			"Molako[4] shot Ravenous Scavenger[9][2954HP] for 193 damage.", -- [63]
			"Molako[4] cast Purification Ray at Ravenous Scavenger[11][3671HP] for 193  damage.", -- [64]
			"Kyrian Halberdier[0] meleed Frenzied Razorwing[5][656HP] for 193 damage.", -- [65]
			"Kyrian Phalanx[2] meleed Frenzied Razorwing[5][601HP] for 55 damage.", -- [66]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Kyrian Phalanx[2][307HP].", -- [67]
			"Kyrian Phalanx[2] applied Shield of Tomorrow to Kyrian Halberdier[0][1035HP].", -- [68]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[2][183HP] for 124 damage.", -- [69]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[2][59HP] for 124 damage.", -- [70]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[2][0HP] for 124 damage.", -- [71]
			"Ravenous Scavenger[9] killed Kyrian Phalanx[2][0HP].", -- [72]
			"Frenzied Razorwing[5] removed Protective Wings from Frenzied Razorwing[5][601HP].", -- [73]
			"Frenzied Razorwing[5] removed Protective Wings from Ravenous Scavenger[9][2954HP].", -- [74]
			"Frenzied Razorwing[5] removed Protective Wings from Ravenous Scavenger[10][4140HP].", -- [75]
			"Frenzied Razorwing[5] removed Protective Wings from Ravenous Scavenger[11][3671HP].", -- [76]
			"Frenzied Razorwing[5] shot Kyrian Halberdier[0][815HP] for 220 damage.", -- [77]
			",", -- [78]
			"Start of round 5", -- [79]
			",", -- [80]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Phalanx[3][2415HP].", -- [81]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Halberdier[0][815HP].", -- [82]
			"Kyrian Phalanx[3] meleed Frenzied Razorwing[5][463HP] for 138 damage.", -- [83]
			"Molako[4] shot Ravenous Scavenger[9][2678HP] for 276 damage.", -- [84]
			"Kyrian Halberdier[0] meleed Frenzied Razorwing[5][187HP] for 276 damage.", -- [85]
			"Kyrian Halberdier[0] cast Halberd Strike at Ravenous Scavenger[9][2347HP] for 331  damage.", -- [86]
			"Kyrian Phalanx[2] removed Shield of Tomorrow from Kyrian Halberdier[0][815HP].", -- [87]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[3][2277HP] for 138 damage.", -- [88]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[3][2139HP] for 138 damage.", -- [89]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[3][2001HP] for 138 damage.", -- [90]
			"Frenzied Razorwing[5] shot Kyrian Halberdier[0][539HP] for 276 damage.", -- [91]
			",", -- [92]
			"Start of round 6", -- [93]
			",", -- [94]
			"Kyrian Phalanx[3] meleed Frenzied Razorwing[5][49HP] for 138 damage.", -- [95]
			"Molako[4] shot Ravenous Scavenger[9][2071HP] for 276 damage.", -- [96]
			"Kyrian Halberdier[0] meleed Frenzied Razorwing[5][0HP] for 276 damage.", -- [97]
			"Kyrian Halberdier[0] killed Frenzied Razorwing[5][0HP].", -- [98]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[3][1863HP] for 138 damage.", -- [99]
			"Ravenous Scavenger[10] cast Heel Bite at Kyrian Phalanx[3][1822HP] for 41  damage.", -- [100]
			"Ravenous Scavenger[10] applied Heel Bite to Kyrian Phalanx[3][1822HP].", -- [101]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[3][1684HP] for 138 damage.", -- [102]
			"Ravenous Scavenger[11] cast Heel Bite at Kyrian Phalanx[3][1643HP] for 41  damage.", -- [103]
			"Ravenous Scavenger[11] applied Heel Bite to Kyrian Phalanx[3][1643HP].", -- [104]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[3][1505HP] for 138 damage.", -- [105]
			"Ravenous Scavenger[9] cast Heel Bite at Kyrian Phalanx[3][1464HP] for 41  damage.", -- [106]
			"Ravenous Scavenger[9] applied Heel Bite to Kyrian Phalanx[3][1464HP].", -- [107]
			",", -- [108]
			"Start of round 7", -- [109]
			",", -- [110]
			"Molako[4] shot Ravenous Scavenger[9][1795HP] for 276 damage.", -- [111]
			"Molako[4] cast Purification Ray at Ravenous Scavenger[11][3395HP] for 276  damage.", -- [112]
			"Kyrian Phalanx[3] meleed Ravenous Scavenger[10][3998HP] for 142 damage.", -- [113]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Phalanx[3][1464HP].", -- [114]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Halberdier[0][539HP].", -- [115]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][3722HP] for 276 damage.", -- [116]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[3][1340HP] for 124 damage.", -- [117]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[3][1216HP] for 124 damage.", -- [118]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[3][1092HP] for 124 damage.", -- [119]
			",", -- [120]
			"Start of round 8", -- [121]
			",", -- [122]
			"Molako[4] shot Ravenous Scavenger[9][1519HP] for 276 damage.", -- [123]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Phalanx[3][1092HP].", -- [124]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Halberdier[0][539HP].", -- [125]
			"Kyrian Phalanx[3] meleed Ravenous Scavenger[10][3580HP] for 142 damage.", -- [126]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][3304HP] for 276 damage.", -- [127]
			"Ravenous Scavenger[10] removed Heel Bite from Kyrian Phalanx[3][1092HP].", -- [128]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[3][954HP] for 138 damage.", -- [129]
			"Ravenous Scavenger[11] removed Heel Bite from Kyrian Phalanx[3][954HP].", -- [130]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[3][816HP] for 138 damage.", -- [131]
			"Ravenous Scavenger[9] removed Heel Bite from Kyrian Phalanx[3][816HP].", -- [132]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[3][678HP] for 138 damage.", -- [133]
			",", -- [134]
			"Start of round 9", -- [135]
			",", -- [136]
			"Molako[4] shot Ravenous Scavenger[9][1243HP] for 276 damage.", -- [137]
			"Kyrian Phalanx[3] meleed Ravenous Scavenger[10][3166HP] for 138 damage.", -- [138]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][2890HP] for 276 damage.", -- [139]
			"Kyrian Halberdier[0] cast Halberd Strike at Ravenous Scavenger[9][912HP] for 331  damage.", -- [140]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[3][540HP] for 138 damage.", -- [141]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[3][402HP] for 138 damage.", -- [142]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[3][264HP] for 138 damage.", -- [143]
			",", -- [144]
			"Start of round 10", -- [145]
			",", -- [146]
			"Molako[4] shot Ravenous Scavenger[9][636HP] for 276 damage.", -- [147]
			"Molako[4] cast Purification Ray at Ravenous Scavenger[11][3119HP] for 276  damage.", -- [148]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][2614HP] for 276 damage.", -- [149]
			"Kyrian Phalanx[3] meleed Ravenous Scavenger[10][2476HP] for 138 damage.", -- [150]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Phalanx[3][264HP].", -- [151]
			"Kyrian Phalanx[3] applied Shield of Tomorrow to Kyrian Halberdier[0][539HP].", -- [152]
			"Ravenous Scavenger[11] meleed Kyrian Phalanx[3][140HP] for 124 damage.", -- [153]
			"Ravenous Scavenger[10] meleed Kyrian Phalanx[3][16HP] for 124 damage.", -- [154]
			"Ravenous Scavenger[9] meleed Kyrian Phalanx[3][0HP] for 124 damage.", -- [155]
			"Ravenous Scavenger[9] killed Kyrian Phalanx[3][0HP].", -- [156]
			",", -- [157]
			"Start of round 11", -- [158]
			",", -- [159]
			"Molako[4] shot Ravenous Scavenger[9][360HP] for 276 damage.", -- [160]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][2200HP] for 276 damage.", -- [161]
			"Kyrian Phalanx[3] removed Shield of Tomorrow from Kyrian Halberdier[0][539HP].", -- [162]
			"Ravenous Scavenger[11] meleed Molako[4][1587HP] for 138 damage.", -- [163]
			"Ravenous Scavenger[11] cast Heel Bite at Molako[4][1546HP] for 41  damage.", -- [164]
			"Ravenous Scavenger[11] applied Heel Bite to Molako[4][1546HP].", -- [165]
			"Ravenous Scavenger[10] meleed Molako[4][1408HP] for 138 damage.", -- [166]
			"Ravenous Scavenger[10] cast Heel Bite at Molako[4][1367HP] for 41  damage.", -- [167]
			"Ravenous Scavenger[10] applied Heel Bite to Molako[4][1367HP].", -- [168]
			"Ravenous Scavenger[9] meleed Kyrian Halberdier[0][401HP] for 138 damage.", -- [169]
			"Ravenous Scavenger[9] cast Heel Bite at Kyrian Halberdier[0][360HP] for 41  damage.", -- [170]
			"Ravenous Scavenger[9] applied Heel Bite to Kyrian Halberdier[0][360HP].", -- [171]
			",", -- [172]
			"Start of round 12", -- [173]
			",", -- [174]
			"Molako[4] shot Ravenous Scavenger[9][82HP] for 278 damage.", -- [175]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][1923HP] for 277 damage.", -- [176]
			"Ravenous Scavenger[11] meleed Molako[4][1229HP] for 138 damage.", -- [177]
			"Ravenous Scavenger[10] meleed Molako[4][1091HP] for 138 damage.", -- [178]
			"Ravenous Scavenger[9] meleed Kyrian Halberdier[0][222HP] for 138 damage.", -- [179]
			",", -- [180]
			"Start of round 13", -- [181]
			",", -- [182]
			"Molako[4] shot Ravenous Scavenger[9][0HP] for 278 damage.", -- [183]
			"Molako[4] killed Ravenous Scavenger[9][0HP].", -- [184]
			"Molako[4] cast Purification Ray at Ravenous Scavenger[11][2841HP] for 278  damage.", -- [185]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][1646HP] for 277 damage.", -- [186]
			"Kyrian Halberdier[0] cast Halberd Strike at Ravenous Scavenger[11][2509HP] for 332  damage.", -- [187]
			"Ravenous Scavenger[11] removed Heel Bite from Molako[4][1091HP].", -- [188]
			"Ravenous Scavenger[11] meleed Molako[4][953HP] for 138 damage.", -- [189]
			"Ravenous Scavenger[10] removed Heel Bite from Molako[4][953HP].", -- [190]
			"Ravenous Scavenger[10] meleed Molako[4][815HP] for 138 damage.", -- [191]
			"Ravenous Scavenger[9] removed Heel Bite from Kyrian Halberdier[0][222HP].", -- [192]
			",", -- [193]
			"Start of round 14", -- [194]
			",", -- [195]
			"Molako[4] shot Ravenous Scavenger[10][1370HP] for 276 damage.", -- [196]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][1094HP] for 276 damage.", -- [197]
			"Ravenous Scavenger[11] meleed Molako[4][677HP] for 138 damage.", -- [198]
			"Ravenous Scavenger[10] meleed Molako[4][539HP] for 138 damage.", -- [199]
			",", -- [200]
			"Start of round 15", -- [201]
			",", -- [202]
			"Molako[4] shot Ravenous Scavenger[10][818HP] for 276 damage.", -- [203]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][542HP] for 276 damage.", -- [204]
			"Ravenous Scavenger[11] meleed Molako[4][401HP] for 138 damage.", -- [205]
			"Ravenous Scavenger[10] meleed Molako[4][263HP] for 138 damage.", -- [206]
			",", -- [207]
			"Start of round 16", -- [208]
			",", -- [209]
			"Molako[4] shot Ravenous Scavenger[10][266HP] for 276 damage.", -- [210]
			"Molako[4] cast Purification Ray at Ravenous Scavenger[11][2233HP] for 276  damage.", -- [211]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[10][0HP] for 276 damage.", -- [212]
			"Kyrian Halberdier[0] killed Ravenous Scavenger[10][0HP].", -- [213]
			"Ravenous Scavenger[11] meleed Molako[4][125HP] for 138 damage.", -- [214]
			"Ravenous Scavenger[11] cast Heel Bite at Molako[4][84HP] for 41  damage.", -- [215]
			"Ravenous Scavenger[11] applied Heel Bite to Molako[4][84HP].", -- [216]
			",", -- [217]
			"Start of round 17", -- [218]
			",", -- [219]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[11][1957HP] for 276 damage.", -- [220]
			"Kyrian Halberdier[0] cast Halberd Strike at Ravenous Scavenger[11][1626HP] for 331  damage.", -- [221]
			"Molako[4] shot Ravenous Scavenger[11][1349HP] for 277 damage.", -- [222]
			"Ravenous Scavenger[11] meleed Molako[4][0HP] for 138 damage.", -- [223]
			"Ravenous Scavenger[11] killed Molako[4][0HP].", -- [224]
			",", -- [225]
			"Start of round 18", -- [226]
			",", -- [227]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[11][1073HP] for 276 damage.", -- [228]
			"Ravenous Scavenger[11] meleed Kyrian Halberdier[0][84HP] for 138 damage.", -- [229]
			",", -- [230]
			"Start of round 19", -- [231]
			",", -- [232]
			"Kyrian Halberdier[0] meleed Ravenous Scavenger[11][797HP] for 276 damage.", -- [233]
			"Ravenous Scavenger[11] meleed Kyrian Halberdier[0][0HP] for 138 damage.", -- [234]
			"Ravenous Scavenger[11] killed Kyrian Halberdier[0][0HP].", -- [235]
		},
		["missionID"] = 2312,
		["finalHealth"] = {
			nil, -- [1]
			0, -- [2]
			0, -- [3]
			0, -- [4]
			0, -- [5]
			nil, -- [6]
			nil, -- [7]
			nil, -- [8]
			0, -- [9]
			0, -- [10]
			797, -- [11]
			[0] = 0,
		},
		["followers"] = {
			{
				["maxHP"] = 2415,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -65,
				["name"] = "Kyrian Phalanx",
				["boardIndex"] = 2,
				["baseAttack"] = 138,
				["level"] = 59,
				["HP"] = 2415,
				["levelXP"] = 1,
			}, -- [1]
			{
				["maxHP"] = 2415,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 46,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFE",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -108,
				["name"] = "Kyrian Phalanx",
				["boardIndex"] = 3,
				["baseAttack"] = 138,
				["level"] = 59,
				["HP"] = 2415,
				["levelXP"] = 1,
			}, -- [2]
			{
				["maxHP"] = 1725,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 73,
					}, -- [1]
				},
				["xp"] = 2450,
				["followerID"] = "0x0000000052C71511",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["predictedFinalHP"] = 84,
				["name"] = "Molako",
				["boardIndex"] = 4,
				["baseAttack"] = 276,
				["level"] = 59,
				["HP"] = 1725,
				["levelXP"] = 23600,
			}, -- [3]
			{
				["maxHP"] = 1035,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 50,
					}, -- [1]
				},
				["xp"] = 0,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = 815,
				["name"] = "Kyrian Halberdier",
				["boardIndex"] = 0,
				["baseAttack"] = 276,
				["level"] = 59,
				["HP"] = 1035,
				["levelXP"] = 1,
			}, -- [4]
		},
		["addonVersion"] = "9.2-102",
		["enemies"] = {
			{
				["followerID"] = -1,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Frenzied Razorwing",
				["maxHP"] = 2070,
				["baseAttack"] = 276,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 4,
						["spellID"] = 345,
					}, -- [1]
				},
				["HP"] = 2070,
				["boardIndex"] = 5,
			}, -- [1]
			{
				["followerID"] = -2,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Ravenous Scavenger",
				["maxHP"] = 4140,
				["baseAttack"] = 138,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 346,
					}, -- [1]
				},
				["HP"] = 4140,
				["boardIndex"] = 10,
			}, -- [2]
			{
				["followerID"] = -3,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Ravenous Scavenger",
				["maxHP"] = 4140,
				["baseAttack"] = 138,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 346,
					}, -- [1]
				},
				["HP"] = 4140,
				["boardIndex"] = 9,
			}, -- [3]
			{
				["followerID"] = -4,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Ravenous Scavenger",
				["maxHP"] = 4140,
				["baseAttack"] = 138,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 346,
					}, -- [1]
				},
				["HP"] = 4140,
				["boardIndex"] = 11,
			}, -- [4]
		},
	},
}

**Comment by teelolws** [comment]
Thanks for the report!
