### ISSUE TITLE
[BUG] Other - Then, anything else for XP option

### ISSUE THREAD

**Issue by Zautix** [TLDRMissions/TLDRMissions#477]
I'm not really sure if this is a bug or a design choice, but it doesn't work intuitively.

Currently, the option "Then, anything else for XP" on the missions tab is being restricted by the settings for "Special Treatment for Follower XP Missions" on the Advanced tab. This is an issue because setting minimum followers in the advanced options causes this option not to fire as expected since it doesn't meet the "anything else" criteria very well.

Ideally, after all selected missions are sent, this option should send as many followers as possible (to reduce total anima costs) and ignore all other options entirely.

**Comment by teelolws** [comment]
Yes its by design. It will try to send as many <lv60 followers as it can. If you don't want the mission treated as a "bonus XP" missions then just put all the other missions into your reward queue instead.
