### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by Lucetia** [TLDRMissions/TLDRMissions#479]
### Upload your Character-Specific Saved Variables here

[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/9100397/TLDRMissions.zip)

**Comment by teelolws** [comment]
Hi, you uploaded your account-wide saved variables. I need the character-specific saved variables. They're under \WTF\Account\_ACCOUNT_\REALM\CHARACTER\SavedVariables
