### ISSUE TITLE
Feature request: optimize for least hp lost

### ISSUE THREAD

**Issue by Kristnovo** [TLDRMissions/TLDRMissions#480]
Hi I love your addon but I find sometimes my followers end up paying the price with their lives and the next time I log on they're all half dead and it spends forever simulating trying to find a solution that just isn't there.  They're all 60 so its not like I can drop one of the follower items on them either lol.  So it would be super nice to have an optimize for followers health option instead of the most followers used or least followers used I don't really care about that. I just want to win in a way that makes the next log on as nice as the first time I used your addon =)

Thanks for your time and your addon!

**Comment by teelolws** [comment]
No, that is not the purpose of this addon. If they're "half dead" it can still find solutions for them. Go into the Advanced tab and set it to mininum 4 troops.
