### ISSUE TITLE
Simming some missions drop my FPS down a lot more than others

### ISSUE THREAD

**Issue by Nillx** [TLDRMissions/TLDRMissions#481]
Is there a reason why simming some missions on my Venth char drop my FPS down to 10 while others are dropping it down to 30? 

Example for missions like that:

Venth mission: A Few Too Many

**Comment by teelolws** [comment]
Because some missions are more complicated than others, and need more processing time. If you don't like the FPS loss, go into the Advanced tab and lower the simulations per frame.

**Comment by Nillx** [comment]
I thought so thanks.
