### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by stvcobbs** [TLDRMissions/TLDRMissions#483]
### Copy/paste the Lua error here

* 1st error *
Message: Interface\AddOns\TLDRMissions\caching.lua:80: script ran too long
Time: Sat Jul 16 18:53:01 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\caching.lua:80: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\TLDRMissions\caching.lua"]:80: in function `isResultCacheGuaranteedFailure'
[string "@Interface\AddOns\TLDRMissions\combinations.lua"]:213: in function `func'
[string "@Interface\AddOns\TLDRMissions\workhandler.lua"]:71: in function <Interface\AddOns\TLDRMissions\workhandler.lua:23>
----
* 2nd Error after reloading * 
Message: Interface\AddOns\TLDRMissions\caching.lua:264: script ran too long
Time: Sat Jul 16 19:03:45 2022
Count: 1
Stack: Interface\AddOns\TLDRMissions\caching.lua:264: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\TLDRMissions\caching.lua"]:264: in function `C_Garrison_GetFollowerAutoCombatStats'
[string "@Interface\AddOns\TLDRMissions\caching.lua"]:68: in function <Interface\AddOns\TLDRMissions\caching.lua:46>
[string "@Interface\AddOns\TLDRMissions\caching.lua"]:78: in function `isResultCacheGuaranteedFailure'
[string "@Interface\AddOns\TLDRMissions\combinations.lua"]:213: in function `func'
[string "@Interface\AddOns\TLDRMissions\workhandler.lua"]:71: in function <Interface\AddOns\TLDRMissions\workhandler.lua:23>

Locals: 
![Capture](https://user-images.githubusercontent.com/108513034/179381008-2179ffe9-651e-4d72-b680-7ba32ca4b7e2.JPG)

Locals: 

Locals:

**Comment by teelolws** [comment]
Go into the Advanced settings and turn down the "Simulations per Frame" setting.

**Comment by stvcobbs** [comment]
Will do.. I'll do that now for next set of missions to send.
Thanks :)

**Comment by stvcobbs** [comment]
Of course, your recommendation works.
Once again I am taught the lesson of reading documentation and even looking at tooltips.
Thank you for your guidance,
Cheers
