### ISSUE TITLE
Misleading deDE translation

### ISSUE THREAD

**Issue by Urtgard** [TLDRMissions/TLDRMissions#486]
> TLDRMissions: Oh nein, **ein Abenteuer konnte nicht gestartet werden!** Logge dich bitte aus und schicke dem Autor die SavedVariables um nach einer Lösung zu suchen.

Which translates to **an adventure could not be started** or **an adventure failed to start**.

I was confused because I got this error after completing the missions, not after starting.
I checked and the original message is **Oh no, a mission I sent out failed!**

A better translation would be:
> TLDRMissions: Oh nein, **ein Abenteuer konnte nicht erfolgreich abgeschlossen werden!** Logge dich bitte aus und schicke dem Autor die SavedVariables um nach einer Lösung zu suchen.

Or a shorter one:
> TLDRMissions: Oh nein, **ein Abenteuer ist fehlgeschlagen!** Logge dich bitte aus und schicke dem Autor die SavedVariables um nach einer Lösung zu suchen.

**Comment by teelolws** [comment]
@marco-kretz provided those translations, can you weigh in?

**Comment by Tjark-Kuehl** [comment]
>TLDRMissions: Oh nein, ein Abenteuer ist fehlgeschlagen! Logge dich bitte aus und schicke dem Autor die SavedVariables um nach einer Lösung zu suchen.

Wouldnt be an error case tho. It would also be misleading as it said that the mission failed (which can happen) but its not an error case where you have to check something in the SavedVariables.

> TLDRMissions: Oh nein, ein Abenteuer konnte nicht erfolgreich abgeschlossen werden! Logge dich bitte aus und schicke dem Autor die SavedVariables um nach einer Lösung zu suchen.

Would be the more accurate text on what is actually happening

**Comment by Imna1975** [comment]
but it would also be good if someone could translate the rest

**Comment by marco-kretz** [comment]
I'll do this tomorrow :)

22.07.2022 17:29:47 Imna1975 ***@***.***>:

**Comment by Imna1975** [comment]
![Unbenannt](https://user-images.githubusercontent.com/45740014/180837795-023b1f0f-5d18-49f6-ad62-3202cba9019c.jpg)

the de update somehow didn't arrive

**Comment by teelolws** [comment]
marco-kretz only addressed the translation issue from the first post. If you want the rest of those fields translated, someone has to write translations.

**Comment by marco-kretz** [comment]
Oh didn't see that. Will translate the rest, too.
