### ISSUE TITLE
Packaged Release

### ISSUE THREAD

**Issue by kennywasafk** [TLDRMissions/TLDRMissions#487]
Just wanted to mention that it would be fantastic if there's any chance you could include packaged releases on github so that the addon is available through third-party addon clients like Cursebreaker and WowUp. If that's too much trouble, just having it on a different platform to Curseforge like WowInterface or WagoAddons would be really helpful too!

**Comment by teelolws** [comment]
I have no plans to release outside of Curseforge.

**Comment by kennywasafk** [comment]
Don't want to be a nag but is there any specific reason for this? I know WagoAddons offers a pretty substantial revenue split from their subscription.

**Comment by teelolws** [comment]
I do not agree to their Intellectual Property terms:

> Developer hereby grants Company and its agents a non-exclusive, sub-licensable, transferable, royalty-free, worldwide, fully paid-up license to display, use, distribute, host, monetize (in accordance with the terms set forth in Section 5) all Applications through the Platform during the Term, provided the above license shall be perpetual to End Users making use of said Application pursuant to the Application Conditions.

**Comment by kennywasafk** [comment]
That's fair enough. Thanks for your response 👍
