### ISSUE TITLE
ToolTips

### ISSUE THREAD

**Issue by stvcobbs** [TLDRMissions/TLDRMissions#488]
Request a hover or click through tooltip for the reward(s) on the TLDR send mission UI.
Would be happiness :)
TLDR version: 9.2-113
![image](https://user-images.githubusercontent.com/108513034/179834944-2845e566-d542-4500-b7c7-533388fb8c20.png)

**Comment by teelolws** [comment]
I've looked into this and determined its too complicated to implement. If the addon had more than about 3 months of life left I might refactor the rewards UI to make it possible, bit with such a relatively short lifespan remaining its not worth the hassle of changing everything up.
