### ISSUE TITLE
Feature Request: Blacklist certain missions.

### ISSUE THREAD

**Issue by duranox** [TLDRMissions/TLDRMissions#491]
Certain missions like Break the Briarbane can take alot of time or Corrupted Builders is extremely hard to find a correct team for.

**Comment by teelolws** [comment]
Those two missions are persistently been a nuisance for me, too. Rather than blacklisting them, I am considering forcing 4 troop tests on those two missions. I've never been able to complete them with less.

**Comment by solkarnar** [comment]
Corrupted Builders can be done on NF using 3 troops in front and Dreamweaver bottom left, Te'zan bottom right.

What I do with mission tables is, do the >1k attack missions manually, then start TLDR.

**Comment by teelolws** [comment]
Next patch, Break the Briarbane and Corrupted Builders should be faster. The closer your followers and troops are to 60, the more likely the mission can actually be beaten and not skipped.

I'll be watching to see if there are any other seemingly impossible missions and apply the same efficiencies to them.

There are 82 followers. When paired with Croman, 47 out of 81 of the remaining followers cannot beat Break the Briarbane, even when full HP, max level, with max troops. That mission is so overtuned.
