### ISSUE TITLE
Feature request: sending mainly followers when the reward is bonus follower xp

### ISSUE THREAD

**Issue by Mirimes** [TLDRMissions/TLDRMissions#492]
**TLDR Version of your idea**
If the reward of the mission is extra xp for followers, it should cover the 5 spots with followers

**Slightly longer version**
there are missions whose reward is extra xp for followers, would be better if those missions would be carried by a full followers group so the extra xp aren't wasted

**Comment by teelolws** [comment]
Look in the advanced settings.
