### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by Lucetia** [TLDRMissions/TLDRMissions#493]
### Upload your Character-Specific Saved Variables here

Got the error late last night and ran a few missions since then.  Not sure if it makes it harder or not.  I had another toon that had the message but I can't remember who and wasn't sure if there was an easy way to search the settings file for a string that would indicate it was that toon.

[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/9155129/TLDRMissions.zip)

**Comment by teelolws** [comment]
Update the addon. The cause of this failed mission was fixed a couple of weeks ago.

**Comment by Lucetia** [comment]
I'm not sure how it was a couple of weeks ago.  I'm on 9.2-113 which was updated 5 days ago.  9.2-114 came out a day ago.

**Comment by teelolws** [comment]
The only failed mission in the file you uploaded was sent during addonVersion 9.2-109. If a different mission failed, then you have probably replaced the failed mission details by sending the mission back out again.

**Comment by Lucetia** [comment]
Ok then that is probably what happened then as I know I sent out missions this morning and afternoon before I remember to send the file in.  I was under the assumption that it would keep past data / failed data regardless.
