### ISSUE TITLE
follower health -- is it taken into account?

### ISSUE THREAD

**Issue by Earthling-Z3R0** [TLDRMissions/TLDRMissions#494]
Hey!

I would like to know if followers that haven't healed up yet (e.g. are at 32% health) will be treated as such or treated as if they were full health. I don't want a mission to fail because the calculation always runs with full health followers (I don't know).

Currently I am waiting for my followers to heal up over time before sending them again. (Or heal them up with anima when cheap.)

So if this is a feature request at all, it would be something like "Please take follower low health into account when computing mission success/setup".

Thank you very much for this awesome addon. I most likely would not run the missions table in the game without TLDR at all :-D

**Comment by teelolws** [comment]
Hi. Yes, of course your followers starting HP is taken into account. If it wasn't, I'd just have a giant file of about ~10MB with all the solutions for every follower for every mission. But throwing HP into the mix expands that size about 3000x.
