### ISSUE TITLE
[BUG] Several errors doing missions that were told to be blocked.

### ISSUE THREAD

**Issue by N6REJ** [TLDRMissions/TLDRMissions#498]
There are several times, today, that I noticed that campaigns that were told to NOT run, are infact running.
Light, getting soul ash when its specifically unchecked, getting rep for wrong covenants.  and others... please see the images for details
<img width="532" alt="tldr error" src="https://user-images.githubusercontent.com/1850089/180706824-18a9268a-021e-440e-b320-42d2ee4b6cda.png">
<img width="480" alt="tldr error 2" src="https://user-images.githubusercontent.com/1850089/180706828-969b9df8-7783-4253-a1e4-0e1092ed65a5.png">
<img width="540" alt="tldr error 3" src="https://user-images.githubusercontent.com/1850089/180706829-a2836b03-aa5a-4442-876f-2ccc4ed271d2.png">

**Comment by teelolws** [comment]
You're not handling that submenu incorrectly. By unchecking Soul Ash you're telling it "don't forbid Soul Ash".

**Comment by N6REJ** [comment]
so to exclude all just leave it blank?

**Comment by teelolws** [comment]
If you want to exclude them all, you need to X the Runecarver option, and put a Tick next to all the items in the submenu.
