### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by kirin7777** [TLDRMissions/TLDRMissions#499]
### Copy/paste the Lua error here

1x TLDRMissions\simulation.lua:1552: attempt to index local 'info' (a nil value)
[string "@TLDRMissions\simulation.lua"]:1552: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:15: in function `func'
[string "@TLDRMissions\workhandler.lua"]:51: in function <TLDRMissions\workhandler.lua:23>

Locals:
self = <table> {
 createWorkBatch = <function> defined @TLDRMissions\workhandler.lua:100
 TestFirstTenFollowersPlusTroops = <function> defined @TLDRMissions\testing.lua:49
 reputationCurrencyIDs = <table> {
 }
 updateRewards = <function> defined @TLDRMissions\guihandlers.lua:28
 craftingCacheCategories = <table> {
 }
 getFrontEnemies = <function> defined @TLDRMissions\targetting.lua:425
 logSentMission = <function> defined @TLDRMissions\logging.lua:10
 isCurrentWorkBatchEmpty = <function> defined @TLDRMissions\workhandler.lua:119
 craftingCacheQualities = <table> {
 }
 getAllEnemies = <function> defined @TLDRMissions\targetting.lua:529
 unpauseWorker = <function> defined @TLDRMissions\workhandler.lua:92
 setResultCacheGuaranteedFailure = <function> defined @TLDRMissions\caching.lua:94
 getAdjacentAlliesOrAllAllies = <function> defined @TLDRMissions\targetting.lua:383
 ProfileChanged = <function> defined @TLDRMissions\profiles.lua:624
 additionWithErrors = <function> defined @TLDRMissions\matherrors.lua:67
 LibStub = <table> {
 }
 sortFollowers = <function> defined @TLDRMissions\combinations.lua:120
 GetAllMissionsMatchingFilter = <function> defined @TLDRMissions\missions.lua:201
 sanctumFeatureItems = <table> {
 }
 getBackEnemies = <function> defined @TLDRMissions\targetting.lua:466
 getLineEnemies = <function> defined @TLDRMissions\targetting.lua:208
 isResultCacheGuaranteedFailure = <function> defined @TLDRMissions\caching.lua:77
 currentFollowersBeingTested = <table> {
 }
 spellsDB = <table> {
 }
 getPseudorandomMawswornStrength = <function> defined @TLDRMissions\targetting.lua:623
 runecarverCurrencyIDs = <table> {
 }
 GUI = TLDRMissionsFrame {
 }
 getCleaveEnemies = <function> defined @TLDRMissions\targetting.lua:67
 getClosestEnemy = <function> defined @TLDRMissions\targetting.lua:23
 arrangeAllFollowerPositions = <function> defined @TLDRMissions\combinations.lua:40
 getAllAllies = <function> defined @TLDRMissions\targetting.lua:517
 Simulate = <function> defined @TLDRMissions\simulation.lua:1484
 dontWait = false
 db = <table> {
 }
 RefreshProfile = <function> defined @TLDRMissions\profiles.lua:8
 getFurthestEnemy = <function> defined @TLDRMissions\targetting.lua:141
 followerList = <table> {
 }
 C_Garrison_GetFollowerAutoCombatStats = <function> defined @TLDRMissions\caching.lua:262
 setResultCacheCombinationKnown = <function> defined @TLDRMissions\caching.lua:207
 setResultCacheCombinationUnknown = <function> defined @TLDRMissions\caching.lua:173
 GetRunecarverMissions = <function> defined @TLDRMissions\missions.lua:408
 isResultCacheCombinationKnown = <function> defined @TLDRMissions\caching.lua:128
 getPseudorandomLashOut = <function> defined @TLDRMissions\targetting.lua:873
 followerXPItemIDs = <table> {
 }
 getConeEnemies = <function> defined @TLDRMissions\targetting.lua:270
 C_Garrison_GetFollowerInfo = <function> defined @TLDRMissions\caching.lua:6
 GetCraftingCacheMissions = <function> defined @TLDRMissions\missions.lua:374
 garrisonMissionStartedHandler = <function> defined @TLDRMissions\guihandlers.lua:954
 addWork = <function> defined @TLDRMissions\workhandler.lua:106
 GetFollowerXPItemMissions = <function> defined @TLDRMissions\missions.lua:261
 arrangeFollowerCombinationsByFewestFollowersPlusTroops = <function> defined @TLDRMissions\combinations.lua:358
 TestExistingMission = <function> defined @TLDRMissions\testing.lua:69
 craftingMaterialsCacheIDs

Don't even know when I got it, I just checked my bugsack

**Comment by teelolws** [comment]
Update the addon.
