### ISSUE TITLE
Feature Request: Health % determent if the NPC is send on mission

### ISSUE THREAD

**Issue by Manniala** [TLDRMissions/TLDRMissions#502]
Health of the NPC, amount of health, if its under that amount, do not calculate them in or use them.

TLDR version: 9.2-117c

**Slightly longer version**
The idea is, to have an option to say do NOT use followers if they have less than xx% life, slider 10, 20, 30, 40, 50, 60% or so life.
Putting slider to 0% Means it will ignore the life of the followers, as long as it is at least at 1 life.
For instance, sending the followers out on a mission with 5 life, seams like a bad idea, it wont win anything, so i would like an option to say, do not send them if they have less than for instance 40% life, all under that wont be send out.

**Comment by teelolws** [comment]
The addon already does this, somewhat. Take a look inside the ResultsCache folder. It is a large database of the minimum HP your followers need to beat each of the missions. If the follower doesn't have enough HP yet it will be ignored.

Don't worry about its HP. The addon will try the follower on missions it has enough HP to beat. It will combine it with another follower if it has to. In a majority of cases, a 1HP follower with 4 troops can still beat the mission.

**Comment by Manniala** [comment]
Ty for the Reply, did not know about this, all i knew was it send them out as long as they got 1 health.
