### ISSUE TITLE
[BUG] Pelodis and Nemea in the Kyrian "Missing" Follower List

### ISSUE THREAD

**Issue by Kanegasi** [TLDRMissions/TLDRMissions#504]
These two are mutually exclusive. If one is collected, the other is permanently locked.

After completing the Bastion optional storyline [Pride or Unit](https://www.wowhead.com/storyline/pride-or-unit-1150), Kyrian characters will get an extra quest at Elysian Hold for their choice: [Nemea](https://www.wowhead.com/quest=61859/adventurer-nemea) or [Pelodis](https://www.wowhead.com/quest=61860/adventurer-pelodis). You cannot change your choice.

**Comment by teelolws** [comment]
I know. The addon accounts for this already.

**Comment by Kanegasi** [comment]
My apologies for not being specific enough with the bug. I have chosen Pelodis. Nemea indeed does not show up in the table list, but they show up in the "Companions" list in the covenant report window.

![GIF 30-Jul-22 16-02-26](https://user-images.githubusercontent.com/2686302/181994551-0a8de36f-5fe0-42e1-9792-8a065fcc746f.gif)

**Comment by teelolws** [comment]
It works to remove Pelodis if you have Nemea. I don't have a Kyrian character with Pelodis to test it. The garrFollowerID for Pelodis must be different to the one listed on: https://wowpedia.fandom.com/wiki/GarrFollowerID

**Comment by Kanegasi** [comment]
It's the same. Nemea is 1270 and Pelodis is 1271.

I discovered the problem, it's a Lua logic issue. Since you're not iterating the data table in order, there's a chance on each addon load for the loop to reach the uncollected one before you reach the collected one, inserting the uncollected one into the companion list. There's no guarantee in what order pairs() goes through a table. Since there are separate loops for the table list and the report window, one may show the other, or both or neither. I swear I saw Nemea in the mission table list when I initially reported.

I rewrote the loop so that it goes through once to find known followers, deleting the Pelodis or Nemea if you know the other, then goes through again. Since they cannot be changed, and the addon loads again fresh on a login or reload, it's not an issue to just remove the other one.

```Lua
local uncollectedFollowers,known = {},{}
for garrFollowerID, data in pairs(gDB) do
    for _, follower in pairs(followers) do
        if (garrFollowerID == follower.garrFollowerID) then
            known[garrFollowerID] = true
            if (garrFollowerID == 1270) then
                gDB[1271] = nil
            end
            if (garrFollowerID == 1271) then
                gDB[1270] = nil
            end
        end
    end
end
for garrFollowerID, data in pairs(gDB) do
    if (not known[garrFollowerID]) and ((data.covenantID == 0) or (data.covenantID == C_Covenants.GetActiveCovenantID())) then
        local info = C_Garrison.GetFollowerInfo(garrFollowerID)
        info.source = data.source
        info.status = GARRISON_FOLLOWER_ON_MISSION
        table.insert(uncollectedFollowers, info)
    end
end
```

**Comment by teelolws** [comment]
`for garrFollowerID, data in pairs(gDB) do`
[...]
`                gDB[1271] = nil`

I've always been hesitant to do this. Change a table while iterating through the table. Can this cause problems for the iterator?

**Comment by Kanegasi** [comment]
You can safely change or delete a value when iterating through a table. You cannot, however, add to a table. That is, for all intents and purposes, like Lua's equivalent to dividing by zero. If iterating through an array in ascending order, using table.remove() will shift all higher indexes down by one, so you need to account for that otherwise you'll skip the next index which was moved to the one you deleted.
