### ISSUE TITLE
[BUG] Lua error new update with Oilvl

### ISSUE THREAD

**Issue by Rathaniel** [TLDRMissions/TLDRMissions#509]
### Copy/paste the Lua error here

No error with Oilvl turned off and TLDR turned on.
No error with Oilvl turned on and TLDR Turned off.
This only started to happen with update 118 today, i looked for an older version but i cant see any.

------------------------------------------------------------------------------------------------------------------------------

7x ...DropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua:90: attempt to index local 'button' (a nil value)
[string "@Oilvl\libs\!LibUIDropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:90: in function <...DropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua:72>
[string "=[C]"]: ?
[string "@Oilvl\libs\!LibUIDropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:427: in function `L_UIDropDownMenu_Initialize'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5834: in function `OilvlRaidMenu'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5949: in function `OilvlConfigFrame'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5537: in function `?'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5748: in function <Oilvl\Oilvl.lua:5747>

Locals:
frame = ORaidDropDownMenu {
 0 = <userdata>
 PixelSnapDisabled = true
 Right = ORaidDropDownMenuRight {
 }
 Left = ORaidDropDownMenuLeft {
 }
 Text = ORaidDropDownMenuText {
 }
 Button = ORaidDropDownMenuButton {
 }
 Icon = ORaidDropDownMenuIcon {
 }
 Middle = ORaidDropDownMenuMiddle {
 }
 noResize = 1
}
button = nil
dropDownList = L_DropDownList1 {
 0 = <userdata>
 Button1 = L_DropDownList1Button1 {
 }
 MenuBackdrop = L_DropDownList1MenuBackdrop {
 }
 numButtons = 0
 Border = L_DropDownList1Border {
 }
 maxWidth = 0
}
(for index) = 1
(for limit) = 2
(for step) = 1
i = 1
(for index) = 2
(for limit) = 10
(for step) = 1
j = 2
(*temporary) = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 SoulbindCacheOpener_WildHuntSuppliesFlash = SoulbindCacheOpener_WildHuntSuppliesFlash {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 AchievementFrameStatsBG = AchievementFrameStatsBG {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 759
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 405
 SoulbindCacheOpener_tributeofthecourtFlyoutBorder = SoulbindCacheOpener_tributeofthecourtFlyoutBorder {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TLDRMissionsFollowerXPItemsAnimaCostDropDownLeft = TLDRMissionsFollowerXPItemsAnimaCostDropDownLeft {
 }
 FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture = FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 AchievementFrameSummaryAchievement3Shield = AchievementFrameSummaryAchievement3Shield {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 359
 MerchantItem5AltCurrencyFrameItem1Text = MerchantItem5AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 ExtraGoodies_DarkmoonPetSuppliesCount = ExtraGoodies_DarkmoonPetSuppliesCount {
 }
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:791
 PaperDollTitlesPaneButton12BgTop = PaperDollTitlesPaneButton12BgTop {
 }
 ERR_NOAMMO_S = "%s"
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 973
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:1107
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }
 Is64BitClient = <function> defined =[C]:-1
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = Compact

------------------------------------------------------------------------------------------------------------------------------

7x ...DropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua:736: attempt to index local 'button' (a nil value)
[string "@Oilvl\libs\!LibUIDropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:736: in function `L_UIDropDownMenu_AddButton'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5829: in function `initFunction'
[string "@Oilvl\libs\!LibUIDropDownMenu\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:432: in function `L_UIDropDownMenu_Initialize'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5834: in function `OilvlRaidMenu'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5949: in function `OilvlConfigFrame'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5537: in function `?'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5748: in function <Oilvl\Oilvl.lua:5747>

Locals:
info = <table> {
 value = "Sanctum of Domination"
 text = "Sanctum of Domination"
 func = <function> defined @Oilvl\Oilvl.lua:5815
}
level = 1
listFrame = L_DropDownList1 {
 0 = <userdata>
 Button1 = L_DropDownList1Button1 {
 }
 MenuBackdrop = L_DropDownList1MenuBackdrop {
 }
 numButtons = 2
 Border = L_DropDownList1Border {
 }
 maxWidth = 122.133331
}
index = 2
width = nil
listFrameName = "L_DropDownList1"
button = nil
(*temporary) = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 SoulbindCacheOpener_WildHuntSuppliesFlash = SoulbindCacheOpener_WildHuntSuppliesFlash {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 AchievementFrameStatsBG = AchievementFrameStatsBG {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 759
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 405
 SoulbindCacheOpener_tributeofthecourtFlyoutBorder = SoulbindCacheOpener_tributeofthecourtFlyoutBorder {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TLDRMissionsFollowerXPItemsAnimaCostDropDownLeft = TLDRMissionsFollowerXPItemsAnimaCostDropDownLeft {
 }
 FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture = FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 AchievementFrameSummaryAchievement3Shield = AchievementFrameSummaryAchievement3Shield {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 359
 MerchantItem5AltCurrencyFrameItem1Text = MerchantItem5AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 ExtraGoodies_DarkmoonPetSuppliesCount = ExtraGoodies_DarkmoonPetSuppliesCount {
 }
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:791
 PaperDollTitlesPaneButton12BgTop = PaperDollTitlesPaneButton12BgTop {
 }
 ERR_NOAMMO_S = "%s"
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 973
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:1107
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }
 Is64BitClient = <function> defined =[C]:-1
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 TutorialFrame_OnMouseDown = <function> defined @FrameXML\TutorialFrame.lua:376
 ContainerFrame4Item16Cooldo
------------------------------------------------------------------------------------------------------------------------------

7x Oilvl\Oilvl-v9.0 SL.lua:1346: attempt to index global 'OilvlTooltip' (a nil value)
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:1346: in function `func'
[string "@Details\Libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <...ceDetails\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'OilvlTooltip' (a nil value)"
rpdframe = nil
rpdframesw = false
------------------------------------------------------------------------------------------------------------------------------
11x Oilvl\Oilvl-v9.0 SL.lua:5255: attempt to index field '?' (a nil value)
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5255: in function `oilvlSaveItemLevel'
[string "@Oilvl\Oilvl-v9.0 SL.lua"]:5310: in function <Oilvl\Oilvl.lua:5310>

Locals:
n = 1
OTilvl = 237.200000
OTmia = 0
missenchant = "Chest, Hands"
missgem = ""
missenchant2 = "Feet, Wrist"
missgem2 = "Head, Neck, Chest"
count2 = 16
legendary2 = 1
gspec = 258
(*temporary) = nil
(*temporary) = nil
(*temporary) = 16
(*temporary) = "Chest, Hands"
(*temporary) = ""
(*temporary) = "Feet, Wrist"
(*temporary) = "Head, Neck, Chest"
(*temporary) = "attempt to index field '?' (a nil value)"
OILVL_Unit = "player"
miacount = 0
miaunit = <table> {
 1 = ""
 2 = ""
 3 = ""
 4 = ""
 5 = ""
 6 = ""
}
OTCurrent = "OILVLRAIDFRAME1"
OTCurrent2 = "player"
oilvlframedata = <table> {
 mg = <table> {
 }
 role = <table> {
 }
 name = <table> {
 }
 guid = <table> {
 }
 gear = <table> {
 }
 spec = <table> {
 }
 me = <table> {
 }
 ilvl = <table> {
 }
}
OTCurrent3 = 1
OILVL = <unnamed> {
 0 = <userdata>
}

**Comment by teelolws** [comment]
Please ask the author of OIlvl to update the LibUIDropDownMenu that he is using. https://www.curseforge.com/wow/addons/libuidropdownmenu/

He has bundled in v57. The current is v97. Using such an out of date library is causing interference.
