### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by skmzarn** [TLDRMissions/TLDRMissions#513]
### Upload your Character-Specific Saved Variables here

Failed several Follower bonus XP missions. 

[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/9240388/TLDRMissions.zip)

**Comment by teelolws** [comment]
Nothing in that file failed. Why do you believe they failed?

**Comment by skmzarn** [comment]
Wow, that was fast. It showed a "cross" when they were completed. Isn't that when they fail?

**Comment by teelolws** [comment]
You mean a "cross" in the Venture Plan complete missions button? You're just trusting a completely different addon?

**Comment by skmzarn** [comment]
I have Venture Plan active, but I am only using your addon. Could they mess up with each other? I need to check on the next and see what it says. All I noticed was whether it was a red cross or a green mark. Maybe Venture Plan mess with pictures.

**Comment by teelolws** [comment]
The red cross in Venture Plan doesn't mean the mission failed. Next time watch for the text "Victorious" or "Failed". Its common for missions sent from my addon to show "Victorious" with a red cross in Venture Plan.

**Comment by skmzarn** [comment]
Okay, it seems to work, misunderstanding from me. I close this, thanks!
