### ISSUE TITLE
Bonus Follower missions assign level 60 followers and waste bonus

### ISSUE THREAD

**Issue by actineon** [TLDRMissions/TLDRMissions#518]
I noticed when Tldrmissions tried to do a bonus follower xp mission, it chose a level 60 follower and then added troops to make the mission succeed. This is great for all missions except bonus follower xp missions. A level 60 follower has no use for bonus XP so this wasted anima doing a mission that had no value. Normally when I want to do a bonus follower mission, I want followers who are not level 60 and I'd prefer to use many of them without using any troops or using troops if I don't have enough followers below 60.

**Comment by teelolws** [comment]
Take a look through the settings. *All* the settings. Not just the ones visible on the front page.

**Comment by dave128** [comment]
FWIW "Special Treatment for Follower XP Missions" should be checked by default. Optimizing these XP missions is paramount for maximizing overall rewards over time.
