### ISSUE TITLE
instructions would be nice

### ISSUE THREAD

**Issue by actineon** [TLDRMissions/TLDRMissions#519]
It would be nice if your description web page had instructions for use. That will make using this more popular and result in fewer bug reports. Great job by the way.

For example:
what does a golden check mark do?
what does a red x do?
what does a blank box do?
do I need to wait for simulations to end before starting missions?

More advanced instructions like:
what would be a good example set up if someone already had troops at level 60 and was just interested in gold farming?
what would be a good example set up if someone had very low level troops and wanted them leveled up because their ultimate goal was gold farming?

**Comment by teelolws** [comment]
Okay, heres some basic instructions about the check marks: https://github.com/TLDRMissions/TLDRMissions/wiki/Short-Guide

> do I need to wait for simulations to end before starting missions?

If the button is clickable, theres something ready to send.

As for setups, I'm leaving that to the community. There are some very good videos on Youtube, and written guides on Reddit. I just make the tool, strategies are up to you.
