### ISSUE TITLE
[BUG] Campaign Progress missions not being sent

### ISSUE THREAD

**Issue by Sluimerstand** [TLDRMissions/TLDRMissions#520]
As title. I've got all campaign mission progress categories enabled except 17+, for all anima costs, as the #1 priority within the addon. Yet, it always skips these missions. They seem to get stuck on progress level 12, so the missions for 13 are where it stops sending them. I've manually sent for these missions on one of my characters after calculating through Venture Plan, and these are easy victories. Yet even after manually pushing the mission progress to 13, 14 and 15 the addon for some reason refuses to send these missions.

If any additional information is helpful, I'll gladly provide.

**Comment by teelolws** [comment]
Check the secondary reward for the campaign mission. If you've added the other reward to your exclusions (with a red X) it won't send that mission.

**Comment by Sluimerstand** [comment]
I've not excluded any rewards. Now that I'm looking at my remaining missions more closely though, it seems to also not be prioritising some other missions properly, but it could be those simply appeared after I'd sent my missions.

I'll reset the addon by reinstalling it and deleting the SavedVariables files tomorrow, and see which missions it's actually sending to make sure it's not to do with my imagination and/or erroneous settings. I'll report back here.

![image](https://user-images.githubusercontent.com/29845810/182708237-8bb67eb7-7aa5-4fbd-8f1b-a23dd3bf2066.png)

**Comment by teelolws** [comment]
You shouldn't need to delete your variables. Check the other filters. The campaign missions can sometimes cost a lot. Do you have an anima filter? Check the dropdown next to campaign, and the global setting under the Advanced tab.

**Comment by Sluimerstand** [comment]
It ended up being a combination of other filters. Apologies for the wasted time, the issue is resolved. :)
