### ISSUE TITLE
LUA Error on one of 8 toons 

### ISSUE THREAD

**Issue by elBizzle** [TLDRMissions/TLDRMissions#526]
Works on all other toons except one 
This development started yesterday. 

Screen attached 
![1ED6ABEE-D5BF-47F6-96DC-9EB2C7E356E3](https://user-images.githubusercontent.com/110627457/182915296-ec2b1d8f-4364-43ba-8c26-206ef9ecd911.png)

**Comment by elBizzle** [comment]
Add on is updated.  All profiles are the same.

**Comment by teelolws** [comment]
Can you try it with all other addons turned off?

**Comment by elBizzle** [comment]
I disabled some newer Addons and it works. Something was bugging it

V/R,

Lawrence Abber

**Comment by teelolws** [comment]
Can you work out which one is bugging it?
