### ISSUE TITLE
[BUG] Two missions failed

### ISSUE THREAD

**Issue by sosiskha** [TLDRMissions/TLDRMissions#530]
### Upload your Character-Specific Saved Variables here

Got missions 2243 and 2301 failed on two different characters (first one is in russian, but hope it'll help anyway).
[SavedVariables.zip](https://github.com/TLDRMissions/TLDRMissions/files/9275579/SavedVariables.zip)

**Comment by teelolws** [comment]
Thanks! Fixed next patch.
