### ISSUE TITLE
[BUG] It's ignoring the campaign

### ISSUE THREAD

**Issue by wheatbread** [TLDRMissions/TLDRMissions#531]
Hi,

Just wanted to report that TLDR seems to be ignoring the campaign missions, despite it being set to having campaign mission progress as #1.

All missions sent, but campaign mission still there:

![image](https://user-images.githubusercontent.com/548824/183267568-b1577959-175d-42e5-97a8-9a82f24ad162.png)

The settings were originally

![image](https://user-images.githubusercontent.com/548824/183267587-f257f097-bbdf-406c-8b8a-ba06f23942fe.png)

and it didn't do the campaign mission.  So just now I changed the settings to:

![image](https://user-images.githubusercontent.com/548824/183267577-7eca5276-6450-4c17-8041-db802a6d1b64.png)

before sending just now, and it still didn't do the campaign mission.

**Comment by teelolws** [comment]
Show me the dropdowns next to the Campaign option

**Comment by wheatbread** [comment]
Oh, yes, that's probably it.  I have 2 followers at 55 and the rest are 36/35.  

![image](https://user-images.githubusercontent.com/548824/183310144-60da3cc3-9506-4e5b-9a5b-22e7d73995de.png)

Thank you and sorry for the trouble!
