### ISSUE TITLE
[BUG] Still having confusing issues with NOT doing missions

### ISSUE THREAD

**Issue by N6REJ** [TLDRMissions/TLDRMissions#532]
Before you told me to NOT send missions, like follower xp.  You needed red X on the left and gold on the right.
That is no longer possible...
![image](https://user-images.githubusercontent.com/1850089/183269525-d9d39a90-a39c-48b6-8821-4e62756bcddb.png)
but then it won't go gold.. stays X
also, it doesn't seem to doing things completely correctly.  For example, it didn't send the pet coin out.
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/1850089/183269577-87a31a27-9082-4d40-9d47-f92e718a4d54.png">

**Comment by N6REJ** [comment]
if you could please set it so that if gold on left and red on right to not send, that would be logical

**Comment by teelolws** [comment]
Close and reopen that submenu after you change the main option from tick to cross. Theres an issue with the submenu I'll address in a future patch.

**Comment by teelolws** [comment]
It probably didn't send that Bag Inspection mission because your followers aren't high enough level for it.

**Comment by N6REJ** [comment]
> It probably didn't send that Bag Inspection mission because your followers aren't high enough level for it.

all my followers are level 60

**Comment by teelolws** [comment]
It didn't send the Bag Inspection mission because you have Red X'ed the Follower XP Items.

Exclusions have priority over Inclusions. This means "I don't want Follower XP Items" means it won't send missions that award them, no matter what.

**Comment by N6REJ** [comment]
I was wondering that.  
just so its clear to others...
If one reward is disabled then that mission is disabled even if the other reward is enabled.
