### ISSUE TITLE
[BUG] Other - Then, Anything else for XP, doesn't send missions

### ISSUE THREAD

**Issue by fotoman-62** [TLDRMissions/TLDRMissions#533]
Very often, while having "Then, anything else for XP." checked, it leaves a few followers that could run missions for xp. I usually manually run them. Seems like that setting doesn't work at all.

**Comment by teelolws** [comment]
It followers your Bonus XP settings. Check this setting:
![image](https://user-images.githubusercontent.com/49792789/183288858-67a944a1-9f8b-4252-8940-f5162e72d207.png)

**Comment by fotoman-62** [comment]
So how then, do I send all followers for Follower XP missions, but then if I have two left over at the end send those together on a mission for XP?

**Comment by teelolws** [comment]
Lower the minimum. It'll still send 5 if you have 5.

That setting was added due to other players telling me they **didn't** want just 2 followers being sent out, as that was considered "wasteful".
