### ISSUE TITLE
Feature request: Weekly Stats

### ISSUE THREAD

**Issue by I-AM-T3X** [TLDRMissions/TLDRMissions#534]
A simple stats window 

Basicly a button that we can hit that will open a window for maybe weekly or monthly stats
just shows some basic information like gold earned this week from the mission table, amount of anima the table used minus the amount we gained from the table, maybe a count of how many pet charms we have collected from the table

**Comment by teelolws** [comment]
That sounds like a great idea for another addon. If there wasn't such limited time before the tables are obsolete I might look at it. Maybe TSM already does this?

**Comment by I-AM-T3X** [comment]
They did say we wouldnt have tables going forward, but I'm sure they are gonna leave these tables active just like all the other expansions, so maybe this could be added sometime down the line when its still active?

**Comment by solkarnar** [comment]
TSM does this under Ledger, but I think TSM is overkill for a lot of people. I'm personally using [Accountant](https://www.curseforge.com/wow/addons/accountant) to track my gold gains. That addon works but it isn't fantastic and could be improved. An addon that breaks down gold gain from different sources across characters and servers, with data displayed by days/weeks/months/across a range would be nice.
