### ISSUE TITLE
Checkbox for Stygia Items

### ISSUE THREAD

**Issue by Amadeus-** [TLDRMissions/TLDRMissions#537]
**Checkbox for Stygia Items**
Add a checkbox for missions that include Stygia granting items.  Or, if this type of item is included with another category, provide clarification text or tooltip.

An example of a mission of this type would be:  [Topple the Giants (wowhead link)](https://www.wowhead.com/mission=2253/topple-the-giants)

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/184059495-7354372c-8131-4d36-936b-819f39e929aa.png)

**Comment by Amadeus-** [comment]
Oh, I'm so sorry, I didn't think to check those dropdowns.   I apologize for the inconvenience.
