### ISSUE TITLE
Feature Request: Ability to prioritize completing all gold missions first

### ISSUE THREAD

**Issue by scotty562** [TLDRMissions/TLDRMissions#539]
**TLDR Version of your idea**
TLDR version: 9.2-122b

**Slightly longer version**
I like to put as many followers on a mission as possible for anima efficiency. I often run out of followers before gold missions which leaves uncollected gold. It would be great if the addon would be able to ensure all gold missions are completed and then max follower the rest of the missions.

**Comment by teelolws** [comment]
It sounds like you're overthinking the anima efficiency. The difference between 1 follower + 4 troops and 5 followers is 4 anima, which is insignificant. Micromanaging advanced settings per reward type is not a feature that has enough demand to implement.

**Comment by scotty562** [comment]
I believe there is misunderstanding.

Let's say I do 2 followers per mission and I do 10 missions with each mission costing 10 anima. That is 100 anima. Now let's say I do 4 gold missions with 2 followers each and 2 missions with 5 followers with each mission costing 10 anima. That is 60 anima. Each will use all of my available followers. The second way cuts my anima usage almost in half. The odds of there being ten 10 anima missions is low which means at least a few would be higher than 10 anima which would mean the anima savings are even higher.

Why does this matter you may ask. I like to run a whole bunch of characters and all I do with them is the mission table and farm mounts. So the last thing I want to do is farm anima to be able to do the mission table. This feature would go a long way towards this goal while still taking the most advantage of the gold offered from the available missions. Perfectly understandable if it doesn't get implemented, but I thought I would share. Also thank you for all your work on this addon it is nothing short of amazing.

**Comment by teelolws** [comment]
Could you not just only check Gold and Anima? If you don't want those other missions, they'll expire after a few hours and be replaced.

**Comment by teelolws** [comment]
The XP options will obey your "Special Treatment" settings. So, if you enable Special Treatment and set it to minimum 1 follower, it should do what you want!

**Comment by scotty562** [comment]
Ahh I see. Yes that does exactly what I'm looking for. Thank you for clarifying.
