### ISSUE TITLE
[BUG] Other : A herb mission does not get picked up

### ISSUE THREAD

**Issue by solkarnar** [TLDRMissions/TLDRMissions#541]
![bug](https://user-images.githubusercontent.com/69765868/184258956-74f1b901-a675-41f0-83ab-4f40930396ba.png)

As shown in this picture, the herb mission does not get picked up even when I ticked Herb Gathering on all anima costs.

**Comment by teelolws** [comment]
That herb is a Venthyr-only reward connected to the Ember Court. Look for it in the menu next to Sanctum Feature.

**Comment by solkarnar** [comment]
Ok got it. Thanks!
