### ISSUE TITLE
Missing Crafting Material Mission?

### ISSUE THREAD

**Issue by Cellcubed** [TLDRMissions/TLDRMissions#543]
I think the mission called Glimmerfly Overpopulation is not being picked for crafting materials. The reward includes porous stone. It's being picked up by sanctum feature for some reason. Venthyr.

**Comment by teelolws** [comment]
Because it is a mission connected to the Ember Court, a Sanctum Feature. You'll see all of its rewards in the sanctum feature dropdown:

![image](https://user-images.githubusercontent.com/49792789/184556698-842e7497-b852-4b55-b8eb-54e7433ce22a.png)
