### ISSUE TITLE
Few suggestions how to make TLDR faster

### ISSUE THREAD

**Issue by sirzooro** [TLDRMissions/TLDRMissions#546]
I have checked code in `simulation.lua` looking for things which may be optimized and found that `getTargets` looks like a good candidate to improve. This function compares `targetType` with strings multiple times. ~~String comparison is slow, it would be better to replace strings with numbers.~~ (edit: I read that LUA internalizes strings so comparison is fast) LUA does not have native `enum` type like other languages, so you would need to create local constants like suggested here: https://stackoverflow.com/a/70529411/2333421 . To avoid changes in `spellsdb.lua`, you could convert strings to numbers before simulation.

Above change also would open way to use table of lookup functions to emulate `switch` statement: https://lua-users.org/wiki/SwitchStatement (check "Simple Table of functions" part) as a replacement for this long list of `if`/`elseif` statements. Edit: lookup table also would work with string keys, but LUA would have to do lookup via hash table. With numbers it can perform lookup via array part what is faster.

`getTargets` also calls multiple `addon:something` functions. This needs extra hashtable lookup, and can be optimized by creating local aliases for them like desribed here: https://blog.roblox.com/2012/02/an-optimization-for-lua-scripts/

Note: I code in C++ for a living so above suggestions may not be as good for LUA as they are for C++, but please check them anyway.

**Comment by teelolws** [comment]
I'll change those strings to a Blizzard-style Enum. May not be as efficient as hardcoding the constants into the spells DB directly, but it keeps it readable. I prefer this over `type = 1` which the other simulator addons do, where I'm left reading that and don't know what `type 1` is.

![image](https://user-images.githubusercontent.com/49792789/184555946-357bfb40-f9ae-4c81-a379-d85f1ac80298.png)


I think a bigger improvement would be to move the inner functions inside doSimulation outside of it, so they're not reinitialized every simulation. I'll work on that.
