### ISSUE TITLE
[BUG] Other - Missions not being recognized as within parameters?

### ISSUE THREAD

**Issue by jsholt83** [TLDRMissions/TLDRMissions#548]
Missions for Crystalline Memory Repository (and others follower xp items?)  not recognized as "follower xp item"? 

For whatever reason, TLDR is not sending missions that are clearly for a follower xp item. All of my followers are 60 so I am not sure if its stopped recognizing it as something that is valuable or not.  These items are account bound so they can be sent to other toons.  The missions on the board also have gold attached to them.  Not sure if I am doing something wrong here or its the addon.  It used to work until all my followers reached 60.  All followers are healed to max

![2022-08-17](https://user-images.githubusercontent.com/53126391/185180516-aa81858f-108e-4d23-8889-e5fbfc050b21.png)
![2022-08-17 (1)](https://user-images.githubusercontent.com/53126391/185180526-6108556b-3aa3-4199-a559-e7811b35a621.png)

**Comment by teelolws** [comment]
Why do you have the simulations limited to 500 per mission?

**Comment by jsholt83** [comment]
I do this on like 10 toons, so I have to limit it or I'd be there forever :) That number didnt seem to effect it finding missions for me in the past, now only since they are all leveled to 60.  Should I be putting it up higher?

**Comment by teelolws** [comment]
If it happens again raise the limit and try again.
