### ISSUE TITLE
[BUG] Other - Venthyr tables take much longer than other covenants

### ISSUE THREAD

**Issue by tsmuse** [TLDRMissions/TLDRMissions#550]
I'd like to know if there is some data I can provide to help with this. I have toons in each covenant and the other 3 sending a batch of missions takes at most a minute or two. The Venthyr table requires so many simulations that I regularly am set to AFK while it's running. I'm using the same settings profile for all of these characters. Is there some data I can provide to help tweek the addon or is this just an issue with the covenant's adventurers being not as strong? 

Thanks, I love the addon.

**Comment by teelolws** [comment]
Because Venthyr followers and troops suck. It just takes so much longer to find something that works.
