### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by dbamaidens** [TLDRMissions/TLDRMissions#555]
### Upload your Character-Specific Saved Variables here

Got this fail in 9.2-125, just noticed 9.2-126 is out so apologies if it's already fixed.
[TLDRMissions.zip](https://github.com/TLDRMissions/TLDRMissions/files/9418431/TLDRMissions.zip)

**Comment by teelolws** [comment]
Thanks for the report!
