### ISSUE TITLE
pin the TLDR-window to the mission-table

### ISSUE THREAD

**Issue by Ahfau77** [TLDRMissions/TLDRMissions#556]
**TLDR Version of your idea**
TLDR version: 9.2-127

**Slightly longer version**
hello,

at two toons the TLDR-window pins automatically to the left border of the window of the mission-table.
On any other chars the windows are not pinned together.

Is there an option or method to archieve the pinning at all chars ?

**Comment by teelolws** [comment]
Just click and drag the window to where you want it. As long as you don't turn the addon off, it will remember where you left it.

**Comment by Ahfau77** [comment]
but it does not pin to the window of the mission-table ?

I would like to have the two windows stick together, so when i move the mission-table, the TLDR-window should "follow"...

**Comment by teelolws** [comment]
Ah. You'll have to revert the window back to its default.

Run this:

`/run TLDRMissions.GUI:SetPoint("RIGHT", CovenantMissionFrame, "LEFT")`

**Comment by Ahfau77** [comment]
ok, that does the trick about the pinning (for the current session, after relog the windows are "free" again).
But after running the given command the TLDR-window just resizes horizontally and does not move when i drag the table-window to one side.

**Comment by teelolws** [comment]
What addon are you using to move the mission table window?

**Comment by Ahfau77** [comment]
BlizzMove (https://www.curseforge.com/wow/addons/blizzmove)

**Comment by teelolws** [comment]
Okay. When I get some time I'll do some testing and get back to you.

**Comment by Ahfau77** [comment]
thanks a lot!

your addon is really great and provides a huge improvement for doing the daily missions :)

**Comment by teelolws** [comment]
Replace gui.lua with the file in this zip. I'll release a patch with the fix some other day. The GUI will now latch to the left side of the mission frame if you drag it back within 20 pixels of the edge of the mission frame.
[gui.zip](https://github.com/TLDRMissions/TLDRMissions/files/9433059/gui.zip)

**Comment by Ahfau77** [comment]
works like a charm, thx for your effort!
