### ISSUE TITLE
I would like to request an additional Korean translation file.

### ISSUE THREAD

**Issue by free4one** [TLDRMissions/TLDRMissions#557]
**TLDR Version of your idea**
TLDR version: 9.2-127

**Slightly longer version**
I would like to request an additional Korean translation file.
The Korean translation file has been added as an attachment.

**Additional context**
[koKR.zip](https://github.com/TLDRMissions/TLDRMissions/files/9437883/koKR.zip)

**Comment by teelolws** [comment]
> local L = LibStub("AceLocale-3.0"):NewLocale("TLDRMissions", "koKR", true)

Should be:

> local L = LibStub("AceLocale-3.0"):NewLocale("TLDRMissions", "koKR")

The `, true` is only for the default language, which is English.
