### ISSUE TITLE
Faster simulations

### ISSUE THREAD

**Issue by Naxterra** [TLDRMissions/TLDRMissions#564]
**TLDR Version of your idea**
TLDR version: 9.2-130

Simulations are taking too much time. I don't know why.
**Slightly longer version**
I simple mission shouldn't take a minute to get processed. I am getting around 14k simulations for a mission now. Here is a screenshot when it was around 10k

**Additional context**
![grafik](https://user-images.githubusercontent.com/41871948/188642540-926f48d5-e81d-4bfa-860e-9993ae0052fa.png)

**Comment by teelolws** [comment]
Can you show me your Advanced settings, and your followers?

**Comment by Naxterra** [comment]
> Can you show me your Advanced settings, and your followers?

Sure, here are screenshots.

![grafik](https://user-images.githubusercontent.com/41871948/188720120-4d5d31ce-18bf-486f-a58f-6ee452c37796.png)
![grafik](https://user-images.githubusercontent.com/41871948/188720164-6165dc5d-9e40-44db-9eae-27ca616cf577.png)
![grafik](https://user-images.githubusercontent.com/41871948/188720195-6888c4b2-f03a-4b82-9294-92be4f978d98.png)

**Comment by teelolws** [comment]
Venthyr can be difficult to find solutions on, especially if you didn't use the troop trick to get your troop level up. Their followers and troops are quite underpowered compared to the other covenants. I suggest you drop the Simulations Limit down to 5000 and just move on from that mission. You'll be able to beat it after your followers level up more. There are other comments about it being unbeatable as Venthyr: https://www.wowhead.com/mission=2275/a-thorn-in-their-side#comments
