### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by micromalc** [TLDRMissions/TLDRMissions#568]
I was a new user about week ago and everything was going OK. The new update seems to have caused it to have problems a. running sims (often the very first mission just sims endlessly or for a very long time) and b. the UI isn't cycling through the missions (1/14>2/14>3/14 etc) as it once did.

For a. it might sim endlessly for a mission I can easily manually organise using VenturePlan. For b. eventually when the sim is complete then clicking Start Mission will present odd behaviour like it will start missions (/14) 1>2>4>4>4>7>8>>8>12>12>14>14>14.

Previously as it cycled through the sims for each mission you could see it "working" as it went through each mission. Now, it seems it might be simming the entire rosta of missions while the UI says it is still simming mission 1. Not sure. Anyway, this happened since the most recent update.

**Comment by teelolws** [comment]
If it sims "endlessly", its stuck on a hard mission, you have a lot of followers, and it can't find a solution.

If it skips over a mission 1 -> 2 -> 4 its because (3) was judged impossible to beat with your followers.

**Comment by micromalc** [comment]
I'll go into more detail about the UI problem. It's not skipping missions by not sending them out. It's just the UI that's not progressing rationally through the mission count. Here's what happened just now:
I open the Mission Table.
Click TL:DR.
Mission 1/15 displays with followers and troops.
I click Calculate.
The first sims start running on Mission 1/15. (The counter starts going).
The sims counter resets to 0 and starts going again. But the mission info stays the same i.e. it's on mission 1/15 with the same follower, same troops.
If I keep an eye on the the sims counter I can see it completing and resetting back to 0 a few times, then suddenly the sims stop going. For the entire simming process, the mission info has remained on mission 1/15. Same troops etc. Previously the mission info changed each time the sims counter reset, which made sense, as you could see which mission it was simming. Now you can't.

(Well, so what. If it gets to the end of the sims anyway, then it doesn't matter. But if it doesn't, you can't see which mission it is stuck on, I can't report it to the addon developer like they've asked for, and the addon can't improve.)

I click Start Mission anyway. Mission 1 starts. Instead of diplaying Mission 2/15, the mission info jumps skips all the way to 10/15 (I expected it to go to 2/15, 3/15 etc).
I click Start Mission again. Some other Mission starts. The mission info still says mission 10/15, but the followers and troops have changed.
I click Start Mission again. Some other Missions starts. Now the UI says 13/15. I click it again. It still says 13/15, but the followers and troops have changed. So it's not just because it's skipping difficult missions. The UI isn't updating properly after each Start Mission.
Even when it cycles through the missions properly, it might suddenly get caught at the end, ie I click Start Mission several times on what should be the final mission, e.g. on a separate alt I start mission 14/14 FOUR times, all with different troops and followers.

Here's another behaviour on a different alt / different covenant. The mission count goes from 1>3>5>6>7>8>9>10>10 (different troops / followers / mission name) > 10 (different troops / followers / mission name). Then, the report says "All missions sent (ie none were skipped). So it is sending the missions, the UI is just not updating correctly.

RE. difficult missions / number of followers. I don't think it can be an issue with the number of followers or the difficulty of the mission. Firstly, none of my mission tables (I have 16) are well developed. If it's a prob with the number of followers, then we may as well admit the addon can only handle default rostas. Having said that, I don't think it's a widespread problem as the addon seems to only get stuck on the occasional mission. I'm only reporting it as I noticed it was stuck on simming a level 20 elite mission when I had about 4 followers at level 38-41 range and troops (Ardenweald.....) at level 28, rest of the followers in the low 20s, and VenturePlan (which I don't prefer) easily simmed by dropping in one follower and asking it to autofill.

**Comment by teelolws** [comment]
While it is waiting for you to click the Start Mission button, it is still calculating the remaining missions in the background. If you send out 1/15 and it skips to 10/15, that means it couldn't find a solution for missions 2 through 9, or you have level/anima restrictions that prevented your followers from being tested.

I have never experienced the issue you describe of it showing 10/10 multiple times in a row. Can you record it happening, and show me your advanced settings?

**Comment by micromalc** [comment]
You obviously understand what is happening, so I don't see why you are asking for a video. The only possible reason would be that you think I'm either hallucinating / making things up for some perverse reason / or an idiot. Either way, good luck with the addon.

**Comment by teelolws** [comment]
I want to see a video of it happening so I can see if I can spot a reason why its happening. Maybe a setting. Maybe interference from another addon. If you don't want my help then thats fine.
