### ISSUE TITLE
[BUG] Mission sorting is broken

### ISSUE THREAD

**Issue by sirzooro** [TLDRMissions/TLDRMissions#571]
One of last few TLDR versions broke mission sorting. This is my configured priority:
1 - Anima
2 - Pet Charms
3 - Gold
4 - Augment Runes
5 - Crafting Materials
6 - Equipment
7 - Reputation Tokens
8 - Runecarving Crafting Currencies

When I tried to simulate missions and pressed Skip on all of them, I got following mission order:
Mission (1/14) - Defiled But Protected (Unlabeled Culture Jars) - p1
Mission (5/14) - Mawsworn Invaders (Soul Cinders, Gold) - p3
Mission (5/14) - A Few Too Many (Crystalline Memory Repository, Gold) - p3
Mission (5/14) - Invasive Action (Polished Pet Charm) - p2
Mission (6/14) - Warden's Wrath (Veiled Augment Rune) - p4
Mission (7/14) - Dangerous Harvest (Hero's Herbalism Cache) - p5
Mission (8/14) - Echo of Aelia (Champion's Herbalism Cache) - p5
Mission (9/14) - Illicit Celebration (Champion's Herbalism Cache) - p5
Mission (10/14) - Backup Brigade (Runetender Headguard) - p6
Mission (11/14) - Flight of Necrorays (Hymnal of the Path) - p6

Notice that mission number is also broken, 5/14 is used 3 times. 

On second try I got different results:

Mission (1/14) - Defiled But Protected (Unlabeled Culture Jars) - p1
Mission (7/14) - Dangerous Harvest (Hero's Herbalism Cache) - p5
Mission (8/14) - Echo of Aelia (Champion's Herbalism Cache) - p5
Mission (8/14) - Invasive Action (Polished Pet Charm) - p2
Mission (9/14) - Illicit Celebration (Champion's Herbalism Cache) - p5
Mission (9/14) - Mawsworn Invaders (Soul Cinders, Gold) - p3
Mission (10/14) - Backup Brigade (Runetender Headguard) - p6
Mission (10/14) - A Few Too Many (Crystalline Memory Repository, Gold) - p3
Mission (10/14) - Warden's Wrath (Veiled Augment Rune) - p4
Mission (11/14) - Flight of Necrorays (Hymnal of the Path) - p6

3rd attempt gave another unique results - Defiled But Protected, Mawsworn Invaders, Illicit Celebration, ...

**Comment by teelolws** [comment]
Let me know if you still have this issue after the next patch.

**Comment by sirzooro** [comment]
Hi,
Reported bug is fixed, thanks for quick fix. However during testing I have found two more bugs:
- missions which exceed global anima limit (configured on Advanded tab) are not excluded when mission list are built. Later they are skipped during simulation, so mission counter sometimes skips some values - e.g. change from 3/8 to 5/8 after Start Mission or Skip is pressed;
- companions selected for missions which were skipped does not return to pool of available companions. As a result simulation can stop on mission 8 of 11 (when 8 companions were initially available) and addon does not try to simulate missions 9-11.

**Comment by teelolws** [comment]
I've got a fix for the global anima limit, but the available followers not being released is working as intended. In this tool of automation, the Skip button is not meant to be used. If you must press that button, the safest option is to de-select the reward and start the calculations again.

**Comment by sirzooro** [comment]
OK, I see. Anyway, thanks for fixing this anima issue.
