### ISSUE TITLE
Add script for button

### ISSUE THREAD

**Issue by Asmadeii** [TLDRMissions/TLDRMissions#572]
**TLDR Version of your idea**
TLDR version: 9.2-132

**Slightly longer version**

**Additional context**
Hello! May be it will possible to add script for TLDR button "start" (left corner). It will be more comfortable to click bind at keyboard 
instead of dragging the mouse on the button. 

Sorry for any mistakes, I hope that you will understand my message

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/190875619-897f8c0e-559d-4c94-a624-8232be3e6c4d.png)

**Comment by Asmadeii** [comment]
> ![изображение](https://user-images.githubusercontent.com/49792789/190875619-897f8c0e-559d-4c94-a624-8232be3e6c4d.png)

I feel like a cretin. thanks for opening my eyes and sry for useless issue
