### ISSUE TITLE
1. Low Anima Breakpoints - 2. Follower numbers

### ISSUE THREAD

**Issue by Shnacks** [TLDRMissions/TLDRMissions#573]
Was wondering if it were possible to implement a setting where if your reservoir anima dips below, say 200, it activates and prioritizes anima missions only until above said breakpoint where it goes back to normal mission settings.

Also, when selecting use Least/Most followers. Is it possible to have a setting that limits/sets the minimum number of followers? Don't want to be sending a follower and 4 troops if I could send 2 followers to save that sweet sweet anima.
Similar to how we can get the minimum number of troops.

**Comment by teelolws** [comment]
I have considered replacing the least/most with a 1-5 followers slider. Your other request could be accomplished with two profiles, where the profile switches based on how much Anima you have. You should be able to achieve that with a simple Weakaura.

With only about a month of life left in this addon, though, I don't intend to add any new features anymore. This would be different if 10.0.0 wasn't slated to break the mission tables.

**Comment by Shnacks** [comment]
Do you have an example weakaura on a notepad? I wouldn't know how to set that up. 
Thanks for the info though. It is late, just thought in case there are future tables in Dragonflight.

**Comment by teelolws** [comment]
The code to change a profile is `TLDRMissions.db:SetProfile("NAME")`

You can check how much anima you have with `C_CurrencyInfo.GetCurrencyInfo(1813)`
