### ISSUE TITLE
[BUG] Campaign is not taken

### ISSUE THREAD

**Issue by Rubyurek** [TLDRMissions/TLDRMissions#574]
I put the campaign at #1 so that would be done first, however that is not considered at all.
![Screenshot_3](https://user-images.githubusercontent.com/42946288/191475252-1e9cbc34-d5c4-47aa-adde-f2e8e980c97d.png)

**Comment by teelolws** [comment]
Show me the two arrows next to Campaign

**Comment by Rubyurek** [comment]
Thought my followers would be sacrificed even though I ranked the campaign #1. All followers are level 41
![4](https://user-images.githubusercontent.com/42946288/191482218-8ec7951a-340b-449f-a579-341951793a14.png)
![3](https://user-images.githubusercontent.com/42946288/191482220-1b3f49e2-4bb8-4a45-a103-b83e1f65305f.png)

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/191482992-94501381-9270-4f38-8e16-3fdcd309523f.png)
These options mean they will be considered *after* everything you've ranked, and they choose the missions with the most experience first.
