### ISSUE TITLE
Toggle to allow level 60 companions 

### ISSUE THREAD

**Issue by jmoliver88** [TLDRMissions/TLDRMissions#575]
**TLDR Version of your idea**
Allow level 60 companions to be sent on missions.

**Slightly longer version**
Currently level 60 companions are just skipped over. It would be great to be able to send them out for rewards, with a preference on anima/gold/exp tokens.  

**Additional context**
Line 481 of guihandlers.lua can be changed to allow 60's on missions, but it follows the basic priority already set up with no regard that they are already 60. 
`if v.status or alreadyUsedFollowers[v.followerID] or (v.level >= 60) then`

**Comment by teelolws** [comment]
Line 481 is in a block of code concerning sending followers to die. Why do you want to send level 60 followers to die?

**Comment by jmoliver88** [comment]
Ah, I misinterpreted the line then. It was the only one that I saw that referenced level 60's and changing it to >60 from >=60, it allowed missions with them. Guess I didn't look at it deep enough, but my desire to send 60's on other missions still stands.

**Comment by teelolws** [comment]
Check your settings. Level 60s only get reserved if:

1. For Bonus Follower XP missions where you have "Special Treatment" enabled
2. For sending followers on anything else for XP
3. For sending followers to die for XP
