### ISSUE TITLE
Feature request: allow setting layer number for Torghast Follower Farm

### ISSUE THREAD

**Issue by sirzooro** [TLDRMissions/TLDRMissions#577]
Rationale: on lower Torghast  layers is is easier to outrun, skip and defeat mobs than on higher layers. It makes sense to recruit followers from layer 1 by queuing for layer 1, then queue for layer to to get followers available on layer 2, and so on up to 5. I propose to extend `/tldr-tff` command to optionally allow passing layer number as an argument, e.g. `/tldr-tff 2`. Repeated use of this command should allow to update layer number.

**Comment by teelolws** [comment]
Yeah okay.
