### ISSUE TITLE
[Potential Blizzard Bug] Starting HP changing to 1HP on return

### ISSUE THREAD

**Issue by stevebeck89** [TLDRMissions/TLDRMissions#588]
### Upload your Character-Specific Saved Variables here

Had to add the `.txt` extension to upload it.

[TLDRMissions.lua.txt](https://github.com/TLDRMissions/TLDRMissions/files/9857039/TLDRMissions.lua.txt)

**Comment by teelolws** [comment]
It looks like you've encountered a bug on Blizzards end. When your followers were sent out, they had between 50% and 90% of their max HP. But when they came back, their starting HP had changed to 1HP.

I haven't seen this before, and there isn't much I can do about random Blizzard bugs unfortunately.
