### ISSUE TITLE
[BUG] Shadowlands Campaign mission doesn't work at all

### ISSUE THREAD

**Issue by jsaue003** [TLDRMissions/TLDRMissions#593]
I often ONLY check off that I want to complete the campaign missions, because I'm trying to complete them on multiple characters, then anything else for XP. However, it doesn't detect campaign missions at all, as shown in the image im including. It skips right over the campaign, or doesn't even detect it, thus not allowing progression on campaign missions 

![image](https://user-images.githubusercontent.com/32148757/198380178-68b07f03-a850-4313-964d-22baaee00c5f.png)

![image](https://user-images.githubusercontent.com/32148757/198380374-fd18c8db-c864-4188-8d7d-8e9f12fb25e3.png)

Also, it says 'successful'. I have 5 lvl 39+ companions at full hp, and tons of anima so I can use the companions on the mission.....

**Comment by teelolws** [comment]
Check your other settings. The campaign mission is level 24. Are your followers lower level? Do you have it set to not use followers that are too low level?

**Comment by jsaue003** [comment]
> Do you have it set to not use followers that are too low level?

Is this a default setting? This might be the issue. Is it possible to complete a higher level mission with lower level companions?

**Comment by teelolws** [comment]
Check the advanced settings. There is a level range. Followers can *usually* complete *most* missions that are about 2 or 3 levels higher than them. But at lower levels, if you have level 60 troops, you can safely increase that slider, as the troops will carry them instead.

![image](https://user-images.githubusercontent.com/49792789/198382218-802547ef-5013-46eb-95b7-41eac26a52e1.png)

The default is, I believe, 3. So if your follower is Level 20, it won't test it on a Level 24 mission. But if it is Level 21, it will.

**Comment by jsaue003** [comment]
Yeah that was the issue. You can close this bug. User error! <3
