### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by Voxxel** [TLDRMissions/TLDRMissions#595]
Hi! 
I don't understand why the addon sends only 1 follower with 4 troops into a bonus XP mission. Logically it must be filled by 5 followers and 0 troops to gain the maximum profit since the XP is per follower and not shared between followers afaik.

Can I set it somewhere?

**Comment by teelolws** [comment]
Look in the Advanced settings tab.

**Comment by Voxxel** [comment]
Thank you I think I get it.

Also couldn't figure out what does this settings do:
"Don't use followers less than this many levels below the mission level" - I don't understand. Maybe the wording could be more simple or my English understanding is lower than what this sentence requires.

**Comment by teelolws** [comment]
f = your follower's level
m = the mission's level
s = the slider

if f + s < m, it won't try that follower.
if f + s >= m, it will try to send out the mission with that follower.

Its a filter for you to judge how many levels is "too low".

Generally, I think 3 is enough. Sometimes at lower levels, if you have level 60 troops, it can go closer to 20.

**Comment by Voxxel** [comment]
thank you!
This filter is listed right under the XP mission exclusions so it's for XP missions exclusively, or all missions, or only for non-XP missions exclusively?

**Comment by teelolws** [comment]
Ahh that one is unrelated to the XP missions. Its just a global XP filter for everything, including XP missions.

**Comment by Voxxel** [comment]
Ok, thank you very much for the help! It's a pretty nice addon to eliminate the time the missions required to do. Especially useful for players with dozens of alts. Thank you for this masterpiece!

**Comment by Voxxel** [comment]
For an idea, I'd love to have an option to entirely skipping the low, 3000xp item missions because it's totally not worth any effort.

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/199192874-e2e62c24-bb3a-4490-a521-f5e5c438962e.png)

Untick "Uncommon".

**Comment by Voxxel** [comment]
Oh well. So professional! <3
