### ISSUE TITLE
Make button under big red "TL;DR" bigger ;)

### ISSUE THREAD

**Issue by Unplayed** [TLDRMissions/TLDRMissions#597]
**TLDR Version of your idea**
TLDR version: 10.0-003

On 4K monitors new second button is very small. Can you make it same size as "TL;DR" button and place it on right side of it? On my monitor it is only 2 millimeters high.
![изображение](https://user-images.githubusercontent.com/43932588/198832219-07b116c3-00aa-47ed-9d05-9c9457e41d93.png)

**Comment by teelolws** [comment]
When I added that button, I received a lot of negative feedback about those buttons being **too big**.

The code to move it to the right of the other button is:

`TLDRMissionsShortcutButton:ClearAllPoints() TLDRMissionsShortcutButton:SetPoint("LEFT", TLDRMissionsToggleButton, "RIGHT")`

To make them both full size:

`TLDRMissionsShortcutButton:SetHeight(40) TLDRMissionsToggleButton:SetHeight(40)`

![image](https://user-images.githubusercontent.com/49792789/198847801-ae17b029-aca1-42c2-9ab7-e05e0f4bbee0.png)

You should be able to slot that code into an addon or weakaura or some other method of running custom code on login.
