### ISSUE TITLE
[BUG]: Augment rune mission ignored.

### ISSUE THREAD

**Issue by Voxxel** [TLDRMissions/TLDRMissions#598]
I set Augment Rune missions to do task but the addon failed to include the mission called "On Wings of Ferocity" which actually rewards 7x Augment Runes and some Soul Cinders. The addon says: No more missions matching my conditions.

**Comment by teelolws** [comment]
You probably have Runecarver Red X'ed. Exclusions have priority over Inclusions.

**Comment by Voxxel** [comment]
It was, thank you. Didn't know that. Hope this report reaches people with the same problem.
