### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by SpeedLancer** [TLDRMissions/TLDRMissions#603]
TLDR has stopped working properly with my Venthyr character. It will begin calculating, then display the first mission with no troops or companions filled in, Simulations showing as zero. This happened frequently before DF launch, but was remedied with a reload, however this no longer works.

I've tried deleting the profile, and it does process correctly with the default setting, But as soon as I change any single Advanced option, it once again fails.

In all the attempts I've made, ticking the Special Treatment for XP Missions option causes the failure most often.

**Comment by teelolws** [comment]
Can you make sure errors are turned on and tell me if you get any errors when this happens:
/console scriptErrors 1

Or check your bugsack/buggrabber if you're running one of them.

**Comment by SpeedLancer** [comment]
Sorry for taking so long to get back. Real Life kept me away from the game.

Installed buggrabber and bugsack, but I haven't been able to replicate the problem. The only error I can get is a calculation taking too long, and a reload enabled me to run calculations again. 

If it happens again in future, I'll report back.
