### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by tommy610** [TLDRMissions/TLDRMissions#604]
### Copy/paste the Lua error here

11x TLDRMissions/profiles.lua:469: attempt to call method 'CreateFromItemID' (a nil value)
[string "@TLDRMissions/profiles.lua"]:469: in function `RefreshProfile'
[string "@TLDRMissions/events.lua"]:98: in function <TLDRMissions/events.lua:85>

Locals:
self = <table> {
 createWorkBatch = <function> defined @TLDRMissions/workhandler.lua:100
 TestFirstTenFollowersPlusTroops = <function> defined @TLDRMissions/testing.lua:49
 reputationCurrencyIDs = <table> {
 }
 updateRewards = <function> defined @TLDRMissions/guihandlers.lua:28
 craftingCacheCategories = <table> {
 }
 getFrontEnemies = <function> defined @TLDRMissions/targetting.lua:434
 logSentMission = <function> defined @TLDRMissions/logging.lua:10
 isCurrentWorkBatchEmpty = <function> defined @TLDRMissions/workhandler.lua:119
 craftingCacheQualities = <table> {
 }
 getAllEnemies = <function> defined @TLDRMissions/targetting.lua:542
 unpauseWorker = <function> defined @TLDRMissions/workhandler.lua:92
 setResultCacheGuaranteedFailure = <function> defined @TLDRMissions/caching.lua:94
 getAdjacentAlliesOrAllAllies = <function> defined @TLDRMissions/targetting.lua:392
 ProfileChanged = <function> defined @TLDRMissions/profiles.lua:512
 additionWithErrors = <function> defined @TLDRMissions/matherrors.lua:93
 LibStub = <table> {
 }
 sortFollowers = <function> defined @TLDRMissions/combinations.lua:120
 GetAllMissionsMatchingFilter = <function> defined @TLDRMissions/missions.lua:201
 sanctumFeatureItems = <table> {
 }
 getBackEnemies = <function> defined @TLDRMissions/targetting.lua:475
 getLineEnemies = <function> defined @TLDRMissions/targetting.lua:215
 isResultCacheGuaranteedFailure = <function> defined @TLDRMissions/caching.lua:77
 SimulateFromLog = <function> defined @TLDRMissions/simulation.lua:1408
 spellsDB = <table> {
 }
 getPseudorandomMawswornStrength = <function> defined @TLDRMissions/targetting.lua:636
 runecarverCurrencyIDs = <table> {
 }
 GUI = TLDRMissionsFrame {
 }
 getCleaveEnemies = <function> defined @TLDRMissions/targetting.lua:67
 getClosestEnemy = <function> defined @TLDRMissions/targetting.lua:23
 arrangeAllFollowerPositions = <function> defined @TLDRMissions/combinations.lua:40
 getAllAllies = <function> defined @TLDRMissions/targetting.lua:530
 Simulate = <function> defined @TLDRMissions/simulation.lua:1286
 db = <table> {
 }
 RefreshProfile = <function> defined @TLDRMissions/profiles.lua:8
 getFurthestEnemy = <function> defined @TLDRMissions/targetting.lua:148
 C_Garrison_GetFollowerAutoCombatStats = <function> defined @TLDRMissions/caching.lua:262
 setResultCacheCombinationKnown = <function> defined @TLDRMissions/caching.lua:207
 setResultCacheCombinationUnknown = <function> defined @TLDRMissions/caching.lua:173
 isResultCacheCombinationKnown = <function> defined @TLDRMissions/caching.lua:128
 GetRunecarverMissions = <function> defined @TLDRMissions/missions.lua:408
 C_Garrison_GetFollowerInfo = <function> defined @TLDRMissions/caching.lua:6
 getPseudorandomLashOut = <function> defined @TLDRMissions/targetting.lua:893
 followerXPItemIDs = <table> {
 }
 getConeEnemies = <function> defined @TLDRMissions/targetting.lua:279
 isWorkerPaused = <function> defined @TLDRMissions/workhandler.lua:96
 GetCraftingCacheMissions = <function> defined @TLDRMissions/missions.lua:374
 garrisonMissionStartedHandler = <function> defined @TLDRMissions/guihandlers.lua:997
 Enums = <table> {
 }
 GetFollowerXPItemMissions = <function> defined @TLDRMissions/missions.lua:261
 arrangeFollowerCombinationsByFewestFollowersPlusTroops = <function> defined @TLDRMissions/combinations.lua:358
 TestExistingMission = <function> defined @TLDRMissions/testing.lua:69

**Comment by teelolws** [comment]
Hi, I think you have another addon causing interference. Can you try it with all other addons turned off, please.

**Comment by tommy610** [comment]
So apparently https://www.curseforge.com/wow/addons/healthstone-auto-macro new update causes all other addons to throw errors. I disable healthstoneautomacro and no more errors.

**Comment by teelolws** [comment]
> commit e22f20afe632e8a9ef8fe91dbfd5e197dd27605d
> Author: Oliver Maus <ollidiemaus@googlemail.com>
> Date:   Thu Dec 22 23:38:44 2022 +0100

>    fixed item naming

Looks like they fixed it about 18 minutes ago. Based on the error, I'm guessing they named a variable `Item` and let it into the global namespace, overwriting Blizzard code. Oops!
