### ISSUE TITLE
[BUG] Other

### ISSUE THREAD

**Issue by blecaplol** [TLDRMissions/TLDRMissions#608]
hi im not sure if this is a bug it just look weird from my hunter's table slimmer
https://gyazo.com/a4d85478950b7274fa064f75b536e7f0

but the rest of my char's mission list look taller like this:
https://gyazo.com/41782a16e7936f3617eb01f0c1ade891

**Comment by teelolws** [comment]
One of them, you have another addon turned on. Probably Venture Plan.

**Comment by teelolws** [comment]
TLDR doesn't do anything to the table like that. You should work out which addon it is. Probably covenant mission helper, or master plan.

**Comment by blecaplol** [comment]
i'm gonna open just to reply. i repeat 1 more time i dont have any other addon except tldrmission. now u can close it again.

**Comment by teelolws** [comment]
Have you tried turning off TLDR Missions, see if it changes?
