### ISSUE TITLE
[BUG] Bugs in /tldr-tff command

### ISSUE THREAD

**Issue by sirzooro** [TLDRMissions/TLDRMissions#609]
When I use `/tldr-tff` command or `/tldr-tff N` with N<=5, addon prints in chat "TLDR-TFF: You have not unlocked Level 6 yet!" when I try to enter Skodus Hall. When I use `/tldr-tff N` with N>=6, addon does not complain, but it also does not work correctly - it enqueues me for layer N+1.

Edit: When I manually select level (e.g. 3 and enter) TLDR monitors my run and trigger instance leave as expected. If I remember correctly, it used to print what it detected in the chat. Now this message is gone.

**Comment by teelolws** [comment]
> If I remember correctly, it used to print what it detected in the chat. Now this message is gone.

It only says the reason if it detects a treasure chest, a follower you already have, or a map that doesn't spawn them. I left out "chat message from follower you can't recruit" as its the most common reason and would spam up your chat box.

**Comment by sirzooro** [comment]
Thanks for quick fix!
