### ISSUE TITLE
[BUG] The window moves back to the wrong position

### ISSUE THREAD

**Issue by Machou** [TLDRMissions/TLDRMissions#612]
Hello,

Since the last update, the **TLDRMissions** window always moves to the left, instead of staying where you asked.

Could you please fix the bug?

Screenshot bad position : ![](https://i.ibb.co/2vsVt2H/bad.jpg)

Screenshot good position : ![](https://i.ibb.co/XpLwrCx/Wo-WScrn-Shot-080823-170426.jpg)

Regards

**Comment by teelolws** [comment]
Got it. Making the addon LoadOnDemand stopped the position being saved in the layout cache.
