### ISSUE TITLE
Allow completion of non-anima missions without anima quest

### ISSUE THREAD

**Issue by sirzooro** [TLDRMissions/TLDRMissions#613]
New option added in https://github.com/TLDRMissions/TLDRMissions/issues/611 is very handy, but it has important downside: it does not allow to complete non-anima mission without weekly anima quest active. Number of available companions is limited so I quickly run of them with option enabled. Please change it or add new sub-option to allow completion of non-anima missions.

**Comment by teelolws** [comment]
Option will now skip over Anima missions if you do now have the weekly Anima quest.

**Comment by sirzooro** [comment]
Thanks!
