### ISSUE TITLE
With "Block completing..." allow to start new missions

### ISSUE THREAD

**Issue by Unplayed** [TLDRMissions/TLDRMissions#614]
"Block completing..." also blocks starting new missions by main button.

If it allows to start them, in Tue/Wed player will have huge amount of ready-to-finish missions to complete weekly quest instantly.

**Comment by teelolws** [comment]
Yeah I'm going to redesign that button to just skip over finishing Anima missions instead. Just haven't had time to work on it yet: https://github.com/TLDRMissions/TLDRMissions/issues/613

I suggest you just don't use the option in the meantime.
