### ISSUE TITLE
[BUG] Anima weekly mode is not correct

### ISSUE THREAD

**Issue by RedSkotina** [TLDRMissions/TLDRMissions#615]
If i have anima quest completed then i cant send new anima missions.  
I have message  'TLDRMissions: Missions not completed - this character does not have a weekly Anima quest!'  

Tested with actual curseforge version: TLDRMissions 10.1-007

**Comment by teelolws** [comment]
Just don't use the option until it is changed: https://github.com/TLDRMissions/TLDRMissions/issues/613
