### ISSUE TITLE
Help with Adventures: Into the Breach

### ISSUE THREAD

**Issue by Machou** [TLDRMissions/TLDRMissions#617]
Hello,

I'm not sure which category I should post this in, so here goes, when I have the high fact missions [Adventures: Into the Breach](https://www.wowhead.com/achievement=14844) pop up, they never get counted and so I have to run them manually.

Which category do these 10 missions belong to?

Regards

**Comment by teelolws** [comment]
If its the ones I think they are, they should be under the Runecarver category.

**Comment by Machou** [comment]
This ? :

!()[https://i.ibb.co/dDnjrpR/Wo-WScrn-Shot-101523-183728.jpg]

**Comment by teelolws** [comment]
Yes. Check the options next to it. Some reward Stygia, some soul ash. Depends which ones you have selected.

**Comment by Machou** [comment]
> Yes. Check the options next to it. Some reward Stygia, some soul ash. Depends which ones you have selected.

i will try thanks
