### ISSUE TITLE
[BUG] Other - Sort of bug, but not really, kinda

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#625]
When all followers are at level 60, the addon keeps waiting for the 1 follower at 0 life to 'recharge to 1 life' which can really take up 1min sometimes, considering that there were a dozen more available and that there is no need to wait for the 'lower level' to receive the exp ideally it should either disregard the 0 life follower(if there are others available) and if no other was capable of doing the misson after the simulations it could retry with that follower which would likely be at 1 life.
Additionally a check box allowing the person to ignore '0 life followers' or not could be a possibility when there are others available.
Or an option to 'auto wait' for the follower to reach 1 life and then simulate.

**Comment by teelolws** [comment]
This was something I tried to fix a long time ago.

I can't start the calculations while you have a "dead" follower because it causes the table to break if I do, forcing a /reload

I can't "wait" for the follower because the addon has no way to detect when it gets to 1HP. All we can do is keep trying and see if its healed yet.

The follower shouldn't ever take longer than 30 seconds to heal. The safest way is to just wait for it - ideally don't sit at the table waiting for a mission to finish!

**Comment by theruan** [comment]
it breaks if u try to calculate using that follower(i guess that's what u tried/meant) i don't see why using other followers to calculate would result in that, i know we can at least send missions with a dead follower(if the one that is dead isn't used).
I got a few tables at upgrade 0 to 1, created like a 100 chars during DF hehe, with the table at 3 i think it takes about 30s, lower than that it can take awhile.

**Comment by theruan** [comment]
As for the wait for the follower, u can run a function that calls itself every 5s or so with C_Timer.After(seconds, callback).
Like if follower life < 1 then function name else TLDRMissionsShortcutButton:Click() for instance.

**Comment by theruan** [comment]
If you want experience missions that wouldn't change by much, because it would be an odd behavior to have the exact same follower to end up 'stuck at 0' for more than 1 day, in fact the worst it could happen would be to be stuck between 2 followers cause in each 'send wave' one would be left back.

This could be a simple option as others btw, not necessarily a fixed behavior, in my case it forced me to wait about 30+ minutes over the past 2 weeks, that's why i decided to hunt down a way to go around that.

What I did was to completely ignore the follower, but i don't care much for xp.
in guihandlers.lua i changed the followerLineup function to this:
`	local info = C_Garrison.GetFollowerAutoCombatStats(follower.followerID) -- moved from under

        if (not follower.status) and (follower.isCollected) and (not(info.currentHealth < 1)) then --(info.currentHealth >= 1) then -- old was if (not follower.status) and (follower.isCollected) then
            table.insert(followerLineup, follower.followerID)
		elseif (not follower.status) and (follower.isCollected) then
		if WeakAuras then
                        WeakAuras.ScanEvents("TLDRMISSIONS_SENT_WITH_IGNORED")
                      end
		end
        --commented section as ignoring/skpping is default behavior but if a DB option is added it should be here and this should be active
		--if info and (info.currentHealth < 1) then
         --   gui.shortcutButton:SetText(FAILED)
        --    gui.FailedCalcLabel:SetText(L["FollowerZeroHPError"])
        --    gui.CalculateButton:SetEnabled(true)
        --    gui.AbortButton:SetEnabled(false)
        --    gui.SkipCalculationButton:SetEnabled(false)
        --    return
        --end
    end `

The code needs cleaning though xD

So far it has been working fine, ignore followers about 5~10 times and a few times the follower wasn't used in the first sent mission but was used later in a next one cause it changed from 0 to 1~2 health.

This could be added as either:
Option to simply ignore 0 health follower with end up msg annoucing it was ignored(like the red messages do under the buttons calc/cancel/skip)
And/Or an option that ignores based on follower level, like if follower equal/above level 30 then it can be ignored.

On a side note, I also added to gui.FailedCalcLabel:SetText(L["MissionsAboveRestrictionsError"]) to make it more 'event complete' :
`if WeakAuras then
                        WeakAuras.ScanEvents("TLDRMISSIONS_SENT_NONE")
end`
To be able to track using weakauras.

Great addon btw.

**Comment by teelolws** [comment]
Added an option to skip over dead followers instead of cancelling calcs. Lmk if it works as I am never in a situation to test this case.
