### ISSUE TITLE
[BUG] Other - Small adjustment to skip

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#626]
When i first wrote I didn't realize the followerLineup at line 747 to 769 was just to measure if there were followers available, had some bugs but couldn't check when i wrote, but now it seems to work fine, so far anyway.

So this is also needed:
From line 874:
                   for _, follower in ipairs(followers) do
                        if (not follower.status) and (not alreadyUsedFollowers[follower.followerID]) and (follower.level < 60) then
                            table.insert(followerLineup, follower.followerID)
                        end
                    end

From line 896:
                        for i = 1, median do
                            if (not followers[i].status) and (not alreadyUsedFollowers[followers[i].followerID]) and (followers[i].level < 60) then
                                table.insert(followerLineup, followers[i].followerID)
                            end
                        end
From line 922:
               for _, follower in ipairs(followers) do
                    if (not follower.status) and (not alreadyUsedFollowers[follower.followerID]) 
                        if (follower.level + gui.LowerBoundLevelRestrictionSlider:GetValue()) >= nextMission.missionScalar then
                            table.insert(followerLineup, follower.followerID)
                        end
                    end
                end 

So ' and (info.currentHealth > 0)' needs to be added to each ' if (not follower.status)' check WITH A 'local info = C_Garrison.GetFollowerAutoCombatStats(follower.followerID)' right before it inside the for loop.

Also, for the sake of preventing precision errors, a bigger value than zero would be wiser, maybe a 30 to 50, not sure what is the margin of error, I had some missions sent with followers at 5 health that failed.

**Comment by teelolws** [comment]
If you had a mission fail that *wasn't meant to fail per the settings* then you should report your combat log per https://github.com/TLDRMissions/TLDRMissions/issues/new?assignees=teelolws&labels=&projects=&template=2issue--a-mission-failed-.yaml&title=%5BBUG%5D+A+mission+failed%21
