### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#627]
### Upload your Character-Specific Saved Variables here

can't believe i didn't find this, I was looking hard inside the main saved variables like an idiot LoL
This mission i can't remember the char, i will likely get more today/tomorrow and will add later.
I'm running troops at 50 to 60 with followers at 10 to 40, most likely this is the reason for the unexpected behavior.
	[2224] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Guardian Kota[2] meleed Panicked Necroray[6][1325HP] for 210 damage.", -- [4]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[6][1136HP] for 189  damage.", -- [5]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[9][1346HP] for 189  damage.", -- [6]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[10][1346HP] for 189  damage.", -- [7]
			"Guardian Kota[2] cast Flashing Arrows at Ancient Necroray[11][4046HP] for 189  damage.", -- [8]
			"Ardenweald Grovetender[0] shot Panicked Necroray[12][1185HP] for 350 damage.", -- [9]
			"Ardenweald Grovetender[3] shot Panicked Necroray[9][996HP] for 350 damage.", -- [10]
			"Ancient Necroray[11] shot Guardian Kota[2][2622HP] for 178 damage.", -- [11]
			"Ancient Necroray[11] cast Heal the Flock on Panicked Necroray[10][1524HP] for 178 healing.", -- [12]
			"Panicked Necroray[6] meleed Guardian Kota[2][2474HP] for 148 damage.", -- [13]
			"Panicked Necroray[6] cast Panic Attack at Panicked Necroray[7][1239HP] for 296  damage.", -- [14]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[3][1252HP] for 148 damage.", -- [15]
			"Panicked Necroray[7] cast Panic Attack at Panicked Necroray[7][943HP] for 296  damage.", -- [16]
			"Panicked Necroray[9] meleed Guardian Kota[2][2326HP] for 148 damage.", -- [17]
			"Panicked Necroray[9] cast Panic Attack at Panicked Necroray[7][647HP] for 296  damage.", -- [18]
			"Panicked Necroray[10] meleed Guardian Kota[2][2178HP] for 148 damage.", -- [19]
			"Panicked Necroray[10] cast Panic Attack at Panicked Necroray[7][351HP] for 296  damage.", -- [20]
			"Panicked Necroray[12] meleed Ardenweald Grovetender[3][1104HP] for 148 damage.", -- [21]
			"Panicked Necroray[12] cast Panic Attack at Panicked Necroray[7][55HP] for 296  damage.", -- [22]
			",", -- [23]
			"Start of round 2", -- [24]
			",", -- [25]
			"Guardian Kota[2] meleed Panicked Necroray[6][926HP] for 210 damage.", -- [26]
			"Ardenweald Grovetender[0] shot Panicked Necroray[12][835HP] for 350 damage.", -- [27]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Guardian Kota[2][2528HP] for 350 healing.", -- [28]
			"Ardenweald Grovetender[3] shot Panicked Necroray[9][646HP] for 350 damage.", -- [29]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Guardian Kota[2][2800HP] for 350 healing.", -- [30]
			"Ancient Necroray[11] shot Guardian Kota[2][2622HP] for 178 damage.", -- [31]
			"Panicked Necroray[10] meleed Guardian Kota[2][2474HP] for 148 damage.", -- [32]
			"Panicked Necroray[12] meleed Ardenweald Grovetender[3][956HP] for 148 damage.", -- [33]
			"Panicked Necroray[6] meleed Guardian Kota[2][2326HP] for 148 damage.", -- [34]
			"Panicked Necroray[9] meleed Guardian Kota[2][2178HP] for 148 damage.", -- [35]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[3][808HP] for 148 damage.", -- [36]
			",", -- [37]
			"Start of round 3", -- [38]
			",", -- [39]
			"Guardian Kota[2] meleed Panicked Necroray[6][716HP] for 210 damage.", -- [40]
			"Ardenweald Grovetender[0] shot Panicked Necroray[12][485HP] for 350 damage.", -- [41]
			"Ardenweald Grovetender[3] shot Panicked Necroray[9][296HP] for 350 damage.", -- [42]
			"Ancient Necroray[11] shot Guardian Kota[2][2000HP] for 178 damage.", -- [43]
			"Panicked Necroray[10] meleed Guardian Kota[2][1852HP] for 148 damage.", -- [44]
			"Panicked Necroray[6] meleed Guardian Kota[2][1704HP] for 148 damage.", -- [45]
			"Panicked Necroray[12] meleed Ardenweald Grovetender[3][660HP] for 148 damage.", -- [46]
			"Panicked Necroray[9] meleed Guardian Kota[2][1556HP] for 148 damage.", -- [47]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[3][512HP] for 148 damage.", -- [48]
			",", -- [49]
			"Start of round 4", -- [50]
			",", -- [51]
			"Guardian Kota[2] meleed Panicked Necroray[6][506HP] for 210 damage.", -- [52]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[6][317HP] for 189  damage.", -- [53]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[9][107HP] for 189  damage.", -- [54]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[10][1335HP] for 189  damage.", -- [55]
			"Guardian Kota[2] cast Flashing Arrows at Ancient Necroray[11][3857HP] for 189  damage.", -- [56]
			"Ardenweald Grovetender[0] shot Panicked Necroray[12][135HP] for 350 damage.", -- [57]
			"Ardenweald Grovetender[3] shot Panicked Necroray[9][0HP] for 350 damage.", -- [58]
			"Ardenweald Grovetender[3] killed Panicked Necroray[9][0HP].", -- [59]
			"Ancient Necroray[11] shot Guardian Kota[2][1378HP] for 178 damage.", -- [60]
			"Panicked Necroray[10] meleed Guardian Kota[2][1230HP] for 148 damage.", -- [61]
			"Panicked Necroray[6] meleed Guardian Kota[2][1082HP] for 148 damage.", -- [62]
			"Panicked Necroray[12] meleed Ardenweald Grovetender[3][364HP] for 148 damage.", -- [63]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[3][216HP] for 148 damage.", -- [64]
			",", -- [65]
			"Start of round 5", -- [66]
			",", -- [67]
			"Ardenweald Grovetender[0] shot Panicked Necroray[12][0HP] for 350 damage.", -- [68]
			"Ardenweald Grovetender[0] killed Panicked Necroray[12][0HP].", -- [69]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Guardian Kota[2][1432HP] for 350 healing.", -- [70]
			"Guardian Kota[2] meleed Panicked Necroray[6][107HP] for 210 damage.", -- [71]
			"Ardenweald Grovetender[3] shot Panicked Necroray[10][985HP] for 350 damage.", -- [72]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Guardian Kota[2][1782HP] for 350 healing.", -- [73]
			"Ancient Necroray[11] shot Guardian Kota[2][1604HP] for 178 damage.", -- [74]
			"Ancient Necroray[11] cast Heal the Flock on Panicked Necroray[10][1163HP] for 178 healing.", -- [75]
			"Panicked Necroray[10] meleed Guardian Kota[2][1456HP] for 148 damage.", -- [76]
			"Panicked Necroray[6] meleed Guardian Kota[2][1308HP] for 148 damage.", -- [77]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[3][68HP] for 148 damage.", -- [78]
			",", -- [79]
			"Start of round 6", -- [80]
			",", -- [81]
			"Ardenweald Grovetender[0] shot Ancient Necroray[11][3507HP] for 350 damage.", -- [82]
			"Guardian Kota[2] meleed Panicked Necroray[6][0HP] for 210 damage.", -- [83]
			"Guardian Kota[2] killed Panicked Necroray[6][0HP].", -- [84]
			"Ardenweald Grovetender[3] shot Panicked Necroray[10][813HP] for 350 damage.", -- [85]
			"Ancient Necroray[11] shot Guardian Kota[2][1130HP] for 178 damage.", -- [86]
			"Panicked Necroray[10] meleed Guardian Kota[2][982HP] for 148 damage.", -- [87]
			"Panicked Necroray[10] cast Panic Attack at Guardian Kota[2][686HP] for 296  damage.", -- [88]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[3][0HP] for 148 damage.", -- [89]
			"Panicked Necroray[7] killed Ardenweald Grovetender[3][0HP].", -- [90]
			"Panicked Necroray[7] cast Panic Attack at Guardian Kota[2][390HP] for 296  damage.", -- [91]
			",", -- [92]
			"Start of round 7", -- [93]
			",", -- [94]
			"Ardenweald Grovetender[0] shot Ancient Necroray[11][3157HP] for 350 damage.", -- [95]
			"Guardian Kota[2] meleed Panicked Necroray[10][603HP] for 210 damage.", -- [96]
			"Guardian Kota[2] cast Flashing Arrows at Panicked Necroray[10][414HP] for 189  damage.", -- [97]
			"Ancient Necroray[11] shot Guardian Kota[2][212HP] for 178 damage.", -- [98]
			"Panicked Necroray[10] meleed Guardian Kota[2][64HP] for 148 damage.", -- [99]
			"Panicked Necroray[7] meleed Guardian Kota[2][0HP] for 148 damage.", -- [100]
			"Panicked Necroray[7] killed Guardian Kota[2][0HP].", -- [101]
			",", -- [102]
			"Start of round 8", -- [103]
			",", -- [104]
			"Ardenweald Grovetender[0] shot Ancient Necroray[11][2807HP] for 350 damage.", -- [105]
			"Ancient Necroray[11] shot Ardenweald Grovetender[0][1222HP] for 178 damage.", -- [106]
			"Panicked Necroray[10] meleed Ardenweald Grovetender[0][1074HP] for 148 damage.", -- [107]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[0][926HP] for 148 damage.", -- [108]
			",", -- [109]
			"Start of round 9", -- [110]
			",", -- [111]
			"Ardenweald Grovetender[0] shot Ancient Necroray[11][2457HP] for 350 damage.", -- [112]
			"Ardenweald Grovetender[0] cast Revitalizing Vines on Ardenweald Grovetender[0][1276HP] for 350 healing.", -- [113]
			"Ancient Necroray[11] shot Ardenweald Grovetender[0][1098HP] for 178 damage.", -- [114]
			"Ancient Necroray[11] cast Heal the Flock on Panicked Necroray[10][592HP] for 178 healing.", -- [115]
			"Panicked Necroray[10] meleed Ardenweald Grovetender[0][950HP] for 148 damage.", -- [116]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[0][802HP] for 148 damage.", -- [117]
			",", -- [118]
			"Start of round 10", -- [119]
			",", -- [120]
			"Ardenweald Grovetender[0] shot Ancient Necroray[11][2107HP] for 350 damage.", -- [121]
			"Ancient Necroray[11] shot Ardenweald Grovetender[0][624HP] for 178 damage.", -- [122]
			"Panicked Necroray[10] meleed Ardenweald Grovetender[0][476HP] for 148 damage.", -- [123]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[0][328HP] for 148 damage.", -- [124]
			",", -- [125]
			"Start of round 11", -- [126]
			",", -- [127]
			"Ardenweald Grovetender[0] shot Ancient Necroray[11][1757HP] for 350 damage.", -- [128]
			"Ancient Necroray[11] shot Ardenweald Grovetender[0][150HP] for 178 damage.", -- [129]
			"Panicked Necroray[10] meleed Ardenweald Grovetender[0][2HP] for 148 damage.", -- [130]
			"Panicked Necroray[10] cast Panic Attack at Ancient Necroray[11][1461HP] for 296  damage.", -- [131]
			"Panicked Necroray[7] meleed Ardenweald Grovetender[0][0HP] for 148 damage.", -- [132]
			"Panicked Necroray[7] killed Ardenweald Grovetender[0][0HP].", -- [133]
		},
		["missionID"] = 2224,
		["sentTime"] = 1702273089,
		["finalHealth"] = {
			[0] = 0,
			[7] = 55,
			[2] = 0,
			[9] = 0,
			[10] = 592,
			[3] = 0,
			[6] = 0,
			[12] = 0,
			[11] = 1461,
		},
		["followers"] = {
			{
				["maxHP"] = 2800,
				["spells"] = {
					{
						["duration"] = 1,
						["cooldown"] = 2,
						["spellID"] = 97,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 2,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["predictedFinalHP"] = -90,
				["name"] = "Guardian Kota",
				["levelXP"] = 1,
				["baseAttack"] = 210,
				["level"] = 60,
				["HP"] = 2800,
				["followerID"] = "0x000000002E72A349",
			}, -- [1]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 3,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["predictedFinalHP"] = -80,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["level"] = 60,
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [2]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 0,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["predictedFinalHP"] = 114,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["level"] = 60,
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [3]
		},
		["addonVersion"] = "10.2-008",
		["enemies"] = {
			{
				["maxHP"] = 1535,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Panicked Necroray",
				["boardIndex"] = 6,
				["baseAttack"] = 148,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 212,
					}, -- [1]
				},
				["HP"] = 1535,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 1535,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Panicked Necroray",
				["boardIndex"] = 7,
				["baseAttack"] = 148,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 212,
					}, -- [1]
				},
				["HP"] = 1535,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 1535,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Panicked Necroray",
				["boardIndex"] = 9,
				["baseAttack"] = 148,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 212,
					}, -- [1]
				},
				["HP"] = 1535,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 1535,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Panicked Necroray",
				["boardIndex"] = 12,
				["baseAttack"] = 148,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 212,
					}, -- [1]
				},
				["HP"] = 1535,
				["followerID"] = -4,
			}, -- [4]
			{
				["maxHP"] = 1535,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Panicked Necroray",
				["boardIndex"] = 10,
				["baseAttack"] = 148,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 4,
						["spellID"] = 212,
					}, -- [1]
				},
				["HP"] = 1535,
				["followerID"] = -5,
			}, -- [5]
			{
				["maxHP"] = 4235,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["name"] = "Ancient Necroray",
				["boardIndex"] = 11,
				["baseAttack"] = 178,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 213,
					}, -- [1]
				},
				["HP"] = 4235,
				["followerID"] = -6,
			}, -- [6]
		},
	},

**Comment by teelolws** [comment]
Mission 2224 was a persistent nuisance all through Shadowlands that has about 10,000 different combinations and I probably never will truly "solve" that one. It has a crazy amount of randomness compared to all the other ones.

**Comment by theruan** [comment]
2221 had an error too, but i can't remember in which character it was.
