### ISSUE TITLE
Option to block doing or completing reputation missions IF the char is close or at cap in paragon.

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#628]
I did some modifications myself to try to handle this, isn't clean, could be done with a for loop, but:
In missions.lua
After line 345 `for _, reward in pairs(rewards) do
            if reward.currencyID and reputationCurrencyIDs[reward.currencyID] and addon.db.profile.reputations[reward.currencyID] then`

`				if reward.currencyID == 1804 then -- Ascended
					local current, threshold, _, hasRewardPending = C_Reputation.GetFactionParagonInfo(2407)
					if  not hasRewardPending or hasRewardPending == nil then
						table.insert(missionLineup, mission)
						if hasRewardPending then
							if threshold - mod(current, threshold) > reward.quantity then
								table.insert(missionLineup, mission)
							else
							print("NOT Sent mission:", mission, "reaching paragon cap")	-- debugging
							end
						end
					end
				elseif  reward.currencyID == 1805 then -- Undying Army
					local current, threshold, _, hasRewardPending = C_Reputation.GetFactionParagonInfo(2410)
					if  not hasRewardPending or hasRewardPending == nil then
						table.insert(missionLineup, mission)
						if hasRewardPending then
							if threshold - mod(current, threshold) > reward.quantity then
							table.insert(missionLineup, mission)
							else
							print("NOT Sent mission:", mission, "reaching paragon cap")	-- debugging
							end
						end
					end
				elseif  reward.currencyID == 1806 then -- Wild Hunt
					local current, threshold, _, hasRewardPending = C_Reputation.GetFactionParagonInfo(2465)

					if  not hasRewardPending or hasRewardPending == nil then
						table.insert(missionLineup, mission)
						if hasRewardPending then
							if threshold - mod(current, threshold) > reward.quantity then
							table.insert(missionLineup, mission)
							else
							print("NOT Sent mission:", mission, "reaching paragon cap")	-- debugging
							end
						end
					end
				elseif  reward.currencyID == 1807 then  --Court
					local current, threshold, _, hasRewardPending = C_Reputation.GetFactionParagonInfo(2413)
					if  not hasRewardPending or hasRewardPending == nil then
						table.insert(missionLineup, mission)
						if hasRewardPending then
							if threshold - mod(current, threshold) > reward.quantity then
							table.insert(missionLineup, mission)
							else
							print("NOT Sent mission:", mission, "reaching paragon cap")	-- debugging
							end
						end
					end
				
				end`				

This wouldn't allow missions with reputation IF the reputation is nearly full(paragon cap after one is pending)
(if the gap* is smaller than the reward from the mission)

Exception would happen only if one of the reputations isn't at cap for missions like "Joint Operations" in that case a bit of rep could be wasted.

Ideally i would put this as a "do not send if nearly at cap" to avoid keeping a follower stuck, but people might think different, so an option to not send and another to not complete after one was sent, would be nice.

**Comment by teelolws** [comment]
I'll make a public interface so you can code this in a separate addon, same with your solution for https://github.com/TLDRMissions/TLDRMissions/issues/621

**Comment by teelolws** [comment]
See the new publicAPI.lua file for usage instructions. Make a separate addon, call the :Hook functions, change the mission list or set up blocks using your own custom logic.
