### ISSUE TITLE
[BUG] A mission failed! - 2277 - Invasive Action

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#629]
### Upload your Character-Specific Saved Variables here

	[2277] = {
		["combatLog"] = {
			",", -- [1]
			"Start of round 1", -- [2]
			",", -- [3]
			"Ardenweald Grovetender[1] shot Invasive Creeper[5][1400HP] for 350 damage.", -- [4]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Elwyn[0][669HP] for 350 healing.", -- [5]
			"Ardenweald Grovetender[3] shot Invasive Creeper[5][1050HP] for 350 damage.", -- [6]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Elwyn[0][1019HP] for 350 healing.", -- [7]
			"Ardenweald Grovetender[4] shot Invasive Creeper[5][700HP] for 350 damage.", -- [8]
			"Elwyn[0] shot Invasive Creeper[5][420HP] for 280 damage.", -- [9]
			"Elwyn[0] applied Arcane Empowerment to Ardenweald Grovetender[3][1400HP].", -- [10]
			"Elwyn[0] applied Arcane Empowerment to Ardenweald Grovetender[3][1568HP].", -- [11]
			"Ingra Krazic[6] meleed Ardenweald Grovetender[3][1413HP] for 155 damage.", -- [12]
			"Ingra Krazic[6] cast Viscous Sweep at Ardenweald Grovetender[3][1320HP] for 93  damage.", -- [13]
			"Ingra Krazic[6] applied Viscous Sweep to Ardenweald Grovetender[3][1320HP].", -- [14]
			"Invasive Creeper[5] meleed Elwyn[0][849HP] for 170 damage.", -- [15]
			"Invasive Creeper[5] cast Drust Claws at Ardenweald Grovetender[3][1162HP] for 158  damage.", -- [16]
			"Invasive Creeper[5] cast Drust Claws at Ardenweald Grovetender[4][1273HP] for 127  damage.", -- [17]
			"Invasive Creeper[7] meleed Ardenweald Grovetender[3][950HP] for 212 damage.", -- [18]
			"Invasive Creeper[7] cast Drust Claws at Ardenweald Grovetender[3][792HP] for 158  damage.", -- [19]
			"Invasive Creeper[7] cast Drust Claws at Ardenweald Grovetender[4][1146HP] for 127  damage.", -- [20]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[4][976HP] for 170 damage.", -- [21]
			"Invasive Creeper[8] cast Drust Claws at Ardenweald Grovetender[3][634HP] for 158  damage.", -- [22]
			"Invasive Creeper[8] cast Drust Claws at Ardenweald Grovetender[4][849HP] for 127  damage.", -- [23]
			"Invasive Lasher[10] shot Ardenweald Grovetender[1][1210HP] for 190 damage.", -- [24]
			",", -- [25]
			"Start of round 2", -- [26]
			",", -- [27]
			"Ardenweald Grovetender[1] shot Invasive Creeper[5][70HP] for 350 damage.", -- [28]
			"Elwyn[0] shot Invasive Creeper[5][0HP] for 280 damage.", -- [29]
			"Elwyn[0] killed Invasive Creeper[5][0HP].", -- [30]
			"Ardenweald Grovetender[4] shot Invasive Lasher[10][900HP] for 350 damage.", -- [31]
			"Ardenweald Grovetender[4] cast Revitalizing Vines on Ardenweald Grovetender[3][984HP] for 350 healing.", -- [32]
			"Ardenweald Grovetender[3] shot Invasive Creeper[8][1288HP] for 462 damage.", -- [33]
			"Ingra Krazic[6] meleed Ardenweald Grovetender[3][791HP] for 193 damage.", -- [34]
			"Invasive Creeper[7] meleed Ardenweald Grovetender[3][579HP] for 212 damage.", -- [35]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[4][679HP] for 170 damage.", -- [36]
			"Invasive Lasher[10] shot Ardenweald Grovetender[1][1020HP] for 190 damage.", -- [37]
			",", -- [38]
			"Start of round 3", -- [39]
			",", -- [40]
			"Ardenweald Grovetender[1] shot Invasive Lasher[10][550HP] for 350 damage.", -- [41]
			"Elwyn[0] shot Ingra Krazic[6][2470HP] for 280 damage.", -- [42]
			"Ardenweald Grovetender[4] shot Invasive Lasher[10][200HP] for 350 damage.", -- [43]
			"Ardenweald Grovetender[3] shot Invasive Creeper[8][826HP] for 462 damage.", -- [44]
			"Ingra Krazic[6] removed Viscous Sweep from Ardenweald Grovetender[3][579HP].", -- [45]
			"Ingra Krazic[6] meleed Ardenweald Grovetender[3][424HP] for 155 damage.", -- [46]
			"Invasive Creeper[7] meleed Ardenweald Grovetender[3][254HP] for 170 damage.", -- [47]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[4][509HP] for 170 damage.", -- [48]
			"Invasive Lasher[10] shot Ardenweald Grovetender[1][830HP] for 190 damage.", -- [49]
			"Invasive Lasher[10] applied Drust Thorns to Ingra Krazic[6][2470HP].", -- [50]
			"Invasive Lasher[10] applied Drust Thorns to Invasive Creeper[7][1750HP].", -- [51]
			"Invasive Lasher[10] applied Drust Thorns to Invasive Creeper[8][826HP].", -- [52]
			",", -- [53]
			"Start of round 4", -- [54]
			",", -- [55]
			"Elwyn[0] removed Arcane Empowerment from Ardenweald Grovetender[3][254HP].", -- [56]
			"Elwyn[0] removed Arcane Empowerment from Ardenweald Grovetender[3][254HP].", -- [57]
			"Elwyn[0] shot Ingra Krazic[6][2190HP] for 280 damage.", -- [58]
			"Ingra Krazic[6] cast Drust Thorns at Elwyn[0][694HP] for 155  damage.", -- [59]
			"Ardenweald Grovetender[1] shot Invasive Lasher[10][0HP] for 350 damage.", -- [60]
			"Ardenweald Grovetender[1] killed Invasive Lasher[10][0HP].", -- [61]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Elwyn[0][1044HP] for 350 healing.", -- [62]
			"Ardenweald Grovetender[4] shot Ingra Krazic[6][1840HP] for 350 damage.", -- [63]
			"Ingra Krazic[6] cast Drust Thorns at Ardenweald Grovetender[4][354HP] for 155  damage.", -- [64]
			"Ardenweald Grovetender[3] shot Invasive Creeper[8][476HP] for 350 damage.", -- [65]
			"Invasive Creeper[8] cast Drust Thorns at Ardenweald Grovetender[3][84HP] for 170  damage.", -- [66]
			"Ardenweald Grovetender[3] cast Revitalizing Vines on Elwyn[0][1394HP] for 350 healing.", -- [67]
			"Ingra Krazic[6] meleed Ardenweald Grovetender[3][0HP] for 155 damage.", -- [68]
			"Ingra Krazic[6] killed Ardenweald Grovetender[3][0HP].", -- [69]
			"Invasive Creeper[7] meleed Ardenweald Grovetender[4][184HP] for 170 damage.", -- [70]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[4][14HP] for 170 damage.", -- [71]
			",", -- [72]
			"Start of round 5", -- [73]
			",", -- [74]
			"Elwyn[0] shot Ingra Krazic[6][1560HP] for 280 damage.", -- [75]
			"Ingra Krazic[6] cast Drust Thorns at Elwyn[0][1239HP] for 155  damage.", -- [76]
			"Elwyn[0] applied Arcane Empowerment to Ardenweald Grovetender[1][830HP].", -- [77]
			"Elwyn[0] applied Arcane Empowerment to Ardenweald Grovetender[1][998HP].", -- [78]
			"Ardenweald Grovetender[1] shot Ingra Krazic[6][1098HP] for 462 damage.", -- [79]
			"Ingra Krazic[6] cast Drust Thorns at Ardenweald Grovetender[1][843HP] for 155  damage.", -- [80]
			"Ardenweald Grovetender[4] shot Ingra Krazic[6][748HP] for 350 damage.", -- [81]
			"Ingra Krazic[6] cast Drust Thorns at Ardenweald Grovetender[4][0HP] for 155  damage.", -- [82]
			"Ingra Krazic[6] killed Ardenweald Grovetender[4][0HP].", -- [83]
			"Ingra Krazic[6] meleed Elwyn[0][1084HP] for 155 damage.", -- [84]
			"Invasive Creeper[7] meleed Elwyn[0][914HP] for 170 damage.", -- [85]
			"Invasive Creeper[7] cast Drust Claws at Elwyn[0][787HP] for 127  damage.", -- [86]
			"Invasive Creeper[7] cast Drust Claws at Ardenweald Grovetender[1][716HP] for 127  damage.", -- [87]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[1][546HP] for 170 damage.", -- [88]
			"Invasive Creeper[8] cast Drust Claws at Elwyn[0][660HP] for 127  damage.", -- [89]
			"Invasive Creeper[8] cast Drust Claws at Ardenweald Grovetender[1][419HP] for 127  damage.", -- [90]
			",", -- [91]
			"Start of round 6", -- [92]
			",", -- [93]
			"Elwyn[0] shot Ingra Krazic[6][468HP] for 280 damage.", -- [94]
			"Ingra Krazic[6] cast Drust Thorns at Elwyn[0][505HP] for 155  damage.", -- [95]
			"Ardenweald Grovetender[1] shot Ingra Krazic[6][6HP] for 462 damage.", -- [96]
			"Ingra Krazic[6] cast Drust Thorns at Ardenweald Grovetender[1][264HP] for 155  damage.", -- [97]
			"Invasive Creeper[7] meleed Elwyn[0][335HP] for 170 damage.", -- [98]
			"Ingra Krazic[6] meleed Elwyn[0][180HP] for 155 damage.", -- [99]
			"Ingra Krazic[6] cast Viscous Sweep at Elwyn[0][87HP] for 93  damage.", -- [100]
			"Ingra Krazic[6] applied Viscous Sweep to Elwyn[0][87HP].", -- [101]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[1][94HP] for 170 damage.", -- [102]
			"Invasive Lasher[10] removed Drust Thorns from Ingra Krazic[6][6HP].", -- [103]
			"Invasive Lasher[10] removed Drust Thorns from Invasive Creeper[7][1750HP].", -- [104]
			"Invasive Lasher[10] removed Drust Thorns from Invasive Creeper[8][476HP].", -- [105]
			",", -- [106]
			"Start of round 7", -- [107]
			",", -- [108]
			"Ardenweald Grovetender[1] shot Ingra Krazic[6][0HP] for 462 damage.", -- [109]
			"Ardenweald Grovetender[1] killed Ingra Krazic[6][0HP].", -- [110]
			"Ardenweald Grovetender[1] cast Revitalizing Vines on Elwyn[0][437HP] for 350 healing.", -- [111]
			"Elwyn[0] shot Invasive Creeper[7][1470HP] for 280 damage.", -- [112]
			"Invasive Creeper[7] meleed Elwyn[0][225HP] for 212 damage.", -- [113]
			"Invasive Creeper[8] meleed Ardenweald Grovetender[1][0HP] for 170 damage.", -- [114]
			"Invasive Creeper[8] killed Ardenweald Grovetender[1][0HP].", -- [115]
			",", -- [116]
			"Start of round 8", -- [117]
			",", -- [118]
			"Elwyn[0] shot Invasive Creeper[7][1190HP] for 280 damage.", -- [119]
			"Invasive Creeper[7] meleed Elwyn[0][13HP] for 212 damage.", -- [120]
			"Invasive Creeper[8] meleed Elwyn[0][0HP] for 212 damage.", -- [121]
			"Invasive Creeper[8] killed Elwyn[0][0HP].", -- [122]
		},
		["missionID"] = 2277,
		["followers"] = {
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 3,
				["level"] = 60,
				["predictedFinalHP"] = -71,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [1]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 4,
				["level"] = 60,
				["predictedFinalHP"] = -156,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [2]
			{
				["maxHP"] = 2100,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 3,
						["spellID"] = 306,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 0,
				["level"] = 60,
				["predictedFinalHP"] = -122,
				["name"] = "Elwyn",
				["levelXP"] = 1,
				["baseAttack"] = 280,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 311,
				["followerID"] = "0x00000000297F9595",
			}, -- [3]
			{
				["maxHP"] = 1400,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 2,
						["spellID"] = 71,
					}, -- [1]
				},
				["xp"] = 0,
				["boardIndex"] = 1,
				["level"] = 60,
				["predictedFinalHP"] = 325,
				["name"] = "Ardenweald Grovetender",
				["levelXP"] = 1,
				["baseAttack"] = 350,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1400,
				["followerID"] = "0xFFFFFFFFFFFFFFFF",
			}, -- [4]
		},
		["finalHealth"] = {
			0, -- [1]
			nil, -- [2]
			0, -- [3]
			0, -- [4]
			0, -- [5]
			0, -- [6]
			1190, -- [7]
			476, -- [8]
			[0] = 0,
			[10] = 0,
		},
		["sentTime"] = 1702358841,
		["addonVersion"] = "10.2-008",
		["enemies"] = {
			{
				["maxHP"] = 2750,
				["spells"] = {
					{
						["duration"] = 2,
						["cooldown"] = 4,
						["spellID"] = 252,
					}, -- [1]
				},
				["name"] = "Ingra Krazic",
				["boardIndex"] = 6,
				["baseAttack"] = 155,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 2750,
				["followerID"] = -1,
			}, -- [1]
			{
				["maxHP"] = 1750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 253,
					}, -- [1]
				},
				["name"] = "Invasive Creeper",
				["boardIndex"] = 7,
				["baseAttack"] = 170,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1750,
				["followerID"] = -2,
			}, -- [2]
			{
				["maxHP"] = 1750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 253,
					}, -- [1]
				},
				["name"] = "Invasive Creeper",
				["boardIndex"] = 5,
				["baseAttack"] = 170,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1750,
				["followerID"] = -3,
			}, -- [3]
			{
				["maxHP"] = 1750,
				["spells"] = {
					{
						["duration"] = 0,
						["cooldown"] = 3,
						["spellID"] = 253,
					}, -- [1]
				},
				["name"] = "Invasive Creeper",
				["boardIndex"] = 8,
				["baseAttack"] = 170,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 11,
				},
				["HP"] = 1750,
				["followerID"] = -4,
			}, -- [4]
			{
				["maxHP"] = 1250,
				["spells"] = {
					{
						["duration"] = 3,
						["cooldown"] = 3,
						["spellID"] = 254,
					}, -- [1]
				},
				["name"] = "Invasive Lasher",
				["boardIndex"] = 10,
				["baseAttack"] = 190,
				["autoAttack"] = {
					["duration"] = 0,
					["cooldown"] = 0,
					["spellID"] = 15,
				},
				["HP"] = 1250,
				["followerID"] = -5,
			}, -- [5]
		},
	},

**Comment by teelolws** [comment]
Did you wait like 10 minutes or something before sending the mission out? The addon simulated the follower Elwyn with 661HP, but it had 669HP when it was sent out. This threw all the turn order calculations off leading to a mission loss.

**Comment by theruan** [comment]
sometimes i hit calc/send and go afk, if there is no anima when i come back, i deposit the anima and send, so yes, that may have happened.

**Comment by teelolws** [comment]
I can look at adding a verficiation simulation before sending but if it fails you'll have to start over.

**Comment by theruan** [comment]
It's likely just this follower and 1~2 others that give this kind of mess, i remember this was an odd one when i used to manually do the sims in venture plan, maybe add a margin limiting to 2~3 HP, that must be like 2 to 3 mins, or a timer.
Or add an auto recalc if the follower life changes and the person is keeping the interface open(likely afk).

**Comment by teelolws** [comment]
If its taking that long to find a solution then adding a margin is only going to exponentially increase the amount of time it takes to find a solution. Even 3 HP means ^3 more simulations needed.

**Comment by theruan** [comment]
Finding a solution, at least for this mission usually takes like 3s, i go afk cause i play while i work and if the job calls, we answer ^^
except for the known mess break the b... and a corruption one, can't remember the name.
Or maybe add an exception to error reporting, so in cases where the margin of life changed was minimal, so people don't get the message to report u, but receive something like this is a known error where the follower life changed or something.
Doubt anyone would care if it is something known and rare.

**Comment by teelolws** [comment]
If you're sending out missions still you might want to put them on pause. I found a pretty bag bug in yesterdays update that will probably cause a bunch of missions to fail.

**Comment by teelolws** [comment]
Ok in this push https://github.com/TLDRMissions/main/commit/920bc108cf80bfb6bdf15e74f4d5784cc58313c9 it will do one final re-check before sending the mission. If you've got "auto start" enabled it'll just cancel everything and start over. Otherwise, it will print an error and stop.

I don't have the means to test that it works properly so we will have to find out in time.
