### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by GrinningStudios** [TLDRMissions/TLDRMissions#630]
### Copy/paste the Lua error here

Message: Interface/AddOns/TLDRMissions/guihandlers.lua:901: attempt to index global 'follower' (a nil value)
Time: Wed Dec 13 15:18:39 2023
Count: 1
Stack: Interface/AddOns/TLDRMissions/guihandlers.lua:901: attempt to index global 'follower' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/TLDRMissions/guihandlers.lua"]:901: in function `processing'
[string "@Interface/AddOns/TLDRMissions/guihandlers.lua"]:953: in function <Interface/AddOns/TLDRMissions/guihandlers.lua:804>
[string "@Interface/AddOns/TLDRMissions/guihandlers.lua"]:289: in function <Interface/AddOns/TLDRMissions/guihandlers.lua:257>
[string "@Interface/AddOns/TLDRMissions/combinations.lua"]:371: in function <Interface/AddOns/TLDRMissions/combinations.lua:369>
[string "@Interface/AddOns/TLDRMissions/combinations.lua"]:30: in function <Interface/AddOns/TLDRMissions/combinations.lua:15>
[string "@Interface/AddOns/TLDRMissions/simulation.lua"]:1403: in function `callback'
[string "@Interface/AddOns/TLDRMissions/simulation.lua"]:1283: in function <Interface/AddOns/TLDRMissions/simulation.lua:1229>
[string "@Interface/AddOns/TLDRMissions/simulation.lua"]:1402: in function `Simulate'
[string "@Interface/AddOns/TLDRMissions/combinations.lua"]:15: in function `func'
[string "@Interface/AddOns/TLDRMissions/workhandler.lua"]:55: in function <Interface/AddOns/TLDRMissions/workhandler.lua:23>

Locals:

**Comment by teelolws** [comment]
Got it, thanks.
