### ISSUE TITLE
XP item

### ISSUE THREAD

**Issue by jejelol** [TLDRMissions/TLDRMissions#631]
**Additional context**
hi i have a lot of these xp item
https://www.wowhead.com/item=187414/fractal-thoughtbinder
https://www.wowhead.com/item=187415/mind-expanding-prism
i macro it and then each time i click on a companion it pop dialog to confirm using. was wondering if u can make it auto accept the dialog? just some QOL feature.
https://imgur.com/TEmv0lK

thx!

**Comment by teelolws** [comment]
Thats a bit outside the scope of my addon, but I found this weakaura that adds a clickable button for those items and skips the confirmation box:

`!WA:2!TNv(ZXXr1)SEjy8MeklfBfh7kjteeHuSTowDABCk0UALTCjljp7QyhmMDU6DN2A2zg3ZmsAnxjIqI5iby54leoZceUcxl3b(cbbeGaK8YsieiCemvcNvrW)fWR7z2vYorCKQ4hsvERYRMUFVx3V(1V3N3NzDSRVvp5b7EKUhU1sTA0QXPgPIktFsIDrFZBUTtR5WmiSuQ6ZzWCCD3ykl6jpPkZqkNJJLp1vBb1Iotmwf2u6dp18PhFxSfNUqbpI)(Fzx5DEVxa(HvUXe349)upooXz8Cy(7VSgJAKtvZImU7Moi12yNzw0v12GAxuAgg1RKP7MhNPQ7RAjLZ0jOOPVgQfHzEMdt9C9KCkiDqsjhwzt3RinRShQOf1MenPKmX1XJ6ZLFgQTpHzRAD9eMh1X(2QfEQs7y5WoqSyXIl75QQtwFYaML72m99D92Dp9WpzDtD6P5rRNb4(dUaEdjJBhZprkQn1pHwb8pEMjwYNrlwe3JT2bl6XBPQbrlOqHCLDjS9NzYzgF2jt5JdKvdyQjxYZLyznHHxIt7fOrMNy7Nf1MUyT8PhnBU8zZnQCUMIMHrqrYzNjZKtMka3znxl1YeMSqQ2(jQw(MY2QLiEjQeyh5cjQP7yfuYol)igxJPAqd8U5lUIhXQWmoyOrlDMPYLrww1Iw0g2EnvBDthMqeS9Lyo(Q8ZCm28HrVnuf9hzsrECiH7gd8iJgAaHnl6tMvuTPLeMmeSPXHTLY2XMSmr1JK1NjsRwFDd8WZ1ippuW8i6o2gElX1HhOG(tvsLAJ2c9ddSEyqyiyy8X2o3zsz5OAmUgEZJN)2KlfGzKjsHXu92G9Kqw3s1ZJ)ukp6jj8hwc92jPLqVSUwukDysq84XNjEVDpyYaQrnAN2lE9h5aAPtxMfEyiklvKNUIox7YJj7PJ7y8Q6eEELyYjL1cZPmRg(3mgfjUTK9ebQmI04bwwsh2K6tQYeboUnlBugVQO6fzobUrwLf9ZlmfV(apCOGfQU)PLN4Lp9u5gDYAfy4nlgdv9vJhLbpHnwyfx2IFKUOtJrrmT02FCml1HPjp6ytmBw8cCHWR(LdTjSACdAEKs4nQCFD3B39x13rp66DlXUvZ2PgUTCKzKs5445JvsLefEv88jUJAx0ICvv4rJdtn8nVOZeMUmo354hlTSPLZKzQ6Qb(40t7kQxsOH(wbAXeAEobmDIgTKlEiRio7tGY2YLCxVIQfWWuAkt3IOuLNrqdTTg1UGdlmLQTA4J6Km8eEpfgEC5P4XAv)aNA7vPOrzfRFm4cHNpS(yv1d88DkLJSOFRjGxqmyNW2RRJixgolyNDbQlrz5gd53yMP4RHcCz3EhWwo1gXikwgL3bZrvXiARx3s4vyPPWt6ww3J)3RGjt5fAOaxjCvlZh2qUIBl8Hfj2egvpRPZctBRu)SgEApXFshT9q7WlcUIeGeC1YIfT1EHosaV4QtGlPuA(mUTYxtYI417kBewGXFgUCyRWljrndQ3XdSruQ5jjrar3wJIaHybt6uKQVySlRGqfh7o97kHe(HwqY)OjpMKVjXwmb)Zo3j12JAqKy0c(nNvOA)NJQnf03ZGa(hgXpGzlvq1YJSNZskbNzTu3NfCUABBCwJtSkbRmOH5O7SI5jwT9jE6ofkYTfvrKlkADqhdYDFbvXGEuZoZZmhblb4am(Y88rfizii3zdunY)EOlSVGNQphgKyc9SbO3d0gST6iYkhxIxwyB8K1lA5SW4mYjci26LN551B3jhe2gdvIlyz(xJfbKgFj(iE9N8m0fjwv5ddBIV5A8NVHWY(yv4dAI5fNN0UVgZyk08irAMIpqr4d5mP6Zzt88IlmpRa(t84KyhxVwe7wQq8Vc1dHzY7eUmW2QWpvI5IqGWIMgnEJ4xKFEQhfPcOeHRLNWHp3ygR5NDcP91CXBiLdNh)uBX9Q9Xc78IVcriY7M3NwIK3Lr0PC0S4Ux(tthVOhG(R0uw7xJ3ZGMUrpiZxuJtle1STzQrNn30UxQyseSZHdqPlWetnko8mHleEzecuEt1dbkBCrSSq(XXQtAHYW2Rk6Zs4ivPMA6PYeEpZ1PQqr9MxzvI8qepyJJZONu6qbQg8Mcs5YvVPmbHJPNn3Ktmvg3wd9CtvJvseICNg32HwUagFpmt1DPdh9qOx242XDJHN2vtqW9kxRlHWrXImkC3xHY1kUkVP31421ATmrTjZ7BYiiKPLr5Z6804aOzsOihXdb76uBIHKi5Dw6qZJY7xjlgb7Pd4EusXuPgk1fiP2cGwmPn1jrokR70wirkRMW9BfX75QXLzEMgO7y1i22WWuwO8wBFWDbxhNArTgQIS5mRtfDI1jccoO4cxIslkxHYguUALEueQopblQSWI)xk36QguK2NosGPChWxxRuzFukSN2G7tb2nxbHd7s81u99rRQVQLywQjlAJD3zF7AO(2rF9p4W9UJ(gCG(3rFJKSx(x9X)kj)R(3rYE7Di(xdxnSdwjCrnH9Y3grpnXjtbubni)1opSnnFNIyuel9kOIEOske7s3vkTjrFojFhPsQZr4W(s8o5s6wiybNxFY5iLD3mg6rYjzdkvYXoDdrmCBgdxeLuC2QUBouCO9nvsEbEDt87c2Mm12nWh(zkWJehEq3DM2u1UiFlPEsco)OtO3yoIe2duqm2qINNapG7wN1JiLdV4TX52NWHKsRYyucdEy3TS6DFSqBL4fIWdvlAP4JqpsaNwrqZKVTM8OviiRjCaOeuOnOOsdB4lNwF93FYbhqELQxy0AZPprzBzFhT0NaUuS9rcyZDOf2MEXy1W2O2o(s8xpatqNV7MHtbdRv6UA5GOWsmP9UIQHClfsxlZ3RuAgbXzeJ6S9ub((o2TVdP2tJmTckrAobdNllrpGrgvWuiuqosj8O5tAVlSfkVxAI1yJ2DwI)OwwcmcVo76FPA(4lQOf4JUdVyH7mLu1zoTV2wXF7dKmkBChMiBXRZ2h1U8yilk0Oe)hUzInrG9VdPJE0e9WcWCphKyjYG(GupE3JqsTQAj3TyBWZrp4nUehgy39nYidn4Gjo2X6QIHt(WRpfOT2GNWeEKdbZe3DtnywYZEW8kUJyychgocCdrSSHlbrECkXF1J(fS7AWgePEiZFTd4yWReFXmxt14GshqDf4XsIjZiahNUoIECTW2HwGwbsILASDMWl82o12bAdsWWXBY9fMtbSmHsnz4c2TEDGdYM9Paxblw4ekatb8a)vrifcIiJcZdlGmoHfJOBcLHtcVk4vdVM7(cGxRj86E2ticUXv4bb30tcl1GVd86HBoo8gGBbU1ndNkg8gdRJEtMWBog8wuGBloC7XH3AlWBZSa82r(gqf4DiAXaVtf4DbVB4)d5kaVN4W7f3L7a70dVp49dFa4dcFi4dd35nbvJbFem28rHpgA8DbF8Wn4taFs4tbFA4UJbFMyWNf(CWNxb(cOE1IbFXW1)lDnWxUm8vIbFvrBh4RHy3W9e2Nb(gkW30e()xh8TWgjW32eUxt47Ss)cyzt47EUDgGVxu)a47ZxQ7B1DaGFGj8dnHFeC)WpocTg(jRcLg(PWdOapiaWdb15yLpm8Zr8se(e(fnGoHhfEa4xIs(vOspg8R3m8BmHF7QaVGFhRVbgS3(gya433aVQlJmUZuoN(jkz0eVc(dNhQ65wqvdXHQGN4SGOGN8CGJUi4pkWIG)Ka5b(ZnrDG)c8xxnAd83EwbZ8popmZ5Hz4WmAd1xVdn8UwbLr9qJCddEGJmY(SZDEuMNZIYm8)jOmj(FmkZJAEEuMZJYiiZ0)Gjhj5WdUcmJBWKo5kFOdCC3ZcMzD3X5HzEUcmZqdmCsomtIeMooZ5jcw8Fq7oBpl))Qk9zCCdCZZ)r2XDO5V0DGBrMQH4)IIU4)w1RAS0E3lErm9uJpH8bZp(0to50hoJC(zNzFYJowM2fx9sRAPhJQA5u07ORTjhR7PThvxN4635QSRVUw9QKF)udmASMRrxIFsB8F)BHtV4)lHtBD(h(i)Z)`

**Comment by jejelol** [comment]
cool ty!

**Comment by jejelol** [comment]
im sorry to open. i tried the aura but it still requires to click confirmation. may we trouble u some of yr time to implement it? if not really then its fine just gotta suck it up lol! thanks u!

**Comment by teelolws** [comment]
This is the code to skip that confirmation:

`hooksecurefunc("StaticPopup_Show", function(upgradeType) if upgradeType == "CONFIRM_FOLLOWER_UPGRADE" then StaticPopupDialogs["CONFIRM_FOLLOWER_UPGRADE"].OnAccept(StaticPopup1) StaticPopup_Hide("CONFIRM_FOLLOWER_UPGRADE") end end)`

Maybe you could stick it in an addon using https://addon.bool.no/ ? If it doesn't work, you probably have another addon interfering with it. It worked for me!
