### ISSUE TITLE
[BUG] %d instead of level number

### ISSUE THREAD

**Issue by Unplayed** [TLDRMissions/TLDRMissions#632]
![Снимок экрана 2024-01-24 105718](https://github.com/TLDRMissions/TLDRMissions/assets/43932588/21107053-dd7f-4839-918a-83bb96176672)

Version: 10.2-015

ruRU

In the list of uncaught followers, a code is written instead of the floor number where the follower can be caught.

On Russian correct text will be:

"Торгаст, 4-й уровень"

or simpler:

"Торгаст, 4 уровень"

or just:

"4 уровень Торгаста"

**Comment by teelolws** [comment]
That string actually comes from `MYTHIC_PLUS_POWER_LEVEL`, written by the game developers, which I see is slightly different in the ruRU locale.

In English it is: `MYTHIC_PLUS_POWER_LEVEL = "Level %d"`
In Russian it is: `MYTHIC_PLUS_POWER_LEVEL = "%d-й уровень"`

The final string is `C_Map.GetMapInfo(1645) MYTHIC_PLUS_POWER_LEVEL` where the `%d` is supposed to be replaced by a number. So, "Torghast Level 1" and "Торгаст 4-й уровень".

I didn't consider `%d` being at the start of the string and will make adjustments for it.

**Comment by teelolws** [comment]
Does this look right? I can't fix how its positioned a bit too low, so just the text:

![image](https://github.com/TLDRMissions/TLDRMissions/assets/49792789/7cb183a7-c525-4e75-b8aa-fe69f43679d0)

**Comment by Unplayed** [comment]
Yes, variant "Торгаст 4-й уровень" is acceptable.

Thanks ;)
