### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#635]
### Copy/paste the Lua error here

Srry, forgot to describe:
This error happened when I opened the table an attempted to complete missions, some were completed but 1 was kept there and when clicking the finish missions button the error happens.

TLDR 10.2-021

8x ...faceTLDRMissions/Shadowlands/guihandlers.lua:1336: attempt to index upvalue 'AceEvent' (a nil value)
[string "@TLDRMissions/Shadowlands/guihandlers.lua"]:1336: in function <...faceTLDRMissions/Shadowlands/guihandlers.lua:1330>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Done!"
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'AceEvent' (a nil value)"
size = 0
self = TLDRMissionsFrameCompleteMissionsButton {
 SetTextToFit = <function> defined @SharedXML/SecureUIPanelTemplates.lua:244
 usedShortcut = true
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 FitToText = <function> defined @SharedXML/SecureUIPanelTemplates.lua:249
 Text = TLDRMissionsFrameCompleteMissionsButtonText {
 }
 0 = <userdata>
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}
gui = TLDRMissionsFrame {
 AugmentRunesPriorityLabel = TLDRMissionsAugmentRunesPriorityLabel {
 }
 SimulationsPerFrameSlider = TLDRMissionsFrameSimulationsSlider {
 }
 EstimateFollower1Label = TLDRMissionsFrameEstimateFollower1Label {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 ReputationAnimaCostDropDown = TLDRMissionsReputationAnimaCostDropDown {
 }
 RightEdge = Texture {
 }
 CostLabel = TLDRMissionsFrameCostLabel {
 }
 MainTabPanel = TLDRMissionsFrameMainPanel {
 }
 LowTimeWarningLabel = TLDRMissionsFrameLowTimeWarningLabel {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 AnimaPriorityLabel = TLDRMissionsAnimaPriorityLabel {
 }
 SkipMissionButton = TLDRMissionsFrameSkipMissionButton {
 }
 NextMissionLabel = TLDRMissionsFrameNextMissionLabel {
 }
 DurationLowerSlider = TLDRMissionsFrameDurationLowerSlider {
 }
 PetCharmsAnimaCostDropDown = TLDRMissionsPetCharmsAnimaCostDropDown {
 }
 AugmentRunesAnimaCostDropDown = TLDRMissionsAugmentRunesAnimaCostDropDown {
 }
 LowerBoundLevelRestrictionLabel = TLDRMissionsLowerBoundLevelRestrictionLabel {
 }
 TitleBarTexture = TLDRMissionsTitleBar {
 }
 TopRightCorner = Texture {
 }
 SanctumFeaturePriorityLabel = TLDRMissionsSanctumFeaturePriorityLabel {
 }
 BlockCompletionDropDown = TLDRMissionsBlockCompletionDropDown {
 }
 FollowerXPSpecialTreatmentDropDown = TLDRMissionsFollowerXPSpecialTreatmentDropDown {
 }
 TopEdge = Texture {
 }
 SanctumFeatureAnimaCostDropDown = TLDRMissionsSanctumFeatureAnimaCostDropDown {
 }
 ReputationCheckButton = TLDRMissionsFrameReputationCheckButton {
 }
 ReputationDropDown = TLDRMissionsReputationDropDown {
 }
 AbortButton = TLDRMissionsFrameAbortButton {
 }
 FollowerXPPriorityLabel = TLDRMissionsFollowerXPPriorityLabel {
 }
 FewestOrMostLabel = TLDRMissionsFrameFewestOrMostLabel {
 }
 AnimaCostLimitLabel = TLDRMissionsAnimaCostLimitLabel {
 }
 AnythingForXPDropDown = TLDRMissionsAnythingForXPDropDown {
 }
 NextFollower3Label = TLDRMissionsFrameNextFollower3Label {
 }
 CampaignPriorityLabel = TLDRMissionsCampaignPriorityLabel {
 }
 Tabs = <table> {
 }
 SanctumFeatureCheckButton = TLDRMissionsFrameSanctumFeatureCheckButton {
 }
 EstimateLabel = TLDRMissionsFrameEstimateLabel {
 }
 FollowerXPAnimaCostDropDown = TLDRMissionsFollowerXPAnimaCostDropDown {
 }
 GoldCheckButton = TLDRMissionsFrameGoldCheckButton {
 }
 DurationLabel = TLDRMissionsDurationLabel {
 }
 FailedCalcLabel = TLDRMissionsFrameFailedCalcLabel {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 AnythingForXPCheckButton = TLDRMissionsFrameAnythingForXPCheckButton {
 }
 CraftingCacheDropDown = TLDRMissionsCraftingCacheDropDown {
 }
 EstimateFollower2Label = TLDRMissionsFrameEstimateFollower2Label {
 }
 AnimaDropDown = TLDRMissionsAnimaDropDown {
 }
 GearAnimaCostDropDown = TLDRMissionsGearAnimaCostDropDown {
 }
 MainTabButton = TLDRMissionsFrameTab1 {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 CalculateButton = TLDRMissionsFrameCalculateButton {
 }
 AutoStartButton = TLDRMissionsFrameAutoStartButton {
 }
 CompleteMissionsButton = TLDRMissionsFrameCompleteMissionsButton {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 RunecarverCheckButton = TLDRMissionsFrameRunecarverCheckButton {
 }
 SimulationsPerFrameLabel = TLDRMissionsSimulat

**Comment by teelolws** [comment]
Not sure why this is happening. Doesn't happen in any of my tests

**Comment by theruan** [comment]
Reinstalled the last version, gonna run that one again and report if if i find anything til tomorrow, but when the error happened I made sure to check if i had anything else related to the table loaded and had nothing.
I know that there are some 'oddities' that cause things like error when depositting anima, that could be one of those.

**Comment by teelolws** [comment]
No I made some changes to that part of the code today, but nothing I try is causing that error

**Comment by theruan** [comment]
Oddly, done the table a hundred times since i put this up and got no error at all, if it ever comes up again i will try to get more details.
