### ISSUE TITLE
[BUG] Other: saved file max size for TLDRMissions.lua

### ISSUE THREAD

**Issue by theruan** [TLDRMissions/TLDRMissions#636]
World of Warcraft\_retail_\WTF\Account\AccNumberID#1\SavedVariables seems to have a max size about 30MB to 33MB once this is reached the file won't be loaded properly and all configuration stored is lost, as a result a new file is created.

If this was fixed in one of the last 2~3 versions plz disregard, this happened to me in Feb, just hadn't had time to report.

Considering this takes a long time to happen i would say this is a low priority, took me about 4~6 months for this to happen.

**Comment by teelolws** [comment]
I'll turn off the logging. We probably don't need it anymore.
