### ISSUE TITLE
[BUG] Lua error GetAddOnMetadata now namedspaced inside C_AddOn

### ISSUE THREAD

**Issue by SpareSimian** [TLDRMissions/TLDRMissions#638]
### Copy/paste the Lua error here

Message: Interface/AddOns/TLDRMissions/gui.lua:63: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Tue Aug 13 14:58:21 2024
Count: 1
Stack: Interface/AddOns/TLDRMissions/gui.lua:63: attempt to call global 'GetAddOnMetadata' (a nil value)

Other addons are using this to remain compatible with classic:
```
local GetAddOnMetadata = C_AddOns and C_AddOns.GetAddOnMetadata or GetAddOnMetadata
```
This affects 3 files, caching.lua, gui.lua, and profile.lua and all 3 are just looking at the addon version, so I suggest factoring a function to report the version.

**Comment by SpareSimian** [comment]
A similar problem affects GetSpellInfo in missions.lua. I grabbed this from another addon:
```
local GetSpellInfo = C_Spell and function(spellID)
	if not spellID then
		return nil;
	end

	local spellInfo = C_Spell.GetSpellInfo(spellID);
	if spellInfo then
		return spellInfo.name, nil, spellInfo.iconID, spellInfo.castTime, spellInfo.minRange, spellInfo.maxRange, spellInfo.spellID, spellInfo.originalIconID;
	end
end or GetSpellInfo
```

**Comment by teelolws** [comment]
Have they changed it since 11.0 went live? It was working when I tested it on patch day.

**Comment by SpareSimian** [comment]
In events.lua you'll need:
```
local IsAddOnLoaded = IsAddOnLoaded or C_AddOns.IsAddOnLoaded;
```

**Comment by teelolws** [comment]
Oh, there was a patch today.

**Comment by teelolws** [comment]
I don't need to do any classic workarounds for this addon - it is not compatible with classic.

**Comment by teelolws** [comment]
> In events.lua you'll need:
> 
> ```
> local IsAddOnLoaded = IsAddOnLoaded or C_AddOns.IsAddOnLoaded;
> ```

I don't have a call to this function anywhere in events.lua?
