### ISSUE TITLE
[BUG] Other TLDRMissions does often not load

### ISSUE THREAD

**Issue by deus81** [TLDRMissions/TLDRMissions#641]
Hello, thank u for this very helpful addon ;).

Often i have to open and close the Command Table UI 3 or 5 times until the TLDRMissions UI finally loads with it. I disabled all other addons but this bug still presists.

**Comment by teelolws** [comment]
Its a bug with the game. If you open the table and TLDRMissions doesn't load, then the table itsself isn't going to work either.

**Comment by deus81** [comment]
Wow, thanks for the fast response ... tested it ... u are right :/
