### ISSUE TITLE
Add Project ID to TOC file

### ISSUE THREAD

**Issue by jungheeMW** [TLDRMissions/TLDRMissions#642]
Hello, could you add the following line to the TOC file? It allows 3rd party addon managers to download the addon.
`## X-Curse-Project-ID: 602487`

**Comment by teelolws** [comment]
Allright. Its in the Mainline.toc but not the generic one.

**Comment by jungheeMW** [comment]
Actual issue was related to bug with addon manager. Sorry about that.
